### ISSUE TITLE
Import events - when empty categorys field it will crash import

### ISSUE THREAD

**Issue by JKoelman** [jemproject/JEM-Project#1002]
Maybe it should be tested more but did got a hard error notice during import.

Had a events.csv with +/- 600 events and tried to import that (as test). it did contain a column categories but only in the first row I had a number in the categories fields. Did forget to add the numbers in the rest of the rows.

so during import it did crash and no cat-event relations were saved. Basicly that's fine but think it would be nicer to have a soft error or no error at all.

//
To note: in Joomla 3 the errors are displayed a bit different then in Joomla 2.x

**Comment by jojo12** [comment]
my question is after all for the tooltips: how can we describe better, when to use "yes" and when "no"
it is now not to understand!

**Comment by mckillo** [comment]
Closed. This issue is older and doesn't apply in current JEM version. Don't have any error to importing file to JEM 4.
