### ISSUE TITLE
JEM 2.1.5: Option nr of events frontend should change

### ISSUE THREAD

**Issue by JKoelman** [jemproject/JEM-Project#1007]
In the backend we have a setting "nr of events on the frontend views" but when set to a value not in the limitbox it won't be taken into account.  So something should change.

The limit is set but it's not displayed correctly as the option does not exist with that value and doing so the select can't display it.

**Comment by JKoelman** [comment]
maybe the easiest way for now can be to add some options to the field so people can only select values that are also in the limit box (5-10-15-20-25-30-50-100-all)

**Comment by JKoelman** [comment]
that said, it would be good if there is an option to set a value people want to have displayed.
In that case the limit-box is not that usefull as it can't display that option/value so that one shouldn't be displayed.

**Comment by Hoffi1** [comment]
The last comment I don't understand. But I agree to change edit field to dropdown list in backend to allow only values available on dropdown in frontend.

**Comment by JKoelman** [comment]
For example: if we have 1000 events and we want to display only 200 on a page. The option "all" will be to much, but 100 is to low.

So then the question will be how to achieve that

**Comment by Hoffi1** [comment]
Hm... If I look on my list each entry requires 10 or more millimeters. Showing 100 events we have more than one meter. So do one really want e.g. 200 entries on a single page?
Instead I would completely remove the "All" option and call "100" as the "more-than-enough" value.

Theoretically it would be no problem to enhance both lists with 150, 200, 250, ... - but personally I think that's too much.

**Comment by JKoelman** [comment]
Would say it's indeed good to keep it inline with the limitbox. And the "all" woud be good to keep.

The 200 was just an example, but someone in the forum did set it to 127 so there are people who do set it more then 100
