### ISSUE TITLE
JEM 2.1.5: Event-view (backend) - Repeating Events - "By the end of" is showing 1970-01-01

### ISSUE THREAD

**Issue by JKoelman** [jemproject/JEM-Project#1009]
Within Joomla 3 the option for "by the end of  is showing 1970-01-01 so would say it should be changed.

**Comment by JKoelman** [comment]
would say this happens as the field "recurrence_limit_date" has a default with "0000-00-00" but better would be to show the current date (now).

**Comment by jojo12** [comment]
yes, the date remembered me something :-)

**Comment by JKoelman** [comment]
the intention was to set a text "unlimited" but would say it's better to just show the current date. People can then select the needed date.  It would also be good to have a notice about the generating shield

**Comment by JKoelman** [comment]
changed the field
