### ISSUE TITLE
JEM 2.1.5:  attendees-view (backend) - add Toolbarbutton for changing status of selected rows

### ISSUE THREAD

**Issue by JKoelman** [jemproject/JEM-Project#1014]
When there is a waitinglist it's possible to change status but why 1-by-1? it would be nicer to have a button so people can select multiple rows and change the status.

**Comment by JKoelman** [comment]
the button is there but did not include the mailing-part. when pressing the toolbar buttons the waiting field will be updated but there won't be a mail sent as the mailing trigger is not added.

ofcourse it can be but that would be for later.

**Comment by jojo12** [comment]
I tried the new view:
when I choose an attending user and click "set waitinglist", he is set on waitinglist but at the same time I get an error notice: "an error has occurred".
The same with "set attending"
When I click directly on the symbol, I can change the status without any errors!

**Comment by JKoelman** [comment]
right will dive into this one as well.  (will test with Joomla 3.4.8 + Joomla 2.x)

**Comment by JKoelman** [comment]
it will be fixed, had to do with #1016  

Forgot to rename &id to &eventid

**Comment by Hoffi1** [comment]
The buttons are nice but on J 2.5 no icons are shown.

**Comment by JKoelman** [comment]
alright will add it.
