### ISSUE TITLE
JEM 2.1.5: attendees-view (backend) - move print+export to toolbar

### ISSUE THREAD

**Issue by JKoelman** [jemproject/JEM-Project#1015]
this as it's looks better

**Comment by jojo12** [comment]
in print (and export) I can't see any difference between "attending" and "on waitinglist"

**Comment by JKoelman** [comment]
> in print (and export) I can't see any difference between "attending" and "on waitinglist"

Will install a clean versionand will into this

**Comment by JKoelman** [comment]
> I can't see any difference between "attending" and "on waitinglist"

was it there before? am looking into the print tmpl but am not seeing a status column.
Maybe it would also be nice to remove the ip column. It can be good to have in the back but wouldn't want to see it in the printed list

**Comment by JKoelman** [comment]
uhm, am seeing in the front that the column is there but it's not in the backend so yep it's something that can be added.

**Comment by jojo12** [comment]
Is fine now
