### ISSUE TITLE
JEM 2.1.5: Venues-model (front) - don't extend JemModelEventsList

### ISSUE THREAD

**Issue by JKoelman** [jemproject/JEM-Project#1018]
As the base of that view are venues and we don't have a event-table there i would say that it would be better to not extend the eventsModel.

**Comment by JKoelman** [comment]
Doing so will lead to a problem with this function "_populatePublishState"

**Comment by JKoelman** [comment]
Would say the AssignedEvents function can be changed to have a call to ```JModelLegacy::getInstance('Eventslist','JemModel');```

**Comment by JKoelman** [comment]
```php
$model = JModelLegacy::getInstance('Eventslist','JemModel');
		$model->setState('filter.filter_locid',$id);
		$items = $model->getItems();
		
		$nr = count($items);
		
		if (empty($nr)) {
			$nr = 0;
		}
		
		return ($nr);
```

doing so will retrieve more info about the events then only the id so am not sure if that's correct to do.

**Comment by Hoffi1** [comment]
Generally venues model is not an eventslist model so deriving from that is not the best solution, yes.
On the other hand if the venues model - not derived from eventslist model - does load and use the eventslist model we have no pro so it seems to make no sense.

Regarding ```filter.published```: If it contains a numeric value this will be used for query. But it there is also a ```filter.unpublished``` with a numeric value additional terms will be added by ```_getPublishWhere()``` to also ask for unpublished events on which the user can do something (e.g. edit or publish).

btw: I created ```_populateState()``` and ```_getPublishWhere()``` to give models derived from eventslistmodel an easy way to "inject" specific handling required without the need to completely override ```populateState()``` and ```getListQuery()```.

**Comment by JKoelman** [comment]
> On the other hand if the venues model - not derived from eventslist model - does load and use the eventslist model we have no pro so it seems to make no sense.

It's only with the assignEvents function but what if there is an option not to show the count? In that case the events-model is not needed.

But it's fine with me to leave i as it is for now
