### ISSUE TITLE
JEM 2.1.5: Cleanup function - don't delete but rather trash

### ISSUE THREAD

**Issue by JKoelman** [jemproject/JEM-Project#1019]
did see that the cleanup function has an option to delete events but would say it's better to trash as the user will have an option then to recover events if it was an accident.

**Comment by jojo12** [comment]
? Do you mean the settings to delete all when uninstalling? How can db be deleted when only trashed?

**Comment by JKoelman** [comment]
> Do you mean the settings to delete all when uninstalling?

No, i meant the setting "Handle old events", tab "basic settings".

it's the function that's triggered when people are viewing the front.
Depending on the setting archiving/deleting/or doing nothing.

Would rather see the option "trash" instead of delete.

**Comment by jojo12** [comment]
ok

**Comment by Hoffi1** [comment]
I disagree a bit. Additional option "trash" is fine but I would also like to provide the option "delete" which users can use to keep db short without additional manual action.
Sure, they should be informed about what delete means - permanently destroy.

**Comment by JKoelman** [comment]
Ah yes, am agreeing with you there
