### ISSUE TITLE
Question: translation of State match mode

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1025]
Hi, I've just seen that in german there's no translation in the banner and teaser module.
What's the function of that. Can you explain me, for I can translate after!

What's the function in these modules?

**Comment by Hoffi1** [comment]
The "State" means "Bundesland" as well as "Kanton". :wink: 
Mode "exact match" means user must exactly give the state(s), e.g. "Berlin,Sachsen,Nordrhein-Westfalen" which match events on these three states only.
Mode "contains" allows e.g. "Sachsen" which would match events in "Sachsen", "Sachsen-Anhalt" or "Niedersachsen".

**Comment by jojo12** [comment]
thanks! :-)
