### ISSUE TITLE
jem mailer: strange notification after event edit

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1026]
Hi, is this quite new?
when edit and save an event, I get a notification: Message body empty (see image)
where this body should be, I get a good email notification.
![empty body](https://cloud.githubusercontent.com/assets/2960236/12444556/e9faa952-bf5f-11e5-88db-ad08af004fa7.png)

**Comment by Hoffi1** [comment]
Never seen so far, must take a look.

Is there another, additional recipient where something goes wrong with the body? (e.g. no text define or so)

**Comment by jojo12** [comment]
the post of lecoqroach #21230 in forum says about the same!

**Comment by Hoffi1** [comment]
On my sites it works fine. But it is very important to have not more %-tags within the translated text than expected. e.g. PLG_JEM_MAILER_EDIT_EVENT_9 expects nine %-tags because it will be formatted with nine arguments.

**Comment by Hoffi1** [comment]
@jojo12 Do I remember rigth that this was caused by a little mistake in translation file so we can mark it as fixed and close?

**Comment by jojo12** [comment]
yes, you're right. This is fixed
