### ISSUE TITLE
enhancement: time to change between two events

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1028]
in the jem_banner is the possibility to change between a number of events. After each refresh, there is (in most cases) an other event visible.

My question is: Is there a possibility to add some code, that this change is done automaticly after a given time? So it could be like a slider.

**Comment by Hoffi1** [comment]
Generally yes. There should be a way implemented to update the module only (e.g. using ajax, same principle as the ajax calendar module) and some javascript which does this from time to time.
That's the theory. Now you need someone of the JS experts - I'm not one of them, sorry...

**Comment by jojo12** [comment]
An other thing is:
when I have e.g. two events and  I want to show with shuffle only one at a time, the shuffle makes, that sometimes I get a lot of times after refreshing the same event. That's shuffle: with a dice you can have more times a six.
It would be great, if there's a control to disable an eventshow, when it was just the active one.
(I hope you understand my thoughts)
By the way I am working on a extra jem_banner wide (a variation of jem_banner) which uses wide positions in my template and it looks nice

**Comment by Hoffi1** [comment]
> (I hope you understand my thoughts)

Yes, I know what you mean.
It's a hard work to teach that every cast is absolutely independent from each other - and now comes you and ask for making them dependent... :laughing: 

...it's not very easy because it requires to remember last id.
