### ISSUE TITLE
(plg_finder_jemvenue) backend edit venue: error notice after trying to save

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1029]
I edited a venue, when I tried to save, I got the error notice (see image)
![error](https://cloud.githubusercontent.com/assets/2960236/12517188/db609e8c-c131-11e5-8529-2a9c39be2ed2.png)

**Comment by JKoelman** [comment]
uhm what version of JEM?
tried it with dev but couldn't replicate the problem.

**Comment by Hoffi1** [comment]
The message itself is correct, #__jem_venues doesn't have an 'access' field.
But I wonder where this query comes from? I've searched all JEM files but nowhere found such code.
Could it be that you talk about a personal version @jojo12 ?

**Comment by JKoelman** [comment]
maybe it's related to finder?

**Comment by JKoelman** [comment]
and indeed it's related to that plugin:
http://www.joomlaeventmanager.net/forum/jem-2-1-x-for-joomla-2-5-joomla-3-community-support/9481-smart-search-jem-for-venues?limitstart=0

Will update that plugin..

**Comment by JKoelman** [comment]
the thing was that the function "onFinderBeforeSave" is called and there is a call to the function "checkItemAccess".  Like Hoffi said there is no access field so we can always return true.

**Comment by jojo12** [comment]
@blufox: thanks to update it

**Comment by JKoelman** [comment]
tweaked a little bit:

[jemvenues.zip](https://github.com/jemproject/JEM-Project/files/101808/jemvenues.zip)

**Comment by jojo12** [comment]
works, error is away! Thanks.
