### ISSUE TITLE
ICal-output causing a problem with outlook

### ISSUE THREAD

**Issue by JKoelman** [jemproject/JEM-Project#1030]
as reported over here: http://www.joomlaeventmanager.net/forum/jem-2-1-x-for-joomla-2-5-joomla-3-community-support/9537-urgent-ical-export-does-not-regard-german-summertime

**Comment by Hoffi1** [comment]
It's not a bug of JEM but maybe it helps to workaround the Outlook bug if we add all date/time elements always as UTC/Zulu. By no means I would touch the vcalendar class itself.

**Comment by mckillo** [comment]
This issue is old and the current version 4.2.2 & next 4.3.0, it doesn't have this problem with ical file.
