### ISSUE TITLE
Mailer plugin - function _getRecipients is causing a problem in the logs (Undefined index: ev-creator/registered)

### ISSUE THREAD

**Issue by JKoelman** [jemproject/JEM-Project#1031]
Did notice in the logs that the function getRecipients is causing a problem in the log. The thing is that, that function is checking if the index if empty but it's not checking if it's defined. So would say it can be added to prevent the notice.

Did get the notice in attendees-view, after adding a new attendee as it's sending mails

**Comment by JKoelman** [comment]
to add:  option send_to['category'] will cause a note in the log when there is no email given. we are firing up a is_null for category_receivers but it would also be good to check if we do have a value. so something like 

``` if (is_null($category_receivers) || empty($category_receivers)) { ```

**Comment by Hoffi1** [comment]
Don't understand the problem. The job of ```empty()``` is to simply return ```true``` if a variable is ```0```, ```0.0```, ```"0"```, ```false```, ```array()```, ```null```, or not defined.

The php manual also says that there will be no warning generated if the variable doesn't exist so ```empty($v)``` is a legitimate equivalent to ```!isset($v) || $v == false```

Instead ```is_null($v)``` will cause an "Undefined variable" notice if $v is not defined. So your suggestion will cause log entries.

**Comment by JKoelman** [comment]
actually am not seeing any notices in the log anymore so would say it's working fine now but did modify a bit more.  but had a problem that `$category_receivers` was empty. in that case it's firing up ```array_unique($this->categoryDBList($category_receivers));``` and doing so there was note about string/array problem.

**Comment by JKoelman** [comment]
> see if i can replicate the problem
did revert some of the changes, tried again am running into the ```Warning: array_unique() expects parameter 1 to be array, string given``` so there is something that needs to change.

**Comment by Hoffi1** [comment]
Do you use latest from dev21? I made a fix after 2.1.5.
But you're right, ```categoryDBList()``` should return ```array()``` instead of ```''``` - will commit a fix soon...

**Comment by Hoffi1** [comment]
> am running into the Warning: array_unique() expects parameter 1 to be array, string given so there is something that needs to change.

This should be historical now. :smile: 

// good time to go to sleep for me now...

**Comment by JKoelman** [comment]
You were right, wasn't using the Mailer plugin of the dev branch.
