### ISSUE TITLE
JEM 2.1.5: frontend edit event/venue disable attachment/image upload

### ISSUE THREAD

**Issue by Hoffi1** [jemproject/JEM-Project#1033]
In JEM Settings it's possible to disable image upload (User control tab). In that case the Image block should be hidden in event/venue edit views of frontend. (more precise: hide complete block if no image is set, otherwise show Image block with image but no form to upload/delete image).

Also it should be possible to disallow Attachment uploads on frontend. Currently one could set Max size to zero to inspire this but maybe a dedicated "Attachment uploads: Yes/No" would be better.
If disabled the Attachment tab should be hidden. (or shown as read-only if there are attachments?)

**Comment by jojo12** [comment]
i made a comment into the fix:
if image upload is optional and upload attachments is disabled, image upload is disabled too!

**Comment by Hoffi1** [comment]
Thanks @jojo12, you're right. Image upload doesn't work (independent from attachment setting).

This is because I had changed the field from manually fiddled to JForm generated. But that has the negative effect that id changes from 'userfile' to 'jform_userfile' and name to 'jform[userfile]'. So it is not found by JemTableEvent.

But I'll find a solution (incl. "Clear" button). :wink: 

btw: The change was required to get setting "Image required" working again after @JKoelman's general change in "required" handling (which I agree). As a side effect the bulb is gone but the tooltip is kept.
