### ISSUE TITLE
JEM216-dev3: error notification on settings

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1037]
Hi,
installed dev3 over dev2: ok
all main windows open except settings/Einstellungen:
gives an error:
Fatal error: Can't use method return value in write context in mysite.ch/httpdocs/administrator/components/com_jem/models/settings.php on line 107

[tested on:
PHP erstellt für 	Linux server46.hostfactory.ch 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u3 x86_64
Datenbankversion 	5.5.47-0+deb7u1
Datenbankzeichensatz 	utf8_general_ci
PHP-Version 	5.4.45-0+deb7u2
Webserver 	Apache
PHP-Interface für den Webserver 	cgi-fcgi
Joomla!-Version 	Joomla! 3.4.8 Stable [ Ember ] 24-December-2015 19:30 GMT
Joomla!-Plattform-Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Browsererkennung 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0 ]

**Comment by Hoffi1** [comment]
grrr... I don't learn the old php :cry: 

I think the line 
```
if (!empty($settings->getFields())) {
```
should be changed to 
```
$fields = $settings->getFields();
if (!empty($fields)) {
```

**Comment by jojo12** [comment]
works fine. problem fixed
