### ISSUE TITLE
mod_jem_banner: today's event not showed

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1045]
there seems to be a problem:
when setting to todays event, no event of today is showed!

**Comment by jojo12** [comment]
in addition:
events from today in combination with module setting only featured doesn't show featured event from today.

**Comment by jojo12** [comment]
both are working fine in mod_jem_teaser.

**Comment by Hoffi1** [comment]
With today's events you're, there's a typo.

Regarding "Featured": In Teaser it's implemented as "unfinished featured events", in Banner as "upcoming featured events".
Because "featured" is timeless I would suggest to remove this Display-Type and add a Yes/No option "Featured events only" instead.

**Comment by jojo12** [comment]
yes, the fix of the typo resolved the today problem.

and the featured event is not showed when he is today. (Perhaps your proposal is good. I don't understand, I must see.)

**Comment by Hoffi1** [comment]
Because the display type "Featured only" has benn removed now users must adapt the settings manually. Below is a new toggle "Featured only" which can be set on each Display type.

**Comment by Hoffi1** [comment]
@jojo12: Have you tried my last commit? Is it understandable, useful and working?

**Comment by jojo12** [comment]
yes it works fine (even your proposal to herkle) if there's no event to show.
[By the way, you should sleep longer! ;-)]
