### ISSUE TITLE
JEM2.1.6RC1: sidebar only on mainmenu and settings

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1048]
Hi,
I tho ught, the sidebar was first on all pages (main, events, venues, groups, settings..)
now it's only on main and settings.
Why ?

[od did I add it, have I to add it by myself?]

**Comment by Hoffi1** [comment]
It should be shown on nearly all backend views.

Do you have template overrides? It was required to move the code to show the sidebar inside the tmpl files to add the required surrounding span-2 / span-10 divs..

**Comment by jojo12** [comment]
sorry, they are only lost on venues and events.
(I disabled all template overrides)

**Comment by jojo12** [comment]
in events and venues it isn't even after complete uninstall.

**Comment by Hoffi1** [comment]
Sorry, I can't reproduce.

Have copied my original 2.1.5 testsite, updated J! 3.5.1 and installed JEM 2.1.6-rc1 + Ajax calendar module. On JEM backend I clicked all items in sidebar menu, incl. "Events" and "Venues" and always had this sidebar.

**Comment by jojo12** [comment]
yes, when I installed on a other clean 3.5.1, all worked well. Can it be because I first updated from a -dev?
