### ISSUE TITLE
2.1.6RC1: strange in settings of mod_jem_calajax

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1050]
![strangesettings](https://cloud.githubusercontent.com/assets/2960236/14858318/eddc38aa-0c9f-11e6-850e-9b08955b69e9.png)

how can this be? 
In english I have as translation "Event" and "Events"
in german "Veranstaltung" und "Veranstaltungen"
and here only the keys

**Comment by Hoffi1** [comment]
That's correct (and same as in mod_jem_cal).

The admin MUST type in a key to allow multiple languages. If you type in "Event" it will be always "Event", never "Veranstaltung".
