### ISSUE TITLE
2.1.6RC1: JEM settings>listlayout no custom css possible!

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1052]
Hi, if I want to insert and save the address of a custom list. 
After saving, the input is lost and it uses only the default css.

**Comment by Hoffi1** [comment]
You're right, it's on fresh installations. It's because 'css' record is empty ('{}') which somewhere prevents adding the values.So I must find the right "somewhere"...

**Comment by jojo12** [comment]
welldone! works!
