### ISSUE TITLE
2.1.6RC2 from dev21: registered user get mail "unregistered"

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1055]
Hi, 
I made a package from dev21 and installed. All ok
But when a user registers, the emails for unregistered are triggered!

**Comment by Hoffi1** [comment]
oops... as sayed, it's not really tested, fast committed to give you quick view about coming text changes.
...will do my work tonight. :wink:

**Comment by Hoffi1** [comment]
I forgot that 0 is equal to 'on' - crazy php...
