### ISSUE TITLE
2.1.6.RC3: where is contact person? lost

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1058]
Hi, even without template overrides, the contact is not anymore visible and even not saved!
That's a big mistake. The contact is very important!

Strange: the old contacts I just had before, are visible. 
So it seems only the problem of new contacts in JEM

**Comment by Hoffi1** [comment]
Hi @jojo12, I'm very sorry but I can't reproduce this problem.

On my test site with exact the same files as provided as rc3 I created a new event (as super user) and selected a contact in popup list. This was shown in Contact field of editevent and also in details view after Save. I then clicked Edit and selected a venue which is also shown as expected.

The only thing I changed rgarding contact was to move this line above Venue line in editevent view.

Do you have a Javascript problem? There is a js function (jSelectContact_jform_contactid) which puts name and id of the selected contact into the fields of editevent view's form. Do you see the contact name in the field?
Or is the contact published and has a "good" view level? (Edit: unpublished contacts will not be listed/selectable, view level is ignored - ohmy...)
Which PHP version do you use?

**Comment by jojo12** [comment]
Hi Hoffi, you're right, on other sides it's working. So now the long search, to find the conflict!
