### ISSUE TITLE
Localisation of Metatag text suggestion

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1062]
After installing (and even with language) the metatext is always in english. I  have to change it by myself e.g. to german. But then there is a problem of the other languages.

Is there a possibility to add there a translation in the language files? Would be much better.

**Comment by Hoffi1** [comment]
??? It is within the language file: COM_JEM_META_DESCRIPTION_STANDARD

But it will not translate AFTER event was created because this information is stored within the event.
