### ISSUE TITLE
JEM event button shows new error notifications

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1065]
Notice: Undefined property: stdClass::$access_level in /srv/www/vhosts/mysite.ch/httpdocs/components/com_jem/views/eventslist/tmpl/modal.php on line 116

Notice: Undefined property: stdClass::$path in /srv/www/vhosts/mysite.ch/httpdocs/components/com_jem/classes/output.class.php on line 1131

**Comment by jojo12** [comment]
as I wrote earlier, it would be nice to have that plugin for JEM 2.1.6+ and Joomla 3.5.1+

**Comment by Hoffi1** [comment]
I assume you talk about plg_editor-xtd_event, isn't it?
I will add it, no question. It's just a question of time...

**Comment by jojo12** [comment]
yes, meanwhile the notifications are away (don't know why).
but much more important is non-attending. (I used this plugin together with gj-events for non-attendings.)
