### ISSUE TITLE
JEM2.1.6: myevents no emailaddresses visible

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1066]
Hi,
in frontend in myevents settings I choosed "show emails" but I only see the name of the attendees no email address. This should be with this setting. 
(Or did I understand something wrong?)

**Comment by Hoffi1** [comment]
Sorry @jojo12 but I can't reproduce this.
With JEM 2.1.6 the column "E-Mail" of Attendees view (reachable by clicking the numbers on "My Events" view) exactly corresponds the menu item option "Display Email address" of My Events menu item.

Do you have multiple "My Events" menu items? Or template overrides? (myevents or attendees)

**Comment by jojo12** [comment]
I have no overwrites
![myeventsatt](https://cloud.githubusercontent.com/assets/2960236/15972506/26e98942-2f3f-11e6-8d51-3c1927e56c03.png)

**Comment by Hoffi1** [comment]
As sayed, on my sites it works perfect.

If you take a look on the form around the tables you'll find a hidden input "enableemailaddress" which must have the value 1 on both view My Events and Attendees.
If not maybe it helps to Save the menu item.

**Comment by jojo12** [comment]
I don't find this place. Please give me more coordinates!

**Comment by Hoffi1** [comment]
Enter My Events view and right click somewhere between filter block and table, select "Element untersuchen". This will show html code with ```<form``` selected. Within this block you'll find a lot of ```<input``` lines below ```<table```. One of them has ```name="enableemailaddress"```

Same for "Anmeldungsmanager".

**Comment by jojo12** [comment]
followed your hints and found in Anmeldungsmanager it was "0". Changed it in ftp. Emails are visible now.
Only the question, why it was like that and was not changed with settings?

**Comment by Hoffi1** [comment]
Now I can't follow you. Have you hard-coded set this option to 1?
I can't loose the mind that you have another My Events menu item somewhere.
If you're in Attendees view the url must be like /my-events/attendees/123 where "my-events" is the alias of the My Events menu item and 123 is an event id. Otherwise Joomla doesn't present the option of My Events menu item to Attendees view.
