### ISSUE TITLE
ALERT: where is joomlaeventmanager.net?

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1068]
I can not reach it!
EDIT I only get:

"This account has been suspended.
Either the domain has been overused, or the reseller ran out of resources."

**Comment by ernst67** [comment]
Oops, the account has ontdeed been suspendeer and all sites down.

The hosting company reported Overuse of the server and sent à report:


stop proces	10684198	baudeds68_JEM09	159.253.0.41:44626	baudeds68_jemdemo	Sleep	4	---	---
stop proces	10684205	baudeds68_JEM09	159.253.0.41:44628	baudeds68_jemdemo	Sleep	2	---	---
stop proces	10684216	baudeds68_JEM09	159.253.0.41:44629	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10684255	baudeds68_JEM09	159.253.0.41:44635	baudeds68_jemdemo	Sleep	4	---	---
stop proces	10684312	baudeds68_JEM09	159.253.0.41:44643	baudeds68_jemdemo	Query	3	Copying to tmp table	SELECT a.access,a.alias,a.attribs,a.author_ip,a.checked_out,a.checked_out_time,a.contactid,a.created
stop proces	10684320	baudeds68_JEM09	159.253.0.41:44647	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10684347	baudeds68_JEM09	159.253.0.41:44652	baudeds68_jemdemo	Query	2	Copying to tmp table	SELECT a.access,a.alias,a.attribs,a.author_ip,a.checked_out,a.checked_out_time,a.contactid,a.created
stop proces	10684348	baudeds68_JEM09	159.253.0.41:44653	baudeds68_jemdemo	Sleep	4	---	---
stop proces	10684354	baudeds68_JEM09	159.253.0.41:44654	baudeds68_jemdemo	Query	2	Copying to tmp table	SELECT a.access,a.alias,a.attribs,a.author_ip,a.checked_out,a.checked_out_time,a.contactid,a.created
stop proces	10684356	baudeds68_JEM09	159.253.0.41:44655	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10684357	baudeds68_JEM09	159.253.0.41:44656	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10684406	baudeds68_JEM09	159.253.0.41:44662	baudeds68_jemdemo	Query	2	Copying to tmp table	SELECT a.access,a.alias,a.attribs,a.author_ip,a.checked_out,a.checked_out_time,a.contactid,a.created
stop proces	10684448	baudeds68_JEM09	159.253.0.41:44671	baudeds68_jemdemo	Query	2	Copying to tmp table	SELECT a.access,a.alias,a.attribs,a.author_ip,a.checked_out,a.checked_out_time,a.contactid,a.created
stop proces	10684453	baudeds68_JEM09	159.253.0.41:44673	baudeds68_jemdemo	Sleep	2	---	---
stop proces	10684454	baudeds68_JEM09	159.253.0.41:44674	baudeds68_jemdemo	Sleep	2	---	---
stop proces	10684455	baudeds68_JEM09	159.253.0.41:44675	baudeds68_jemdemo	Sleep	4	---	---
stop proces	10684488	baudeds68_JEM09	159.253.0.41:44683	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10684493	baudeds68_JEM09	159.253.0.41:44686	baudeds68_jemdemo	Query	2	Copying to tmp table	SELECT a.access,a.alias,a.attribs,a.author_ip,a.checked_out,a.checked_out_time,a.contactid,a.created
stop proces	10684494	baudeds68_JEM09	159.253.0.41:44685	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10684525	baudeds68_JEM09	159.253.0.41:44695	baudeds68_jemdemo	Query	2	Copying to tmp table	SELECT a.access,a.alias,a.attribs,a.author_ip,a.checked_out,a.checked_out_time,a.contactid,a.created
stop proces	10684538	baudeds68_JEM09	159.253.0.41:44696	baudeds68_jemdemo	Sleep	4	---	---
stop proces	10684540	baudeds68_JEM09	159.253.0.41:44698	baudeds68_jemdemo	Sleep	2	---	---
stop proces	10684541	baudeds68_JEM09	159.253.0.41:44699	baudeds68_jemdemo	Sleep	4	---	---
stop proces	10684543	baudeds68_JEM09	159.253.0.41:44700	baudeds68_jemdemo	Query	2	Copying to tmp table	SELECT a.access,a.alias,a.attribs,a.author_ip,a.checked_out,a.checked_out_time,a.contactid,a.created
stop proces	10684564	baudeds68_JEM09	159.253.0.41:44704	baudeds68_jemdemo	Query	2	Copying to tmp table	SELECT a.access,a.alias,a.attribs,a.author_ip,a.checked_out,a.checked_out_time,a.contactid,a.created
stop proces	10684604	baudeds68_JEM09	159.253.0.41:44709	baudeds68_jemdemo	Query	2	Copying to tmp table	SELECT a.access,a.alias,a.attribs,a.author_ip,a.checked_out,a.checked_out_time,a.contactid,a.created
stop proces	10684610	baudeds68_JEM09	159.253.0.41:44712	baudeds68_jemdemo	Sleep	4	---	---
stop proces	10684686	baudeds68_JEM09	159.253.0.41:44718	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10684696	baudeds68_JEM09	159.253.0.41:44721	baudeds68_jemdemo	Sleep	4	---	---
stop proces	10684698	baudeds68_JEM09	159.253.0.41:44722	baudeds68_jemdemo	Query	3	Copying to tmp table	SELECT a.access,a.alias,a.attribs,a.author_ip,a.checked_out,a.checked_out_time,a.contactid,a.created
stop proces	10684700	baudeds68_JEM09	159.253.0.41:44723	baudeds68_jemdemo	Sleep	4	---	---
stop proces	10684731	baudeds68_JEM09	159.253.0.41:44726	baudeds68_jemdemo	Query	2	Copying to tmp table	SELECT a.access,a.alias,a.attribs,a.author_ip,a.checked_out,a.checked_out_time,a.contactid,a.created
stop proces	10684749	baudeds68_JEM09	159.253.0.41:44728	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10684756	baudeds68_JEM09	159.253.0.41:44730	baudeds68_jemdemo	Sleep	4	---	---
stop proces	10684758	baudeds68_JEM09	159.253.0.41:44731	baudeds68_jemdemo	Sleep	4	---	---
stop proces	10684759	baudeds68_JEM09	159.253.0.41:44732	baudeds68_jemdemo	Query	2	Copying to tmp table	SELECT a.access,a.alias,a.attribs,a.author_ip,a.checked_out,a.checked_out_time,a.contactid,a.created
stop proces	10684786	baudeds68_JEM09	159.253.0.41:44738	baudeds68_jemdemo	Sleep	2	---	---
stop proces	10684789	baudeds68_JEM09	159.253.0.41:44739	baudeds68_jemdemo	Sleep	2	---	---
stop proces	10684823	baudeds68_JEM09	159.253.0.41:44746	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10684824	baudeds68_JEM09	159.253.0.41:44747	baudeds68_jemdemo	Query	2	Copying to tmp table	SELECT a.access,a.alias,a.attribs,a.author_ip,a.checked_out,a.checked_out_time,a.contactid,a.created
stop proces	10684825	baudeds68_JEM09	159.253.0.41:44748	baudeds68_jemdemo	Sleep	2	---	---
stop proces	10684847	baudeds68_JEM09	159.253.0.41:44752	baudeds68_jemdemo	Sleep	4	---	---
stop proces	10684849	baudeds68_JEM09	159.253.0.41:44753	baudeds68_jemdemo	Sleep	4	---	---
stop proces	10684862	baudeds68_JEM09	159.253.0.41:44755	baudeds68_jemdemo	Query	2	Copying to tmp table	SELECT a.access,a.alias,a.attribs,a.author_ip,a.checked_out,a.checked_out_time,a.contactid,a.created
stop proces	10684868	baudeds68_JEM09	159.253.0.41:44756	baudeds68_jemdemo	Query	3	Copying to tmp table	SELECT a.access,a.alias,a.attribs,a.author_ip,a.checked_out,a.checked_out_time,a.contactid,a.created
stop proces	10684883	baudeds68_JEM09	159.253.0.41:44760	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10684894	baudeds68_JEM09	159.253.0.41:44762	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10684925	baudeds68_JEM09	159.253.0.41:44768	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10684928	baudeds68_JEM09	159.253.0.41:44770	baudeds68_jemdemo	Sleep	2	---	---
stop proces	10684934	baudeds68_JEM09	159.253.0.41:44771	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10684950	baudeds68_JEM09	159.253.0.41:44775	baudeds68_jemdemo	Sleep	2	---	---
stop proces	10684968	baudeds68_JEM09	159.253.0.41:44776	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10684969	baudeds68_JEM09	159.253.0.41:44777	baudeds68_jemdemo	Sleep	2	---	---
stop proces	10684973	baudeds68_JEM09	159.253.0.41:44778	baudeds68_jemdemo	Sleep	2	---	---
stop proces	10684978	baudeds68_JEM09	159.253.0.41:44781	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10684984	baudeds68_JEM09	159.253.0.41:44782	baudeds68_jemdemo	Sleep	2	---	---
stop proces	10685021	baudeds68_JEM09	159.253.0.41:44784	baudeds68_jemdemo	Sleep	2	---	---
stop proces	10685032	baudeds68_JEM09	159.253.0.41:44785	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685033	baudeds68_JEM09	159.253.0.41:44786	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685073	baudeds68_JEM09	159.253.0.41:44792	baudeds68_jemdemo	Sleep	2	---	---
stop proces	10685077	baudeds68_JEM09	159.253.0.41:44793	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685080	baudeds68_JEM09	159.253.0.41:44794	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685096	baudeds68_JEM09	159.253.0.41:44796	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685107	baudeds68_JEM09	159.253.0.41:44797	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685146	baudeds68_JEM09	159.253.0.41:44800	baudeds68_jemdemo	Sleep	2	---	---
stop proces	10685147	baudeds68_JEM09	159.253.0.41:44801	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685154	baudeds68_JEM09	159.253.0.41:44803	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685172	baudeds68_JEM09	159.253.0.41:44807	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685183	baudeds68_JEM09	159.253.0.41:44808	baudeds68_jemdemo	Sleep	2	---	---
stop proces	10685215	baudeds68_JEM09	159.253.0.41:44813	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685217	baudeds68_JEM09	159.253.0.41:44814	baudeds68_jemdemo	Sleep	2	---	---
stop proces	10685219	baudeds68_JEM09	159.253.0.41:44815	baudeds68_jemdemo	Sleep	2	---	---
stop proces	10685221	baudeds68_JEM09	159.253.0.41:44816	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685222	baudeds68_JEM09	159.253.0.41:44817	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685223	baudeds68_JEM09	159.253.0.41:44818	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685266	baudeds68_JEM09	159.253.0.41:44821	baudeds68_jemdemo	Sleep	2	---	---
stop proces	10685273	baudeds68_JEM09	159.253.0.41:44822	baudeds68_jemdemo	Sleep	2	---	---
stop proces	10685274	baudeds68_JEM09	159.253.0.41:44823	baudeds68_jemdemo	Sleep	2	---	---
stop proces	10685300	baudeds68_JEM09	159.253.0.41:44824	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685318	baudeds68_JEM09	159.253.0.41:44825	baudeds68_jemdemo	Sleep	2	---	---
stop proces	10685320	baudeds68_JEM09	159.253.0.41:44827	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685325	baudeds68_JEM09	159.253.0.41:44828	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685326	baudeds68_JEM09	159.253.0.41:44829	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685362	baudeds68_JEM09	159.253.0.41:44835	baudeds68_jemdemo	Sleep	1	---	---
stop proces	10685376	baudeds68_JEM09	159.253.0.41:44838	baudeds68_jemdemo	Sleep	2	---	---
stop proces	10685393	baudeds68_JEM09	159.253.0.41:44840	baudeds68_jemdemo	Sleep	2	---	---
stop proces	10685394	baudeds68_JEM09	159.253.0.41:44841	baudeds68_jemdemo	Sleep	1	---	---
stop proces	10685435	baudeds68_JEM09	159.253.0.41:44847	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685437	baudeds68_JEM09	159.253.0.41:44848	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685444	baudeds68_JEM09	159.253.0.41:44849	baudeds68_jemdemo	Sleep	1	---	---
stop proces	10685451	baudeds68_JEM09	159.253.0.41:44850	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685456	baudeds68_JEM09	159.253.0.41:44854	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685502	baudeds68_JEM09	159.253.0.41:44859	baudeds68_jemdemo	Sleep	1	---	---
stop proces	10685508	baudeds68_JEM09	159.253.0.41:44860	baudeds68_jemdemo	Sleep	1	---	---
stop proces	10685537	baudeds68_JEM09	159.253.0.41:44863	baudeds68_jemdemo	Sleep	1	---	---
stop proces	10685544	baudeds68_JEM09	159.253.0.41:44865	baudeds68_jemdemo	Sleep	1	---	---
stop proces	10685545	baudeds68_JEM09	159.253.0.41:44867	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685570	baudeds68_JEM09	159.253.0.41:44869	baudeds68_jemdemo	Sleep	1	---	---
stop proces	10685577	baudeds68_JEM09	159.253.0.41:44871	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685578	baudeds68_JEM09	159.253.0.41:44872	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685580	baudeds68_JEM09	159.253.0.41:44874	baudeds68_jemdemo	Sleep	1	---	---
stop proces	10685584	baudeds68_JEM09	159.253.0.41:44875	baudeds68_jemdemo	Sleep	1	---	---
stop proces	10685585	baudeds68_JEM09	159.253.0.41:44876	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685604	baudeds68_JEM09	159.253.0.41:44878	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685607	baudeds68_JEM09	159.253.0.41:44879	baudeds68_jemdemo	Sleep	1	---	---
stop proces	10685631	baudeds68_JEM09	159.253.0.41:44881	baudeds68_jemdemo	Sleep	1	---	---
stop proces	10685633	baudeds68_JEM09	159.253.0.41:44882	baudeds68_jemdemo	Sleep	1	---	---
stop proces	10685729	baudeds68_JEM09	159.253.0.41:44889	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685737	baudeds68_JEM09	159.253.0.41:44890	baudeds68_jemdemo	Sleep	0	---	---
stop proces	10685739	baudeds68_JEM09	159.253.0.41:44891	baudeds68_jemdemo	Sleep	0	---	---
stop proces	10685779	baudeds68_JEM09	159.253.0.41:44894	baudeds68_jemdemo	Sleep	0	---	---
stop proces	10685783	baudeds68_JEM09	159.253.0.41:44895	baudeds68_jemdemo	Sleep	0	---	---
stop proces	10685833	baudeds68_JEM09	159.253.0.41:44899	baudeds68_jemdemo	Sleep	0	---	---
stop proces	10685845	baudeds68_JEM09	159.253.0.41:44900	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685846	baudeds68_JEM09	159.253.0.41:44901	baudeds68_jemdemo	Sleep	0	---	---
stop proces	10685849	baudeds68_JEM09	159.253.0.41:44902	baudeds68_jemdemo	Sleep	0	---	---
stop proces	10685851	baudeds68_JEM09	159.253.0.41:44898	baudeds68_jemdemo	Sleep	0	---	---
stop proces	10685852	baudeds68_JEM09	159.253.0.41:44903	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685864	baudeds68_JEM09	159.253.0.41:44904	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685873	baudeds68_JEM09	159.253.0.41:44906	baudeds68_jemdemo	Sleep	0	---	---
stop proces	10685930	baudeds68_JEM09	159.253.0.41:44912	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685931	baudeds68_JEM09	159.253.0.41:44913	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685932	baudeds68_JEM09	159.253.0.41:44914	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685934	baudeds68_JEM09	159.253.0.41:44915	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685939	baudeds68_JEM09	159.253.0.41:44916	baudeds68_jemdemo	Sleep	0	---	---
stop proces	10685972	baudeds68_JEM09	159.253.0.41:44918	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10685982	baudeds68_JEM09	159.253.0.41:44920	baudeds68_jemdemo	Sleep	0	---	---
stop proces	10686002	baudeds68_JEM09	159.253.0.41:44922	baudeds68_jemdemo	Sleep	0	---	---
stop proces	10686024	baudeds68_JEM09	159.253.0.41:44925	baudeds68_jemdemo	Sleep	2	---	---
stop proces	10686025	baudeds68_JEM09	159.253.0.41:44926	baudeds68_jemdemo	Sleep	0	---	---
stop proces	10686030	baudeds68_JEM09	159.253.0.41:44928	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10686091	baudeds68_JEM09	159.253.0.41:44932	baudeds68_jemdemo	Sleep	3	---	---
stop proces	10686181	baudeds68_JEM09	159.253.0.41:44954	baudeds68_jemdemo	Sleep	0	---	---
stop proces	10686229	baudeds68_JEM09	159.253.0.41:44961	baudeds68_jemdemo	Sleep	1	---	---


I guess someone has plating with the demo. I will ask them to put everything back online and toen I 'll take the demo offline for now....

**Comment by Hoffi1** [comment]
The IP comes from Amsterdam...

**Comment by jojo12** [comment]
always these dutch peoples!

**Comment by Hoffi1** [comment]
Not sure, maybe it's from the server itself?
@ernst67 : Be carefully posting server reports to the world. They could give more information as we see.

**Comment by Hoffi1** [comment]
Previous comments removed.
As summary: Ernst is talking with provider to find a solution.

(just to note: I can't read emails before today evening)

**Comment by ernst67** [comment]
Site back online. Demo offline.
More info in de Dev forum

**Comment by Hoffi1** [comment]
So we can close this ticket.
If there is a problem in code we open a new ticket.

**Comment by jojo12** [comment]
sorry about abusing this place, but it was the only possibility to inform you!

**Comment by ernst67** [comment]
No worries, i'm glad you notified me.
The hosting company sent me an email at 2.30 so I found 2 warnings this morning ;)
