### ISSUE TITLE
Joomla 3.6. Beta 2 with PdoMySql not supported yet

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1069]
I installed Joomla 3.6.Beta2 fresh  for testing. I choosed for database pdomysql:
When trying to install JEM 2.1.6,I get a notification:
Hinweis
Database driver 'pdomysql' is not supported. Please use MySQL instead.

I never installed Joomla 3.5.1 freshly, as I red, there should be the possibility too to use pdomysql.
So I don't know, it this problem happens even here with JEM 2.16.

**Comment by Hoffi1** [comment]
It's not a bug, it's simply not supported yet.

To support this we have to understand what this is and if all our queries will work as expected.
