### ISSUE TITLE
2.1.7 dev 3 attending

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1078]
installation ok, I am trying.

There seems to be a problem:

it seems you took away the possibility to making impossible unregistering after being registered.
That can be a problem when someone is registering for a place (others can't use then) and the same person is unregistering later or too late. Then you have no prove, that this person was registered before.

Ich versuchs auf deutsch: der Button Unregister=Nein (Annulation der Anmeldung) Verunmöglichte es bis 2.1.6 sich nach einer Anmeldung (Register) noch abzumelden. So hatte man etwas in der Hand, wenn sich jemand zu spät abmeldete und der Platz freiblieb (=kostenrelevant)

Jetzt scheint es so (ist es so?), dass man sich immer an- und abmelden kann.

Zumindest als Option müsste die Annulation einer gemachten Anmeldung verhindert werden können.

**Comment by Hoffi1** [comment]
You're right, there is no option to forbid "will not attend" (or changing from "will attend" to "will not attend").
...I must think about how to integrate such an option...

Another thing was that there is no information (within db) if the user was originally invited or not. That's why I removed the old unregister which removed the record from table.

**Comment by jojo12** [comment]
could this be a solution?
something like:
a registrated user who is unregistrating is forced to give a comment.

**Comment by Hoffi1** [comment]
It could be possible to "patch" the 'required' attribute - but I don't see a real chance to block another send without comment (A crazy user can send "I will attend" or "I will not attend" 10 or more times - each with a different comment - why not. The last comment is shown and the user gets only one place, of course. but for each click a set of notofocation emails will be sent.)
(see also forum)

**Comment by Hoffi1** [comment]
(...or not - forum has currently an error to show an error...and all my words are lost... :cry: )

**Comment by Hoffi1** [comment]
Now we have a simple Yes/No option on event creation which shows "I will not attend" radio button or a text "not allowed" if user is already attending.
But if user is on waiting list it's allowed because I expext in that case no cost already involved, isn't it?

**Comment by jojo12** [comment]
you're right!
