### ISSUE TITLE
notification after unattending

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1079]
the notification after unattending is:
COM_JEM_REGISTERED_SUCCESSFULL="Sie haben sich erfolgreich zu dieser Veranstaltung angemeldet."

**Comment by Hoffi1** [comment]
Hm...here "register" does not mean "angemeldet". It's more "we have successfully received and stored your decision". In the past only "I will attend" was stored and on unregistration the record was removed from db. But now we store every decision and never remove (as long as the event exists or an admin deletes the entry).

So we could try to find a single, "universal" sentence for both cases or I spend a second text. What do you like?

**Comment by jojo12** [comment]
My words are only in german:
"Rückmeldung" or "An-/Abmeldung"

Eigentlich gibt es drei Zustände: 
-Einschreibung zur Teilnahme/Zusage
-Keine Reaktion
-Absage
(mit der Einladung noch mehr.)
Wer seine explizite Einschreibung zurücknimmt, ist wie keine Reaktion
Wer seine explizite Absage zurücknimmt, ist wie keine Reaktion

**Comment by jojo12** [comment]
Sorry, I only no see that I was in other thoughts. Iwas thinking general aboug the title and notvthe notification.

**Comment by Hoffi1** [comment]
Sorry for the new "Your Registration" label, it was just added to indicate registration fields are in the correct position and have not to move to the left.

Regarding your other German words
Irgendwo hatten wir diskutiert, dass neben Ja und Nein ein Vielleicht eigentlich keinen Sinn/Nutzen hat, weshalb es nur zwei Optionen gibt. Hat ein Nutzer zugesagt, kann er nur absagen. Ein Zurücknehmen = keine Reaktion ist nicht eingeplant. Irgendwann muss man sich einfach klar entscheiden und kann sich nicht mit der Quantentheorie rausreden. :wink: 
Also ich denke schon, dass man sich immer für eine der beiden Optionen entscheiden sollte, ein Mittelweg bringt garnichts. Durch das Kommentarfeld kann man das ja relativieren. Man sollte sich aber schon klar äußern müssen, ob man die Kosten auf jeden Fall trägt oder lieber auf die Teilnahme verzichtet. Ein "ich zahle nur, wenn ich wirklich erscheine" möchte ich nicht anbieten.

...aber Du hast meine Frage von oben noch gar nicht beantwortet... :grin:

**Comment by jojo12** [comment]
G'morning!
You're right: if someone gives a reaction: there is no "vielleicht".
But there is always a third status:  "has not yet seen/or not yet answered" that means the person is registered as joomla user but in db jem_register there is no entry with his ID.

**Comment by jojo12** [comment]
I try to answer your question.
"Rückmeldung bezüglich Event-Teilnahme ist erfolgt"
"Your feedback concerning attending of this event was successful"

You see, I am trying more in direction of one common solution. If possible.

**Comment by Hoffi1** [comment]
Oh yes, that's easier for me :wink: - and, more important, independent from number of answers.

What's about something like "Thank you for your response which has been stored successfully." or "Thank you for your response. Your decision has been stored successfully." ?

**Comment by jojo12** [comment]
Much better than my proposal.
