### ISSUE TITLE
dev3: no Register part visible when invited

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1081]
when I am invited, I don't see the Part with Register. Even when I am logged in .

**Sorry when I bring back a lot. It is not bad, but like that I can help to find bugs.**

**Comment by Hoffi1** [comment]
(no sorry required. :+1: )

I think I found it. I developed with JEM Setting Allow Event Registration = Optional but I think you use Yes in which case event creator can't actively activate registration - and my new code doesn't too...

**Comment by jojo12** [comment]
you're right:
with admin setting optional it works fine
