### ISSUE TITLE
dev3: delete attending user impossible

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1082]
button to delete attending user gives no reaction!
![impossible](https://cloud.githubusercontent.com/assets/2960236/17097258/5ca8550e-525d-11e6-9b6c-62fbe8db954a.png)

**Comment by Hoffi1** [comment]
will take a look... (tomorrow)

**Comment by Hoffi1** [comment]
You're right. It can't work and it never worked. It's code copied from backend view and never adapted.
Must search for a working alternative...

**Comment by jojo12** [comment]
yes it's fixed,
