### ISSUE TITLE
JEM2.1.7 dev4 : super

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1084]
I installed and tried, all seems to work well.

The only thing I did not yet test (because it's not yet finished) is the Making impossible of Unregistration when registrated.

Super thanks a lot, I can use it like it is now. 
"Ein kleiner Schritt für einen Menschen, aber ein grosser Sprung für die Menschheit oder so ;-)

Edit: Ah es scheint doch schon etwas in die Richtung:
Sah gerade:
"Annulation of event registration is not allowed"

**Comment by Hoffi1** [comment]
Och nö - ich will nicht im Vollgummi durch 'ne Wüste hüpfen! :grinning: 

btw: You realised the little update of CB plugin (events)?

**Comment by jojo12** [comment]
installiert sich das automatisch? oder muss ich das speziell?

**Comment by jojo12** [comment]
Ich habs nun selber gezippt und installiert. Aber mir fällt nichts auf. Hast du mir einen Tipp!

**Comment by Hoffi1** [comment]
> Ich habs nun selber gezippt und installiert. Aber mir fällt nichts auf. Hast du mir einen Tipp!
Schwer zu beschreiben. Es soll einfach alle möglichen Konstellationen korrekt darstellen. :wink: Z.B. bei globalem "Registrieren = Ja" (s. #1081)
Außerdem wird die Attendee-Spalte nun nur noch dem Eigentümer angezeigt, so wie es auch bei den JEM-Views ist.
