### ISSUE TITLE
dev 4: BE clicking button from waitinglist to attending doesnt work

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1085]
in backend when I hoover over status button in attending list: it says I can move from waitinglist to attending, This doesn't work.

Meanwhile from attending to waitinglist is working
![button](https://cloud.githubusercontent.com/assets/2960236/17448505/00b810c6-5b55-11e6-8e71-424ceff2d240.png)

**Comment by Hoffi1** [comment]
You're right. I'll fix it...
