### ISSUE TITLE
dev4 cbplugin: error notice

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1086]
I get:

Notice: Use of undefined constant _JEMMYATTENDING_STATUS_UNREGISTERED - assumed '_JEMMYATTENDING_STATUS_UNREGISTERED' in /srv/www/vhosts/mysite.ch/httpdocs/components/com_comprofiler/plugin/user/plug_jemmyattending/jemmyattending_cb.php on line 410

**Comment by Hoffi1** [comment]
Hm... maybe your german.php is incomplete?
Please take a look at /srv/www/vhosts/mysite.ch/httpdocs/components/com_comprofiler/plugin/user/plug_jemmyattending/language/german.php vs. english.php.

btw: these texts will be used as tooltip on status icons.

**Comment by jojo12** [comment]
yes, can be closed
