### ISSUE TITLE
FE editing: save and close sometimes not working

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1089]
You see it in some posts: FE editing and create is sometimes not working.
In my case it was with Joomla 3.6.2, and JCE. I was logged in as superuser
The text filter in configuration was set (not by me) for "superusers" to "standard blacklist". 
After changing that to "no filter", save and close worked.
Is this normal? How it is with no superusers which want to enter events?

**Comment by Hoffi1** [comment]
This seems to be a problem of JCE (which isn't part of Joomla, right?)
I tried with J! 3.6.2, JEM 2.1.6 and included editor TinyMCE.
The event will always be saved, regardless which things are configured on Text filter page. The forbidden tags will simply be removed, that's all. I also tried tag ```p``` - funny, but works.

**Comment by diesl** [comment]
I did not try it, what do you propose? is this something to change/fix, or close as wontfix?

**Comment by jojo12** [comment]
I don't know. We can't fix here. But it's good to know, if you encounter such problems in JEM, you've to look in joomla settings "textfilters"
