### ISSUE TITLE
FR-question: author should add an attending user from FE?

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1092]
This is a question from the posts in the forum: We should think about it (the positive and negative)
If an author gets an attending/non-attending e.g. with email, how can he add such users to the list?
If he is administrator - no problem, but he can only access FE?

**Comment by Hoffi1** [comment]
You're right, there's no way on FE yet.
I'll try to spend Manage Attendees view an Add button where users can be added with given status.

**Comment by jojo12** [comment]
sounds good!
