### ISSUE TITLE
FR: FE editevent view and editvenue view should be in a better order

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1093]
after a discussion in forum:
Authors who did not often create events, have problems to see and find
1. The tab "other" should be on second place (attachments all come at the end of a letter) and perhaps it's better to call it "more"
2. Place the Meta Options at the end of "other". A normal user doesn't need that.
3. Place "Recurrence" and "Registration" in the first tab at the end.

I tried these things with overrides. It's very easy.

What do you mean?

**Comment by Hoffi1** [comment]
I think too there's optimization potential.
Must take a deeper look...

**Comment by jojo12** [comment]
my proposal for the first tab of eventedit:
![eventedit](https://cloud.githubusercontent.com/assets/2960236/18225531/7086b848-71f4-11e6-880d-4bdbac1f8f09.png)

**Comment by jojo12** [comment]
My proposal for editvenue:
![editvenue](https://cloud.githubusercontent.com/assets/2960236/18227202/cc31f6bc-721c-11e6-8c76-378b6065f8a2.png)

**Comment by jojo12** [comment]
loud thinking after some experiences with non-experienced people in frontend /witn not all rights.
Because it needs first a place/locality, it would be more logical to fill in in the following order:
WHERE, WHEN and WHAT.  That means: Locality in eventedit should be the first item (even if you can choose noplace).
If I start otherwise (and in Frontend there is no explanation, only some hidden tooltips) and have to choose no_place or break the addevent. If I start with locality, I see very quickly, that I have to create a new event.

**Comment by ernst67** [comment]
I agree with most of your ideas, except for the last one, where you want to change the order into WHERE, WHEN, WHAT. Or maybe I don't understand the reason behind it.

Additionally, I made a suggetion it the tasklist, to allow fields to be switched on or off in the settings.
Not all fields off course, some are mandatory, like title and dates. But meta keywords is something 90% of our users don't want to show, and it only makes submitting much too complex.

In the original Eventlist as Schlu designed it, there was a much simpler Event Submission form. It seems at some point all backend fields were copied to the FE submission screen, resulting in a way too complex form.

**Comment by jojo12** [comment]
@ernst: I agree with your argument about WHERE, WHEN WHAT. (it was an idea, because a lot of my creators start with the event, then after filling the fields they see they forgot to build her new location first. 

About your suggestion in the tasklist: Yes some fields are too much, but when a creator ist experienced it can be good for him (and not only for the admin in backend). 
If you switch that in the backend off, it's only the admin who decides. And there can be cases, in which the creator of an event likes to adapt (because he knows what he is doing).
Therefore I  would say, we should add such things in the additional tab and visibly declare, that normally this should not be touched, only if the creator really knows what he is doing. I mean the customfields are such kind too, because they should be in the additional tab too.

The problem is, we have only tooltips as help in the frontend.

**Comment by ernst67** [comment]
Well, tooltips can help out a lot, as long as the text is clear. 
I understand you thoughts, but I still think the for is way too complex as it is now.

**Comment by jojo12** [comment]
done in JEM 2.3.0 responsive
