### ISSUE TITLE
2.1.7.dev6: problem

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1095]
Hi Hoffi, first of all, thank you very much for your great work. A lot is not for me, but for a lot of users and for our work JEM. A lot of users even don't know, how much you are working on that.

I installed dev 6 fine on a JEM 2.1.6. I added the examples. Then in FE I added a person. after saving I got an error notification:
0 Class 'JemModelAttendees' not found. 

(earlier perhaps when adding a user as author of an event I got some other notification, which I overlooked. I will go back for that.

**Comment by Hoffi1** [comment]
Hm... I thought I fixed this before commit... seems it was really too late.

(ater looking into commit here)
Yes, my last change was not committed - why ever...
In ste/controller/attendees.php(71) above ```$regs = JemModelAttendees::getRegisteredUsers($eventid);``` a line like ```$modelAttendees = $this->getModel('attendees');``` is missing to ensure model file is loaded.
I'll fix this (before) tonight...

**Comment by jojo12** [comment]
Yes, your right: with that, it works fine without error notification.
