### ISSUE TITLE
Maps API Key does not work anymore

### ISSUE THREAD

**Issue by crysix** [jemproject/JEM-Project#1097]
For a few months (I think since 22th june) now the API Key for "new" sites is required from google.
So you cannot use the Maps-API without an API Key anymore (as I said before, only for new sites).

But, if you enter the API key in the JEM settings, nothing happens. You still get Maps warnings in console in front- and backend. And I can't see the API key in the page source (where it should be).

Backend-Error: "This service requires an API key.  For more information on authentication and Google Maps Javascript API services please see: https://developers.google.com/maps/documentation/javascript/get-api-key"

Frontend-Errors:
Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required

**Comment by jojo12** [comment]
I am a lucky man who has the old API key. So for me there's no problem. But I understand the maps should work for new users too! So we need someone who is experienced with Google Maps (and JEM).

**Comment by jojo12** [comment]
What's about that?
https://developers.google.com/maps/documentation/javascript/get-api-key?hl=de

**Comment by crysix** [comment]
With that URL you can generate a new API Key. Thats what I already did!
I entered that new API key in the JEM backend config, but it still says "API key is required".

So for me it looks like the API key field in the backend is not used. An indicator for this is, that the key is not present in the page source (where it should be, as it needs to be transmitted to google). And it is also not transmitted in any request to google service. I checked that.

**Comment by crysix** [comment]
OK I checked a view things.
First JEM makes use of jquery.geocomplete.js version 1.5.0 (https://github.com/ubilabs/geocomplete/)
But there is a 1.7.0 available. But more important they didn't include the API-Key in the request URL here (see view.html.php of edivenue view and admin/venue view):
$document->addScript('http://maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=places&language='.$language);

it should be:
$document->addScript('http://maps.googleapis.com/maps/api/?key=YOUR_KEY&amp;js?sensor=false&amp;libraries=places&language='.$language);

If I have time, I will fix that and add a pull request. But currently I haven't time for this.

**Comment by crysix** [comment]
I created a pull request #1098 for this. Fix was shorter then I thought.

**Comment by jojo12** [comment]
wow, you have no time! Welcome in the team!? I will try to test it. Thank you.

**Comment by ernst67** [comment]
For a person with no time, you're quick!

Thanks a lot for the effort, very appreciated :-)

**Comment by crysix** [comment]
Yeah, working in another big project currently, but the fix was very quick, so as I am looking for it I could directly fix it ;)

**Comment by jojo12** [comment]
I tried inside of an old site where the old keys worked well. And it's working too. No problems encountered.

**Comment by Hoffi1** [comment]
Thanks @crysix, your fix will be part of next version.
