### ISSUE TITLE
JEM 2.2 RC: typo?

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1100]
![typo](https://cloud.githubusercontent.com/assets/2960236/18413140/e30889d6-779f-11e6-804a-1f87a7e747ea.png)
COM_JEM_ADD_USER_REGISSTRATIONS
only one S

**Comment by Hoffi1** [comment]
Déjà-vu - I fixed this ... but overlooked the "Show Icons: No" case.
