### ISSUE TITLE
RC3 pre: after exchanging repared files (not installing) I get an error notification

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1101]
Fatal error: Cannot declare class JemModelAttendees, because the name is already in use in /srv/www/vhosts/kath-jugend.ch/httpdocs/components/com_jem/views/attendees/tmpl/default.php on line 405

EDIT:
sorry, I don't know if this is because I didn't install in a normal way

**Comment by Hoffi1** [comment]
I'll try...

**Comment by Hoffi1** [comment]
I updated to RC2 and then copied the changes of RC3 - no problem found.

But I wonder why line 405? On my site this file has 165 lines only. It seems there is something like ```<?php class JemModelAttendees ...``` pasted by your clipboard into this file without your knowledge?
(really no sarcasm, please take it with smile, regardless if I'm right or wrong)

**Comment by jojo12** [comment]
sorry I made a mistake! Can be closed
