### ISSUE TITLE
Add Openstreetmap as Google Map alternative to display venues

### ISSUE THREAD

**Issue by diesl** [jemproject/JEM-Project#1103]
Currently, only Google Maps can be used to display venues in a map. [Openstreetmap](http://osm.org) is a free alternative that suits perfectly to JEM.

**Comment by Hoffi1** [comment]
:+1:

**Comment by diesl** [comment]
I want to clean up a bit and suggest to remove the settings
- _Top Level Domain of Google Maps Homepage._
- _Google Map language_

which are available after **Choose Map Service** is set to _Display Google Map_. 

Reason:
- I think these settings are not important because the map is then displayed as if the user is visiting the maps.google.com website. Google most likely displays a language that is convenient for the user.
- The _Google Map (Api-key)_ option does not use the setting

@Hoffi1 comments?

**Comment by jojo12** [comment]
Are you talking about Backend?
Because in the settings, this is not anymore there (is away just longtime ago)!

**Comment by diesl** [comment]
> Are you talking about Backend-Programming?
Because in the settings, this is not anymore there (is away just longtime ago)!

Yes, in the backend. It is only visible when selecting _Display Google Map_

**Comment by jojo12** [comment]
I think, the experience with Google Map had after all @Bluefox.
Hoffi is very skeptical with Google.
So @Bluefox should answer here.
For me as user, if this doesn't concern the other settings like api keys, I agree.

**Comment by Hoffi1** [comment]
> @Hoffi1 comments?

No comment. Let's say it so: I don't have a local clone of google so I can't develop/test. :grinning: 
I don't know the API in detail so I can't give a qualified comment.

btw: What's about client id? I'm not sure if this is (a) relevant, (b) overall correct implemented (FE/BE, event/venue, ...)

**Comment by diesl** [comment]
> What's about client id? I'm not sure if this is (a) relevant, (b) overall correct implemented (FE/BE, event/venue, ...)

I think it *should* work, but I have to check the docs once again.

Another question, do we need separate settings concerning map display on the event page? I would say no. For instance, nobody would use Google Maps as general map and Openstreetmap on the event page. So I would remove this setting and leave only a **show map?** yes/no option

**Comment by Hoffi1** [comment]
> Another question, do we need separate settings concerning map display on the event page?

Without knowing the details of e.g. the different google modes I would say one general block to configure the maps and on/off switches on the views (venue, event, maybe venues with multi markers).
Could be more options would be useful per map, but GM vs. OSM, keys etc. are global in my eyes.
(or short: I agree :wink: )

**Comment by jojo12** [comment]
Hi, where are you with that? A long time passed!

**Comment by jojo12** [comment]
There's a post from AlainR with a procedure to use OSModul and with pins to all venues in one map!
This looks very good. If it's possible to work with that, it would be great!
![osmultiple](https://user-images.githubusercontent.com/2960236/27985464-9149d1e8-63eb-11e7-8935-f19b59122bf7.png)

**Comment by jojo12** [comment]
There's also a plugin from a_kuechler which let you insert in articles and e.g. venue descriptions an openstreetmap in the html sourcecode. It's a bit more complicated but it works fine! osm_akuechler at github.
