### ISSUE TITLE
FR: enable visibility of attending status for all registered users

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1105]
I've seen this wish in some posts in the forum. And for some cases I understand.
How is it possible to give access to all registered users. Does this need a decision to enable or disable this.

Me personally, I don't need this. But as feature can be good.

**Comment by Hoffi1** [comment]
Enhancing the model to provide this info is easy but it should be configurable.

**Comment by jojo12** [comment]
In a post of our forum there is a hack from 19flashover69 #22875 to resolve this.
It's working but registrated people can then delete users and/or change their attendee status.
It's not so good to hack this like that. It would be better to give soon a possibility more safe!

**Comment by jojo12** [comment]
is this possible? This would really fulfill the attend/not attend feature.
