### ISSUE TITLE
Bug in JEM2.2: In BE I can add attending users with attending status even when registration on event is disabled!

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1107]
Hi,
I added in BE attending users, but they were not shown in FE, because FE eventregistration was not enabled.
(settings in BE: optional, in FE not activated.)

But the attending users are saved, but hidden in FE.

(Perhaps in Backend it needs a notification, that eventregistration for this event is not enabled ...)

**Comment by Hoffi1** [comment]
You're right, there should be a notice shown.
