### ISSUE TITLE
bug: strange date shown, when creating a recurrence

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1110]
Hi, when I edit an event and want to make it recurrent, there is a strange date inserted (see image).
This seems not to be a problem to create recurrence, but it's a bit strange!
![rep](https://cloud.githubusercontent.com/assets/2960236/19383593/832bda92-9205-11e6-8b36-4a3e914da927.png)

**Comment by Hoffi1** [comment]
This field "recurrence_limit_date" is defined in /administrator/components/com_jem/models/forms/event.xml as type calendar with default="now".
Corresponding this I see current date if I try to reproduce.

Have you used an existing with with possibly crazy value in db? (but on my tests I couldn't type in crazy values on db - I always got current date or empty field)

btw: The date you show is the November 30 of year 1 B.C. :grin:

**Comment by jojo12** [comment]
I didn't change anything.
I created an event with the date of coming 21 of october and saved.
I reopened this event, went to the third tab with recurrence and opened (dayly, but the same with weekly too).
It's filled in the date like the image some posts ago.
Now I saved the event with dayly (each 1 day).
I reopened: instead of a date is now written: "unendlich" and the event is repeated until the given end of recurrence 23 of January.

**Comment by Hoffi1** [comment]
Sorry but I can't reproduce this, there seems to be something different with your site.
Backend and frontend use the same form containing the calendar form field. In case of a saved event the value is '0000-00-00' which is detected by JHtml::calendar() as invalid date so an empty string is shown. I don't see any way in code to produce something like "-1-11-30".

If you don't have template overrides of editevent view the only idea could be a file /components/com_jem/models/fields/calendar.php which shouldn't be there. But this should also influence the start and end date fields. No idea...

**Comment by jojo12** [comment]
I've no overrides on the tested website and I've tested with protostar. But for me this is not a problem.
(I encountered this while checking the post from Herkle "No more recurrence")
If no others can reproduce, then sorry I've stolen your time.

**Comment by jojo12** [comment]
After uninstalling und reinstalling JEM 2.2.0 stable on a clean Joomla! 3.6.2 with php 7.0.9, I retried.
If you try to reproduce, please try it step by step.
1) creating a category "Testcategory" in backend and saving.
2) opening a new event "Testevent" in backend and (only) looking in recurrence. Is prefilled with date of today when choosing e.g. "dayly".  Then "cancel", so the new event is not saved.
3) The same like 2) but in frontend = the same result.

4) Creating  a new event in frontend, only with "Testevent" in "Testcategory", the start date e.g. from today (17.10.2016) and start time 19:00 h. Saving this event.
5) Then reopening this event in frontend, then opening "Recurrence".
    Results in the descripted bug in Recurrence Counter is  "-1-11-30"
