### ISSUE TITLE
bug in frontend atttendeemanager: no date of inscription in exportfile

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1111]
Hi, from a post of Kralyk:
when I export the attendees in frontend, there is a header of a column with "Anmeldedatum" but no date in the column!
I can reproduce this. And this is not so heavy but not nice!

**Comment by Hoffi1** [comment]
Uhm...yep. A little typo creates this effect.

**Comment by diesl** [comment]
I took a look at the code too, and having the big picture in mind, it is really messy. Big parts of the code in FE and BE are identical, but with different variable names, FE code in controller, BE code in model. 👎

**Comment by jojo12** [comment]
I know this, but these things are just very old. If you want to change it, it will be big work, I fear. 
And "never change a winning system".
