### ISSUE TITLE
bug/strange in frontend lost attendees

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1112]
Hi,
Eventregistration is yes
I have 7 attendees, I see them in Frontend and Backend.
In Frontend editevent I wanted to change the maximum of participants I had 14, made 0 for unlimited.
After saving the whole part of attendees in event view is away (like there is no eventregistration.
In backend they are still there. Any hints?

**Comment by jojo12** [comment]
sorry, it seems there is a problem in my template override of event view!
Can be closed

**Comment by diesl** [comment]
@jojo12 Could you add the *invalid* tag to issues that were falsely entered as bug? It helps to distinguish between the real and the false ones afterwards. Thanks! 👍

**Comment by jojo12** [comment]
yes, sorry
