### ISSUE TITLE
Problem with contacts (bigger IDs)

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1116]
There's a new post form mickspice. 
Adding a newer contact on JEM 2.2.0 and Joomla 3.6.4 doesn't work. Nor in backend nor in frontend.
He has some more informations in the post!  #23002	
EDIT:
I tested: it seems contact IDs > 127 aren't accepted
I tested 123 ok
I tested 125 ok
I tested 128 not ok
I tested 129 not ok

**Comment by Hoffi1** [comment]
Good catch! :+1: 

The field contactid of events table is wrongly specified as tinyint which limits to -128..127.

**Comment by jojo12** [comment]
did not try the dev2, but with manual change it works best now! Thanks!
