### ISSUE TITLE
Bug? users can create events in all categories

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1119]
There's a thread #23376  in the forum.
I tried and it seems during creating you can see all categories (not only the allowed ones).
Would be good if others could test too! I remember earlier the forbidden categories were hidden.

**Comment by Hoffi1** [comment]
Hi @jojo12, hadn't seen a problem.
All categories user is allowed to see are listed, but only those user is allowed to attach events to are selectable.
And if the user is also member of a Joomla group like Author (s)he has general add-event permission for all categories.

**Comment by jojo12** [comment]
thanks for looking in it. Sometimes the permissions are a book with seven .... 
Can be closed.
