### ISSUE TITLE
error 2.2.1-dev4: in Backend event view

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1128]
Notice: Undefined variable: selDisabled in /mysite.ch/httpdocs/components/com_jem/helpers/helper.php on line 649

**Comment by jojo12** [comment]
The same in BE venue view

**Comment by jojo12** [comment]
I updated before from a fresh JEM 2.2 with a package made from 2.2.1-dev4

**Comment by Hoffi1** [comment]
Yes, found this too. Already fixed but not pushed to server yet.
