### ISSUE TITLE
irritating error notice when creating new event

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1130]
I don't know exactly when started  this:
when e.g. creating a new event in BE and save it, I get a error notification:
![err1](https://cloud.githubusercontent.com/assets/2960236/25408362/036bc0a0-2a0e-11e7-8964-c2be139b7c43.png)
but the event is saved. When saving again, there are two same events.

this time it was on dev6

I tried on FE too:
Fehler
Speichern fehlgeschlagen! Fehler: COM_JEM_EVENT_ERROR_STORE_CATEGORIES

**Comment by Hoffi1** [comment]
Hm... if the code is exactly from GitHub (especially admin/models/event.php) this message means that there was a problem while storing category - event relations in DB - maybe inserting new categories or removing obsolete ones.

Unfortunately the event itself is not removed (rolled-back) so we have this "intermediate" situation.

And yes, on FE the text is missing, thanks.

**Comment by jojo12** [comment]
Hi, it seems I found the solution of the problem.
It was after importing categories.
I have now rebuild the category system with the butten, now the error notice seems away.

**Comment by jojo12** [comment]
From which file comes this error notice?
COM_JEM_EVENT_ERROR_STORE_CATEGORIES

**Comment by Hoffi1** [comment]
@jojo12 , I pushed the missed strings.
But I can't reproduce your problem. The code itself is correct.
Of course, you can comment out line 368 ("$saved = false;") and maybe 369 too but I fear your database is corrupt. - Or your database works different.
Just an idea: in admin/models/event.php(436ff) you'll see 
```
if (!is_array($cur_cats)) {
    return false;
}
```
Change this to
```
if (!is_array($cur_cats)) {
    $cur_cats = array();;
}
```
Normally ```$db->loadColumn()``` should return an empty array if no entries where found. But maybe it return null instead which would abort the function.

But also possible that one of the other two queries fail...

**Comment by jojo12** [comment]
yes, it seems and I fear you're right.
I reinstalled dev6 completely new and the error notices were away.

**Comment by jojo12** [comment]
can be closed
