### ISSUE TITLE
adapt modified 'calendar' field of J! 3.7

### ISSUE THREAD

**Issue by Hoffi1** [jemproject/JEM-Project#1131]
With Joomla! 3.7 the calendar field (edit field to type in date/time) has exchanged. The new one has improved and e.g. shows additionally drop down boxes for time.

(a) Because we have dedicated time fields they should be hidden in calendar popup.
(b) On Export view something is crazy. Instead of a form (xml) the calendar field is added directly via JHtml::_() - and looks somehow crazy. The Close button is within the calendar table instead of a dedicated area below - solutions welcome! (for this part I've no idea yet)

**Comment by jojo12** [comment]
welldone!

**Comment by ernst67** [comment]
Trying to understand what impacts this..? I've tested, and see no difference in the New Event form (backend)?

I was also wondering abot the drom downs we currently have for start- and endtime. They've been introduced after EL 1.0.1, but are so annoying. Entering an event takes longer as it requires mouse action. 
Can we revert to plain old keyboard entry?
I'd be more than happy to do the actual work and go over the forms...

**Comment by jojo12** [comment]
As much as I understand: the new joomla 3.7.0 has a js-calendar with datetime picker in one, but packs date and time in one field. This gives problems with our separate date and time. The solution is to have only a date picker in jem.
Better would be to have a date time picker and then to send them in separate fields. 
But this needs a complete rebuilding of the date time part. And I remember there was years ago a long search and discussion (even in bluefox times).

**Comment by Hoffi1** [comment]
Guys, this time input method we don't love in JEM is what the new date/time picker in Joomla! 3.7 provides to the world! 😆

**Comment by jojo12** [comment]
yes, you're right, I see. But it's better to have date and window in one modal (not in one field). I think.

**Comment by jojo12** [comment]
I found a new problem: with joomla 3.7.0 you can not  change a date in the line! If you change there and save it, it's the old date! You are forced to take datetimepicker

**Comment by ernst67** [comment]
Grrr..... get's worse by the day :-(

**Comment by Hoffi1** [comment]
@jojo12, same bad behaviour as color picker (used e.g. on categories). You have to finish your input with Enter key.
But that's a post for the Joomla forum / bug tracker, not here. I can't fix all the Joomla code too. 😉

**Comment by jojo12** [comment]
I know. I was only collecting new strange behaviour for us inside of joomla.

**Comment by ernst67** [comment]
Are we obliged to comply to "standard Joomla behaviour" if there are good reasons not to do so?

**Comment by jojo12** [comment]
I don't understand your question: I see, that with updating to joomla 3.7.0 the behaviour inside of JEM changed too. If you don't want that, you have to persist in earlier joomlas to start programming beneath joomla (both are not good ideas in my mind). So we can hope there will be a change back in joomla (it's discussed in issue tracker!)

**Comment by Hoffi1** [comment]
@ernst67 Yes we are. Or we have to implement all the things ourselve, loosing the date picker and having a simple text field with a lot of code to hopefully understand all the different ways to write a date around the world. Also we would get a lot of overstrained users not able to press ordinary keys instead of touch and swipe. Not my way, but maybe that's the entropy increase of the universe...

**Comment by ernst67** [comment]
@Hoffi1  OK, clear. 
I think it's a step backward for people using a PC environment, and want to use keyboard entry. Much quicker than touch and swipe methods.
As far as I understand you've chacked the admin backend. Does that still leave the front end editing / entry of events left to-do?

**Comment by Hoffi1** [comment]
regarding (b) (problem on Export view):
This will be fixed with next Joomla 😉  (see https://github.com/joomla/joomla-cms/issues/15569)

@ernst67 : sorry for my bad english but what do you mean with "chacked"? With v2.2.1-dev7 I changed the editevent views on BE and FE to hide the time fields of calendar popup for out start and end date fields. The only thing was the Export view on BE which I found out yet is a bug in Joomla. To also prevent the time fields shown there (with fixed Joomla) I need to adapt this view too. This will coming soon so this ticket will be fixed then from my point of view.

**Comment by ernst67** [comment]
Sorry for the typo.. I meant 'changed'. 
OK, I get it, both FE en BE changed. Thanks!
