### ISSUE TITLE
strange: only english mailer notifications

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1136]
I have a JEM site multilingual with a general en-GB, but then de-DE, fr-FR and en-GB languages. The event views all work well each in his language. But the mailer notifications are all in en-GB, even when all languages in mailer plugin are installed. How can I change that?

**Comment by Hoffi1** [comment]
If your site's default language is set to de-DE mailer plugin will use the German languga file. There is nothing else you have to do.

**Comment by jojo12** [comment]
That is the strange thing. The default is de-DE but I get english mails
