### ISSUE TITLE
http://-Links should all be changed to https://-Links

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1137]
see  #23610 from stevent in the forum: "Geocoding latitude/longitude of a venue" 
if not ssl users have problems with the maps

**Comment by jojo12** [comment]
There are a lot of http:// Links which can be called with https://
If not addressed with https:// we get mixed pages = unsafe

because there is a call for safe pages with ssl. We need to change that.
This is in geomap js files too!

**Comment by Heklaterriol** [comment]
did it in JEM4
