### ISSUE TITLE
Google maps not displayed when sites move over to https

### ISSUE THREAD

**Issue by ernst67** [jemproject/JEM-Project#1142]
Sites that run under https fail to load the google map, as it calls a http url.

probable solution: calling Gllogle map url via https.
Most probably, including a https url into a http Website does not run into problems, but the other way round will. 
But that should be tested. 

Refer to the issue here: 
http://www.joomlaeventmanager.net/forum/jem-2-2-x-on-joomla-3/10076-issue-with-venue-map-on-https-site?limitstart=0#23499

**Comment by jojo12** [comment]
There's a cheap possibility to get https with let's encrypt. Will encrypt the conversations between user and site

**Comment by jojo12** [comment]
Sorry, but it's not so easy!
When I try in frontend or backend to create a new venue and I want a map, I have to click on a checkbox.
when I make this in my site in http://, this opens a grey canvas and so on and later here comes the map
when I make this in the same site in https://, there is no grey canvas and I can never e.g. move the pointer.
I changed from http to https and back.
(in venue view and event view the map is there!)

There must be an other kind of programming for this. Who knows something about that?

**Comment by jojo12** [comment]
Because more and more people will go to https (will be forced), this is an important bug which needs to be resolved as quick as possible!

**Comment by jojo12** [comment]
Perhaps this has to do with:
https://stackoverflow.com/questions/22456131/js-not-working-under-ssl-in-rails

**Comment by jojo12** [comment]
In the console (facebook) I get
Laden von gemischten aktiven Inhalten "http://maps.googleapis.com/maps/api/js?key=MYAPIKEY&sensor=false&libraries=places&language=de" wurde blockiert.[Weitere Informationen] editvenue
Laden von gemischten aktiven Inhalten "http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" wurde blockiert.[Weitere Informationen]

EDIT: I found it: in editvenue/views/editvenue/view.html.php there is a http:// too. When I replaced that, it works!
