### ISSUE TITLE
a lot of deprecated in Joomla! 3

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1144]
When I check with JED checker, there are a lot of deprecated in Joomla! 3.
Why not update this?

**Comment by jojo12** [comment]
@Hoffi1 : There should not be all to do up to you. If you can say me what I can do, I will do it. I think we need a better sharing of duties.

**Comment by Hoffi1** [comment]
I checked and "fixed" nearly all reasonable issues of JED Checker.
The only things left are all the JError lines. They must be fixed before Joomla! 4.0 but there is no simple search'n'replace possible.
