### ISSUE TITLE
ajax calendar module 2.2.0 has problems with multilingual

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1145]
changing the language the normal calendar module 2.2.1 changes the monthname too.
The ajax calendar module stays with the old language.

**Comment by Hoffi1** [comment]
Please set module's option "Joomla language Day/Month?" to Yes.

If this option is set to No the system language will be used. This could be made user-depending by using setlocal() but this is no good idea and may cause problems on multithreaded servers.

I don't know the reason for this option. Maybe there is one so I wouldn't remove the option.

**Comment by Hoffi1** [comment]
@jojo12 Does this option solve your problem?

**Comment by jojo12** [comment]
the new mod_jem_cal with ajax 2.2.3 dev1 has resolved this!
