### ISSUE TITLE
JEM 2.2.1 error on Jem_module_basic

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1147]
Hi, there seems a problem insidie jem_module_basic. (Joomla 3.7.4 and JEM 2.2.1)
There is a post in forum which brings this issue. 
In my case I get this error (see image)
![errmodjem](https://user-images.githubusercontent.com/2960236/28816593-a832760e-76a5-11e7-9681-e12d28349482.png)

EDIT: 
there seems a mismatch between module_basic and module_teaser

EDIT 2: sorry, it seems there is a mismatch in my, will try more!

**Comment by Hoffi1** [comment]
Tried but on my testsites I have no problems.
The class is defined in helper.php which is loaded by mod_jem.php

**Comment by jojo12** [comment]
Sorry, during testing I made a mistake. I tested now on a clean Joomla-JEM-CB install. No problems there.
Can be closed!
