### ISSUE TITLE
finish with supporting Joomla 2.5 to save up code

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1150]
three years after the support finish of Joomla 2.5 it's time to finish. It's ok to hold the possibility to change from 2.5 to 3.+, But the code could be cleaned up and make place for enhancements for Joomla 3+. It's time now!

**Comment by Hoffi1** [comment]
At the moment I don't see any need to actively remove code working fine. This will cost some rare time and give you absolutely nothings.
If we add things which collide with old code than ok. But at the moment I don't see such situations.

**Comment by jojo12** [comment]
I think e.g. the venueslist. You there said, we've not enough codespace to add this. 
I think the responsive proposals of egnarts should be integrated in core JEM....

**Comment by Hoffi1** [comment]
The first sentence I don't understand. I said that we have a lot of views, some of them doing nearly the same (e.g. calendar, category calendar, venue calendar view). So changes must be made multiple times. But this has nothings to do with J! 2.5 support.
Regarding venueslist I understood it's useful and I'll see how to integrate this.

The responsive proposals I've not followed so far so I can't say something about this yet. But yes, this would be not working on a J! 2.5 site. (but personally on a J! 3 site I need a template working together with a beez3-like site template)

**Comment by jojo12** [comment]
thanks, this sounds much better: there is a need of supporting all core  joomla! 3 templates. This means the not responsive beez 3 and the responsive protostar. it's not anymore joomla 2.5 and joomla 3.5! It's only joomla 3.5+.
