### ISSUE TITLE
mod_jem: adding "no events" would be good

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1151]
In the forum there was the discussion how to add "no events" to mod_jem. Egnarts  brought a solution which should be integrated into mod_jem! (I will not do any pull requests!)

**Comment by Hoffi1** [comment]
I will add an option so site admin can decide to show a text or fully hide the module if no events were found.
This will come on Basic, Banner, Teaser, and Wide module. (I think on Jubilee module it doesn't make really sense to hide the module, isn't it?)
