### ISSUE TITLE
TO DO: update libraries

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1152]
Stevent wrote in the forum:
I know you developers are doing your best, but I think there should be a list of all the external libraries used, and someone should check regularly on updates.

There's one other library I could find: the icalcreator.class which is outdated as well.
Version used: 2.20
Current version: 2.23.20

github.com/iCalcreator/iCalcreator
EDIT: Caution in the old class is written: "Do NOT remove or change version!!"

**Comment by jojo12** [comment]
Stevent wrote too:
Just curious: the latest version of JEM uses the 2.2.3 Zebra Image library, dated juli 2013. Shouldn't this be updated to the latest version 2.2.6 (may 2017)?

**Comment by Hoffi1** [comment]
Good point. 👍 

I checked Zebra_Image 2.2.6 which can rotate an image depending on exif orientation. So yes, we should update this.

iCalcreator seems to be a little bit more complicated. We use a single file where the package contains a lot if files. Maybe they were simply concatenated?
So checking the differences is a bit more complicated and needs more time.
(@JKoelman do you remember and can tell something about this in the past?)
