### ISSUE TITLE
error notification in jemlistevents 2.2.2.dev1 

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1154]
Notice: Undefined variable: style in /srv/www/vhosts/mysite.ch/subdomains/intra/httpdocs/plugins/content/jemlistevents/jemlistevents.php on line 143

EDIT: 
when I try with {jemlistevents} in article

**Comment by jojo12** [comment]
when I try with the example
{jemlistevents catids=2,14,62;venueids=3;max=5;cuttitle=25;noeventsmsg=nothing going on}
I get:
Notice: Undefined index: no_event_msg in /srv/www/vhosts/folk-tanz.ch/subdomains/intra/httpdocs/plugins/content/jemlistevents/jemlistevents.php on line 380

**Comment by jojo12** [comment]
SOLVED
replace in line 380 "no_event_msg" with "no_events_msg", then the second error notification is away

**Comment by Hoffi1** [comment]
Thanks for finding. Will be fixed soon...
