### ISSUE TITLE
2.2.2 dev 3: there are no changes to https://

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1155]
#1143
if you use https, you get problems, if you have inside the code links to http.
Meanwhile you don't get problems, if you use http and the links go to https.

So, why you don't change  ??? Why this seems not possible???

**Comment by Hoffi1** [comment]
I don't understand your emotions! I never sayed it's changed, so yes, it isn't touched yet.
(a) there are more than enough tasks so I can't fix them all
(b) I'm not able to test https so all changes would be totally blind resulting in high risk of time-eating ping-pong

**Comment by jojo12** [comment]
Thanks for your answer now. There were a lot of post concerning this, you never answered.
@a: I know and I appreciate your work. Such things could easy be done from others. In my sites I made it and it worked. 
Then we get an update and have to redo all. This is annoying.
@b: how can we test this. How can others contribute?
