### ISSUE TITLE
 jemlistevents 2.2.2.dev2 doesn't work

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1157]
Meanwhile the plugin from hekla works with only {listevents} or with additional conditions,
this version of jemlistevents doesn't work:
not when I use only {jemlistevents}
EDIT:
when I use the adapted exemple with conditions, it works

**Comment by jojo12** [comment]
when I take away all conditions, but I leave a place {jemlistevents }
then I get results like set in the plugin, but I get the error notification:
Notice: Undefined offset: 1 in /srv/www/vhosts/mysite.ch/subdomains/intra/httpdocs/plugins/content/jemlistevents/jemlistevents.php on line 148

**Comment by Hoffi1** [comment]
The second one I found and fixed (really line 148? on my plg it's line 168).

The first one is a bug or feature of the article editor.
Please toggle editor to plain mode and remove the "<span ...>" between "{" and "jemlisevents" as well as the "</span>" behind closing "}".
I don't know why the editor swaps span tag and curly brace. On plugin page it's shown correct and would work regardless if span tag would be copied too or not.

**Comment by jojo12** [comment]
I tried - it doesn't work with only the {jemlistevents}.
And this can not be a solution
And I don't understand why someone should use this backway to get results. All other plugins I know and the listevents-plugin of hekla work in the normal way!
must be fixed!

**Comment by Hoffi1** [comment]
Your wording is inacceptable! I don't like to invest my precious time to get such posts.

Back to the theme: In this special case the problem is the pattern which expects at least a space between ```jemlistevents``` and closing curly brace.
I will change the pattern to also handle this case.

**Comment by jojo12** [comment]
sorry for my wording, Perhaps I used wrong words. I try to talk with thhat what I think it's english.

**Comment by jojo12** [comment]
no it works best, thanks a lot! [And once more sorry!]
