### ISSUE TITLE
Module helpers should contain additional lines for custom fields

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1158]
Long time ago hekla postulated this addition in the helper files of the modules. So in overrides the people who want can add custom fields in the modules! It would be very helpful! Please!
	
   		 $lists[$i]->custom1  = htmlspecialchars($row->custom1, ENT_COMPAT, 'UTF-8');
			$lists[$i]->custom2  = htmlspecialchars($row->custom2, ENT_COMPAT, 'UTF-8');
			$lists[$i]->custom3  = htmlspecialchars($row->custom3, ENT_COMPAT, 'UTF-8');
			$lists[$i]->custom4  = htmlspecialchars($row->custom4, ENT_COMPAT, 'UTF-8');
			$lists[$i]->custom5  = htmlspecialchars($row->custom5, ENT_COMPAT, 'UTF-8');
			$lists[$i]->custom6  = htmlspecialchars($row->custom6, ENT_COMPAT, 'UTF-8');
			$lists[$i]->custom7  = htmlspecialchars($row->custom7, ENT_COMPAT, 'UTF-8');
			$lists[$i]->custom8  = htmlspecialchars($row->custom8, ENT_COMPAT, 'UTF-8');
			$lists[$i]->custom9  = htmlspecialchars($row->custom9, ENT_COMPAT, 'UTF-8');
			$lists[$i]->custom10 = htmlspecialchars($row->custom10, ENT_COMPAT, 'UTF-8');

**Comment by jojo12** [comment]
I can do it, if you accept (but if and how, it's up to you to decide!

**Comment by Hoffi1** [comment]
That's easy to add, can I made in some minutes.
