### ISSUE TITLE
Bug in 2.2.2dev3:  from eventsview to attendees list 

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1161]
Hi, I've found a bug:
as author of the event (and as registrated for the event), I can click on the number of attendees and come then to the list of attendees. This was in 2.2.1

In JEM 2.2.2 dev 3: Instead of the attendees list, I get there an error notification:
0 Call to a member function get() on null

**Comment by jojo12** [comment]
does this help?:

Call stack
--
# | Function | Location
1 | () | JROOT/components/com_jem/classes/output.class.php:701
2 | JemOutput::backbutton() | JROOT/components/com_jem/classes/output.class.php:113
3 | JemOutput::createButtonBar() | JROOT/components/com_jem/views/attendees/tmpl/default.php:45
4 | include() | JROOT/libraries/legacy/view/legacy.php:694
5 | JViewLegacy->loadTemplate() | JROOT/libraries/legacy/view/legacy.php:229
6 | JViewLegacy->display() | JROOT/components/com_jem/views/attendees/view.html.php:139
7 | JemViewAttendees->display() | JROOT/components/com_jem/controller.php:101
8 | JemController->display() | JROOT/libraries/legacy/controller/legacy.php:709
9 | JControllerLegacy->execute() | JROOT/components/com_jem/jem.php:44
10 | require_once() | JROOT/libraries/cms/component/helper.php:389
11 | JComponentHelper::executeComponent() | JROOT/libraries/cms/component/helper.php:364
12 | JComponentHelper::renderComponent() | JROOT/libraries/cms/application/site.php:191
13 | JApplicationSite->dispatch() | JROOT/libraries/cms/application/site.php:230
14 | JApplicationSite->doExecute() | JROOT/libraries/cms/application/cms.php:265
15 | JApplicationCms->execute() | JROOT/index.php:49

**Comment by jojo12** [comment]
I think, the problem is in output.class.php.
When I add in the 
	static public function backbutton($backlink, $view)

		$jinput = $app->input;	(which was in version 2.1.7)

then the attending list is opened with no error!

What was the reason to oppress it? Forgotten or a real reason?

**Comment by Hoffi1** [comment]
Oops... Yes, you're right. I overlooked one ```$jinput``` - will be fixed soon.

Generally I partially replaced ```$jinput``` by ```$app->input``` to avoid the additional local variable and so hopefully reduce memory consumption a bit. But then I have to replace **all** of them within a function, of course.

Thanks for finding this, @jojo12  👍
