### ISSUE TITLE
I don't understand some words!

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1163]
What does mean:
"No group successfully trashed" = "Keine Gruppe kam erfolgreich in den Papierkorb" ???
"No venue successfullty trashed"
usw.

**Comment by Hoffi1** [comment]
This is part of Joomla's plural feature. You can define one default string but also strings for any specific number you want. Here JEM will say the number of items user requested was successfully moved to trash. And one of the theoretically possible numbers is 0.

**Comment by jojo12** [comment]
Would it not make more sense to write:
No group trashed =Keine Gruppe in den Papierkorb verschoben
und
1 group successfully trashed = 1 Gruppe erfolgreich in Papierkorb verschoben.

**Comment by Hoffi1** [comment]
"No group trashed" does not indicate if this was expected or a problem.
Also as alreaady sayed in case of action on no items a text in form "please select items" will be shown instead so discussion about this is pure philosophical.

**Comment by jojo12** [comment]
I am now a philosopher
