### ISSUE TITLE
JEM2.2.2 with php7.1: error notification

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1165]
In some sites I get an error notification when notifications are on:

Warning: A non-numeric value encountered in /srv/www/vhosts/mysite.ch/httpdocs/components/com_jem/classes/image.class.php on line 196

when I read some infos via google, it has to do with a new notification with php 7.1

EDIT: meanwhile it works best when notifications are off

EDIT2: I tried on the same page with php 7.0 and there's no error notification.

**Comment by Hoffi1** [comment]
Seems you cleared Basic Settings - Image Handling - Max. Height of Thumbnails 😉 

Will be handled with v2.2.3-dev4...
