### ISSUE TITLE
JEM 2.2.2 stable: no googlemap in editvenue because of http://

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1166]
after update there is no googlemap in editvenue,
when I change in views/editvenue/view.html.php 
line 156 and line 162 from http:// to htpps://
it works best!

i addition in output.class.php:
Line 782
line 795
line 805
I didn't find these because I have a CORE hack for output.class.php

I don't understand, why this was not changed with fixing the older issue #1155, perhaps overlooked.

**Comment by Hoffi1** [comment]
Don't know why but somehow three files were not pushed to GitHub.
