### ISSUE TITLE
JEM 2.2.2 with Joomla! 3.8 error notification with inserting time in backend and frontend

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1167]
0 DateTime::__construct(): Failed to parse time string (-1-11-30) at position 5 (-): Double timezone specification 
I had first a opendate, then I wanted to insert a date (not via calendar- inserting directly), then I got the notification above.
(but only once - I have to retry)

**Comment by jojo12** [comment]
to reproduce problems in backend: in a clean JEM 2.2.2 on a clean Joomla! 3.8.1 with php 7.1.8 on protostar template
I have an event with a date.
To get an open date, when I delete date directly in the field (not with the calendar) and save
first during the save there is 0000-00-00 00:00:00 and changes then to 2017-01-11 (today is 2017-10-13)
when I use within the calendar the "leeren"button and save
first during the save there is 0000-00-00 00:00:00 and changes then to 2017-01-11 (today is 2017-10-13)
very rarely 2 times I got there the message in the first post. But at the moment I can't reproduce anymore. the same was in the enddate field.

In Addition:
When I use in the enddate "leeren" I get the same 0000-00-00 00:00:00 and then a
"Not saved: End must be before startdate"
this is bad, because I need no enddate, when the event is only one day!

**Comment by jojo12** [comment]
Similar problems in frontend!

**Comment by Hoffi1** [comment]
One more bug caused by Joomla!
With J! 2.5 - J! 3.6.x all works perfect, but the new, stupid calendar field since J! 3.7 causes these problems.
Will be workarounded soon...
