### ISSUE TITLE
question about procedure between attending and waitinglist

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1170]
There's a good question of Jebavy in the forum

> https://www.joomlaeventmanager.net/forum/jem-2-2-x-on-joomla-3/10245-waitlist-good-feature,-but-could-be-better#24501

if the attending list is full, the next is automaticly put on the waitinglist.
How this works when after an attending user is canceling his attending:
does the next new user will come on the attending list (because there is one place free)?
If the system would be fair, the new attending user is coming on the waitinglist too and the organiser can decide which one on the waitinglist will be changed onto the attending list. Or is there an automatic way, that the first on the waitinglist will be changed auatomaticly onto the attending list?

**Comment by Hoffi1** [comment]
If a user changes it's registration from "I'll attend" to "I can't attend" first user on waiting list will automaticly become attendee.
If an admin plays with registrations on backend (s)he must know how to handle this fair.

**Comment by jojo12** [comment]
yes,I found this too,but had no time to post here. It works like wanted
