### ISSUE TITLE
Urgent enhance: Admin lists need list_limit

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1171]
the admin lists events, venues and categories need a list_limit field. Only like that you can work good as admin, if you have more than 20 items in a list.  It's a must to be able to list more than 20 items on one page!

**Comment by Hoffi1** [comment]
This is caused by Isis template since J! 3.7.
Fix will follow...

**Comment by jojo12** [comment]
I tried it: it's there, but on bottom of the page, where I don't look for it. It would be better to be on the same place like in joomla articles... on top right beneath the filter!

**Comment by Hoffi1** [comment]
This would require to have complete page identical to articles page which will limit JEM to be compatible to J! 3.8 compatible or a lot of special code to find the best way for each Joomla version.
At the moment I don't have the time (and motivation) to rewrite the views, sorry.
