### ISSUE TITLE
adding a hint in the placeholder for dates and enddates

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1172]
It depends on the country how you would like to enter a date. Because Joomla! has only one possibility there are a lot of mistakes you can do, entering the date directly. For this it would be better to add a hint inside of the date field. something like "please use the calendar button". You can do it with a key, so you have a translation for each language!
EDIT1
if you don't know how, I know it.
EDIT2:
There could be better solutions but they will be much more complicated.

**Comment by Hoffi1** [comment]
@jojo12: I tried to find a good solution not too complicated for me - I hope you like it. 😃 
Can you create a full package from v2.2.3-dev3 and play around with it? I also changed some modules.

**Comment by jojo12** [comment]
Wow, how you managed it that it's possible now to insert 31.12.2017?
Does it works for other date systems too? Or do they have now a problem?

**Comment by Hoffi1** [comment]
No problem, I just motivated the (Joomla) calendar field to translate the format to user's language. The date itself is always stored in same form so reading from DB is exact as before.

**Comment by jojo12** [comment]
In german it works well. I tried with changing language to english, but the hint was the same

**Comment by Hoffi1** [comment]
Sorry, but I can't reproduce your problem.
If user or site is configured to frontend language German I see ```Startdatum  Format: 31.12.2017```.
If I change frontend language of user or site to English I see ```Start Date  Format: 2017-12-31```.
In case of changing site language user's frontend language must be set to "Use Default", of course.

**Comment by jojo12** [comment]
yes, you're right.  It works even on english. Thanks. This is really good!
