### ISSUE TITLE
Event page does show a comma at the entry "Where" even if state is not defined

### ISSUE THREAD

**Issue by genesisfan** [jemproject/JEM-Project#1174]
Event page does show a comma at the entry "Where" even if state is not defined:

With state defined; Where: venue - city, state
Without state defined; Where: venue - city,

Would be nice if the comma will disappear when state is not defined ?

**Comment by Hoffi1** [comment]
I changed event details view to show all four combinations possible: "venue", "venue - city", "venue - city, state", "venue, state".
Also I changed some feed views to respect venues w/o city.
