### ISSUE TITLE
colored venue

### ISSUE THREAD

**Issue by Lazaaa** [jemproject/JEM-Project#1176]
Add color to the location. In a cultural center, there are several cultural centers that are distinguished by colors. Example page http://csokonaiksk.hu

**Comment by Lazaaa** [comment]
Add color to the location. In a cultural center, there are several cultural centers that are distinguished by colors. Example page http://csokonaiksk.hu

**Comment by jojo12** [comment]
what's that? a feature request? a hint for a solution?

**Comment by Lazaaa** [comment]
sorry, I wrote it wrong, that request.

**Comment by jojo12** [comment]
I think, this will be too much work and maybe confusion with the colours of the categories. If you dont use the category colours, you could use a category for each mainvenue!

**Comment by Lazaaa** [comment]
i think nope, my local test site use country field, and i put to div class="background-color: '.$item->country.'".

**Comment by Heklaterriol** [comment]
will soon be possible with #1601
