### ISSUE TITLE
(Event) Registrations not belonging to event

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1177]
Hi,
in the forum there's a post from Dete61. I can't reproduce the issue. But if this would be like that, it would be a problem. Can you understand, what could happen?

**Comment by Hoffi1** [comment]
As long as event table is not manually truncated there should be not such an effect.
The only thing which should be fixed is to cleanup #__jem_register if events are deleted (e.g. by daily cleanup where it's missed).
