### ISSUE TITLE
JEM 2.2.3 RC1: error notice when trying to create new venue in backend

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1179]
on a new clean Joomla! 3.8.4 install, when in backend opening a new venue:
Notice: Undefined property: stdClass::$global_googleapi in /srv/www/vhosts/kath-jugend.ch/subdomains/intra/httpdocs/administrator/components/com_jem/views/venue/view.html.php on line 59

**Comment by Hoffi1** [comment]
Oops - you're right. Seems you had never stored JEM settings before so this setting was not set (and therefore non-existant). Bad idea to directly access such elements... I'll change this, thanks for finding. 👍

**Comment by jojo12** [comment]
Hi, I inserted this change to the package, installed and tried to create a new venue, but then I get:

**Es ist ein Fehler aufgetreten!
    0 Call to a member function get() on null.**

**Comment by Hoffi1** [comment]
What do you talk about? Backend or frontend? And are you sure you've inserted ALL changes EXACTLY? (on the two php files)

I downloaded it back from GitHub, installed, tried and all works fine - also if I completely clear globalattribs field in db. Also I checked the functions and I'm absolutely sure it's technically impossible for all the code I see to create ```null->get()``` because ```JemHelper::globalattribs()``` must always return an JRegistry object.

**Comment by jojo12** [comment]
it's only in the backend.
I controlled the files. I even changed the sql install file in the package, before installation.

**Comment by Hoffi1** [comment]
The method is the same in backend and frontend. The only difference is in frontend was already a line ```$settings = JemHelper::globalattribs();``` whilest on backend I had to add ```$globalregistry = JemHelper::globalattribs();``` to keep ```$globalregistry->get(...``` working. Otherwise $globalregistry would be undefined (means: null) which would cause an error "call to a memeber function on null".

**Comment by jojo12** [comment]
uups, I am so sorry: I overlooked the new line 44 in admin. After adding this, all works best.
I hope you did not loose too much time. Sorry. Can be closed now.
