### ISSUE TITLE
Typo in mod_jem_*.xml

### ISSUE THREAD

**Issue by guen92** [jemproject/JEM-Project#1180]
There is a typo in the following xml-files

modules/mod_jem_teaser/mod_jem_teaser.xml
modules/mod_jem_banner/mod_jem_banner.xml
modules/mod_jem_jubilee/mod_jem_jubilee.xml

description="MOD_JEM_TEASER_SATE_MODE_DESC"
description="MOD_JEM_BANNER_SATE_MODE_DESC"
description="MOD_JEM_JUBILEE_SATE_MODE_DESC"

according to 
modules/mod_jem_banner/language/en-GB/en-GB.mod_jem_banner.ini

it has to be

description="MOD_JEM_TEASER_STATE_MODE_DESC"
description="MOD_JEM_BANNER_STATE_MODE_DESC"
description="MOD_JEM_JUBILEE_STATE_MODE_DESC"

**Comment by Hoffi1** [comment]
Oops ... you're right, that must be fixed. Many thanks for your report.
