### ISSUE TITLE
tests with JEM2.2.3rc2: recurrence

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1181]
in frontend in a venue calendar, I entered a new event and saved it. 10.02.2018
Then I opened this event and wanted to add a dayly recurrency for 5 days (from 9 to 12)
dayly until

- I first saw the proposed day in the inputfield was 30.11.2001, **which doesn't make sense.**

- Then I changed this date to 15.02.2018 and saved the event.
  The **bug**: The recurrency is now until the enddate of the shield (I had 365 days until 09.02.2019)!

When I create a recurrent event directly before the first saving:
- the proposed date was right (today:  09.02.2018)
- but the **same bug**: the recurrency is now until the enddate of the shield.

EDIT:
I tested in the backend too: 
the endless recurrency until to the end of the shield exists in backend **too!**
but the proposed date in the input field is correct (the actual date)

EDIT2: 
I don't know if this problem is/was in earlier versions 
(I remember there was a problem with the proposed input date)

**Comment by Hoffi1** [comment]
Hm... I tried in frontend with J! 3.8.4 and it works perfect.
Maybe it's a non-english problem - will switch to German...
Und ja, es gab da ein Problem mit den Datumsfeldern aufgrund des mit J! 3.7 geänderten Kalender-Eingabefelds, siehe #1167 😉

**Comment by jojo12** [comment]
I separate the problems! the problem: daily recurrence is always until the end of the shield instead of thecinserted date.
I tested all on Joomla! 3.8.5 php7.1.11db 5.5.5 on mozilla 
with a clean install of the new package in your cloud.
in Jem 2.2.2 the problem doesn't exist. in jem 2.2.3rc2 it exists!

**Comment by jojo12** [comment]
I tried the different JEM 2.2.3-zips. Between I uninstall with setting "Clean DB on uninstall=Yes"
dev1 no such problem
from dev2 until rc2 ->problem!
Conclusion: There must be an error with recurrence on 2.2.3-dev2!

**Comment by jojo12** [comment]
Settings>global parameters>generate events up to (days)
vs
Repeated events>dayly>
By the end of

**Comment by Hoffi1** [comment]
Hi @jojo12, I see the problem and work on a fix. You don't need to invest time in more experiments until I provide a new version (within the next 1-3 hours, I think).
The problem starts with fixing #1167 and occurs on languages with date format other than yyyy-mm-dd.

**Comment by jojo12** [comment]
Thanks ;-) I normally am testing as long as you can reproduce the bug or as I find my error.

**Comment by Hoffi1** [comment]
Ok, I had to post this yesterday, sorry.

**Comment by jojo12** [comment]
works fine now, thanks!
