### ISSUE TITLE
List of attending is not visible, if the event is for invited only

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1183]
In the forum is a post of jebavy:
if you choose in the settings: attendings are visible for all / registered users
and
if you choose eventregister only for invited
then the list of attendings is not visible.

**Comment by Hoffi1** [comment]
Yes, of course.
If event registration is limited to invited users these users and the author only are allowed to see attendings. You don't want to broadcast this information to the rest of the world - or on your next secret party you're very alone...

**Comment by jojo12** [comment]
yes, you're right!
I had not the best instruments during testing, and then I made a logical bug.
Sorry
