### ISSUE TITLE
FR: discussion check-in functionality

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1187]
After a discussion in the forum I think, the following could be a solution:
in the attendings: we have
-invited
-attending
-non-attending.
Does it make sense to add an fourth possibility (for the backend): -checked-in ? as a control for the admin, who is/was really participating.

**Comment by jojo12** [comment]
there was never a reaction, so I ask:
is it very difficult to add a fourth possibility (present)?

**Comment by Egnarts94** [comment]
Uff, I don't know if its very useful. I would think if someone is attending, so he should be present?

**Comment by jojo12** [comment]
You're right ;-) but somehow a person is saying she will attend, but is not yet there. So this could be a control, how many are effective participating (just present) and how many are not yet there.

**Comment by Egnarts94** [comment]
Uff, I think that is too complex to integrate that.
When the whole registration is reworked, we could increase the states of attendation.

**Comment by jojo12** [comment]
I agree with you
