### ISSUE TITLE
JEM2.3dev1.2: error in JEM-Module_Wide

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1189]
@egnarts: in this new version I get error notices which were not in the previous version:
Notice: Undefined variable: row in mysite.ch/httpdocs/modules/mod_jem_wide/tmpl/default_jem_eventslist.php on line 92

Notice: Undefined variable: row in mysite.ch/httpdocs/modules/mod_jem_wide/tmpl/default_jem_eventslist.php on line 93

**Comment by Egnarts94** [comment]
Yea, thats a copy&paste mistake... I will fix it.
