### ISSUE TITLE
Error: The format of the url e.g. .berlin is incorrect 

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1202]
Post in the forum: 
I've tried to paste an Web-URL for the Venue (Edit Venue). It'a an URL that ends on **.berlin** which obviously is not recognized as a correct URL by JEM. I received the following error message:

Error
Save failed with the following error: The format of the url is incorrect

The new possibilities for URL endings should be accepted!

[or is this a general joomla! bug?]

**Comment by mckillo** [comment]
In JEM 4.0, the issue with some character in URL was solving. See #1317
