### ISSUE TITLE
Joomla JEM number of displayed events

### ISSUE THREAD

**Issue by fmartin2912** [jemproject/JEM-Project#1203]
The JEM-Teaser-Module on my localhost behaves as it should: changing the number of events in the backend really makes JEM display the indicated number of events.

On an other server, changing the number of events in the backend, does .... NOTHING. JEM always displays 20 events, no matter what number I enter.

Joomla Version has been updated from 3.9.4 (1. server) to 3.9.5 (2. server).
JEM version is JEM 2.2.3.

**Comment by depebo** [comment]
I have tested on fresh install J!3.9.5 and JEM 2.2.3 - can confirm JEM Teaser Module displays correct number of events.
