### ISSUE TITLE
FT - Mailer: add option to allow sending mail from backend.

### ISSUE THREAD

**Issue by JKoelman** [jemproject/JEM-Project#1206]
With this i meant the following:

JEM 2.2.3

At the moment the mailer plugin sends a mail from the backend but i might be that you don't want that to happen or only in specific situations. Like only edit in backend, but not when it's done in the front....etc....

**Comment by mckillo** [comment]
@JKoelman Could you tell me the details of this issue and some example or capture? I would like to know if it could be a new feature for next version of JEM 4.0.

**Comment by mckillo** [comment]
This issue is closed because it's old and there isn't more info about it.
