### ISSUE TITLE
2.3.0 Stable: Background Settings wrong name

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1214]
In Background Settings Table-td is wrong, it should be called Table-tr entry.

There is a confusion between Table-td and Table-tr
it should mean: 
Background-color for impair lines (1st entries)
Background-color for pair lines (2 entries)

**Comment by jojo12** [comment]
```
COM_JEM_SETTINGS_FIELD_CSS_COLOR_BG_TABLE_TD="Table-td"
COM_JEM_SETTINGS_FIELD_CSS_COLOR_BG_TABLE_TD_DESC="Here you can select a background color for the table lines."
```
should be:

```
COM_JEM_SETTINGS_FIELD_CSS_COLOR_BG_TABLE_TR="Table-tr"
COM_JEM_SETTINGS_FIELD_CSS_COLOR_BG_TABLE_TR_DESC="Here you can select a background color for the table lines first entries."
```

**Comment by ernst67** [comment]
I guess you are talking about this setting:
![table-tr](https://user-images.githubusercontent.com/3720063/81591891-69b82800-93bd-11ea-8b76-2dd2db9cc482.jpg)

Then I would argree, Table-td should be Table-tr

**Comment by jojo12** [comment]
yes, it is this!

**Comment by ernst67** [comment]
OK clear. I'm not sure what you mean by pair and impair?
Shall we make it:
Table-tr odd lines
Table-tr even lines

**Comment by jojo12** [comment]
The first table-tr is the background-colour for line 1, 3, 5, ...
The second tabletr is the background-colour for line 2, 4, 6....
