### ISSUE TITLE
2.3.0: Updatecheck gives wrong info

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1219]
Update check says: 

  | Ehm, your version wasn't yet released?
-- | --

![updatecheck](https://user-images.githubusercontent.com/2960236/77891439-4011ca00-7271-11ea-8c31-1d6bd6da5e0c.png)

**Comment by ernst67** [comment]
Fixed now.

I will open a new issue; the update check should be delete from the next version on.
