### ISSUE TITLE
Updatecheck should be deleted

### ISSUE THREAD

**Issue by ernst67** [jemproject/JEM-Project#1220]
The (old style) updatecheck should be deleted in next version as we now use Joomla update system

Remember to keep the update.xml at the server side and fill with some useful info for users still on older JEm versions (pre-2.2.3)

**Comment by mckillo** [comment]
When the admins go the JEM update check, get this:

![JEM4 - check update obsolete in backend](https://github.com/jemproject/JEM-Project/assets/2765316/ebf07741-a755-4cde-8602-fd4ed4e55b75)

I think that it could be updated, only change a url of  XML for check update.
Now update url in the controller code \administrator\components\com_jem\models\updatecheck.php : 37 is
`$updateFile       = "https://www.joomlaeventmanager.net/updatecheck/update.xml";`

But in the package xml (pkg_jem.xml) file the update url is:
`<server type="extension" name="JEM Update Site">https://www.joomlaeventmanager.net/updatecheck/update_pkg_jem.xml</server>`

What is the good url to check update? I guess that is the last.

There are to create a new change log for JEM4: https://www.joomlaeventmanager.net/project/changelog-jem-4 and indicate it into xml.

Solution: Update the url in the controller code and update update_pkg_jem.xml file in the web server.

**Comment by ernst67** [comment]
The correct URL is indeed:

<server type="extension" name="JEM Update Site">https://www.joomlaeventmanager.net/updatecheck/update_pkg_jem.xml</server>

When the new version is released we simply update the info in this updatecheck and users will be notified in the backend main control panel.
In my opinion the old update info (shown in JEM'backend) is really obsolete now and not Joomla standard.

BUT: We should also notify that there is a procudure to follow! This is not a one-click update. How can we warn users...?

**Comment by mckillo** [comment]
But, the xml content isn't updated to v.2.3.6
And "update check" must be changed to https://www.joomlaeventmanager.net/updatecheck/update_pkg_jem.xml (I will change the code)

**Comment by ernst67** [comment]
The xml was updated to 2.3.6 but then I reverted that again. I had a good reason but forgot now.
I think because we were not ready for the jump from 2.3.6 to 4.0

So far 2.3.6 had 164 downloads.... 4.0 has 85 :-)

**Comment by jojo12** [comment]
What's possible in the JED? Is it possible to offer there a version for "J3 to migrate" and an other version for J4 for new customers? Important: we don't support those who will stay in J3. JEM2.3.6 is only for migration!

**Comment by mckillo** [comment]
For version 4.0.0, we have to update the https://www.joomlaeventmanager.net/updatecheck/update.xml file. Now, it's v.2.3.5

**Comment by mckillo** [comment]
Other update, we have to create an article http://www.joomlaeventmanager.net/project/changelog-jem-4 for the version 4.
And the url https://www.joomlaeventmanager.net/download?download=80:jem-4-0-0-stable should download JEM 4.0.0 version zip file.

**Comment by mckillo** [comment]
Who do you haver permissions to do it in the JEM website?

**Comment by jojo12** [comment]
Ernst and Jojo

**Comment by jojo12** [comment]
You say me, when it's 100% ready, and I can do it. Jojo can't do it on JED.

**Comment by jojo12** [comment]
I uploaded the zip into the phocadownload folder. it's up to @ernst67 to continue!

**Comment by mckillo** [comment]
Please see commit above. Update de Check Update (include new upsatecheck.php to zip) and in this commit, I have upload the new xml file of server.
Who have permissons to update XML in path https://www.joomlaeventmanager.net/updatecheck/update_pkg_jem.xml

**Comment by mckillo** [comment]
![JEM4-Update check with new XML](https://github.com/jemproject/JEM-Project/assets/2765316/481c4600-e6f3-4807-8e36-e403852cb25f)

This is the result, please review the strings in 'Changes' field and others data in the XML file.

**Comment by mckillo** [comment]
In the future or next version, I think that version JL 2.x and JL 3.X could be deleted in this xml file,

**Comment by mckillo** [comment]
In the XML, I change the infourl to https://www.joomlaeventmanager.net/project/changelog-jem-4, but I have doubts, if it's necessary. 
I've changed 2 to 4, thinking about the major version, but I think it's better to leave it as it was and just have a log of changes on the web.

What do you think? 

If not, return to 
`<infourl title="JEM Package">http://www.joomlaeventmanager.net/project/changelog-jem-2</infourl>`

**Comment by mckillo** [comment]
And if 2 is good, we'll have to update the info in this article with new JEM 4.0 version (or beta too).

**Comment by ernst67** [comment]
@mckillo :
Was your fix of the updatecheck before or after Hekla created the package? If it was after we have to re-create the package.

@all:
I have published JEM4 on our site. Next task is to modify the update_pkg_jem.xml , but I'm a little unsure how to handle...

We need to notify current 2.3.5 users that there is a 2.3.6, and we need to notify 2.3.6 users that are on Joomla4 that there is a JEM4 version.

I found a test file that was created november 2022:
https://www.joomlaeventmanager.net/updatecheck/update_pkg_jem-test.xml

I think this should work but we have to test. Who created it?

**Comment by ernst67** [comment]
About the changelog...: 
It's a pity we have not worked like we previously did. First make a tasklist and then move all items that were handled to the changelog. It makes publishing a new version much simpler and I would be in favour or making the changelog anyway.

So I quicly made the article:
https://www.joomlaeventmanager.net/project/changelog-jem-4
It's currently only visible for Devs.... but I'll make it public as we roll out JEM4

I hope we can write something sensible in it

**Comment by Heklaterriol** [comment]
I wanted to add some information to the changelog, but I cannot write. It looks as if I could, but I cannot change anything the textarea...

![textarea](https://github.com/jemproject/JEM-Project/assets/28540581/b1639768-4b03-4446-b0a2-0ccc516e7625)

**Comment by mckillo** [comment]
@ernst67 The fix of the updatecheck was after Hekla created the package. There will be to do the zip package again.

**Comment by mckillo** [comment]
> https://www.joomlaeventmanager.net/updatecheck/update_pkg_jem-test.xml

@ernst67 You can ignore this test file about update, don't have anything to recover.

![Uploading JEM 4 - Comparation of update_pkg_jem with other old test xml file.jpg…]()

**Comment by mckillo** [comment]
Moved xml file to root JEM project in Github, this file is for server (don't include in the package zip file).
@ernst67  For Joomla 3.x, update xml file for Joomla 3.x + JEM 2.3.6

**Comment by ernst67** [comment]
Ik, I will take the current one offline

**Comment by Heklaterriol** [comment]
I just created a new installation file with all the recent changes from "JEM-4.0.0" and "JEM-for-Joomla-4" included.
It is in the root of "JEM-4.0.0", see: https://github.com/jemproject/JEM-Project/blob/JEM-4.0.0/pkg_jem_v4.0.0.zip

**Comment by jobrusche** [comment]
With this new kit, I got some errors in the update check, maybe because the server side is not in place yet.

![V40-0_update-check](https://github.com/jemproject/JEM-Project/assets/117929258/169657a6-4560-473e-aaf1-d44f8981e326)

**Comment by mckillo** [comment]
Yes, that's right. The XML file will be update today or as soon as possible, and it will be solver.

**Comment by ernst67** [comment]
@Heklaterriol 
Thanks, I updated the package. The previous had 18 downloads already... :-/

**Comment by ernst67** [comment]
> I wanted to add some information to the changelog, but I cannot write. It looks as if I could, but I cannot change anything the textarea...
> 
> ![textarea](https://user-images.githubusercontent.com/28540581/250989426-b1639768-4b03-4446-b0a2-0ccc516e7625.png)

Could you please try again? I think the article was checked-out for some unknown reason

**Comment by ernst67** [comment]
> Yes, that's right. The XML file will be update today or as soon as possible, and it will be solver.

@mckillo @Heklaterriol @jojo12 
could you have a look at the updated xml here, and let me know what you think?
https://www.joomlaeventmanager.net/updatecheck/update_pkg_jem-test.xml
I think it should it should work for an update-notification of all users still on 2.3.5 and also notify users on 2.3.6, IF they are on Joomla 4....
If any of you is ready for a test I can put it live by replacing the current one....

**Comment by ernst67** [comment]
@mckillo 

The pdate_pkg_jem-test.xml file is only for information reasons. So you guys can have a look.
If I modify the live xml (pdate_pkg_jem.xml) then I mess things up.

Thanks for looking into it. I will make modifications ans set it live in approx one hour. Will let you know.

I asked Jojo today about the 2.3.6 package but didn't have a reply yet. The packages that was uploaded to the site is dated May 11 2023. (I de-published it to avoid confusion).
He just answered it's the same file (but if you want me to mention another release date that is fine with me)

**Comment by ernst67** [comment]
OK. xml file has been adapted. Ready to test!

**Comment by mckillo** [comment]
@jobrusche Do you see this info in 'Update Check icon'?

![JEM4-Update check-Final info](https://github.com/jemproject/JEM-Project/assets/2765316/a14f26b8-3f27-43e5-9fb7-943fe758bb02)

**Comment by jobrusche** [comment]
Yes, I confirm that this is the output I see now on my JEM V4.0.0 site
A I also confirm that one of my site with JEM 2.3.5 detected the update to JEM 2.3.6

**Comment by ernst67** [comment]
That sounds good :-)

Then I guess it's on to the next step...: Update the JED!

**Comment by ernst67** [comment]
JED updated! :-D

**Comment by jobrusche** [comment]
Warning !
My 2.3.5 site that detected 2.3.6, pretends to do the update but after succes message the Control panel Configinfo still shows 2.3.5 and the Control Panel Update check now says "Update server currently not available. Please try again later! "

**Comment by jobrusche** [comment]
Yes, but the "Click for more information" link leads to
Error
You are not authorised to view this resource.

Op wo 5 jul 2023 om 18:59 schreef McKillo ***@***.***>:

**Comment by ernst67** [comment]
> Warning ! My 2.3.5 site that detected 2.3.6, pretends to do the update but after succes message the Control panel Configinfo still shows 2.3.5 and the Control Panel Update check now says "Update server currently not available. Please try again later! "

I just repaired a small error in the xml. 
Could you please try again?

**Comment by jobrusche** [comment]
Ok the update now executed for real.
The success message was different, with mention of 2.3.6 being prerequisite for4.0.0
Control panel configinfo now shows : Installed version 2.3.6 ,  but update server still not available

**Comment by mckillo** [comment]
@ernst67 For JEM 2.3.5 and 2.3.6, there is update https://www.joomlaeventmanager.net/updatecheck/update.xml and this xml file doesn't update,

**Comment by ernst67** [comment]
@jobrusche 
That issue schould now be fixed too. The access to the changelog was still restricted....

@Heklaterriol 
Could you please try if you can access and modify the changelog now?
https://www.joomlaeventmanager.net/project/changelog-jem-4

**Comment by ernst67** [comment]
> @ernst67 For JEM 2.3.5 and 2.3.6, there is update https://www.joomlaeventmanager.net/updatecheck/update.xml and this xml file doesn't update,

Sorry, I tought this file was declared obsolete. Will just updated the xml

**Comment by jobrusche** [comment]
Changelog is now accessible from Control Panel - Update check

**Comment by mckillo** [comment]
@ernst67 OK, fixed.
In all JEM 2.3.x installed, the https://www.joomlaeventmanager.net/updatecheck/update.xml file is the reference to check new version of JEM. 
Now, from JEM 4.0.0, the xml of reference is https://www.joomlaeventmanager.net/updatecheck/update_pkg_jem.xml

**Comment by mckillo** [comment]
Good job. I think that this issue is solved and it can be closed.
