### ISSUE TITLE
error in plg_jem_mailer.ini language string

### ISSUE THREAD

**Issue by ernst67** [jemproject/JEM-Project#1223]
In plg_jem_mailer.ini on line 200 it reads:

PLG_JEM_MAILER_LOG_SEND_ERROR="Error sending email to "_QQ_"%s"_QQ_"

This is probably formatted wrong.

We now know that "_QQ_" means a double quote in the string.
So, the intention is to say: Error sending email to "user"

I think that after the last "_QQ_" an extra " should be placed, to close the string.
So:
PLG_JEM_MAILER_LOG_SEND_ERROR="Error sending email to "_QQ_"%s"_QQ_""

**Comment by jojo12** [comment]
I tried with that (you proposed)
`PLG_JEM_MAILER_LOG_SEND_ERROR="Error sending email to "QQ"%s"QQ""`
but then the language file is corrupted, all other translations aren't there (in the backend), only the language keys.
I propose:
`PLG_JEM_MAILER_LOG_SEND_ERROR="Error sending email to %s"`
then the language file in backend works, but I can't test how the mail notification will be!

**Comment by ernst67** [comment]
OK. let's wait for Martin's answer in the forum. If it works we change it like that
