### ISSUE TITLE
Notification JEM with JComments: Deprecated

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1224]
When I use JCommentsplugin for JEM, then I got the error notification:

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; JCommentsACL has a deprecated constructor in /srv/www/vhosts/mysite.ch/httpdocs/components/com_jcomments/classes/acl.php on line 17

We can resolve this with function _construct

But this is a problem inside JComments, which still continues to work but it seems, it is not anymore hosted.

**Comment by mckillo** [comment]
In JEM 4.0 is working, there isn't any deprecated message. See #1337
