### ISSUE TITLE
Urgent decision: Where to go with Acymailing plugins?

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1225]
Hi there,
Our plugins for Acymailing are for Acymailing 5, which is very useful for event programs.
But there is meanwhile a more developed Acymailing 6.10.4. And there is always a free starter version.
Because I am not a developer,  I don't see how to integrate our plugins into the new 6. And at the moment I don't need a more developed paying version.
Meanwhile there are a lot of plugins for other event programs.

Some years ago, we decided to take the plugins for Acymailing into our website. 
But nobody is caring about adapting our plugins here. 
**So I propose to give our plugins to acymailing and to hope, they will do the adaption for Acymailing 6.**
(what's about stevent? Does he?)

**Comment by jojo12** [comment]
stevent got a response from Acymailing. They pointed him to this page with an example file:

https://docs.acymailing.com/developers/acymailing-developer-documentation

Who is able to try?

**Comment by jojo12** [comment]
Acymailing seems not to be interested. They don't know how many users will need it

**Comment by mckillo** [comment]
This issue follow #1335
