### ISSUE TITLE
Help for adapting JEM for J4

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1227]
I think this might be an interesting and helpful place:
https://github.com/astridx/boilerplate/wiki/000.-Creating-a-Simple-Component-for-Joomla!-4.x---Introduction

**Comment by mckillo** [comment]
Jojo12, how is version going for J4? I have tried to acces to https://www.joomlaeventmanager.net/project/tasklist-jem-4, but I don't have permisions. I would to test beta o alfa version.
