### ISSUE TITLE
JEM 2.3 with php8  same like #1278 and #1280

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1232]
I tried with php8 on latest Joomla! 3.9.23:
Deprecated: Required parameter $params follows optional parameter $view in /srv/www/vhosts/mysite.ch/httpdocs/components/com_jem/classes/output.class.php on line 848

Deprecated: Required parameter $i follows optional parameter $value in /srv/www/vhosts/mysite.ch/httpdocs/administrator/components/com_jem/helpers/html/jemhtml.php on line 23

Deprecated: Required parameter $i follows optional parameter $value in /srv/www/vhosts/mysite.ch/httpdocs/administrator/components/com_jem/helpers/html/jemhtml.php on line 58

Deprecated: Required parameter $i follows optional parameter $value in /srv/www/vhosts/mysite.ch/httpdocs/administrator/components/com_jem/helpers/html/jemhtml.php on line 100

Deprecated: Required parameter $i follows optional parameter $value in /srv/www/vhosts/mysite.ch/httpdocs/administrator/components/com_jem/helpers/html/jemhtml.php on line 166

->fixed

**Comment by jojo12** [comment]
In backend, when I open "categories":
0 implode(): Argument #2 ($array) must be of type ?array, string given
in backend, when trying to save something:
0 Attempt to assign property "css_backend_usecustom" on string
when trying to start "Beispieldateien"
Fatal error: Array and string offset access syntax with curly braces is no longer supported in /srv/www/vhosts/mysite.ch/httpdocs/administrator/components/com_jem/models/sampledata.php on line 78

**Comment by jojo12** [comment]
Community Builder is not ready too. Perhaps with J! 4

**Comment by jojo12** [comment]
Meanwhile Community Builder is ready for PHP8

**Comment by mckillo** [comment]
This issue doesn't appear in JEM 2.3.6 (update) and JEM 4.0 with PHP8.0
