### ISSUE TITLE
fontawesome fa-square-plus doesn't exist anymore

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1276]
@egnarts: 
they changed to fa-plus-square
without that there's no icon

**Comment by Egnarts94** [comment]
It does only exist in font awesome 4.

**Comment by jojo12** [comment]
Do you know, how to continue to use it?

**Comment by Egnarts94** [comment]
If you use the backend setting "include font awesome" it should work.
If your template is using the new font awesome 5 its told plus-square
https://fontawesome.com/v5.15/icons/plus-square?style=solid

**Comment by jojo12** [comment]
even when I use the old protostar template, the icon is not shown!

**Comment by Egnarts94** [comment]
Its already working.
![image](https://user-images.githubusercontent.com/14231804/121234192-bbb6d000-c893-11eb-9596-9606ea1ea708.png)
