### ISSUE TITLE
Incorrect language string in menu

### ISSUE THREAD

**Issue by stimpsonjcat** [jemproject/JEM-Project#1281]
If you want to create a new menu item, I found there's a language string missing. The  COM_JEM_MYPLANNING_VIEW_DEFAULT_DESC  string is missing from the language files.

**Comment by jojo12** [comment]
Since the myplanning menu is not core JEM, you've to add it manually.

**Comment by jojo12** [comment]
in the JEM v2.3.2 it will not be anymore
