### ISSUE TITLE
Joomla 3.10.2 Warning when in backend creating new menu

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1285]
(in php 7.4 and 8 and it seems to be general joomla not JEM)
When I try to create a new menu, I get the warning

> Warning: is_file(): open_basedir restriction in effect. File(/metadata.xml) is not within the allowed path(s): (/srv/www/vhosts/folk-tanz.ch/:/tmp/) in /srv/www/vhosts/mysite.ch/httpdocs/administrator/components/com_menus/models/item.php on line 1153

But the creating process works

**Comment by mckillo** [comment]
This issue doesn't appear in JEM 4.0
