### ISSUE TITLE
Tooltips deprecated

### ISSUE THREAD

**Issue by stimpsonjcat** [jemproject/JEM-Project#1288]
You should remove all references to tooltips like
`HTMLHelper::_('behavior.tooltip')`

Joomla removed the tooltips in J4.

**Comment by jojo12** [comment]
have you an alternative?

**Comment by jojo12** [comment]
For Joomla 4 we haver to eliminate mootools!
There is a plugin which disable mootools (mootools disabler). With this you can test where we need to exchange things.
so:
`HTMLHelper::_('behavior.tooltip') `with `HTMLHelper::_('bootstrap.tooltip')`
`HTMLHelper::_('behavior.modal')` with `HTMLHelper::_('behavior.modal')`
this works, perhaps there are more

**Comment by Heklaterriol** [comment]
> You should remove all references to tooltips like `HTMLHelper::_('behavior.tooltip')`
> 
> Joomla removed the tooltips in J4.

Yes, they should already be replaced or removed.

In some places you finde the old code in comments:
`// HTMLHelper::_('behavior.tooltip');	`

Or did you find any active instances?
