### ISSUE TITLE
Usage of tabs code has changed

### ISSUE THREAD

**Issue by stimpsonjcat** [jemproject/JEM-Project#1290]
When using tabs (in edit forms), the code has changed 

Previously the code would be:
`echo HTMLHelper::_('tabs.start', 'det-pane'); `
`echo HTMLHelper::_('tabs.panel',Text::_('COM_JEM_VENUE_INFO_TAB'), 'info' );`
`…`
`echo HTMLHelper::_('tabs.end'); `

The new code for tabs is:
`echo HTMLHelper::_('uitab.startTabSet', 'myTab', array('active' => 'details', 'recall' => true, 'breakpoint' => 768));`
`echo HTMLHelper::_('uitab.addTab', 'myTab', 'details', Text::_('COM_JEM_VENUE_INFO_TAB')); `
`…`
`echo HTMLHelper::_('uitab.endTab');`

**Comment by Heklaterriol** [comment]
like in #1288:

Yes, they should already be replaced or removed.
In some places you finde the old code in comments, right next to the new code
Or did you find any active instances?

**Comment by mckillo** [comment]
It is already implemented in JEM4
