### ISSUE TITLE
List "known issues" in JEM 4 on JEM website

### ISSUE THREAD

**Issue by Heklaterriol** [jemproject/JEM-Project#1333]
all the issues with both labels `bug` and `to do after JEM4 release` should be named as know issues on the JEM website to prevent bug reports on it

**Comment by Heklaterriol** [comment]
I start the list of know issues
- Display OpenStreetMap: sometimes initial zoom level is not correct
- Backend Categories: change category order by numbers not working #1551
- Error 500 in modal window "mail to friend" in events when coming from "venue calendar" #1576

**Comment by mckillo** [comment]
I think that this issue can be closed.

**Comment by Heklaterriol** [comment]
> I think that this issue can be closed.

yes
