### ISSUE TITLE
Add Structured Data / Microdata

### ISSUE THREAD

**Issue by Heklaterriol** [jemproject/JEM-Project#1334]
Add event structured data / event microdata.

See:
https://developers.google.com/search/docs/appearance/structured-data/event
https://developer.mozilla.org/en-US/docs/Web/HTML/Microdata
https://schema.org/Event
https://html.spec.whatwg.org/dev/microdata.html#microdata

**Comment by Heklaterriol** [comment]
These optional microdata fields are missing:
 
- **eventAttendanceMode**
it indicates whether it occurs online, offline, or a mix.
_JEM does not offer microdata values for this field. I suggest we leave it away_
https://schema.org/EventAttendanceModeEnumeration

- **eventStatus**
has the possible values: EventCancelled, EventMovedOnline, EventPostponed, EventRescheduled, EventScheduled
I think the only possible microdata information we provide is "EventScheduled". If an event is cancelled we just deactivate it.
Or we could think of a feature "cancelled", so the event is displayed with an `<del>` tag (line-through), Could be implemented similar to featured events.
--> What do you think?
https://schema.org/EventStatusType

- **image**
only missing if there is no event image. For these cases we could think of a default image …
https://schema.org/image

- **offers**
An offer to provide this item—for example […] give away tickets to an event
_JEM does not offer microdata values for this field. I suggest we leave it away_
https://schema.org/offers

- **organizer**
is either "Organization" or "Person"
_JEM does not offer microdata values for this field. I suggest we leave it away_
https://schema.org/organizer

- **performer**
is either "Organization" or "Person"
_JEM does not offer microdata values for this field. I suggest we leave it away_
https://schema.org/performer

- **description**
is there if filled in, but not provided in the list view.
--> let's implement it. What do you think?
https://schema.org/description


Any further thoughts from your side?
I'm looking forward to your comments …

**Comment by mckillo** [comment]
Good info, we have to study the code for changes in JEM 4.0.1
The default image could be JEM logo.
I agree with eventStatus.
Organizer could be the contact of event.

**Comment by Heklaterriol** [comment]
As far as I can see, it is done.
I hope I did not miss anything …
