### ISSUE TITLE
Acymailing starter_v5.11. works on Joomla! 4:  we have a working update of our old plugin!!!

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1335]

**Comment by jojo12** [comment]
There is no problem to install tagjem. Acymailing 5 continues to work. But creating a newsletter or template, the Tag "Event (JEM)" is not shown.
(when I compare other plugins e.g. tagtime with tagjem, I can at least make visible this tag with only little changings! But not yet more.

**Comment by mckillo** [comment]
Now, I see the file. Thanks.

**Comment by mckillo** [comment]
@jojo12 There are a new branch with this plugin in the project. You tagjem.php file is upload too.
We are doing tests and debugging with several avymailing version.

**Comment by jojo12** [comment]
This tagjem.php works only in AcyMailing5 (not 8) and  only on Joomla 4. (The old one only on Joomla!3)

**Comment by jojo12** [comment]
I tested your acymailing. It works, but there seems to be a problem with language. 
e.g. in /media/com_acymailing/plugins/tagjem_event.php is a "PLG_TAGJEM_CONTACT".
When I use my tagjem.php, there is in english: "Contact" and in german "Kontaktperson"
Using your tagjem.php, there is in both languages: "PLG_TAGJEM_CONTACT".
There is the possibility for more expressions (in general not used)
and in the choosing of tags, there are only some language keys:
PLG_TAGJEM_SHOW_IMAGES
PLG_TAGJEM_RESIZE
PLG_TAGJEM_FEATURED_EVENTS
PLG_TAGJEM_TEMPLATE
PLG_TAGJEM_TITLE
PLG_TAGJEM_DESCRIPTION
PLG_TAGJEM_DATE
PLG_TAGJEM_VENUE 
PLG_TAGJEM_ID

**Comment by mckillo** [comment]
Thank for test it, it's a draft. I know the issue for string and load of template. It don't sport Acymailing 8, first I want to stable content

**Comment by jojo12** [comment]
👍

**Comment by mckillo** [comment]
@jojo12 Fiexd error with tags, It was missing a load other INI file.
