### ISSUE TITLE
Link to osm

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1336]
it would be good to have a link to openstreetmap in output.class.php as new option 

if there is:
$1 =>latitude
$2 =>longitude
$3 =>zoom
$4 =>Venue name

this is a link to openstreetmap:
<a target="_self" href="https://www.openstreetmap.org/?mlat=$1&mlon=$2#map=$3/$1/$2&layers=M">OSMap $4</a>
which shows a marker on the Venue point

The problem is how to find latitude and longitude

**Comment by Heklaterriol** [comment]
Please test.
OSM link and embedded map:
https://github.com/jemproject/JEM-for-Joomla-4/tree/osm-integration

One issue:
the embedded map is sometimes fully zommed out, only afer a reaload the zoom leve is correct

If you have ideas hwo to fix it, let me know.

_By the way: As I'm not a coder, I created it with the help of ChatGPT_

**Comment by jojo12** [comment]
works when you have a clear address. But I get a lot of
**Warning: Undefined variable $countryName in C:\xampp\htdocs\joomla_42\components\com_jem\classes\output.class.php on line 1061**

**Comment by jojo12** [comment]
When I try in nominatim.openstreetmap structured, I can enter in the field "countrY" DE and it shows me Germany.
When I enter CH it shows me Switzerland.
Does it need "countryName"?

**Comment by Heklaterriol** [comment]
> works when you have a clear address. But I get a lot of **Warning: Undefined variable $countryName in C:\xampp\htdocs\joomla_42\components\com_jem\classes\output.class.php on line 1061** even when map is shown

Oh yes, this was a testing leftover, see the commit here:
https://github.com/jemproject/JEM-for-Joomla-4/commit/1a2b7b63367de6544bffc35ae2df6895aee76837

**Comment by Heklaterriol** [comment]
> When I try in nominatim.openstreetmap structured, I can enter in the field "countrY" DE and it shows me Germany. When I enter CH it shows me Switzerland. Does it need "countryName"?

That is interesting, because, it works only when choosing _structured_

I retieve the country name from the short country codes, because in many test addresses there nominatim was not able to get the address. Maybe with your information there is an easier way …

**Comment by jojo12** [comment]
I tested both: Link to OSM and

**Comment by jojo12** [comment]
what's a bit confusing: in backend and editvenue, if you wan't to get a map, you need to klick on the button "Kartendienst aktivieren". And there is the geocomplete map from google. So you don't know, is it google or osm?

**Comment by mckillo** [comment]
@Heklaterriol First, thanks for new geolocate. I'll try to have a break to test osm.
I send you a private message, please see  (about transfer repo and today for branch).

**Comment by Heklaterriol** [comment]
I created a branch "osm integration" [here in this repo](https://github.com/jemproject/JEM-Project/tree/osm-integration).
The previous branch in the repo "JEM-for-Joomla-4" is obsolete now.

**Comment by jojo12** [comment]
When I create in frontend a new venue, there is no button to choose a map (like in backend). Like that there is no map or link to a map shown.
This is only, when I choose this button in backend.

**Comment by Heklaterriol** [comment]
Just realised, that I haven't updated the legacy style yet …

**Comment by jojo12** [comment]
Zoom doesn't work:
I found in https://help.openstreetmap.org/questions/20335/embedded-html-displays-zoomed-out:

> If you are interested in parameters, you can see that generated HTML is an iframe with a 'src' parameter. This points to embed.html with the parameter 'bbox'. It is this parameter which represents the bounding box coordinates of this extent of what's visible on the screen. This is telling it indirectly what the zoom level will be.

**Comment by jojo12** [comment]
how it worked in Joomla3:
![geodate-joomla3](https://github.com/jemproject/JEM-Project/assets/2960236/cde28d1b-79e9-4236-984b-746aa0e38b60)
