### ISSUE TITLE
plg_jem_comments is needed for jcomments

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1337]
plg_jem_comments is obsolete
the new jcomment (pay) for J4 doesn't need a plugin to work together with JEM, and the old one doesn't work in J4!
this is tested!

**Comment by mckillo** [comment]
There is a project of Jcomments for J$ and free: https://github.com/exstreme/Jcomments-4

**Comment by mckillo** [comment]
With this small commit, this Jcomments version for J4 is working, any issue for the moment... I will continue testing.

**Comment by jojo12** [comment]
How do you?

**Comment by mckillo** [comment]
Do you have active JEM-Comments Plugin and select JComments?

![JEM4_jcomments_plugin](https://github.com/jemproject/JEM-Project/assets/2765316/fb1f56b8-07cd-4749-b210-896c7200c1d1)

For me, it works.

**Comment by jojo12** [comment]
That was the point, thanks!

**Comment by jojo12** [comment]
I see it now, but can't write comment

**Comment by mckillo** [comment]
Review the Jcomments setting. 
Can't you write a comment with user or without user? any error message?

**Comment by mckillo** [comment]
In the end, did it work?

**Comment by jojo12** [comment]
yes
