### ISSUE TITLE
field description isn't shown in JEM settings

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1338]
in JEM for Joomla 3 the  field "descriptions" in the settings.xml were visible in the page as tooltips, now there is nothing.
(I remember a issue from hekla).
There are language files e.g. for custom stylesheets, you can't see, but you should.
(But the hint in this textfiles is wrong, so it's better not to see them).

But the problem with these tooltips should be solved or to find an other solution

**Comment by jojo12** [comment]
so we write all issues now here?

**Comment by mckillo** [comment]
Yes, all issues in JEM-Project.

**Comment by jojo12** [comment]
after reading the 4 years discussions in joomla, I must agree, that we too had too many non-sense decscriptions in JEM settings.
