### ISSUE TITLE
There are no tooltips in backend (atum)

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1339]
We have a lot of "descriptions" in <field> in xml. In Joomla!3 they were shown as tooltips, but in Joomla!4 they are away.
But in these description we have a lot of help to handle e.g. JEM settings.
How can we resolve this? Only with the help files? Are they in the help files?

**Comment by Heklaterriol** [comment]
In the modules it works with the "Toggle inline Help". But not in the component. I haven't figured it out yet, why not.

Screenshot for modules:
![inline-help](https://github.com/jemproject/JEM-Project/assets/28540581/9bd3bf71-8f9c-4b32-8fcf-7d0cf47c3519)

**Comment by Heklaterriol** [comment]
see also https://github.com/jemproject/JEM-Project/issues/1537

**Comment by jojo12** [comment]
Interessant discussion:
cms/joomla
Param description as optional mode #35594

We must make them permanent with form-helper

**Comment by Heklaterriol** [comment]
see: https://github.com/joomla/joomla-cms/issues/39545

**Comment by jojo12** [comment]
See #1338 too

**Comment by mckillo** [comment]
I reaearch it ..... but Joomla 4 don't have Tooltip....see discuss about it https://github.com/joomla/joomla-cms/discussions/35594

**Comment by jojo12** [comment]
interesting article:
https://issues.joomla.org/tracker/joomla-cms/35610

**Comment by jojo12** [comment]
interesting article:
https://blog.astrid-guenther.de/en/joomla-hilfe/
