### ISSUE TITLE
where is the latest version?

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1342]
when I compare, then I see the osm version is much older than other versions.
There are old problems like "500 behavior::modal not found. " which were just fixed.

**Comment by Heklaterriol** [comment]
the osm version is based on the branch "JEM for Joomla 4" and up to date.

It is a bit confusing here, that the default "master" branch is the JEM 2.3.6 for J3 …

**Comment by Heklaterriol** [comment]
… and I just checked: there is no active "behavior.modal" in the "osm integration" branch. There are some commented out occurrences.

**Comment by Heklaterriol** [comment]
the latest JEM 4 version is https://github.com/jemproject/JEM-Project/tree/JEM-for-Joomla-4

**Comment by Heklaterriol** [comment]
the latest JEM 2 version for J3 is in the main branch: https://github.com/jemproject/JEM-Project/

**Comment by mckillo** [comment]
For JEM 2, in the 'master' branch of this repo.

**Comment by jojo12** [comment]
yes, the the latest JEM 4 version is https://github.com/jemproject/JEM-Project/tree/JEM-for-Joomla-4
It would be good to have renamed the files as RC. 
AND there should be an actual zipped package.
Who will do this?
