### ISSUE TITLE
Backend Categories: change category order by numbers not working

### ISSUE THREAD

**Issue by Heklaterriol** [jemproject/JEM-Project#1551]
When trying to sort the categories, I encounter strange behaviour.
Changing the order with the numbers and click on the (unlabelled) "save order" button does not work.
See the clip (I'm too lazy to describe all of it)

https://user-images.githubusercontent.com/28540581/229808031-3bb58ba6-87be-4c2b-b253-e9a9636e2988.mov

**Comment by mckillo** [comment]
We have to review and improve the code, we have to reconvert the current model to Joomla 4 model (table and order).

**Comment by mckillo** [comment]
Now, the admin can up or down to change order in categories and venues views. 
Improvement style and format of these views too.

![image](https://github.com/jemproject/JEM-Project/assets/2765316/3d856ac8-a5fa-4013-b65d-ba67d297ca09)
