### ISSUE TITLE
Deprecated: Automatic conversion of false to array is deprecated in /libraries/src/Document/Document.php on line 600

### ISSUE THREAD

**Issue by Heklaterriol** [jemproject/JEM-Project#1554]
when displaying modules I get the deprecated message:

`Deprecated: Automatic conversion of false to array is deprecated in /libraries/src/Document/Document.php on line 600`

As Jojo correctly said: it is caused by JEM when handing over false or null values.

See also, what information I found on this:

> Deprecated Autovivification on False
>
>Autovivification is the auto-creation of arrays from false and null values. While this feature is widely used in PHP applications, creating an array automatically from false values is not ideal as it may be a sign of a buggy code.
>
>Therefore, PHP 8.1 deprecates autovivification only for false values. Implementing autovivification on a false variable on PHP 8.1 will result in a deprecation notice.

**Comment by mckillo** [comment]
How can I replicate the deprecated message? JEM,PHP,JL version? What module?

**Comment by Heklaterriol** [comment]
cannot reproduce it anymore – somehow solved!
