### ISSUE TITLE
Should we remove or fix "Display Google map (api-key)"?

### ISSUE THREAD

**Issue by Heklaterriol** [jemproject/JEM-Project#1559]
Does ot make any sense to keep "Display Google map (api-key)"?
If yes we have to fix it.

**Comment by jojo12** [comment]
Yes, for google part it makes sense! But api works after all with geocomplete. At least you can move the marker on tme map to the correct place. There are lot of situations with addresses not so clear!

**Comment by Heklaterriol** [comment]
OK, then I will try to fix it. Not today or tomorrow but soon.

**Comment by jojo12** [comment]
I tested more: When you use api-key inserted, this gives you the possibility to use geocomplete. But you do not need the menue point "google map with api key". You can choose there "google map".
and the api-key continues to work in preparing the map.

**Comment by Heklaterriol** [comment]
Ok, does this mean, that we do not need the "Display Google Maps with api key" selection, just "Display Google Maps"?

**Comment by jojo12** [comment]
for the venue detail view and event detail view, the api key is not needed.
But I do not know, how does the api key is readed for backend and frontend edit venue ?
