### ISSUE TITLE
legacy opening venue: error

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1560]
with your pkg_jem_4betaOSM_v4.zip
when I open in legacy venue, I get:
syntax error, unexpected token "elseif", expecting end of file

**Comment by jojo12** [comment]
I think (I am not sure), in frontend venue view the map is the same, when the setting is "google map" or "google map with api".
The difference is in backend edit venue and edit venue in frontend, 
when you have insert the api key, you have on the right side a map (satellite with geocomplete, whre you can move the marker
when you have no api key, then you have on the right side a map and and error notification (see images
![diff_api_nonapi](https://github.com/jemproject/JEM-Project/assets/2960236/00118eeb-7e7a-4027-a6a1-4f2a5cdf9c05)

**Comment by jojo12** [comment]
I want to say, in venue detail view /and in event detail the google map is the same. The difference is only in the preparing!

**Comment by jojo12** [comment]
meanwhile, the geocomplete in frontend editvenue is not working anymore. Only in backend.

**Comment by Heklaterriol** [comment]
I tried to get through the issues and come to and limitation:
For a google api key I need give to google my banking information – which I don't want.
So I cannot take care of the "google map with api key" issues …

**Comment by jojo12** [comment]
I have api-key (made before they asked for banking informations).
Can you let the google api part it like it was before? For those who have it or want to give google this informations.
