### ISSUE TITLE
Undefined variable COM_JEM_INSTALLATION_DESCRIPTION

### ISSUE THREAD

**Issue by jobrusche** [jemproject/JEM-Project#1564]
At the end of the installation of component JEM-Project-2.3.6-stable on  Joomla 3.10.11
the following is displayed:

![JEM-2_3_6-inst](https://github.com/jemproject/JEM-Project/assets/117929258/99f71a83-b230-42cc-a4bf-68ba3e8d4463)

**Comment by jojo12** [comment]
Thanks! I hope, we have not to create a new language file only for this :-) because 2.3.6 is after all for preparing the migration.
