### ISSUE TITLE
nominatim4JEM: how to integrate something like this

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1565]
[testnominatim4JEM.zip](https://github.com/jemproject/JEM-Project/files/11518398/testnominatim4JEM.zip)
I can integrate it in a module.
I can enter address or placename and enter.
Then it shows me the right places (perhaps more than one)
When I click on the right place, the map flies to this places and puts a marker.
I can correct the marker by dragging. It gives me the adapted lat and lon.

Something like that can replace the google geolocate (which works only with google api-key)

**Comment by mckillo** [comment]
Very good, I think that It ould be integrated. I have to research... I'm sure that Hekla like too.

**Comment by Heklaterriol** [comment]
nominatim is included in the current OpenStreetMap implementation
