### ISSUE TITLE
min PHP version check

### ISSUE THREAD

**Issue by Heklaterriol** [jemproject/JEM-Project#1566]
Just found in script.php on line 220-227:
```

	// Minimum required PHP version
		$minPhpVersion = "5.3.1";

		// Abort if PHP release is older than required version
		if(version_compare(PHP_VERSION, $minPhpVersion, '<')) {
			Jerror::raiseWarning(100, JText::sprintf('COM_JEM_PREFLIGHT_WRONG_PHP_VERSION', $minPhpVersion, PHP_VERSION));
			return false;
		}
```

Should be `$minPhpVersion = "8.0";`, right?

**Comment by mckillo** [comment]
It's fine In the JEM-for_Joomla-4/script.php:239 $minPhpVersion = "8.0.0";
In he JEM-Project\package\pkg_install.php is fine too..
Only I see this in JEM 2.3.6 (master branch, in this case it's right).
Where do you see $minPhpVersion = "5.3.1"?

**Comment by Heklaterriol** [comment]
Ops, I think I was in the wrong branch :-(
