### ISSUE TITLE
replace J3 blank placeholder image

### ISSUE THREAD

**Issue by Heklaterriol** [jemproject/JEM-Project#1567]
in Joomla 3 there was a blank placeholder image in `media/system/images/blank.png`, this si gone in Joomla 4.
This is still called in some modules in JEM 4 and then causes a missing image.
I could not find a new blank placeholder image in Joomla 4.

Possible solutions:
- upload our own JEM4 blank placeholder image
- use the JEM image in media/images/icon-16-blank.png
- change the code that the placeholder image is not called.
- …

**Comment by mckillo** [comment]
Vote 1º (copy old jl31011\media\system\images\blank.png (or similar 16x16) to jl431\media\com_jem\images)

**Comment by jojo12** [comment]
I never used them, so I won't vote

**Comment by jojo12** [comment]
Ok

**Comment by Heklaterriol** [comment]
Me too, I'm fine with Vote 1º

**Comment by mckillo** [comment]
See commit above.

**Comment by Heklaterriol** [comment]
Cool, I found some more blank.png occurrences with the old path. I adjusted them.

**Comment by mckillo** [comment]
Yes, I don't upload the change for modules. Here you are, see commit above.
