### ISSUE TITLE
event page "show readmore" and "Show introtext" in JEM settings

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1568]
I never used it:
I read in help>settings>event page:
Show "Read More":
If set to Show, the Read More link will be shown

Show Introtext:
If set to Show, the event Introtext will be shown. If set to Hide, only the part of the event description after the "Read More" break will show.

Does this work? Do we need it?

**Comment by mckillo** [comment]
For example, they are used in modules.
