### ISSUE TITLE
JEM Teaser module: readmore

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1569]
When I have a teaser module with an event which has no description, then it makes no sense to have "readmore".
Normally I reach the event details with click on title, after all when it is like that in cassiopeia 
![readmore](https://github.com/jemproject/JEM-Project/assets/2960236/d2a331ee-67fc-4635-a7c3-b9223c1e56a8)
(see image)

**Comment by jojo12** [comment]
in legacy style this is not, so much better!

**Comment by mckillo** [comment]
There isn't code for 'Read more link' in legacy.
You can hide 'Read more link' in JEM Setting. Try it.

![JEM4-Not_shown_read_more_link](https://github.com/jemproject/JEM-Project/assets/2765316/c48128bf-4236-44b5-8472-e6090f6be89a)

See commit above.

**Comment by mckillo** [comment]
![JEM4-shown_read_more_link-at the end of description](https://github.com/jemproject/JEM-Project/assets/2765316/606823f8-a6ae-4cd3-9dab-c05126bed340)

If "Read More"Link option is show in the setting, the "Read more" link is shown at the end of description, not 3rd column.
