### ISSUE TITLE
Nested categories links do not show on on Category Views

### ISSUE THREAD

**Issue by neyworg** [jemproject/JEM-Project#157]
The sub-sub categories (Nested Sub-categories) do not show in the category views

Categories (Primary, sub-category and sub-sub category (Nested Categories))
---------- Primary A
---------- ---------- Secondary
---------- ---------- ---------- ANOTHER SECONDARY
---------- ---------- Fourth Category 

ANOTHER SECONDARY nested category does not show because it is a nested sub-category.

■ A decision needs to be made on how these category views should look. My mockups might not be correct. Another way to show it would be to list all sub-category links under the sub-category part of the first category.
# MOCKUP A

![mockup](https://f.cloud.github.com/assets/3965321/546459/f1f02f56-c296-11e2-9b39-eba8fac298b6.png)
# MOCKUP B

![mockup](https://f.cloud.github.com/assets/3965321/546458/be34b20e-c296-11e2-813b-c2d54926bb8e.png)

**Comment by mckillo** [comment]
This was solved long time ago.
In the JEM 4.2.2,  the subcategories are shown in the categories view like this:
![image](https://github.com/user-attachments/assets/4be80340-211f-41c1-ad72-db3e3cd300eb)
And this issue is closed.
