### ISSUE TITLE
Send email to users who are in the Access groups (ACL) of the event

### ISSUE THREAD

**Issue by mckillo** [jemproject/JEM-Project#1570]
I try to explain it. 
Create a new Joomla group = Meeting
Create a new Joomla access level = acl_meeting
Create a new JEM category = Meeting and with Access = acl_meeting
Set Yes in the new option of 'Category email options of Category'.
Ans save the new JEM category

![JEM4-Proposal_send_email_users_of_ACL_category](https://github.com/jemproject/JEM-Project/assets/2765316/ddd5181a-74da-4f53-9be5-a1f1ad2ee8a6)

Now, you can create a new event for this new 'Meeting' category.
When the admin saves the event, JEM mailer plugin sends an email (new/update event content) to all user active for 'Meeting' Joomla group.

It would be useful for configurations of events/tasks/activities in intranets that use JEM. For example, webs with JEM in 
associations, clubs, schools, academies, neighborhood communities, town halls,... a way to notify users by email according to the category byJoomla ACL. It's similar to the previous field (emails), but I don't have to write email again, when the admin create Joomla user and user is assigned groups to which belong, so emails of new events will be dynamically sent to you.

I am developing it for a client and I think that in the core it would be very useful for JEM users, 
and it has other variants or notification extensions.

What do you think?

**Comment by jojo12** [comment]
Good idea!

**Comment by mckillo** [comment]
![JEM4-Proposal_send_email_users_of_ACL_category-New optin in JEM Mailer plugin setting](https://github.com/jemproject/JEM-Project/assets/2765316/0aa4f4f4-f0eb-4fb2-81f3-4c008f09cf0b)

The admin can setting this new email from JEM Mailer plugin setting --> for new and edit (update) event

**Comment by mckillo** [comment]
Don't forget, import the sql file to add new emailacljl field into _jem_categories_table
`ALTER TABLE `#__jem_categories` ADD `emailacljl` TINYINT NOT NULL DEFAULT '0' AFTER `email`;`

**Comment by mckillo** [comment]
I have moved this commit to email_acl branch
https://github.com/jemproject/JEM-Project/commit/22d9a5ce1f301f5173ddb4810c915535f68094e5

**Comment by jojo12** [comment]
@mckillo: sorry, I had not time and ressources to test!

**Comment by Heklaterriol** [comment]
> What do you think?

Nice feature!

**Comment by mckillo** [comment]
It is working with JEM 2.3 in one of my customer, I moved it because I think that you have to approve it before as new feature. 
I have time you can test it before to add JEM4-for-Joomla-4 branch.

**Comment by mckillo** [comment]
Any tester? before to merge to JEM-for-Joomla-4

**Comment by jojo12** [comment]
I am not able to test; no ressources no knowhow!

**Comment by jojo12** [comment]
you can merge

**Comment by mckillo** [comment]
Done. Thanks. 0 Branch.
