### ISSUE TITLE
no word for keys: 

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1571]
COM_JEM_NOT_ALLOWED_TO_ANNULATE 
This seems forgotten. it's in views/event/tmpl/responsive/default_attendees.php

and when I refuse event: I get an email
Event Refusal Successful
with text:
PLG_JEM_MAILER_USER_REG_NOT_ATTEND_BODY_9

**Comment by mckillo** [comment]
This PLG_JEM_MAILER_USER_REG_NOT_ATTEND_BODY_9 string was commet \plugins\jem\mailer\language\en-GB\en-GB.plg_jem_mailer.ini, And COM_JEM_NOT_ALLOWED_TO_ANNULATE is missing in JEM4, recovered from JEM3.
See commit below.

**Comment by Heklaterriol** [comment]
Oh, good to notice:
some of the language keys are created dynamically! I check them again.

**Comment by mckillo** [comment]
I agree... 2 days ago, update ini files with others strings...action buttoms in Joomla. See commit a2f467ab5151bb55529fbde697fa0cd4386b9f02

**Comment by Heklaterriol** [comment]
I uncommented some of the previous commented language keys. 
https://github.com/jemproject/JEM-Project/commit/2b8300be17ff229c6d8aed04af31a259daf8a3fa

**Comment by mckillo** [comment]
OK and if they report any comments more, we will update them. Thanks.
@jojo12 can closed the issue if it's ok.
