### ISSUE TITLE
Field 'publish_up' doesn't have a default value

### ISSUE THREAD

**Issue by jobrusche** [jemproject/JEM-Project#1572]
Joomla 4.3.1 / JEM 4.0b4 - Downloaded May 25.
Create new venue (OSM)
"Save fails with message: Field 'publish_up' doesn't have a default value"
Venue is not created
Clearing cache did not help

**Comment by jojo12** [comment]
Can you describe (step by step) what you are doing? I can't reproduce! What do you mean with "create new venue (OSM)" ?

**Comment by jobrusche** [comment]
JEM settings – Event page -  Map service OSM – Save settings
JEM venues list
New Venue
Fill in the fields
Save
![Add-venue-save-fail](https://github.com/jemproject/JEM-Project/assets/117929258/7661a053-6b43-4f5f-b7f8-0ef0866f83ab)

**Comment by mckillo** [comment]
@jobrusche Could you tell me if JEM4 is installed for first time or if JEM2.x was installed before? I think in this web server there was a JEM 2.x installation (possibly uninstalled) and that the JEM 4 installer has not detected it.

If you are in a test environment, you can uninstall JEM, delete the JEM tables (#__jem_*) and try installing JEM4 again. And if you are in a production environment or with JEM 2.x installed or with JEM2.x uninstalled but with data in tables, can you copy the #__jem_venues table structure?

**Comment by jobrusche** [comment]
Yes, I did uninstall JEM 2.3.17 before loading JEM 4.0b4

**Comment by mckillo** [comment]
Perfect :-)

If you want to migrate a JEM 2.3 on JL3.10.11 to JL 4.3.x with JEM 4.0.x, please see the help section in the componente menu;

![Migration_JEM2_to_JEM4 - Steps to do_without uninstall](https://github.com/jemproject/JEM-Project/assets/2765316/873fd722-0fc6-4ad4-8a6f-735ab8aeddb3)
