### ISSUE TITLE
error when frontend editevent (via calendar), changing and save

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1574]
Call to a member function format() on bool

I opened an event via (venue) calendar and wanted to unpublish it. Save-->error
in backend it works.
EDIT: This problem comes back (like several times before)
it's not only via calendar, it's general in frontend editevent (editvenue hasn't this problem
and this is something like a releaseblocker, because for JEM it's important that you can edit events from frontend
EDIT2: does this help:
log says: controller - Checking edit ID com_jem.edit.event.120: 1 Array ( [0] => 120 )

**Comment by mckillo** [comment]
I try from Calendar view in menu, from Modules Calendar, from Venue Calendar.... nothing, for me any issue.
I can't reproduce this problem, must be an any data, event capture or details of steps.
