### ISSUE TITLE
error 500 in modal window "mail to friend" in events when coming from "venue calendar"

### ISSUE THREAD

**Issue by Heklaterriol** [jemproject/JEM-Project#1576]
as said:
coming from the venue calendar, clicking on an event and then on "mail to friend", I get an error 500 in the modal window, both in the responsive and in the legacy layout.

```
500 Layout „calendar“ not found.
                            
Call stack
--
# | Function | Location
1 | () | JROOT/libraries/src/MVC/View/HtmlView.php:420
2 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT/libraries/src/MVC/View/HtmlView.php:203
3 | Joomla\CMS\MVC\View\HtmlView->display() | JROOT/components/com_jem/views/mailto/view.html.php:71
4 | JemViewMailto->display() | JROOT/components/com_jem/controller.php:108
5 | JemController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:678
6 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/components/com_jem/jem.php:49
7 | require_once() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
8 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73
9 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
10 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/SiteApplication.php:208
11 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT/libraries/src/Application/SiteApplication.php:249
12 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:293
13 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:61
14 | require_once() | JROOT/index.php:32
```

**Comment by Heklaterriol** [comment]
More insights: it happens only with "Search Engine Friendly URLs" on yes.

When "no" it generates this iframe link, which works:
`https://www.domain.tld/index.php?option=com_jem&tmpl=component&view=mailto&link=18274951ada82854d707739b1d9fac15948ce1db&99af19f9ae98cf65a445b0b6cb373579=1`

When "yes" it generates this iframe link, which does **not** work:
`https://www.domain.tld/index.php/venue-calendar/event/index.php?option=com_jem&tmpl=component&view=mailto&link=aefb8cd994d090f7e5d7b92adfd3f8cba7db427a&99af19f9ae98cf65a445b0b6cb373579=1`

**Comment by mckillo** [comment]
For me it works, I can't simulate with JEM4b4 .
- OK with Search Engine Friendly URLs and with Use URL Rewriting too.
-
I have this code for the mail icon link:
`<iframe class="iframe" src="index.php?option=com_jem&tmpl=component&view=mailto&link=15e2e19f9057b8330071dac97e532a627daf7b39&amp;24a379669a80a4617a7be3a461f8cd82=1" name="Select" title="Select" height="550px" width="800px"></iframe>`

**Comment by mckillo** [comment]
The error look a redirect page error or any conflict with JEM menu created.

**Comment by Heklaterriol** [comment]
coming from a venue calendar? I heve this error only in this case.

**Comment by mckillo** [comment]
Nothing, fo rme it work. Send the steps by steps, capture data event and option, or small video.

**Comment by Heklaterriol** [comment]
Here a video capture, once with SEO friendly URLs on, once with off

https://github.com/jemproject/JEM-Project/assets/28540581/8bd516b6-d437-4af6-b152-3f775f0960b1


Or see: https://j4.datenablage.info/index.php/venue-calendar

**Comment by mckillo** [comment]
Thanks for video, but web is better to see the code. 
If I compare your web with mine, and my test, I don't have the error because I have created a menu of JEM single-event.
Workaround: Create a menu (not visible) of JEM single-event, so, Joomla routing change the url for mail icon.
I have simulate the case, I try to debug the case but if the Joomla routing ....

**Comment by mckillo** [comment]
Sorry, but there are two error, first routing Joomla without reset layout (nothing to do) and other is JEM design view. 
In this last case, I try to explain it:

You have a menu for "Venue calendar" --> index.php?option=com_jem&view=venue&layout=calendar&id=1
When you clic this menu, the url is:
- with friendly active:  https://domain.com/index.php/jem/venue-calendar
- without friendly active: https://domain.com/index.php?option=com_jem&view=venue&layout=calendar&id=1

Details, this url has attribute layout=calendar

In the friendly mode: 
If you create a relative link (in code of view ), in the begining, Joomla try to find a route for this new url, based of menu that you have created. If Joomla finds one (first) then change the url to this other one. If it don't find any menu, inherits from father
and the event URL will be: https://domain.com/index.php/jem/venue-calendar/event/19:test-booked
This URL has a attribute layour=calendar (see above).

When clic mailto icon, you have the same situation, JL find url in the menu created, if don't find any, then inherits from father and try yo load the layout calendar of the mailto view, but this layout doesn't exist in mailto view. For this reason, shown the error that you have found.

Solutions:
1. HARD: change de design JEM and don't use layout as view, for the issue of routing in Joomla.
2. EASY: Workaround, create a menu of JEM single event (no visible) to generate a url with attribute layout. (my vote).
3. OTHER: Joomla should improve the routing of frienly url with attibute as layout.

This error in Joomla is typical, but I think that a change of design will be solved and that they come from code inheritance for previous versions of Joomla, but it's hard to change in time and effort (redisign code).

**Comment by Heklaterriol** [comment]
Thanky McKillo for you detailed explanations.

A (maybe stupid) question: isn't it possible to leave "layout=calendar" in the URL away? I tested it and it worked!
Waht is it good for?

**Comment by mckillo** [comment]
The layout=calendar is necessary to venue calendar view in menú.

**Comment by mckillo** [comment]
Does it work for you with the workaround? I should work

In the other hand, I can try to move this layout to view....bug I sant to finish book-tickets branch

**Comment by mckillo** [comment]
Closed. This issue was fixed and now JEM 4, send email icons works in event opened from venue calendar.
