### ISSUE TITLE
better map zoom for openstreetmap embed

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1577]
for openstreetmap embed, it would be a better map with line 1053: (always a zero more!) in output.class.php

				    `$output = '<iframe width="500" height="250" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.openstreetmap.org/export/embed.html?bbox=' . htmlentities(($lng - 0.001)) . ',' . htmlentities(($lat - 0.001)) . ',' . htmlentities(($lng + 0.001)) . ',' . htmlentities(($lat + 0.001)) . '&amp;layer=mapnik&amp;zoom=' . $zoom . '&amp;layer=mapnik&amp;marker=' . htmlentities($lat) . ',' . htmlentities($lng) . '"></iframe>';`

**Comment by Heklaterriol** [comment]
ok for me.
