### ISSUE TITLE
Don't know why?--> reinstall problem on joomla.com

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1578]
I have a testsite on joomla.com.
I install pkg_jem --> No problem
when I reinstall the same (without doing anything else,  I get:

> Warning
Incorrect datetime value: '%0000-00-00%' for column 'modified_time' at row 1

**Comment by mckillo** [comment]
JL 4.3.1 + PHP 8.0.28 + pkg_jem4beta4..zip (in the root of JEM-for-Joomla-4 branch)
Previously, uninstall JEM4 and delete all JEM tables.
New install, OK. Reinstall same zip, OK. I don't have any error in the install process.
Tell me it the environment is different.

**Comment by Heklaterriol** [comment]
I tried it.
- I installed JEM
- reinstalled, without uninstalling
- uninstalled and kept the tables, reinstalled
- uninstalled and deleted the tables, reinstalled

In all cases no errors.

Are you sure that there weren't any old tables left?

**Comment by jojo12** [comment]
Before uninstalling, I set JEM settings Global Parameters>Global Parameters>Cleanup DB on Uninstall=yes.
(so all tables should be deleted, when uninstall)
installed JEM, ok.
Installed com_jem over this installation--->the error comes! 
The problem is only with com_jem.  But the new com_jem is installed. Only this error is disturbing
All others modules and plugins work.

**Comment by jojo12** [comment]
When I take the package, then it's the same. Then I tried each one alone, then it's only with com_jem

**Comment by jojo12** [comment]
No, I can't.
But I think, we can let this, because I encountered it only there.

**Comment by jobrusche** [comment]
I encountered this error too.
Component 4.0b was installed and then I installed the package JEM-Project-JEM-for-Joomla-4 over it (no uninstall inbetween)
