### ISSUE TITLE
JEM Mailer Plugin -->Integrate infos about booked tickets!

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1579]
I think, the booked places should be written in the mail too! For beginning: write where you can find the number of booked places

**Comment by mckillo** [comment]
I agree, sorry don't undertood you. I review it.

**Comment by mckillo** [comment]
![JEM4-Proposal_define_booked_number_tickets_per_user- options_user-frontend (draft to change registration setting of event)](https://github.com/jemproject/JEM-Project/assets/2765316/9156548b-dee2-457b-96b1-222e1fe85c08)

Draft of new change in registration setting of event (frontend).

**Comment by mckillo** [comment]
I'm on it...

**Comment by mckillo** [comment]
@jojo12 For review. See commit above.

**Comment by jojo12** [comment]
Thanks, it works. will test more

**Comment by jojo12** [comment]
My tester (registrated) is attending and got the mail 2 booked places. (This is ok)
Then he cancels. He gets now an email with "Canceled places:0 " --> This is wrong!

**Comment by mckillo** [comment]
Fixed. See commit above.

**Comment by jojo12** [comment]
yes. it's fixed. can be closed!
