### ISSUE TITLE
RC1 frontend editevent -->0 Call to a member function format() on bool comes always back!

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1581]
I installed an old backup and used the step by step to arrive to JEM4 on Joomla 4. It worked well.
But when I try to change something in a event with editevent (frontend), the old known error is back!
What did I wrong? How can we change, that this will finish?

**Comment by mckillo** [comment]
@jojo12 Check commit above or excecuta in mysql:
INSERT INTO `a8wlc_jem_config` (`keyname`, `value`, `access`) VALUES ('flagicons_path', 'media/com_jem/images/flags/w20-png/', '0');

This error is only for migration from JEM 2.X to JEM 4.0rc1. And with this commit is solved, but you have to update the zip file.

**Comment by mckillo** [comment]
In your migration, the _jem_config table hasn't 'flagicons_path key... This is the error.
To solved, you can run the this sql line (INSERT...) to add this key.
The last zip file shouled be updated with the commit, only add the new admin/sql/updates/mysql/4.0b2.sql file., So, the users do a migration, don't have the error.

**Comment by mckillo** [comment]
Commit solve it?

**Comment by jojo12** [comment]
yes, thanks!

**Comment by jojo12** [comment]
yes it continues

**Comment by jojo12** [comment]
<html><body>


Call stack
--
# | Function | Location
1 | () | JROOT\libraries\src\Form\Field\CalendarField.php:401
2 | Joomla\CMS\Form\Field\CalendarField->filter() | JROOT\libraries\src\Form\Form.php:1047
3 | Joomla\CMS\Form\Form->filter() | JROOT\libraries\src\Form\Form.php:991
4 | Joomla\CMS\Form\Form->process() | JROOT\libraries\src\MVC\Model\FormModel.php:213
5 | Joomla\CMS\MVC\Model\FormModel->validate() | JROOT\libraries\src\MVC\Controller\FormController.php:622
6 | Joomla\CMS\MVC\Controller\FormController->save() | JROOT\components\com_jem\controllers\event.php:289
7 | JemControllerEvent->save() | JROOT\libraries\src\MVC\Controller\BaseController.php:678
8 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT\components\com_jem\jem.php:49
9 | require_once() | JROOT\libraries\src\Dispatcher\LegacyComponentDispatcher.php:71
10 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT\libraries\src\Dispatcher\LegacyComponentDispatcher.php:73
11 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT\libraries\src\Component\ComponentHelper.php:361
12 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT\libraries\src\Application\SiteApplication.php:208
13 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT\libraries\src\Application\SiteApplication.php:249
14 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:293
15 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\includes\app.php:61
16 | require_once() | JROOT\index.php:32


</body>
</html>

**Comment by mckillo** [comment]
You could review to JEM setting and the datetime format ... I think that you have the old format.

**Comment by jojo12** [comment]
all dates have standard NULL

**Comment by mckillo** [comment]
![JEM4rc1 - datetime in the setting (backend)](https://github.com/jemproject/JEM-Project/assets/2765316/47d2cb24-804c-42e2-994d-ca172873d727)
IS JEm setting right too?

**Comment by jojo12** [comment]
the settings are like your image

**Comment by mckillo** [comment]
The old backup, what have it installed? 
I tested agaim migration process from 2.3.6 (with sample data loaded) with JL3 to J4 with JEM 4.0rc1 and it works, after I edita and sace event and it works, not error.

**Comment by jojo12** [comment]
Has it to do that my old backup was Joomla 3.8 with JEM 2.3.3 which I updated first to 2.3.5 updated then Joomla to 3.10.11, then JEM 2.3.6, then like in the step by step.
