### ISSUE TITLE
RC1: invitation in attendeemanager shown as unregistered (should be invited)

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1583]
RC1: invitation in attendeemanager shown as unregistered (should be invited)

AND icon (invited)? doesn't change to yes

**Comment by jojo12** [comment]
![grafik](https://github.com/jemproject/JEM-Project/assets/2960236/a73c641b-3bee-49ae-aaa8-366b4d85f1d8)

**Comment by mckillo** [comment]
A picture better than 1000 words. :-) I understand now.... I'm on it

**Comment by mckillo** [comment]
![JEM4rc1 - USer A is invited and book 1 place](https://github.com/jemproject/JEM-Project/assets/2765316/c0ca19f9-c6d2-4bbe-a128-18cef542eb7d)

In a first test of some combinations, it works for me. This string was changed this weekend past and the zip is right. It's strange.

In the code "Additionla places" is only for user with booked places. 
You could check that \components\com_jem\views\event\tmpl\responsive\default_regform.php is the same one inside the 4rc1 zip.

**Comment by mckillo** [comment]
I have improved the treatment of invited places, so the user can reserve a place if it is available.
I think that this commit (seee above) should resolve it.

**Comment by jojo12** [comment]
yes, I tried and it is very good. Thanks!
Only one question: in german we have uppercase and lowercase letters. Even if I write the first letter with uppercase, after the field it is lowercase
![grafik](https://github.com/jemproject/JEM-Project/assets/2960236/a05b67ef-5c8f-4550-b548-94403e8bfbff)

**Comment by mckillo** [comment]
I don't know. Solved it, see commit above.
