### ISSUE TITLE
add/move ical button in eventslist from footer to the top buttons

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1585]
in eventslist it is difficult to find the ical button in the JEM footer. It is very easy to add this to the group of top right buttons.
This would be much more confortable!

**Comment by mckillo** [comment]
Tell me if it's this. See commit above.

**Comment by jojo12** [comment]
oh no, too much work, sorry
add 'eventslist'
output.class.php: line 119:
`		if (in_array('ical', $btns_show) || (!in_array('ical', $btns_hide) && in_array($view, array('event', 'eventslist')))) {
`

**Comment by mckillo** [comment]
Ok, I understook. Here you are (see refresh commit above)
