### ISSUE TITLE
calendar-responsive.css: the calendar view should be visible in mobile landscape views

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1586]
the change from the table to the month calendar should be earlier
calendar-responsive.css line 353 
this would be much better, because calendar is a kind of overview

**Comment by mckillo** [comment]
![JEM4RC1 - calendar view in landscape orientation for browser mobile](https://github.com/jemproject/JEM-Project/assets/2765316/89f6a579-d1d4-4afe-b97e-e346a68a84d0)

Calendar view in landscape orientation for browser mobile, right?

**Comment by mckillo** [comment]
See commit 7f34a2292999e9741a19723cbdc84a951a838709

**Comment by jojo12** [comment]
no, I mean landscape should be like that, the switch to the other view should be more near 30rem
![image](https://github.com/jemproject/JEM-Project/assets/2960236/43cca3c0-7483-48dc-aaa5-45755f5f3614)

**Comment by mckillo** [comment]
That already was, but depend of mobile screen resolution. Change to 30rem

**Comment by mckillo** [comment]
Is ti right?

**Comment by mckillo** [comment]
Are you testing with mobile device?
Mainly, depend of mobile screen resolution of device user. 
Revert the commit?

**Comment by mckillo** [comment]
Done.
