### ISSUE TITLE
toggle inlinehelp in jem settings

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1587]
see items #1338 and #1339 too.
I tried with these articles. now I see very short time the toggle and then it disappears.
Would be good to have it visible and enabled.
[by the way: there are a lot of description who aren't useful, because they say the same as the label. But only if you can make them visible, it is good to write better texts".]

**Comment by mckillo** [comment]
I have the same issue in edit event view (backend). When the button move to the right, disappear (by 'd-none' class ). I have to debug it.

**Comment by mckillo** [comment]
Add inlinehelp button to FormView: "This pull request has been automatically rebased to 5.0-dev. No new features will be merged into Joomla! 4.3 series. Joomla! 4.4 series is a bridge release to make migration from Joomla! 4 to 5 as smooth as possible." See https://github.com/joomla/joomla-cms/pull/39073

**Comment by mckillo** [comment]
\media\system\js\inlinehelp.min.js is javascript to add  'd-none' class and hidden the bottom.
This is Joomla core. I think that we'll have to wait.

**Comment by jojo12** [comment]
Ok, but why this is working in com_config and in modules since JL4.1?

**Comment by mckillo** [comment]
I don't know, but it doesn't work. There are alot issues about this button ( https://github.com/joomla/joomla-cms/pull/37819, https://github.com/joomla/joomla-cms/pull/37917, https://github.com/joomla/joomla-cms/pull/37849, https://github.com/joomla/joomla-cms/pull/39073, https://github.com/joomla/joomla-cms/pull/35610)

In my debugger of javascript .... If I rename \media\system\js\inlinehelp.min.js file (not load and load inlinehelp.js) .... the 'Toggle Inline Help' buttom appears but It doesn't work.

**Comment by jojo12** [comment]
Thank for your researches. In this case I am not very happy with the responsable makers of Joomla (not with you :-) ). The guided tours isn't the better way.

**Comment by mckillo** [comment]
![JEM4 - help page buttom](https://github.com/jemproject/JEM-Project/assets/2765316/30b84c2e-2aba-4b82-884f-78542f2234a0)

Alternative, prepare help pages in the JEM web. 
There are to migrate JEM web with J3 to J4, create a menú /help/4.0/... or manual page.

**Comment by jojo12** [comment]
yes, I've seen. (but I think, this could be for 4.01.

**Comment by mckillo** [comment]
I have installed JEM 4.0 rc1 in Joomla 5.0.0 rc1 with PHP 8.2 (with small version change into pkg_jem_v4.0rc1\pkg_jem\packages\com_jem.zip\com_jem\script.php to 5.1.0) and JEM works.
I'll try to check this 'Toggle Inline Help buttom witn JEM+JL5.0.0a1

**Comment by mckillo** [comment]
Nothing, it doesn't work.
jl500a1\media\system\js\inlinehelp.js is the same, don't change.
I think that there is something that I don't see. I don't understand.

![JEM4 - help page buttom soens't appear on Joomla5 5 0 alpha 1](https://github.com/jemproject/JEM-Project/assets/2765316/d5a792b8-2a71-4e15-b353-0cda1e689458)

**Comment by mckillo** [comment]
This isn't going to work, because in JEM views, the fields are showing with getLabel and getInputm and 'Toggle Inline Help buttom' works when the fields are generate by renderField layout (use LayoutHelper::render). This is the problem, there are to change all JEM views to use 'Toggle Inline Help buttom'. And I have doubts that it is a final solution in JL5.0

I'll think to find alternative  workaround without change all view code (when the field has a description in xml file)

![JEM4 - help page buttom soens't appear on Joomla5 5 0 alpha 1 (test alternative to works)](https://github.com/jemproject/JEM-Project/assets/2765316/d3d5382e-c5e5-4bfe-8e8d-2a0c93d7dd91)

**Comment by mckillo** [comment]
I think that I have found the way.
Change call getLabel and getInput to show the field for renderfield.

**Comment by mckillo** [comment]
When you have time check these two commits of this issue. 

![JEM4 -Toggle Inline Help works (draft to change code use renderfield)](https://github.com/jemproject/JEM-Project/assets/2765316/c9e53340-3888-4d0c-88c9-786c38418d66)

If we approve this change, we must add the styles (css) of the fields. I think it's a simple solution to adapt.
Tell me, your opinion and testing.

**Comment by jojo12** [comment]
yes it works: the toggle is visible and when clicking on it, the text under the field appears. It is the label.

Now it only needs to finde the desc of the label.

**Comment by mckillo** [comment]
All field descriptions are in \administrator\components\com_jem\models\forms\*.xml
In my case, this last commit is for event view and use event.xml

**Comment by mckillo** [comment]
![JEM4 -Toggle Inline Help works (migration render fields in setting)](https://github.com/jemproject/JEM-Project/assets/2765316/305b9369-40be-4e9b-ac0c-7057255c6b85)

See commit above. Active Toggle Inline Help in other backend views: category, group, venues, setting.

**Comment by jojo12** [comment]
I like the specific help too: it links directly to the right JEM help page!

**Comment by mckillo** [comment]
It would be good to know the help structure in the new web.
For example, if the help page will be in:
https://www.joomlaeventmanager.net/help/4.0/
https://www.joomlaeventmanager.net/documentation/4.0/
https://www.joomlaeventmanager.net/documentation/4.0/backend/
https://www.joomlaeventmanager.net/documentation/4.0/backend/control-panel
https://www.joomlaeventmanager.net/documentation/4.0/backend/events
https://www.joomlaeventmanager.net/documentation/4.0/backend/venues
https://www.joomlaeventmanager.net/documentation/4.0/backend/categories
https://www.joomlaeventmanager.net/documentation/4.0/backend/groups
https://www.joomlaeventmanager.net/documentation/4.0/backend/settings
https://www.joomlaeventmanager.net/documentation/4.0/modules/
https://www.joomlaeventmanager.net/documentation/4.0/modules/basic
https://www.joomlaeventmanager.net/documentation/4.0/modules/wide
https://www.joomlaeventmanager.net/documentation/4.0/modules/calendar
https://www.joomlaeventmanager.net/documentation/4.0/modules/teaser
https://www.joomlaeventmanager.net/documentation/4.0/modules/banner
https://www.joomlaeventmanager.net/documentation/4.0/modules/junilee
https://www.joomlaeventmanager.net/documentation/4.0/plugin/
https://www.joomlaeventmanager.net/documentation/4.0/plugin/content
https://www.joomlaeventmanager.net/documentation/4.0/plugin/list-events-content
https://www.joomlaeventmanager.net/documentation/4.0/plugin/smart-search
https://www.joomlaeventmanager.net/documentation/4.0/plugin/comments
https://www.joomlaeventmanager.net/documentation/4.0/plugin/mailer
https://www.joomlaeventmanager.net/documentation/4.0/plugin/quick-icon
https://www.joomlaeventmanager.net/documentation/4.0/plugin/search

and if the help structure were defined, then we can custom the help buttom to link each pages.
Do you like it? This should be in other issue, do you open it?

**Comment by Heklaterriol** [comment]
@mckillo really cool! Works fine here! Thank you!

One suggestion: I suggest to leave the inline help away when it does not contain any additional information but is just a repetition of the label. It makes the interface more confusing.

![inline-help](https://github.com/jemproject/JEM-Project/assets/28540581/8c7a103e-c0e5-4ea1-8142-6b0ea5f35f14)

**Comment by mckillo** [comment]
These are the ocurrente descripción of fields. If we don't want to show any descripción, it's easy, delete the descripción key un the XML file.

**Comment by Heklaterriol** [comment]
> These are the current description of fields. If we don't want to show any description, it's easy, delete the description key in the XML file.

OK, then I will start to remove the descriptions which double the labels.

**Comment by mckillo** [comment]
@ernst67 
The proposed structure for JEM documentation already has version /4.0/, but it could be JEM v.4 or JEM for Joomla 4.

The reference can be 4.0 or 4 or 4.x, What do you prefer? In the future version, you can replicate the structure for the new version 5.0 or 5.x or 5 (for JEM or for Joomla).

By default, the latest version of JEM will be the one referenced in the code links and web (each JEM version will be set with its help links... /4.0/, /4.1/, /5.0/...). It is a label in case in the future it is necessary to differentiate it.

How long will JEM version 4 live?
What will be the version of JEM when Joomla 5 is available?
Will JEM change a lot for the user when Joomla 5 comes out?

I don't know it. In my opinion, /4.0/ or simply /4/, it should be the mayor version of JEM.
Now, JEM 4 supports Joomla 5.0.0 alpha 1 and PHP 8.2. We don't need to change the version to JEM v.5.0. 

"when a user does not have internet access the help is unavaliable" ... I think the user already knows that :-) 

Tell me, the final structure will be and  update the code of help link. You create links to empty articles in the current web. These articles can have the view capture (default setting) with the descriptions of each field and some.

**Comment by jojo12** [comment]
I am not sure,  but I think, it is better when  the help leads directly to the part of JEMhelp inside of the program and not to joomlaeventmanager.net.

**Comment by mckillo** [comment]
This help buttom is a link to URL

**Comment by jojo12** [comment]
yes, but direct, e.g.:
`ToolBarHelper::help('listevents', true);`
is better

**Comment by mckillo** [comment]
But the user already has JEM-Help to see internally this static content as first resource, I think, that we can add this help button to redirect the user to external help on the JEM web (dynamic content or the help updater and extender). 

On the other hand:
- If JEM has a documentation website we can send the url of reference to other users to help them.
- If we need to publish any help or modification help in the extension, you need a new version, so, with the help web page, we can publish this help for all people without any new version.

Other extensions (Akeeba, Phoca, JCE, Acymailing, ....) has documentation on their website. Google indexes these pages and the users find help about JEM. The official documentation is the reference how Joomla does too or other event managers extension.

What is better (internal or external)?

**Comment by jojo12** [comment]
You're right. Better would be both!

**Comment by ernst67** [comment]
Yes, good points mckillo!

Both would be excellent. For the name I would simply refer to JEM4 (to avoid misunderstandings with Joomla4)
JEM 4 is now for Joomla 4 but may live to Joomla5 

So as URLs":
[](https://www.joomlaeventmanager.net/documentation/JEM4/backend/)

Agree?

**Comment by mckillo** [comment]
https://www.joomlaeventmanager.net/documentation/jem4/
https://www.joomlaeventmanager.net/documentation/jem4/backend/
https://www.joomlaeventmanager.net/documentation/jem4/backend/control-panel
https://www.joomlaeventmanager.net/documentation/jem4/backend/control-panel/export-data
https://www.joomlaeventmanager.net/documentation/jem4/backend/control-panel/import-data
https://www.joomlaeventmanager.net/documentation/jem4/backend/control-panel/housekeeping
https://www.joomlaeventmanager.net/documentation/jem4/backend/control-panel/css-manager
https://www.joomlaeventmanager.net/documentation/jem4/backend/control-panel/load-sampledata
https://www.joomlaeventmanager.net/documentation/jem4/backend/control-panel/update-check
https://www.joomlaeventmanager.net/documentation/jem4/backend/control-panel/manage-plugins
https://www.joomlaeventmanager.net/documentation/jem4/backend/control-panel/help
https://www.joomlaeventmanager.net/documentation/jem4/backend/control-panel/statistics
https://www.joomlaeventmanager.net/documentation/jem4/backend/events
https://www.joomlaeventmanager.net/documentation/jem4/backend/events/add-event
https://www.joomlaeventmanager.net/documentation/jem4/backend/venues
https://www.joomlaeventmanager.net/documentation/jem4/backend/venues/add-venue
https://www.joomlaeventmanager.net/documentation/jem4/backend/categories
https://www.joomlaeventmanager.net/documentation/jem4/backend/categories/add-category
https://www.joomlaeventmanager.net/documentation/jem4/backend/groups
https://www.joomlaeventmanager.net/documentation/jem4/backend/groups/add-group
https://www.joomlaeventmanager.net/documentation/jem4/backend/settings
https://www.joomlaeventmanager.net/documentation/jem4/backend/settings/basic-settings
https://www.joomlaeventmanager.net/documentation/jem4/backend/settings/event-page
https://www.joomlaeventmanager.net/documentation/jem4/backend/settings/layout
https://www.joomlaeventmanager.net/documentation/jem4/backend/settings/global-parameters
https://www.joomlaeventmanager.net/documentation/jem4/backend/settings/user-control
https://www.joomlaeventmanager.net/documentation/jem4/backend/settings/config-info
https://www.joomlaeventmanager.net/documentation/jem4/modules/
https://www.joomlaeventmanager.net/documentation/jem4/modules/basic
https://www.joomlaeventmanager.net/documentation/jem4/modules/wide
https://www.joomlaeventmanager.net/documentation/jem4/modules/calendar
https://www.joomlaeventmanager.net/documentation/jem4/modules/teaser
https://www.joomlaeventmanager.net/documentation/jem4/modules/banner
https://www.joomlaeventmanager.net/documentation/jem4/modules/junilee
https://www.joomlaeventmanager.net/documentation/jem4/plugin/
https://www.joomlaeventmanager.net/documentation/jem4/plugin/content
https://www.joomlaeventmanager.net/documentation/jem4/plugin/list-events-content
https://www.joomlaeventmanager.net/documentation/jem4/plugin/smart-search
https://www.joomlaeventmanager.net/documentation/jem4/plugin/comments
https://www.joomlaeventmanager.net/documentation/jem4/plugin/mailer
https://www.joomlaeventmanager.net/documentation/jem4/plugin/quick-icon
https://www.joomlaeventmanager.net/documentation/jem4/plugin/search
https://www.joomlaeventmanager.net/documentation/jem4/plugin/search
https://www.joomlaeventmanager.net/documentation/jem4/plugin/others/acymailing
https://www.joomlaeventmanager.net/documentation/jem4/plugin/others/community-builer
https://www.joomlaeventmanager.net/documentation/jem4/override
https://www.joomlaeventmanager.net/documentation/jem4/languages
https://www.joomlaeventmanager.net/documentation/jem4/github

This will be the help structure menu. Any more?
In the begining with an article empty with the same name of the end menu.
We would can use Phoca Documentation for Joomla 4 (Template override of blog content, not component...when we'll have website in J4).

**Comment by mckillo** [comment]
There will be to define the design style of content, I proposal to create a fisrt article (real example) to define the template for all help article, for example:
- Intro (1-3 lines).
- Capture view or options from JEM extension (front or backend)
- Define all option. This can be the descripcion of field (ini file)
- - extension help of this field (if apply).
with time or when it will be necesary, extend with)
- Sample config (sector or practical uses).

**Comment by ernst67** [comment]
I'm not too keen to use yet another component (Phoca Documentation like you proposed). Actually, Phoca Download is one of the more complicated components to upgrade the site from Joomla3 to 4. 
I need to export and import all tabels.

I think the documentation can be completed with with just Joomla articles and a menu structure. 

For most things we do I always check with Kunena and see how they solve it. Actually, they also use articles, but their documentation contains more than just the help files. Look at this:

https://docs.kunena.org/en

Their help is only onder item 9 in the list: Manual. 
If we do it like that it would allow us to have more "general" items in the documentation e.g. about mimimum requirements, etc.

So I will set up the menu like you proposed onder Documentation. I propose to add "help" or "manual' after "jem4" for those items that will be linked from component.
I guess all the url's containing "backend" will be linked from the help button?.

**Comment by mckillo** [comment]
I only agree with Joomla (my reference/proposal was for Phoca Documentation for J4, it isn't component, not table, only content template override), but I don't remember that JEM website is in J3.

It's good example of Kukena (9.Manual for backend and frontend).
I think that it isn't necessary to add "help" or "manual, it was redundancy because before there was /documentation/, another it could be to change /documentation/ to /manual/. 

And yes, all urls with backend will be linked from the help button.

**Comment by ernst67** [comment]
All articles have been created. You can see them when logged in the site: a top menu item "documentation" appears. 
The menu is displayed on the right, I set up 2 menu structures to choose from. One is always expanded, the other is an accordeon style menu

**Comment by mckillo** [comment]
Perfect, I'm on it

**Comment by mckillo** [comment]
Ok I wait that you finish it.

**Comment by ernst67** [comment]
Well, just tell me which you prefer

**Comment by mckillo** [comment]
Option 2 too, white and colapse is clear and clean. But add +1or +2 size letter, in mobile is some little.

**Comment by jojo12** [comment]
I agree to mckillo option 2

**Comment by ernst67** [comment]
Done. Changing the font size (currently 12) into something bigger messes up the layout of the module. (I tested in Firefox).
If you have any tip they are welcome!

Also added some articles under the general info ("basics") about system requirements, installation and upgrading (Jojo, i stole the text from your forum post).
Please have a look and feel free to make adaptions

**Comment by jojo12** [comment]
@rubber: well done!😉

**Comment by ernst67** [comment]
rubber?

**Comment by jojo12** [comment]
Robber, my english, sorry

**Comment by mckillo** [comment]
I like it ... tomorrow I'll update the inline-help branch with the new link help button.

**Comment by ernst67** [comment]
OK. Meanwhile I have set the the documentation area to public viewing

**Comment by jojo12** [comment]
you can see the documentation, but it's written "You are not authorised to view this resource."

**Comment by mckillo** [comment]
@ernst67 Me too, same error. See PM.

**Comment by ernst67** [comment]
@mckillo 
I answered your PM

**Comment by jojo12** [comment]
it seems, in Joomla 4.3.3 toggle inlinehelp is away and the helptext is always visible! 
:-)

**Comment by jojo12** [comment]
it works, can this be closed?

**Comment by mckillo** [comment]
Yes, the inline help wa inclued into request-answer branch. All urls of Documentation (website) are in code now (v.4.0.1), 
Can be closed.
