### ISSUE TITLE
Old JEM key and tables from old installation

### ISSUE THREAD

**Issue by mckillo** [jemproject/JEM-Project#1588]
Resolving a case in the forum, I have find 3 things in migration JEM from old versions:

**1. Old JEM tables:**
I found 3 old tables (I think):
#__jem_dates
#__jem_recurrence
#__jem_recurrence_master
But in the JEM 4 code, these tables don't exist. Anybody know about them? 

**2. Old JEM keys:**
In this same JEM installation (migration from old JEM version), there are 14 key old in the #__jem_config table:

![JEM3 - old key into jem_config table](https://github.com/jemproject/JEM-Project/assets/2765316/4b7a365e-f5e0-4147-bd87-a6bc1195c1f1)

In JEM 4 code, they don't use.

**3. Old structure define in some tables:**
Hay que redefine some columns in the following tables:

ALTER TABLE `#__jem_attachments`
    MODIFY COLUMN `id` int(11) unsigned NOT NULL auto_increment;

ALTER TABLE `#__jem_categories`
    MODIFY COLUMN `id` int(11) unsigned NOT NULL auto_increment
    , MODIFY COLUMN `parent_id` int(11) unsigned NOT NULL DEFAULT '0'
    , MODIFY COLUMN `access` int(11) unsigned NOT NULL DEFAULT '0';

ALTER TABLE `#__jem_cats_event_relations`
    MODIFY COLUMN `id` int(11) unsigned NOT NULL auto_increment
    , MODIFY COLUMN `ordering` tinyint(11) NOT NULL DEFAULT 0;

ALTER TABLE `#__jem_countries`
    MODIFY COLUMN `id` int(11) unsigned NOT NULL auto_increment;

ALTER TABLE `#__jem_events`
    MODIFY COLUMN `id` int(11) unsigned NOT NULL auto_increment
    , MODIFY COLUMN `locid` int(11) unsigned NOT NULL DEFAULT '0'
    , MODIFY COLUMN `created_by` int(11) unsigned NOT NULL DEFAULT '0'
    , MODIFY COLUMN `modified_by` int(11) unsigned NOT NULL DEFAULT '0'
    , MODIFY COLUMN `version` int(11) unsigned NOT NULL DEFAULT '0'
    , MODIFY COLUMN `recurrence_number` int(2) NOT NULL DEFAULT '0'
    , MODIFY COLUMN `recurrence_type` int(2) NOT NULL DEFAULT '0'
    , MODIFY COLUMN `hits` int(11) unsigned NOT NULL DEFAULT '0'
    , MODIFY COLUMN `contactid` int(10) NOT NULL DEFAULT '0'
    , MODIFY COLUMN `attribs` varchar(5120) NOT NULL DEFAULT ''''
    , MODIFY COLUMN `language` char(7) NOT NULL DEFAULT ''''';

ALTER TABLE `#__jem_groupmembers`
    MODIFY COLUMN `id` int(11) unsigned NOT NULL auto_increment;

ALTER TABLE `#__jem_groups`
    MODIFY COLUMN `id` int(11) unsigned NOT NULL auto_increment;

ALTER TABLE `#__jem_register`
    MODIFY COLUMN `id` int(11) unsigned NOT NULL auto_increment
    , MODIFY COLUMN `status` tinyint(3) NOT NULL DEFAULT 1;

ALTER TABLE `#__jem_venues`
    MODIFY COLUMN `id` int(11) unsigned NOT NULL auto_increment
    , MODIFY COLUMN `venue` varchar(100) NOT NULL DEFAULT ''''
    , MODIFY COLUMN `created_by` int(11) unsigned NOT NULL DEFAULT '0'
    , MODIFY COLUMN `modified_by` int(11) unsigned NOT NULL DEFAULT '0'
    , MODIFY COLUMN `version` int(11) unsigned NOT NULL DEFAULT '0';

______________________________________________________________________________________

I don't have any idea, what JEm version is 3.0.6, but there are unify code/table to migration to JEM 4.
Any more info?

**Question:** 
I think that we need to create a sql script to update of these points, for example: \administrator\components\com_jem\sql\updates\mysql\4.0rc1.sql
Can I made it and add it?

It will be good, if others old details similar could be detected to include it to final version.

**Comment by jojo12** [comment]
JEM 3.0.6 is/was a version of bluefox, which is/was dead. There was never a backward compatibility. JEM 2.3+ advanced more with more features.

**Comment by jojo12** [comment]
There were experimental version until 3.0.7. The use of them were always AT YOUR OWN RISK and not on livesites. So we don't have to pay attention to them!!!

**Comment by mckillo** [comment]
OK

**Comment by mckillo** [comment]
More info about case: https://www.joomlaeventmanager.net/forum/bugs/12337-backend-events-error?start=12#30412
