### ISSUE TITLE
Frontend Edit event: "Call to a member function format() on bool" if you use not english (date)

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1590]
I have 2 sites which work and 2 sites which give always this error, when trying to save in editevent (even when I don't change anything).
Error and then it is  checked out. Even as superuser.
Editvenue is working fine.
I can't find more infos.

**Comment by mckillo** [comment]
Could you set (temporal) debug system to have more info about error?

**Comment by jojo12** [comment]
Problem is: I have no ftp access!

**Comment by mckillo** [comment]
Send me a PM with the websites and user to test or see the error.

**Comment by jojo12** [comment]
I don't understand: you didn't login. I retry after so many tries and now it works. Why?

**Comment by mckillo** [comment]
I don't know. Sometimes the symptoms disappear when the doctor comes. :-)

**Comment by jojo12** [comment]
Stay with me ;-)

**Comment by mckillo** [comment]
In any case, leave it under observation and one less issue.

**Comment by mckillo** [comment]
After this time, has the error reappeared? If not, this issue could be closed.

**Comment by jojo12** [comment]
yes, sometimes it reappears on new sites, I can only speculate, what this can be. It seems to be only in sites who are offline

**Comment by mckillo** [comment]
I'm sorry, but for this type of error, I can't help you, if I can't replicate the error in local to debug it.

**Comment by mckillo** [comment]
Check to run this script sql (change the xxxxx for you Joomla prefix in DB):

`UPDATE xxxxx_extensions SET params = '{\"context\":\"mod_quickicon\",\"jem_quickicon\":\"JEM\"}' WHERE name = 'Quick Icon - JEM';` 
![JEM4 - Fix to show JEM quickicon (plugin)  in the Joomla Dashboard](https://github.com/jemproject/JEM-Project/assets/2765316/1bbb987a-d3c7-4f96-a4d4-e3565faee203)

Tell me if works.

**Comment by jojo12** [comment]
Sorry , I can't test Im on the roadd

**Comment by jojo12** [comment]
There's a post in joomlaeventmanager.net from pctech with the same problem:
[#30531](https://www.joomlaeventmanager.net/forum/bugs/12370-picture-to-event-upload-error-0-call-to-a-member-function-format-on-bool#30531)

**Comment by jojo12** [comment]
Finally found the conditions, when ERROR happens: if you use german language (perhaps others too)
If you use english --> there are no problems!
So it should be the translation problem between german and DB entry

**Comment by ernst67** [comment]
I'm having an issue while downloading the translations from Transifex. There might be a corruption in one of the translations, but I'm not sure if it's German. I'm working on it with the Transifex support desk.. will keep you updated.

**Comment by jojo12** [comment]
It seems to be a problem in other languages too: there's a post about problems in hungarian language!

**Comment by jojo12** [comment]
I had this error just now, when language is other than english! I changed then to english, and the problem disappeard.
[I am quite sure, it has to do with the different datetime settings]

**Comment by jojo12** [comment]
My question: is there a problem with different datetime format between english and other languages?
In which files is this changement?

**Comment by jojo12** [comment]
At least we can give the hint: **when you have problems saving settings you make in frontend, then change to english!**

**Comment by mckillo** [comment]
One question: Do you install the German Language for JEM4 or only change the language in Joomla?

**Comment by jojo12** [comment]
Both

**Comment by mckillo** [comment]
I have loaded the com_jem.ini for front and back in de-D, and edit an event from front and back, modified the date, save y nothing. No errors. You can send a zip with the JEM language folder of front and back, to test it. 
Send me PM a video with the error (how to simulate),

**Comment by jojo12** [comment]
to reproduce:
I go to Joomla>System>Languages site=german admin=german and save.
I go to JEM **frontend**, login, I open an existing event>edit.
I can let it like that and trying to save or change something and then save --> the error is there
[in english the hint for dateformat is 2017-12-31, in german the hint for dateformat is 31.12.2017, where in the frontend is this changing?]

**Comment by jojo12** [comment]
it would be interesting which languages beneath german and hungarian have this problem too?

**Comment by mckillo** [comment]
I did this operation, and It works. I think that it could be any string of languages (translation). Could you attach your language files (front and back)?
And one more: you can set the debug system in Joomla, generate the error, and send the screen capture.

**Comment by jojo12** [comment]
I attched the language filec before, did you not ee the zip?

**Comment by jojo12** [comment]
With debug I don?t get any infos

**Comment by mckillo** [comment]
Sorry, I don't see it. When I'll return home this night, I'll test it again. Thanks

**Comment by jojo12** [comment]
I'll send you a pm with a link and a whatsapp with a pw

**Comment by mckillo** [comment]
@jojo Thanks, so, I have can to debug it.

I detected that I don't have the update for this field. That's the problem. When you have a recurrence event, the new recurrent events have the finish date in this field. In this case, the value is the recurrence_limit_date of the root event (defined when the user creates the first event of the recurrence).

For the moment the first solution is run this sql script in your DB:
`UPDATE `kpb_jem_events` SET `recurrence_limit_date` = null WHERE `recurrence_limit_date` LIKE '%0000-00-00%';`

It should work; for the moment, it's the first part of the solution, but the recurrence management is something I have to review. The second part is developing a tool for housekeeping called "Recover Recurrence". I have to see if I can recover the link with the root father (finish date). And there will be to improve the recurrence feature of events (to the edit, because the recurrence loses it).

Let's, in the afternoon, I'll add new lines to the 4.0.1.sql (update patch with it) with a new commit.

**Comment by jojo12** [comment]
I was able to change it with your 
`UPDATE `ww84i_jem_events` SET `recurrence_limit_date` = null WHERE `recurrence_limit_date` LIKE '%0000-00-00%';`

**Comment by jojo12** [comment]
I made a new zip and installed over, works fine!

**Comment by jojo12** [comment]
But e.g. on demo.joomlaeventmanager.net there was just a requestanswer, so I get

> Warnung
JInstaller: :Install: SQL-Fehler Duplicate column name 'requestanswer'
Installation der Erweiterung abgebrochen.
Paket Update: Bei der Installation der Erweiterung trat ein Fehler auf: com_jem.zip

**Comment by jojo12** [comment]
Thankyou @Heklaterriol 
so, I think it is better to go back here
(we know, we can save when we are in english language!)
and the normal way in admin is back!

**Comment by mckillo** [comment]
Sorry, why do we have to go back? Do we debug it? The real issue is #1643, right? If it's so, let's me try to debug it the case (1 day). I prefer to debug (first) instead (search solution) of go back. If there are an error, we have to find it.

**Comment by Heklaterriol** [comment]
Yes, I agree with mckillo.
Fixing may sometimes create new bug -- that's normal -- so let's fix them to.

**Comment by Heklaterriol** [comment]
Is this fixed too, see #1643?

**Comment by mckillo** [comment]
I think that you can closed too.

**Comment by jojo12** [comment]
I installed jem 4.1.0 on joomla 4.3.4 on php 8.2.4 xampp. this issue is back!

**Comment by jojo12** [comment]
I tested now without plg_jem_demo. No errors. So,I will create a new issue.
