### ISSUE TITLE
Event view (front) Error 0: array_merge(): Argument #1 must be of type array

### ISSUE THREAD

**Issue by mckillo** [jemproject/JEM-Project#1591]
Reported by jojo and user forum:
JEM --> Settings --> EVENT --> Registration --> Show all related users --> Enabled
Show Attendee Names to:
disabled, Nobody = ERROR for Every User in Group
disabled, only Admins !!!! = ERROR when USER in Registred Group

**Comment by jojo12** [comment]
works, no error, thanks! add to RC
