### ISSUE TITLE
mb_strtolower() in default_attendees.php and default_regform.php make Problems (in german)

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1594]
The texts for attending/waiting/invited should not be in lower letters in german. Why do you added mb_strtolower()?

**Comment by mckillo** [comment]
In Spanish and English, it is lower letters.... sorry, it's a defect/inheritance when not programming for other languages ​​(example: German).
Let's me a minute to eliminate

**Comment by mckillo** [comment]
Tell me, if the issue is with this commit.
