### ISSUE TITLE
July is here! JEM 4.0.0 stable too!

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1598]
July is coming!

**Comment by mckillo** [comment]
Inline help and help button, will they be added in this release or next?

**Comment by mckillo** [comment]
There is to check the update procesa (xml). See #1220

**Comment by jojo12** [comment]
you asked:

> Inline help and help button, will they be added in this release or next?

I would say: it's not yet finished and not yet tested, Release Candidate means, you don't add new things, even if they are very good!
So I would say: it's too late. And I hope you will not postpone JEM4 for that!

**Comment by mckillo** [comment]
Ok.
Then there is to check the update procesa (xml). See #1220

**Comment by mckillo** [comment]
I would like to check the ZIP final release before to publish in web and JED. There are to update process and version number in several files (sql, xml)

**Comment by jojo12** [comment]
Yes, can you do it?

**Comment by mckillo** [comment]
I don't permissions to change the update xml file in the web.

**Comment by jojo12** [comment]
Who makes the package?

**Comment by Heklaterriol** [comment]
> Who renames the files? to 4.0.0? Who makes the package?

I rename the version numbers in the branch "JEM-for-Joomla-4" and create a package.
OK?

**Comment by Heklaterriol** [comment]
I just noticed that in `plug_jemmyevents` and `plug_jemmyattending` there still are some old version numbers in the compatibility information in the header: `for JEM v2.3.10 & CB v2.0`
What is the state of the art? Do they work with JEM 4.0 an Community Builder 2.8?

**Comment by Heklaterriol** [comment]
the same with `plg_tagjem` to include events in acymailing .
Which acymailing versions do work with it?

**Comment by jojo12** [comment]
CB plugins work with CB 2.8 and JEM 4.
There are some things which could be better, but it is an other kind of programming. And it seems noone of you is using CB, so I hope, all other CB users are happy to have it at least like it is.
Tagjem is working fine with Acymailing 5 on Joomla 4.

**Comment by Heklaterriol** [comment]
to be safe, I created a temporary branch for the new version number 4.0.0
https://github.com/jemproject/JEM-Project/tree/JEM-4.0.0

Please check

**Comment by jojo12** [comment]
I checked, I took the zip file inside of JEM-4.0.0 and installed in Joomla 4 without JEM. It works and shows me in config info 4.0.0

**Comment by mckillo** [comment]
This file need to update the reference 4.0.0
\pkg_jem_v4.0.zip\pkg_jem\packages\com_jem.zip\com_jem\README.md

In pkg_jem_v4.0.zip\pkg_jem\packages\com_jem.zip\com_jem\script.php file line 230:, we can change to:
if (version_compare(JVERSION, '5.0.0', 'ge') ||  // J! 5.x NOT supported, but allow alpha/beta

I'm testing ....
I have update Joomla-

**Comment by Heklaterriol** [comment]
> This file need to update the reference 4.0.0 \pkg_jem_v4.0.zip\pkg_jem\packages\com_jem.zip\com_jem\README.md
> 
> In pkg_jem_v4.0.zip\pkg_jem\packages\com_jem.zip\com_jem\script.php file line 230:, we can change to: if (version_compare(JVERSION, '5.0.0', 'ge') || // J! 5.x NOT supported, but allow alpha/beta

Done and included in the new zip package.

**Comment by jobrusche** [comment]
The pkg_jem_v4.0.zip I downloaded at 00:06 (Juli 4) still thinks it is at JEM 2.3.5 (released nov 2022) in control panel "Update check"

**Comment by Heklaterriol** [comment]
this one https://github.com/jemproject/JEM-Project/blob/JEM-4.0.0/pkg_jem_v4.0.zip ?

**Comment by jobrusche** [comment]
Yes

**Comment by mckillo** [comment]
Don't worry, there are to update https://www.joomlaeventmanager.net/updatecheck/update.xml file in the server. It will be updated it.

**Comment by Heklaterriol** [comment]
> Don't worry, there are to update https://www.joomlaeventmanager.net/updatecheck/update.xml file in the server. It will be updated it.

@jobrusche: With other words: the new version number is not yet in the update file, so still the old version number is fetched.

**Comment by Heklaterriol** [comment]
> Don't worry, there are to update https://www.joomlaeventmanager.net/updatecheck/update.xml file in the server. It will be updated it.

@mckillo and @jojo12  (whoever will update the file): I think it would be good to include both JEM 2.3.6 for J3 and JEM 4.0.0 for J4 in the update.xml file, so that JEM 2.3.5 users get the information for the update.

**Comment by jojo12** [comment]
I agree!

**Comment by ernst67** [comment]
@jobrusche 
The XML needs to be updated. I will do it, but off course there is an order-of-things-to-do.

1. Make sure the new version is available for download. It has to be on the JEM website, within Phoca download, otherwise we can't track the number of downloads. 
2. Update the XML file.
3. Update the info on JED and the direct download from there

If all is ready I will organise it. Is the main repo now at it's final place? Then I will also create the links between the language files on github and the files on Transifex to automatically update the files there.

**Comment by ernst67** [comment]
And then there is more to do:

4. send out en e-mailing to all current JEM users to tell them the good news ;-)
5. sit an wait at the forum, for the first bugs to be reported |:-/

**Comment by mckillo** [comment]
@Heklaterriol The xml file for JEM 2.3.x is https://www.joomlaeventmanager.net/updatecheck/update.xml , but for JEM 4.0.0 will be https://www.joomlaeventmanager.net/updatecheck/update_pkg_jem.xml.
This file already is updated, see https://github.com/jemproject/JEM-Project/commit/9ffa70100594fff32d49588f30ffab347e360e60

**Comment by mckillo** [comment]
@ernst67 This version 4.0.0 is very stable, I tested with Joomla 4.4 alpha 2 and 5.0 alpha 2 ahn working fine.
After sit and wait at the forum ..., I'll add one point:

6. Finish the new features in open branch ... request answer, microdata, inline help and documentation (manual).
:-)

**Comment by Heklaterriol** [comment]
> Is the main repo now at it's final place?

- In the master branch is still the version 2.3.6
- the final JEM 4 version is still in https://github.com/jemproject/JEM-Project/tree/JEM-4.0.0  

Should we move the final JEM 4 version to the master branch and JEM 2.3.6 to a 2.3.6 branch ?

**Comment by jojo12** [comment]
I think this will be a new 4.0.1beta

**Comment by mckillo** [comment]
All version JEM are tagged, see https://github.com/jemproject/JEM-Project/tags, For it, I think, we don't need to have open more branch for old version. If in the near future, I need to do any patch for old version, we can create a new branch from old origin version (commit associated to tag version).

**Comment by mckillo** [comment]
New JEM 4.0.0 could be updated with the last commit in the JEM-for-Joomla-4 or if you prefer, I can copy to new branch JEM-4.0.0.
After JEM 4.0.0 merge to master and update JEM-for-joomla-4 with master, rename JEM-for-joomla-4 to v.4.0.1dev branch.
What do you think?

**Comment by ernst67** [comment]
@Heklaterriol 
What is the name of this version? 4.0 or 4.0.0? 
If we want to leave room for bugfixes I suuggest the last one. (all our versions have 3 digits)

**Comment by Heklaterriol** [comment]
> What is the name of this version? 4.0 or 4.0.0?
>  If we want to leave room for bugfixes I suuggest the last one. (all our versions have 3 digits)

Yes, that was also my consideration: 4.0.0
Then 4.0.1 etc will be bugfixes, 4.1.0 will be an update with new features etc.
And if was with three digits before, then we should keep it

**Comment by jojo12** [comment]
I agree

**Comment by Heklaterriol** [comment]
> All versions of JEM are tagged, see https://github.com/jemproject/JEM-Project/tags, For that, I think, we don't need to have open more branches for the old version. If in the near future, I need to do a patch for the old version, we can create a new branch from the old origin version (commit associated to tag version).

But shouldn't we put the stable J4 version in the master branch instead of the old J3 version? In my opinion it seems rather confusing, if it isn't like this …

**Comment by ernst67** [comment]
I would be in favour of removing the J3 version at all. Or at least make it invisible

**Comment by jojo12** [comment]
What do you mean with J3.
Joomla or JEM.
JEM 3 should be hidden just long time ago.

**Comment by ernst67** [comment]
The update_pkg_jem.xml is a bit of a challenge.....

First we need to update the xml for version 2.3.6. 
But also for 4.0.0. And that one needs a warning that you can't just update with a one-click update. 

We can maybe point to https://www.joomlaeventmanager.net/documentation/basics/upgrading

**Comment by mckillo** [comment]
@Heklaterriol  you said "...JEM 2.3.6 to a 2.3.6 branch ?" In my answer, I said "we don't need to have open more branches for the old version."
I agree with you, the last version (4.0.0) must be in máster branch....but We don't need any new branch for okd versión (2.3.6)

**Comment by Heklaterriol** [comment]
OK, I understand.
Then we will overwrite the version 2.3.6 with version 4.0.0, or in other words: merge `JEM-4.0.0` into `master`, right?

**Comment by mckillo** [comment]
Yes

**Comment by Heklaterriol** [comment]
The changes from `JEM-for-Joomla-4` are  taken over to `JEM-4.0.0`
see: Fix Updatecheck for JEM 4.0.0 https://github.com/jemproject/JEM-Project/issues/1220

**Comment by mckillo** [comment]
Ask before, the line 70 of \JEM-Project\admin\views\updatecheck\update_pkg_jem.xml. is it right? url finish in 2 or 4?

**Comment by Heklaterriol** [comment]
I'm not experienced in dealing with releases, but I think it is important now for us to create/maintain a clear structure.

I tought of:
- define the branch "JEM-4.0.0" as release and moving it to "master"
- agreement not to touch "master"
- for bugfixing create a branch like "JEM-4.0.0-bugfix" for a future merge into "master"
- create a branches like "JEM-4-xyz" for new features xyz for future merges / pulls

What is the best practice?

**Comment by mckillo** [comment]
I agree, I try to define more details.

In the pass, the master has the last version JEM, but there aren't branchs opened with old release.
In my experience, this project doesn't have unit test and regression script, if anything fault. For that, We should change the master only for final release. The next version: 4.0.1dev or v.4.0.1alpha or 4.0.1beta or 4.0.1rc should be new branch (rename with the phase version: dev, alpha, beta, rc by orden). New feature should be a child of this new branch, as you said "xxx" (its father is the root version (don't need JEM-4-).

Structure branchs in Github:
- master (last stable release).
- - 4.0.1dev (after rename as 4.0.1alpha, 4.0.1beta, 4.0.1rc)
---- request answer
---- microdata
---- inline help and documentation botton
-- 4.0.2
-- 4.1.0

When a feature is finish, it merges to root (request answer merge into 4.0.1dev) and this child branch will delete).
When a new version is finsih to publish, will be integrate in master (4.0.1 merge into master).
And you always have to add the bug or feature news into change log article v.4 (with the number issue #XXXX opend and closed)
