### ISSUE TITLE
request answer: adding info for event registration?

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1599]
Something is not very clear in the event registration:
in different groups it will be used differently!
1) e.g. booking a ticket for an event, then you don't need to say, that you will not come. Only for canceling a booked ticket.
2) e.g. in a group, it can be essential to say, that you can't come. So it needs an answer!
both things are possible with our system, but is this clear for admins and users?

Do we have to add a phrase for this?

**Comment by mckillo** [comment]
I see two things:
1. When the min.places=max.places=1 don't show option to add new places.
2. In the setting regitration of event, new check for request response assistance. In the first registration, don't show the ' I will NOT go to this event" if cnew check is unmark.

See the proposal in the following image:
![JEM4 - Proposal for improvement of registration information in event](https://github.com/jemproject/JEM-Project/assets/2765316/ad247796-f0c6-486e-ac3e-bf909846cbf7)

What do you think?

**Comment by jojo12** [comment]
Good proposal

**Comment by mckillo** [comment]
Here you are. First step of the proposal. First step to proposal. New 'Request answer asssistence" in setting event, if enabled, show option to the user doesn't go the event.

**Comment by jojo12** [comment]
I installed the com_jem.zip made from request-answer. I see in backend the events and in the new button, but in frontend and modules all events are away!

**Comment by mckillo** [comment]
if Request answer asssistence is uncheck, first time when the user go to the event, in your registration option, doesn't show the 'I will not go to this event' option. Right?

**Comment by jojo12** [comment]
I will test

**Comment by jojo12** [comment]
I can't see any event details because, all events are not visible in frontend, when request-answer is installed.
I can only see the button field "request answer assistance", i can check it or uncheck it, nothing more.

**Comment by jojo12** [comment]
when I go to My attendances I get
 1054
Unknown column 'a.requestanswer' in 'field list'

**Comment by mckillo** [comment]
Your package should have \admin\sql\updates\mysql\4.0rc1.sql, but I don't know why don't run it.

Run this script sql (change #_ for your prefix database):
`ALTER TABLE `#__jem_events` ADD `requestanswer` TINYINT(1) NOT NULL DEFAULT '0' AFTER `waitinglist`;`

**Comment by jojo12** [comment]
when I use this
ALTER TABLE #__jem_eventsADDrequestanswerTINYINT(1) NOT NULL DEFAULT '0' AFTERwaitinglist;
i get#1064 - Fehler in der SQL-Syntax. Bitte die korrekte Syntax im Handbuch nachschlagen bei '' in Zeile 1

**Comment by mckillo** [comment]
You have to change #__ for your prefix xxxxx_ , all you Joomla tableshave a prefix, use this prefix.
For example for me: ALTER TABLE **a8wlc_**jem_eventsADDrequestanswerTINYINT(1) NOT NULL DEFAULT '0' AFTERwaitinglist;

**Comment by jojo12** [comment]
even when I do that, I get: #1064 - Fehler in der SQL-Syntax. Bitte die korrekte Syntax im Handbuch nachschlagen bei 'ALTER TABLE jos_jem_events ADD requestanswer TINYINT(1) NOT NULL DEFAULT '0' ...'

**Comment by mckillo** [comment]
The sentence is right:
ALTER TABLE a8wlc_jem_events ADD requestanswer TINYINT(1) NOT NULL DEFAULT '0' AFTER waitinglist;
I don't have any error.
Testeing with INT:
ALTER TABLE a8wlc_jem_events ADD requestanswer1 INT NOT NULL DEFAULT '0' AFTER waitinglist;
Remember to change the prefix.

**Comment by jojo12** [comment]
Now I uninstalled the whole JEM with cleanup and installed a jem package from branch regquest-answer.
But there's no event and I can't install samplecode it's says: not empty, but there's nothing in

**Comment by mckillo** [comment]
In the beginig, I told you that there is a root category and the this tables isn't empty, you told me that root category must be. 
I use housekeeping - Delete all data and solved.

**Comment by jojo12** [comment]
i get this:
![grafik](https://github.com/jemproject/JEM-Project/assets/2960236/1bd3926c-0f4b-41c1-b097-6ab7bdfbdbd4)

**Comment by mckillo** [comment]
@jojo12 Delete line 180 with` ?>` in \components\com_jem\views\event\tmpl\responsive\default_regform.php file

**Comment by mckillo** [comment]
Finish the proposal with last commit (see above), If max.bookedp places per user =1, don't show "I want to book 1 places", by default is 1 (user).

**Comment by jojo12** [comment]
Actually I can't test the second part. The first part works fine in responsive and legacy now.
I tried on a xampp, but I had the "Call to a member function format() on bool" again.

**Comment by jojo12** [comment]
3)
text for button is better to have it always as "Send"
Don't switch between "send" and "register"!

**Comment by mckillo** [comment]
I don"t know when but I will try to simulate it.

**Comment by jojo12** [comment]
I am thinking loud:
If someone has not yet answered, he has no entry.
The procedure saying NO, seems to look if there is an entry, and because there is not yet an entry, it fails.
(If somebody said YES, then there is an entry. When then someone says NO, the procedure finds an entry and changes it. This works)
-->If someone answers NO, the procedure should create an entry with the answer NO.

**Comment by jojo12** [comment]
[@mckillo: Hi, I am back from holydays, will continue]

**Comment by jojo12** [comment]
I don't find the place in the program where is "COM_JEM_ERROR_REGISTRATION", which comes after a user says "I will not come"

**Comment by jojo12** [comment]
If a user says directly NO, then the program has to make an entry in DB jem_register with status=-1
(this should be like on an other place the first entry, when someone is invited then the program makes an entry in DB jem_register with status=0)

**Comment by jojo12** [comment]
Perhaps it is easier, only to add a sentence like "In any case, we need your answer"!
(But this doesn't solve the problem, that unregistration is  only possible, when registrated or at least invited before.)
If someone feedbacks directly NO, then we get the error.

**Comment by jojo12** [comment]
[Actually you first has to say YES, to say after NO -> to get the wanted result]

**Comment by jojo12** [comment]
I am not sure, 
but there is a $status=2, but there should be only -1, 0 and 1. In xxx_jem_register the waitinglist status is with "waiting=1"
what is $status=2?

**Comment by mckillo** [comment]
I'm sorry, but I thought you knew that the request-answer branch wasn't include in the release 4.0.0 and neither in the 4.0.1dev, but you demand is this feature that I was upload to the branch the 3th july. Do you test it?

**Comment by jojo12** [comment]
the problem, directly to say NO, I can't come is in 4.0.0 and in your request answer branch (came from book tickets)

**Comment by mckillo** [comment]
Yes, I know, but this branch is a solution (patch/enhancement). Are you agreement with the image below and the new option in registration setting?

**Comment by jojo12** [comment]
where is an image?

**Comment by mckillo** [comment]
![image](https://github.com/jemproject/JEM-Project/assets/2765316/02116a83-98dc-44b9-a181-d798db153ecc)

**Comment by mckillo** [comment]
If the new options (Request answer assitence) isn't check, the user haven't 'No' option in the registration form.

**Comment by jojo12** [comment]
yes, but this are two different problems. this here is trying a solution to  **request  answer.**
but there is an other problem which is just in 4.0.0

**Comment by mckillo** [comment]
Explain me please to clarify me.

**Comment by jojo12** [comment]
Issue #1573 and #1625 are just inside of JEM 4.0.0+ and have to be solved. This is a priority!
Issue #1599 is good, but has a problem inside this branch "request answer"

**Comment by jojo12** [comment]
Did you understand?

**Comment by mckillo** [comment]
Yes, do you have the commit with solution at the end of issue #1626

Can we do a merge the 'request-answer' branch as new feature of v.4.0.1?

**Comment by jojo12** [comment]
at the moment I have only this possibility:
![grafik](https://github.com/jemproject/JEM-Project/assets/2960236/143f9f2d-3d73-47de-b1d8-1b254f61ffe6)

**Comment by jojo12** [comment]
when this is solved then it is ok. (the other blockers are fine away!)

**Comment by jojo12** [comment]
it seems default_regform.php line 179 creates the problem!

**Comment by mckillo** [comment]
Yes, the issues can be closed.

**Comment by jojo12** [comment]
for the above image:
![grafik](https://github.com/jemproject/JEM-Project/assets/2960236/7d2cd65a-d1a3-44d7-8993-296d3dfd0cd3)

**Comment by jojo12** [comment]
in both cases DB requestanswer=0 and requestanswer=1 there is "no I will NOT go"

**Comment by mckillo** [comment]
Let's review and debug, because I did merge and update and unify the branchs, and it possibel to overwrite anything.

**Comment by jojo12** [comment]
I made a package with your commit and tested, now it is ok!
The only thing now is the request answer in legacy frontend edit
