### ISSUE TITLE
step-by-step instruction for migration: what, when template overrides?

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1602]
Do we need to say something about that in the instruction?
I added:

> If you are on a clean JEM 2.3.5 for Joomla!3 (if you have template overrides for JEM, you must adapt them by yourself!)

**Comment by Heklaterriol** [comment]
Yes of course this is an important point to mention.
And if someone updates Joomla to version 4, then the adaptation of template overrides is an issue anyway.

In my opinion we can close this issue.

**Comment by jojo12** [comment]
It's ok. But perhaps it is good to mention and think of that, because me, I sometimes forgot my overrides during an update!

**Comment by Heklaterriol** [comment]
I restructured the upgrading instructions on joomlaeventmanager.net and pointed out this issues (in the beginning to save and disable the overrides and at the end to adapt them)
