### ISSUE TITLE
How to update the other branches?

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1604]
I can't test anymore the other branches, because you can't update RC1 on 4.0.0 stable.

**Comment by mckillo** [comment]
I don't know what you use for it. For example with Github Desktop:

![JEM 4 - Comparation of update_pkg_jem with other old test xml file](https://github.com/jemproject/JEM-Project/assets/2765316/080f695e-8cc4-4395-b724-38dda2f8d246)

Other option is command line with git branch and git checkout.

**Comment by mckillo** [comment]
Was it resolved?

**Comment by jojo12** [comment]
I can't test anymore, because I have all my sites on JEM 4.0.0 and it doesn't accept to install RC1 on it!
Can you update to JEM 4.0.0, please.

**Comment by mckillo** [comment]
What do you mean with "update to JEM 4.0.0"? I don't see any RC1 version/branch and the last version is in JEM-4.0.0 branch.

**Comment by jojo12** [comment]
It's done thanks.
(I think, there must be a rule in the install routine, which don't let you install a older version over a newer version. As long as the branch has files with rc1 it isn't possible to install it over 4.0.0)
