### ISSUE TITLE
quickicon plugin doesn't work as it should!

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1606]
If I compare it with the quickicon of Jcomments, I see it doesn't work!

**Comment by jojo12** [comment]
If we can't repare it, we should delete it! But I think, this is not so much.

**Comment by mckillo** [comment]
Let's me check again, but for me, Quick icon plugin worked!

**Comment by jojo12** [comment]
What does it? I see nothing, what would correspond to other quickicons!

**Comment by jojo12** [comment]
it's fixed with the changes via DB and with adding  "use Joomla\CMS\Language\Text;"

**Comment by jojo12** [comment]
I tried to add the icon:
when I add into the array:
`				'access' => array('core.manage', 'com_jem'),	`
and change
`			'image' => 'calendar',`
to
`			'image' => 'icon-calendar',`
then there's an image

**Comment by jojo12** [comment]
not yet committed

**Comment by mckillo** [comment]
For me, tested and works. You can upload commit.

**Comment by jojo12** [comment]
Sorry, I do not commit!

**Comment by Heklaterriol** [comment]
I included jojos changes and added an "add event" feature.

**Comment by jojo12** [comment]
tested it works and nice add! Thanks
