### ISSUE TITLE
What does mean "Register to Read More"

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1608]
I don't understand, so I can't translate!
(in mod_jem_teaser)

**Comment by Heklaterriol** [comment]
I hat a look in the code where it occurs:

```
# check view access
if (in_array($row->access, $levels)) {
	# We know that user has the privilege to view the event
	$lists[$i]->link = Route::_(JemHelperRoute::getEventRoute($row->slug));
	$lists[$i]->linkText = Text::_('MOD_JEM_TEASER_READMORE');
} else {
	$lists[$i]->link = Route::_('index.php?option=com_users&view=login');
	$lists[$i]->linkText = Text::_('MOD_JEM_TEASER_READMORE_REGISTER');
}
```
Tecnically spoken: That means, that the "read more" is just for users with a certain access level(?) . If not in you have to login to have access to the text behind "read more" …

But where is this access level defined?

(And if this makes sense is also an other question!)
