### ISSUE TITLE
"Allow Event Registration" Setting unclear

### ISSUE THREAD

**Issue by Heklaterriol** [jemproject/JEM-Project#1609]
the possible selections of "Allow Event Registration" settings in > User Control > Registration 
are not clear:

`Yes` = globally yes
`No` = globally no
`Optional` = Use the settings of the event

I changed them to 
`Yes`
`No`
`Use Event Setting`

see: https://www.joomlaeventmanager.net/forum/bugs/12378-no-event-registration-wanted

**Comment by jojo12** [comment]
ok, I hope, it will be clearer
