### ISSUE TITLE
JEM 4.0.1-dev nightly builds

### ISSUE THREAD

**Issue by Heklaterriol** [jemproject/JEM-Project#1610]
While progressing with JEM 4.0.1-dev I suggest to create nightly builds from time to time.
I create them anyway to test, so I will just upload the most recent one, if you do not object.

Naming is `pkg_jem_v4.0.1-nightlyYYMMDD.zip` e.g `pkg_jem_v4.0.1-nightly230710.zip`

**Comment by jojo12** [comment]
I would say, pkg_jem_v4.0.1-nightly230827.zip is ready to publish

**Comment by jojo12** [comment]
change the headers to 4.0.1 and create a package. 
I can then upload to joomlaeventmanager.net
Ernst will do it to the JED.
for language there are only a few changes, I don't know how to do that they will come to transifex

**Comment by Heklaterriol** [comment]
Ok.
I will change the version number and create the package.

After that, I will also merge the dev 4.0.1 branch into the master branch and create a new dev 4.0.2 branch.

**Comment by jojo12** [comment]
Please a zip for acymailing_plugin and cb_plugins too.

**Comment by Heklaterriol** [comment]
in the DB update files the latst file is "4.0p1.sql".
I think it would be good to have the DB version also 4.0.1
@mckillo Is it possibe just to rename "4.0p1.sql" to "4.0.1.sql"?

**Comment by mckillo** [comment]
No, because now the squema version is 4.0b4, that was error (it should have been 4.0.0b4 or 4.0.0.b4). The best schema version for this release 4.0.1 is 4.0p1.sql. If you change to 4.0.1 then 4.0.1 < 4.0b4 and the squema isn't updated (don't run update script 4.0.1.sql, it's minor).

**Comment by mckillo** [comment]
Or jump to 4.1.0

**Comment by Heklaterriol** [comment]
> Or jump to 4.1.0

With the whole release?
I ask because I have the same thoughs, since there is more than bugfixing.

**Comment by mckillo** [comment]
Do you see my messsge un the dev forum? See PM.

**Comment by Heklaterriol** [comment]
I think the discussion is located in the dev forum
