### ISSUE TITLE
Hard coded texts

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1612]
in admin/views/import/tmpl/default.php the following words are hard coded = no translation possible:
fields list for venue
fields list for category
fields list for event
fields list for cat_events

**Comment by Heklaterriol** [comment]
Thank you Jojo! 
I added them and I also corrected the naming (not "fields", but "columns") and added somehow more understandable text, I hope you agree:
```
COM_JEM_IMPORT_DB_VENUE_COLUMNS="list columns of table jem_venues"
COM_JEM_IMPORT_DB_CATEGORY_COLUMNS="list columns of table jem_categories"
COM_JEM_IMPORT_DB_EVENT_COLUMNS="list columns of table jem_events"
COM_JEM_IMPORT_DB_CATEVENT_COLUMNS="list columns of table jem_cats_event_relations"
```

**Comment by Heklaterriol** [comment]
After checking the import interface I create an other suggestion:

before:
![import-before](https://github.com/jemproject/JEM-Project/assets/28540581/74938fce-3d1f-4361-bef1-cd368d907852)

new suggestion:
![import-after](https://github.com/jemproject/JEM-Project/assets/28540581/dead77a5-87cd-4692-8963-73ab938543ee)

do you agree?

**Comment by mckillo** [comment]
Perfect, and small detail but more clear. I like it.
