### ISSUE TITLE
there's a lightbox2

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1614]
https://github.com/lokesh/lightbox2

**Comment by mckillo** [comment]
With BT5 is easy, there are a lot example.
See example https://trvswgnr.github.io/bs5-lightbox/

```
<a href="https://unsplash.it/1200/768.jpg?image=250" data-toggle="lightbox" data-caption="This describes the image">
	<img src="https://unsplash.it/600.jpg?image=250" class="img-fluid">
</a>
```

**Comment by Heklaterriol** [comment]
I had some time today and tried to build the lightbox unctionality without loading another JS library, just using Joomla 4 native elements.

Please have a look at the branch here: https://github.com/jemproject/JEM-Project/tree/lightbox (including a test installation package.)

As I'm not a real coder (just some kind of hobby) please do not hesitate to improve my code.

**Comment by Heklaterriol** [comment]
And I noticed that in the image settings the label "Enable Thumbnail" is not clear.
When activated, the thumbnail images has a link to the full size image as a pop up.
So I changed the label to "Enable Pop Up Thumbnail".

**Comment by Heklaterriol** [comment]
Did anybody test this?
Are you ok with this solution or do you want a more sophisticated one?

I added an version based on JEM 4.0.0 (the first one ist based on JEM 4.0.1-dev1)

**Comment by Heklaterriol** [comment]
the modified files (compared with JEM 4.0.0)

![mods fo lb](https://github.com/jemproject/JEM-Project/assets/28540581/4921b2d1-1767-4c6f-9c36-157e15ac4a1b)

**Comment by jojo12** [comment]
Sorry, I am on the road and can not test!

**Comment by Heklaterriol** [comment]
I just noticed that the modules _wide_, _banner_ and _jubilee_ also have modal functionalities, which do not work. 
I will check it out.

(By the way: In English the event images in the modules are called "flyer" – is this the correct word?)

**Comment by jojo12** [comment]
I don't know, but even in component there is the word "flyer"!

**Comment by Heklaterriol** [comment]
After looking at the module I think of redoing the lightbox function with Jojos lightbox2 https://github.com/lokesh/lightbox2
Will be easier to apply to all instances of modal images.

The bootstrap version looks good too, but loads a lot of css an js, lightbox2 is much smaller.

Any opinions?

**Comment by Heklaterriol** [comment]
I added the lightbox2 functionality to the teaser module, the categories view and the venues view.
I hope I've got all now, right?
See: https://github.com/jemproject/JEM-Project/tree/lightbox2

**Comment by jojo12** [comment]
I tested in merged package. Super!
