### ISSUE TITLE
in backend registration settings, there's no "only invited"

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1615]
I think, this should be in backend too!

**Comment by jojo12** [comment]
I can't test but this is not corresponding to the issue!

**Comment by Heklaterriol** [comment]
Ops, I took the wrong issues number, should have been #1612

**Comment by jojo12** [comment]
![grafik](https://github.com/jemproject/JEM-Project/assets/2960236/26a697fd-9a7a-43cf-abd2-ba0aca62443e)
