### ISSUE TITLE
0 Class "Text" not found    in Joomla admin panel caused by JEM Quick Icon plugin

### ISSUE THREAD

**Issue by jobrusche** [jemproject/JEM-Project#1617]
Joomla 4.0 with JEM 4.0.0
The Joomla administrator panel gives an error " 0 Class "Text" not found " which messes up the panel layout.
Disabeling the JEM Quick Icon plugin is a workaround for this issue.

Also reported in https://forum.joomla.org/viewtopic.php?f=811&p=3695988

**Comment by Heklaterriol** [comment]
See here: https://www.joomlaeventmanager.net/forum/update-installation-troubleshooting/12368-error-class-text-not-found
