### ISSUE TITLE
column 'author_ip' in table '#__jem_venues' too short for IPv6

### ISSUE THREAD

**Issue by Wolfgang-Chess** [jemproject/JEM-Project#1618]
[https://www.joomlaeventmanager.net/forum/bugs/12411-error-when-saving-a-venue#30659](https://www.joomlaeventmanager.net/forum/bugs/12411-error-when-saving-a-venue#30659)

Same kind of issue as in #1607 

(I do not have triage access here in in this Github project, so I cannot label it 'J4'... - I am the JEM moderator "Wolfgang".)

**Comment by Heklaterriol** [comment]
Fixed, see #1607
