### ISSUE TITLE
add Link to login in My attendances

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1620]
Hi I've seen the post of pctech in joomlaeventmanager.net.
My attendances is after all a menue point for the users (myevents and myvenues more for event creators)
So it would be helpful not only to say, you aren't logged in, but to add the link (and if possible the redirect) to login!

**Comment by Heklaterriol** [comment]
As a not-really-progrmmmer, I did a bit of tinkering. I created a nwe branch to do it without risk.
Please take a look and give me feedback.

**Comment by jojo12** [comment]
I tested (only with the view.html.php s) and it works fine

**Comment by mckillo** [comment]
I have added buttom to login first in myattendances, myevents and myvenues views (frontend), 
Now button is shown in this view when the user isn't logon. The user clicks to login on the web and return to view page.
This is the new process of Joomla 4 to access a page with credentials.
See commit above. Test it , do you like it?

**Comment by Heklaterriol** [comment]
@mckillo: very nice solution, thank you! 
I think we can close the issue, isn't it?

**Comment by mckillo** [comment]
I think yes
