### ISSUE TITLE
backend>events>attendees: error when saving a new user with "save&new"

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1622]
There is a post in joomlaeventmanager.net "Memberregistration" which shows this bug:

When I add in backend a user as attendee and try to "save" or "save&close" or "save&new", there comes an error!
The event title is "?" 
When I go back to events and go once more into the attendees manager, I see the user added (but with "0 places")

**Comment by mckillo** [comment]
Fix the name of attribute to return same event. See commit above.

**Comment by jojo12** [comment]
yes, I tested and it works!
(But the other problem persists (it's an other issue posted) you can add a new attending user with 0 place (ghost)
