### ISSUE TITLE
Saving config:Attempt to assign property "css_backend_usecustom" on string

### ISSUE THREAD

**Issue by jobrusche** [jemproject/JEM-Project#1623]
Similar issue as reported in #1310 , #1365 and #1401 is BACK
Joomla 4.3.3 / JEM 4.0.0 (first instal)
At save config in control panel

Call stack
--
# | Function >                                               | Location
1 | ()                                                              | JROOT/libraries/vendor/joomla/registry/src/Registry.php:754
2 | Joomla\Registry\Registry->bindData()   | JROOT/libraries/vendor/joomla/registry/src/Registry.php:749
3 | Joomla\Registry\Registry->bindData()   | JROOT/libraries/vendor/joomla/registry/src/Registry.php:297
4 | Joomla\Registry\Registry->loadObject() | JROOT/components/com_jem/classes/config.class.php:152
5 | JemConfig->bind()                                  | JROOT/administrator/components/com_jem/models/settings.php:98
6 | JemModelSettings->store()                    | JROOT/administrator/components/com_jem/controllers/settings.php:125
7 | JemControllerSettings->save()                | JROOT/libraries/src/MVC/Controller/BaseController.php:678
8 | Joomla\CMS\MVC\Controller\BaseController->execute()    | JROOT/administrator/components/com_jem/jem.php:54
9 | require_once()                                         | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
10 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73 |
11 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
12 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:143
13 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:186
14 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:293
15 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:61
16 | require_once()                      | JROOT/administrator/index.php:32

[JEM-bug.pdf](https://github.com/jemproject/JEM-Project/files/12163053/JEM-bug.pdf)

**Comment by jobrusche** [comment]
Don't bother. 
I deinstalled JEM 4.0.0, dropped all _jem_ table entries and reinstalled JEM 4.0.0 and 
now I can save configuration settings.

**Comment by jojo12** [comment]
can this be closed now?

**Comment by jobrusche** [comment]
Can be closed, although it is'nt explained why this happend at first install of JEM.
