### ISSUE TITLE
Remove semicolon in en-GB.plg_finder_jem.ini

### ISSUE THREAD

**Issue by ernst67** [jemproject/JEM-Project#1632]
The Transifex download client crashes wehen downloading the JEM translations. 

This is because the line ";PLG_FINDER_QUERY_FILTER_BRANCH_S_VENUE= ...." in this resource is commented (it starts with a semicolon) and the Joomla version couldn't be determined, resulting in the error.

https://github.com/jemproject/JEM-Project/blob/master/plugins/plg_finder_jem/language/en-GB/en-GB.plg_finder_jem.ini

Semicolon should be removed

**Comment by Heklaterriol** [comment]
done
