### ISSUE TITLE
pkg_jem_v4.0.1-dev2 - please test

### ISSUE THREAD

**Issue by Heklaterriol** [jemproject/JEM-Project#1633]
Hey folks, after mergin our efforts in the last time, I created a package **pkg_jem_v4.0.1-dev2.zip**

Please test and let's just focus on bugfixing, so we can release JEM 4.0.1

**Comment by Heklaterriol** [comment]
@jojo12, could you please communicate what you issues are!

**Comment by mckillo** [comment]
For me, It doesn't work, I have several errors (field in bbdd as places field, description in field, load sample fault,...). I dont' know if we have time today when I finished the debug the other case, but we are testing this zip, For me, it's wrong.
