### ISSUE TITLE
Error in JEM-4.0.1dev3: booking tickets/request answer/reserved places: max.places=0 means unlimited!!!

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1637]
[I made a package from branch "JEM-Project-JEM-4.0.1-dev" and installed for testing I call this JEM-4.0.1dev3!]
compare #1630

Frontend>Editevent>Extended>Registration
EDIT: Backend>Event>Registration is solved!
When max Places>0 then there’s no errors, but when max. Places = “0” then ERRORS
[wenn maximal Plätze nicht 0 ist, keine Fehler, wenn maximal Plätze = 0, dann Fehler!]
1)	Max Places [0 isn‘t Zero, means Unlimited, this has an other meaning!!!] 
[Es macht keinen Sinn, für einen Event 0 Plätze zu organisieren, 0 ist hier keine Zahl, sondern ein schneller Ausdruck für unbegrenzt (>0)

nur dann:
2)	Min. booked / user must be standard=1, not 0 [There are automatic changes!]
[0 Plätze darf nicht möglich sein!]
3)	Reserved places: it must be possible to reserve places, even when max Places=0 (unlimited)
[folgende Überlegung: es gibt Leute, die aus verschiedenen Gründen sich nicht in Joomla registrieren wollen. Sie melden sich anders an (tel., mündlich, mail…), man kann diese mit „reserved places“ dazuzählen.

**Comment by jojo12** [comment]
if this is not corrected, then there are a lot of consequences in attending columns!

**Comment by mckillo** [comment]
It's all right, I know. 
In other issue, I reported that when Max Places change to 0, JavaScript change other value to 0. Yesterday, I uploaded a commit to avoid this reset of values, but there are other error in JavaScript (I report to @Heklaterriol). In the browser console, I can see error of line 159 into function showUnregistraUntil(). This jform_unregistra_until_span ID doesn't exist. Hekla created this function (7m ago in beta1, I don't know if it's obsolete), I suppose that he can say if this function can be deleted, because this error blocks the execution of JavaScript.

**Comment by jojo12** [comment]
in backend it is correct(ed), in frontend the problem persists!

**Comment by Heklaterriol** [comment]
@mckillo I didn't the your report about the javascript errors. 
I didn't create the function showUnregistraUntil, but the one below.

"showUnregistraUntil" is from JEM 2.3.x but has no use here anymore, as far as I can see.

**Comment by jojo12** [comment]
@Heklaterriol: please fix your javascript in site/views/editevent/tmpl/edit.php and site/views/editevent/tmpl/responsive/edit.php too!

**Comment by Heklaterriol** [comment]
Please check if correct, thank you!

**Comment by jojo12** [comment]
@Heklaterriol: now fix your javascript in site/views/editevent/tmpl/responsive/edit.php. You forgot. The others work fine

**Comment by jojo12** [comment]
it's done, seems to work well.
One little problem, in my sites, I tested, i can't update, because there is in DB just "requestanswer", which can't be duplicated.
What can I do, when I don't have direct access to DB? Thank you for your answer.

**Comment by Heklaterriol** [comment]
unzip the installation package.
in the file 4.0p1.sql in /admin/sql/updates/mysql remove the line `ALTER TABLE '#__jem_events' ADD 'requestanswer' TINYINT(1) NOT NULL DEFAULT '0' AFTER 'waitinglist';`
then save and zip the the files again to your personal  installation package :-)
