### ISSUE TITLE
Add event type support for http://schema.org/Event micro-formatting

### ISSUE THREAD

**Issue by neyworg** [jemproject/JEM-Project#164]
Add event type support for http://schema.org/Event micro-formatting

Recommend adding a data field to _jem_events for eventtype 

More specific event types:
    BusinessEvent
    ChildrensEvent
    ComedyEvent
    DanceEvent
    EducationEvent
    Festival
    FoodEvent
    LiteraryEvent
    MusicEvent
    SaleEvent
    SocialEvent
    SportsEvent
    TheaterEvent
    UserInteraction
    VisualArtsEvent 
# Example of micro formatting:

http://www.google.com/webmasters/tools/richsnippets?q=http%3A%2F%2Fwww.usyw.org%2Fevents%2Fdetails%2F273-ia-world-class-team-wrestling-camp&html=

Which corresponds to:
http://www.usyw.org/events/details/273-ia-world-class-team-wrestling-camp

**Comment by mckillo** [comment]
The event type will be implemented ias part of the new JEM Types feature.
See new issue: https://github.com/jemproject/JEM-Project/issues/1603
