### ISSUE TITLE
Registration Annulation "Until" – no field appears  

### ISSUE THREAD

**Issue by Heklaterriol** [jemproject/JEM-Project#1640]
in the backend, editing an event:
Under Registration Annulation if you choose "Until" there should appear an additional field for the number of hours (like in JEM 2.3.x)
But no field appears.

I cheked it: it is not hidden and just not appearing, but it is not there at all.

**Comment by jojo12** [comment]
Good find!

**Comment by Heklaterriol** [comment]
The field is prepared in the code, but not in the layout. It is easy to include, I will do it now.

But:
Do you know, if the funcationality of "registration until" works, if there is a humber or hours set in the field?

**Comment by jojo12** [comment]
In JEM 2.3+ it worked

**Comment by Heklaterriol** [comment]
Just checked – it also works in JEM 4.

**Comment by Heklaterriol** [comment]
Does anybody know: 
Is there a Joomla 4 native practice how to show/hide labels/fields, depending on the content of other fields?
Here: if "Until" is chosen, then show the label/field for the hours, otherwise hide it.

**Comment by jojo12** [comment]
in Joomla 4 cassiopeia frontend it works, so it seems to be a problem in Joomla 4 atum backend!

**Comment by Heklaterriol** [comment]
It is not 100% fixed yet, because now the field is visible and working, but initially it is **always** visible, even when "Registration Annulation" is on "No" or "Yes".
We need that the visibility of the field is correctly set on page load: hidden, except "Until" is already selected.
It only works correctly, when I manually change the value in "Registration Annulation".

The code is not yet committed as it is not working – I will create a branch to get this solved and @mckillo maybe you could have a look at it.

**Comment by jojo12** [comment]
@Heklaterriol 
I found the solution: (I looked in joomla config with the language debug)
add
`			showon="unregistra:2"`
this means, only when unregistra is 2, then show ...

**Comment by Heklaterriol** [comment]
Thanks Jojo, really cool! You accidentally comitted it to the master branch.
I commited it to the dev branch and reverted it in the master branch.

**Comment by jojo12** [comment]
Thank, I was so happyS that I just committed!
