### ISSUE TITLE
jemlistevents: unfinished issue

### ISSUE THREAD

**Issue by mentor2k1** [jemproject/JEM-Project#1641]
If an event goes over several days ( 01.08.2023 - 15.08.2023), it will be not finished, based on the event start.

so in my opinion the query should be change to that, to respect the enddate:

`
$where = ' (DATEDIFF (a.dates, "'. $to_date .'") >= 0 or DATEDIFF (a.enddates, "'. $to_date .'") >= 0)';
`

**Comment by Heklaterriol** [comment]
@mentor2k1: Thanks for reporting.
Could you give some more context for us to check the issue:
About which query are you talking?

And I don't fully understand what you want to say with "it will be not finished, based on the event start".
Du kannst es sonst auch auf Deusch beschreiben, das geht auch :-)

**Comment by mentor2k1** [comment]
Hi,
also, ich betreue eine Schulseite. Dort wird das als Darstellung für die Ferien genutzt. die gehen ja durchaus auch mal über 2 Monate. Mit der bisherigen Logik und "unfinished" als Parameter werden die aktuellen laufenden Ferien bereits zu Beginn einfach ausgeblendet. Hier muss zwingend bei unfinished auch auf das Enddatum geschaut werden, was das Query oben jetzt auch macht.

![Bildschirmfoto 2023-08-04 um 18 55 25](https://github.com/jemproject/JEM-Project/assets/1419917/90ac151f-aae2-41a1-8164-3533b9cb36e3)

**Comment by Heklaterriol** [comment]
Ich verstehe das Problem und ja, natürlich sollten die Events bis zum Ende sichtbar bleiben können.

Ich konnte es jedoch auf die Schnelle nicht reproduzieren – aus irgendeinem Grund bleiben die Events bei mir stehen. 
Ich muss mich etwas tiefer damit beschäftigen.
Wo genau hast du "unfinished" als Parameter eingestellt?

**Comment by mckillo** [comment]
@mentor2k1 For the unfinished event, the right line will be :

 $where = ' (DATEDIFF (a.dates, "'. $to_date .'") <= 0 AND DATEDIFF (a.enddates, "'. $to_date .'") >= 0)';

**Comment by mckillo** [comment]
See the commit uploaded.

**Comment by mentor2k1** [comment]
Thx

**Comment by jojo12** [comment]
in the plugin description: 
type=unfinished: Upcoming and ongoing events
but I then see only ongoing events! Whats right: only ongoing or upcoming AND ongoing?

**Comment by jojo12** [comment]
plugin seems to not work anymore (commandlinesettings)

**Comment by jojo12** [comment]
Sorry, I tested again: all works. I don't know what happened before!
