### ISSUE TITLE
I dislike deleting in output.class.php flyer2

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1642]
thank you for doing that. We discussed earlier and I said, why this is needed. You accepted and now it is deleted!
We need it back!
So I want this now official in JEM with the possibility to choose it in the JEM settings
see #1548

**Comment by Heklaterriol** [comment]
That was me. I wasn't aware of the discussion. Sorry.


I had chechked it and had not found any instances, where flyer2 was called. So I guessed that it was an left-over from previous ideas.

I can easily restore it and will do it tonight.

**Comment by jojo12** [comment]
yes please, perhaps it is better to add it officially, so noone will think, this is a left-over. ;-)

**Comment by mckillo** [comment]
I can try in this week to have a new option in JEM setting for flyer2. In the #1548, the proposal imagen, is it good?

**Comment by mckillo** [comment]
@jojo12 When you return, "Review and test" this new options. Now Flyer2 is into flyer as option of JEM Setting.
I hope that you like it :-)

![JEM4 - Flyer a new feature to show the image in the original resolution](https://github.com/jemproject/JEM-Project/assets/2765316/8ca6fe75-5c47-4c7f-99fb-21c1b2a2d06b)

If this commit is fine for you, this issue and #1548 can be closed.
