### ISSUE TITLE
no archive view when Search Engine Friendly URLs=no

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1646]
I don't know if this is a bug:
to reproduce: 
Joomla settings: Search Engine Friendly URLs=NO
what it makes:
in simplelist view choosing archive -->instead of archive going to home

**Comment by Heklaterriol** [comment]
I can reproduce it:
URL for Simplelist:
https://domain.tid/index.php?option=com_jem&view=eventslist&id=0&Itemid=150

URL after clicking on archive icon:
https://domain.tid/index.php?task=archive&filter_reset=1

Correct URL would be:
https://domain.tid/index.php?option=com_jem&view=eventslist&id=0&Itemid=150&task=archive&filter_reset=1

---

With Search Engine Friendly URLs = yes it works:
https://domain.tid/index.php/simplelist
and
https://domain.tid/index.php/index.php/simplelist?task=archive&filter_reset=1

**Comment by mckillo** [comment]
Fixed this issue. Now archive and iCall icons in simplelist works with or without SEF.
See the commit above.

**Comment by jojo12** [comment]
fixed
