### ISSUE TITLE
JEM 2.3.6 

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1647]
We should mention in the download area, that JEM 2.3.6 will not be continued: it's only for preparing the migration to JEM 4.
We finish other help for JEM 2.3.6 to continue in Joomla 3 

And I am not sure,  if you can update from all JEM versions directly to JEM 2.3.6.

**Comment by mckillo** [comment]
I have updated from 2.3.5 without problem, in previous version I havent't tested it

**Comment by jojo12** [comment]
There's a post in joomlaeventmanager.net with problems updating from 2.3.0 to 2.3.6. He tought, these updates between wwere all minor updates 🤔😃
