### ISSUE TITLE
Deprecated:  Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by jobrusche** [jemproject/JEM-Project#1649]
Early this week Joomal 4.3.4 started to display a message with admin login urging the admin to upgrade PHP from 8.0 to 8.1
indicating that PHP 8.0 soon will be end-off-live.

I did swith to PHP 8.1.22 and the result is :

Deprecated
: trim(): Passing null to parameter #1 ($string) of type string is deprecated in
/var/www/clients/client25259/web29072/wega/libraries/vendor/joomla/registry/src/Format/Json.php on line 56

when listing events per category (listing per venue is OK)
Sequence of actions is: display calender, click on event in calender, click on category

Even with debugging=off and "Log deprecated API"=NO

**Comment by jojo12** [comment]
I think, even Joomla is not yet ready!

**Comment by jobrusche** [comment]
Yes, but is ugly that the visitor sees these errors

**Comment by jojo12** [comment]
Is it visible with standard error settings?

**Comment by jobrusche** [comment]
That's what I say in my original submission

**Comment by mckillo** [comment]
This commit solved it.

**Comment by jobrusche** [comment]
I assume this will also cure the problem on V5.0 where PHP 8.1 is the minimum ?
Have it also on V5.0-rc2 with JEM 4.1.0

**Comment by jobrusche** [comment]
Downloaded JEM 4.1.1-dev of 16/10 and now it's solved.
