### ISSUE TITLE
Add venue type support for http://schema.org/Place micro-formatting

### ISSUE THREAD

**Issue by neyworg** [jemproject/JEM-Project#165]
Add venue type support for http://schema.org/Place micro-formatting

Recommend adding a data field to _jem_venues for venuetype 

More specific types
    AdministrativeArea
    CivicStructure
    Landform
    LandmarksOrHistoricalBuildings
    LocalBusiness
    Residence
    TouristAttraction

**Comment by mckillo** [comment]
The venue type will be implemented ias part of the new JEM Types feature.
See new issue: https://github.com/jemproject/JEM-Project/issues/1603
