### ISSUE TITLE
add infotext when "request answer assistance"

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1650]
in default_attendees.php and default_regform.php (legacy and responsive) there's a need for this assistance.
To remember: request answer assistance ask for sending "absence infos". (This can help groups of sports, schools to plan).

So the "request answer assistance" should not only inform the administrator but the normal user too, that his "absence info" is wanted!
So I propose to add something like:
`					<?php if ($this->item->requestanswer) { echo Text::_('COM_JEM_SEND_UNREGISTRATION');}?>`
in responsive/default_attendees.php at line 190 and in responsive/default_regform.php at line 79.

My version in german is: 
>  (Bitte unbedingt auch Absagen melden!)
And in site language:  
`COM_JEM_SEND_UNREGISTRATION="(Please send Absences too!)<br>"`

**Comment by jojo12** [comment]
I committed, please test!

**Comment by jojo12** [comment]
(I'm sorry, I wanted to commit in my fork, but somehow, it went directly to the source branch.) jem-4.1.1.dev

**Comment by Heklaterriol** [comment]
seems to work, technically.

But the label of the event edit checkbox is quite incomprehensible. 
I showed `Request answer assistance` to some colleagues – they did not understand, what it is about.

How about
"non-attendance also registrable"
"absence confimation is possible"
"with absence confimation"
"non-participation can be confirmed"
?

**Comment by jojo12** [comment]
Sorry, I am not english. Mckillo choosed these expressions!
I was fighting for the possibility to communicate the absence e.g. for schools, sporting groups etc.
If you don't answer in a group which expects the participation...
If you find better expressions, feel free

**Comment by Heklaterriol** [comment]
Yes it is quite difficult to express it in few words.

And  yes, I do not follow every discussion and may the be late with my thought, sorry for that – I just have not enough time to be more active in the JEM project.

**Comment by Heklaterriol** [comment]
I used to work in UX and would like to contribute in this issue by streamlining the registration layout and wording, so that it is coherent. 
That means no change in programming, just layout, wording and order.

Are you fine with that? (and I definitely don't want to disrespect your creation of exenting the registration process!)

**Comment by jojo12** [comment]
What is UX?

**Comment by Heklaterriol** [comment]
As I am lazy I asked the AI bot to give a good answer:
"UX" stands for "User Experience." It refers to the overall impression or feelings that a person has when interacting with the website, The goal of UX design is to ensure that this interaction is positive, efficient, and satisfying for the user.

Good UX encompasses several aspects, including:
- Usability: The interface should be easy to understand and use.
- Efficiency: Users should be able to complete tasks quickly and efficiently.
- Satisfaction: Users should be happy with their experience and willing to return.
- Accessibility: The design should be accessible to all users, including those with disabilities.
- Aesthetics: The appearance of the product or website should be visually pleasing.
- Consistency: The design should be consistent to avoid confusion.

**Comment by mckillo** [comment]
@jojo12 is this issue solved? If so, it can be closed.
