### ISSUE TITLE
Not nice: (only) in large windows: german expressions in frontend <dt> need more space

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1651]
![shortdt](https://github.com/jemproject/JEM-Project/assets/2960236/2be5da1f-2cac-4c86-b5af-7782eb65959d)

**Comment by Heklaterriol** [comment]
Which page is this? I couldn'f find it at first search …

**Comment by jojo12** [comment]
it's the end of event details view (in the image the registration part)

**Comment by mckillo** [comment]
Is this issue open or close?

**Comment by Heklaterriol** [comment]
It's fixed. Thank you-
