### ISSUE TITLE
ical button should be on calendar too

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1657]
There are sites who prefere the calendar view, but for ical, they have to go to the simple list.
They would prefere to have the ical button above the calendar (like the print button)

**Comment by mckillo** [comment]
![20231029 JEM 411 - New ical icon in calendar view](https://github.com/jemproject/JEM-Project/assets/2765316/104a1694-6c82-42e0-9219-90fdbd9472b3)

@jojo12 Check it and if it's good, you can close this improve issue.

**Comment by jojo12** [comment]
it seems, it integrates events only from one category.
But the rest seems good.

**Comment by mckillo** [comment]
I have to review the case, because I think that I don't have any category filter. Let's me check it.

**Comment by mckillo** [comment]
It's fine. If you go the calendar view (FE) and download ical, the result file contains all events of this calendar for all categories. And if you use category filter, it works too. Tell me more details about any error.

**Comment by mckillo** [comment]
@jojo12  Tell me if you can download the events.ics file with several categories. 
If it's goood, you can close this issue.

**Comment by jojo12** [comment]
now it works.
one question: what about weekcalendar, venuecalendar and categorycalendar?

**Comment by mckillo** [comment]
Here you are, but this ics file doesn't include the category filter by JavaScript.
Check it.

**Comment by jojo12** [comment]
I tested:
- Calendar: ical icon in legacy and in responsive
- Weekcalendar: ical icon in legacy and in responsive
- Categorycalendar: no ical icon in legacy, no icon in responsive
- Venuecalendar: no icon in responsive, (in legacy it is, but file shows events from all venues!)=

**Comment by mckillo** [comment]
@jojo12 I have uploaded in the moring that part (yesterday I forgot to add in previous commit). See the commit 8135a641

**Comment by mckillo** [comment]
@jojo12 See last commit 9a162bef with the ical icon for venue calendar view.
