### ISSUE TITLE
calendar in calendar style on mobiles (landscape)

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1658]
there should be the possibility to have calendar look on mobiles landscape.
so the calendar_responsive.css and calendar.css should be changed!
e.g. calendar_responsive.css:
change to:
`    @media only all and (max-width: 30rem), screen and (max-device-width: 30rem) and (orientation: landscape) {`

**Comment by Heklaterriol** [comment]
Yes, that makes sense.
