### ISSUE TITLE
change access for attachments in generic list to public as default

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1659]
Post from bergente in forum
this seems to be a bug:
In my eyes too, It would be better to have one accesstype as selected.
you can change it:
for events in backend: admin/edit_attachments.php line 85 change to

`<?php echo JHtml::_('select.genericlist', $this->access, 'attach-access[]', array('class'=>'inputbox form-control','size'=>'7'), 'value', 'text', 1); ?>`

the same in site/edit_attachments.php line 85.
and the same should be changed for venue attachments! 
and for legacy and responsive style.

**Comment by Heklaterriol** [comment]
should be fixed, please test

**Comment by jojo12** [comment]
it's fixed

**Comment by mckillo** [comment]
@jojo12  Can be closed this issue?
