### ISSUE TITLE
plg_jem_demo create problems like #1590

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1662]

**Comment by Heklaterriol** [comment]
what is the recent vesion? I have just "plg_jem_demo-2.2.1-dev007",
Would be good to have it here in a private repo.

**Comment by jojo12** [comment]
This is the latest wt have

**Comment by Heklaterriol** [comment]
I created a private repo for plg_jem_demo:
https://github.com/jemproject/plg_jem_demo

**Comment by mckillo** [comment]
This link doesn't work.
Where is this plugin?

**Comment by mckillo** [comment]
The issue #1590 was closed, and I suppose that it's other error and same message that #1590. Any capture can help me and action to simulate the error.

**Comment by jojo12** [comment]
@mckillo : how can I send it to you (I don't know, what hekla made?)

**Comment by mckillo** [comment]
Send an gmail with plugin

**Comment by jojo12** [comment]
@mckillo : how you send it to me?

**Comment by Heklaterriol** [comment]
> This link doesn't work. Where is this plugin? @Heklaterriol ?

ops, sorry, it was on provat and no team. Now it should work.

**Comment by Heklaterriol** [comment]
> @mckillo : how can I send it to you (I don't know, what hekla made?)

I haven't commited anything yet – I have done just some local changes to test.

**Comment by jojo12** [comment]
@mckillo: I got the sql file and installed. But the problem persists.

**Comment by mckillo** [comment]
I have answered your email

**Comment by mckillo** [comment]
You can send the error message and url of success

**Comment by Heklaterriol** [comment]
> @mckillo: I got the sql file and installed. But the problem persists.

I checked the sql file: the fields are not complete – all the fields we have added are missing until now.

**Comment by mckillo** [comment]
I haven't found the error, I can't simulate, and I tested with spanish language but I saw that data of demo structure needs an update. Check this demo.sql in the plugin and you tell if it works now.
[demo.zip](https://github.com/jemproject/JEM-Project/files/12905809/demo.zip)

**Comment by Heklaterriol** [comment]
I have also created an updated demo.sql file. I will commit it tomorrow.

**Comment by mckillo** [comment]
Check de ZIP file above, if you can

**Comment by mckillo** [comment]
@Heklaterriol does demo.zip file work? 
Where is the repo of this plugin? It's exist I could update the demo.sql file by commit.
and if it works, the issue can be closed.

**Comment by Heklaterriol** [comment]
It is here: https://github.com/jemproject/plg_jem_demo

**Comment by mckillo** [comment]
I have to update the repo with new demo,sql
