### ISSUE TITLE
error in frontend register for an event -->wrong changes from waitinglist to attendinglist 

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1663]
There is an error:
When a user is "attending, but on waitinglist"
and he is booking more places, then he is on attendinglist included with his additional places.
(my setting was: waitinglist=yes, request answer=no max.places/user=3, max.places/event=0 (unlimited)
I add my test paper
[Tests regform in DE.pdf](https://github.com/jemproject/JEM-Project/files/12730998/Tests.regform.in.DE.pdf)

Error 2:
The same is when he is canceling a place, then he is immediately on attendinglist with his additional places.

**Comment by mckillo** [comment]
For Error 1:
I don't understand this case because I think that it isn't a real situation. I want to understand that the event registration setting doesn't change during the test.
If there is an event with max.places/event=0 and waiting list=yes, then the waiting list is empty because there are places always, the waiting list isn't used.
If the user was added into waiting list, if this user books new places, all places are changed to attendee, because there is unlimited places, and i t doesn't have sense the waiting list.

For Error 2:
Yes, the info isn't clear and there is a error of status places when the user cancel. I'll try to resolve it in the morning.

**Comment by mckillo** [comment]
![JEM410_waiting_list_places](https://github.com/jemproject/JEM-Project/assets/2765316/3ba12129-18f7-4553-ac25-fde934e71613)
Check new commit to fix this issue. Now, when the user want to book or remove any places of waiting list, the registration status doesn't change.

**Comment by jojo12** [comment]
This come from the earlier system where there was only 1 person for each user:
e.g. you have a team of players, where you need 6 persons, the admin is able to choose which one has to wait as reserve player. Normally it's his choice and a player is on the waitinglist. If someone of the principal team can't come e.g. because he is sick, then the admin can choose, which one he will add to the principal team. This must not depend on  the max.places.

**Comment by jojo12** [comment]
see comment to commit 00445fe

**Comment by jojo12** [comment]
thanks, but now there is always 1 place on waitinglist, even whenis no one !

**Comment by mckillo** [comment]
Where? Send me capture and I'll try to simulate it.

**Comment by jojo12** [comment]
![1698135981250464549398872324890](https://github.com/jemproject/JEM-Project/assets/2960236/69205637-782a-4845-8811-7ea857684e87)
Sorry can't capture now

**Comment by jojo12** [comment]
I think, this "1" shows, that there is a waitinglist and not the number of places!
when I add more places to the waitinglist, there is always only1

**Comment by mckillo** [comment]
@jojo: I have updated last commit with the solution of your comment.

**Comment by jojo12** [comment]
in responsive/default_attendees.php line 54 must be changed too:
from `($waitinglist);`
`$this->numWaitingPlaces;`

**Comment by mckillo** [comment]
I agree and sorry, I forget to change it to the responsive style.

**Comment by mckillo** [comment]
@jojo12 are you testing last commit? If it's good, this issue can closed.

**Comment by jojo12** [comment]
yes, it is fixed, thanks.close it
