### ISSUE TITLE
error in frontend attendeemanager: using button can change to waitinglist, even when there is no waitinglist!

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1664]
with settings waitinglist=no
to reproduce: there is an attending user. In attendee manager I can use the button to change him to the waitinglist. And it does, even when there is no waitinglist. 
The infos in regform are "you are attending but on waitinglist"

**Comment by mckillo** [comment]
@jojo12 Review the commit below with solution. If it's good, you can closed.

**Comment by jojo12** [comment]
This fixed the problem, thanks, can be added!
