### ISSUE TITLE
Wrong links in settings help

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1669]
The first six links in the JEM help file (the ones outside the table) point to the administrator part off a webhost www . folk-tanz . ch and of course they don't work. These links are superfluous anyway, because the linked-to items are in the table below them.
(see post in joomlaeventmanager.net from rpbikker

I don't know what me Jojo I made!

**Comment by Heklaterriol** [comment]
Cannot reproduce. I searched the whole repo – I cannot find "folk-tanz" anywhere …

**Comment by jojo12** [comment]
Sorry, me too. Was this a fake?

**Comment by Heklaterriol** [comment]
I got it:
it is not in JEM but on the JEM website unter:
https://www.joomlaeventmanager.net/documentation/manual/backend/settings

**Comment by Heklaterriol** [comment]
I fixed it
