### ISSUE TITLE
is it possible to make an override of the common folder?

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1670]
I don't succeed! Perhaps because the common folder is not in the normal views part?

**Comment by Heklaterriol** [comment]
It is possible.

with the "default (responsive style)" layout style put the files in 
`my-template/html/com_jem/common/responsive/`

with "legacy (table style)" layout style in
`my-template/html/com_jem/common/`

**Comment by jojo12** [comment]
Thanks!
