### ISSUE TITLE
attachment.class.php deprecated when testing with Joomla 5.0:

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1671]
Deprecated: Using ${var} in strings is deprecated, use {$var} instead in C:\xampp\htdocs\joomla\components\com_jem\classes\attachment.class.php on line 277 and line 282

solution: change ${userid} to {$userid}

**Comment by mckillo** [comment]
![JEM411- it was changed](https://github.com/jemproject/JEM-Project/assets/2765316/6a379976-ae0f-4f67-9419-cf07c7905644)
In the last branch for 4.1.1, it fixed. What version do you use?

**Comment by jojo12** [comment]
4.1.0

**Comment by mckillo** [comment]
Then It fixed. :-.)
