### ISSUE TITLE
J4/J5: jem modules: icons are away

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1674]
mod_jem_wide: no clock icon
mod_jem_banner: no calendar icon, no clock icon,  no venue icon, no category icon
mod_jem_teaser: no calendar icon, no clock icon,  no venue icon, no category icon

**Comment by jojo12** [comment]
reopen: if you use JEM 4.2 with cassiopeia and Joomla 5 then the icans are back with your changings, but if you use it with Joomla 4.4, then the icons are lost because there is no fontawesome 6 in Joomla

**Comment by Heklaterriol** [comment]
ops, that was my fault.

**Comment by Heklaterriol** [comment]
I now added support for both "Font Awesome 6 Free" and "Font Awesome 5 Free"
