### ISSUE TITLE
J5: Color issues in Atumn management template

### ISSUE THREAD

**Issue by jobrusche** [jemproject/JEM-Project#1676]
Whatever color/blach&white I choose in the new J5 Autumn management template, some parts op the display
are unreadable due to white text on white background.

Example:
![Schermafbeelding 2023-10-18 235939](https://github.com/jemproject/JEM-Project/assets/117929258/cfa9e9ea-24d5-4c37-9fb2-7166b1738974)

**Comment by mckillo** [comment]
I don't see this style when I change the template style to monochrome.
![JEM4 1 1_with_JL500RC2_BN](https://github.com/jemproject/JEM-Project/assets/2765316/508a0bd9-2f79-4e16-9433-bb160ab3e584)
Can it be with the browser style in dark or custom mode?

**Comment by jojo12** [comment]
It is in J5 stable. At first the re were the normal colours in Atum but suddenly in the evening the colours changed to dark mode. I don't know if this is automatic. Then there were colour problems in JEM. I had not the time to try with changed colours.
(Finally it seems JEM and JOOMLA 5 don't go together actually, don't know in which part the problem is! Better to stay in Joomla 4.4 at the moment!)

**Comment by mckillo** [comment]
The issue is with dark mode in Windows (or system).

**Comment by jojo12** [comment]
How do I get the atum dark mode? Last night suddenly there was dark mode, now in the morning the normal view is back. Is this time relevant?

**Comment by mckillo** [comment]
I have simulated the issue changed Windows to dark mode and in Atum change to monochrome style (last option).

**Comment by mckillo** [comment]
Check this solution.
Now, apply the background color of table from template (by default Atumn).

**Comment by jobrusche** [comment]
Is that a new setting in JEM 4.1.1-dev ?

I now switched to a light theme in Windows and that solves the issue too, but I prefer a dark theme to unburden my eyes.

**Comment by mckillo** [comment]
No, it isn't a new JEM setting, the captures are when you change the style in the atumn template (with or withou monochrome option) in Windows with dark modelo active.

**Comment by mckillo** [comment]
@jobrusche If it's solved, you can close this issue.

**Comment by jobrusche** [comment]
I do not call this solved because I had to change my faforite Windows style.
Lots of admins working under Windows are going to complain about it in the forum when they start using JEM with J5

**Comment by Heklaterriol** [comment]
> I do not call this solved because I had to change my favorite Windows style.

As I'm working on OSX and Linux – I do not fully understand you comment.
What exactly is needed in addition?

**Comment by jojo12** [comment]
> Lots of admins working under Windows are going to complain about it in the forum when they start using JEM with J5
Can you link to it, please!

**Comment by jobrusche** [comment]
![Windows-theme](https://github.com/jemproject/JEM-Project/assets/117929258/2f41c1cc-4b28-4dca-905e-92087d0cf2e8)

**Comment by jobrusche** [comment]
Now that I have installed JEM 4.2.0 on Joomla 5, I cannot reproduce the problem anymore.
I tried several combinations of Windows themes and browser themes.
In all combinations the characters in the management interface remained clearly readable.

Closing this issue, thanks for your efforts.
