### ISSUE TITLE
J5: css-Manager error when saving

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1677]
0 Joomla\CMS\Event\Model\SaveEvent::onSetSubject(): Argument #1 ($value) must be of type object, array given, called in ...joomla\libraries\src\Event\AbstractEvent.php on line 225

**Comment by jojo12** [comment]
`
1 | () | JROOT/libraries/src/Event/Model/SaveEvent.php:42
-- | -- | --
2 | Joomla\CMS\Event\Model\SaveEvent->onSetSubject() | JROOT/libraries/src/Event/AbstractEvent.php:225
3 | Joomla\CMS\Event\AbstractEvent->setArgument() | JROOT/libraries/src/Event/AbstractEvent.php:115
4 | Joomla\CMS\Event\AbstractEvent->__construct() | JROOT/libraries/src/Event/AbstractImmutableEvent.php:51
5 | Joomla\CMS\Event\AbstractImmutableEvent->__construct() | JROOT/libraries/src/Event/Model/ModelEvent.php:55
6 | Joomla\CMS\Event\Model\ModelEvent->__construct() | JROOT/libraries/src/Application/EventAware.php:106
7 | Joomla\CMS\Application\WebApplication->triggerEvent() | JROOT/administrator/components/com_jem/models/source.php:179
8 | JemModelSource->save() | JROOT/administrator/components/com_jem/controllers/source.php:203
9 | JemControllerSource->save() | JROOT/libraries/src/MVC/Controller/BaseController.php:730
10 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/administrator/components/com_jem/jem.php:54
11 | require_once() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
12 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73
13 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
14 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:150
15 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:195
16 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:306
17 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:58
18 | require_once() | JROOT/administrator/index.php:32
`

**Comment by mckillo** [comment]
@jojo12  Check it and if it's good, close the issue.

**Comment by jojo12** [comment]
fix tested ok
