### ISSUE TITLE
BE import.php "Show possible columns of table...." are hardcoded

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1678]
There are keys in language files
COM_JEM_IMPORT_SHOW_VENUE_COLUMNS="Show possible columns of table jem_venues"
COM_JEM_IMPORT_SHOW_CATEGORY_COLUMNS="Show possible columns of table jem_categories"
COM_JEM_IMPORT_SHOW_EVENT_COLUMNS="Show possible columns of table jem_events"
COM_JEM_IMPORT_SHOW_CATEVENT_COLUMNS="Show possible columns of table jem_cats_event_relations"
but in reality they are hardcoded in english!

**Comment by mckillo** [comment]
I don't know, what is the issue. If you want to be more explicit, you can change these strings to:

COM_JEM_IMPORT_SHOW_VENUE_COLUMNS="Click to show columns/fields of table jem_venues"
COM_JEM_IMPORT_SHOW_CATEGORY_COLUMNS="Click to show columns/fields of table jem_categories"
COM_JEM_IMPORT_SHOW_EVENT_COLUMNS="Click to show columns/fields of table jem_events"
COM_JEM_IMPORT_SHOW_CATEVENT_COLUMNS="Click to show columns/fields of table jem_cats_event_relations"

So, is it better? Or should it be shorter?
