### ISSUE TITLE
Frontend manage attendees: list shows undefinded icon in column "Remove user"

### ISSUE THREAD

**Issue by jobrusche** [jemproject/JEM-Project#1684]
![attendee-list](https://github.com/jemproject/JEM-Project/assets/117929258/48442801-f93c-4d8e-952c-8eecb60933c7)

**Comment by jojo12** [comment]
can you help me: where is this?

**Comment by jobrusche** [comment]
Login to frontend with admin priviledges
Click on menu item with calendar
Click on event with reservations
Click on link "Manage attendees"
Above picture is partial screencopy from attendee list
Language is dutch "Verwijder gebruiker" = "Remove( or delete) user"

**Comment by mckillo** [comment]
@jobrusche You could check this file /media/com_jem/images/publish_r.png in your Joomla, does it exist?

**Comment by jobrusche** [comment]
publish_r.png exists, protection is 644
It displays a small red circle with white x

![publish_r](https://github.com/jemproject/JEM-Project/assets/117929258/634f5470-8434-4177-ad0c-97f6f103f4e4)

**Comment by jobrusche** [comment]
Page source: div section containing references to publish_r.png
[page-source.txt](https://github.com/jemproject/JEM-Project/files/13217142/page-source.txt)

**Comment by mckillo** [comment]
In your page, the image call is to "//media/com_jem/images/publish_r.png"., the relative path is wrong. If you change the path for this: the relative and absolute path, it works: 
"media/com_jem/images/publish_r.png" 
"https://yourdomain.xxx/media/com_jem/images/publish_r.png"
Lets me see as to solve in the code.

**Comment by mckillo** [comment]
@jobrusche Could you test the last commit with the solution?

**Comment by jobrusche** [comment]
@mckillo this is a production site, will make an akeeba copy to my testsite and then test the new code

**Comment by mckillo** [comment]
If you prefer, you can download directly the file from https://github.com/jemproject/JEM-Project/blob/ee6f6657557f9a867fbf70be6ed5ac11fda6e34a/site/views/attendees/tmpl/default.php and update this file into \components\com_jem\views\attendees\tmpl\default.php on your site, so, you can test it easily.

**Comment by mckillo** [comment]
The other file is jem.css, add the red color to the icon. If you don't change, the remove icon has a dark blue color.

**Comment by jobrusche** [comment]
Copied site to fgl.brusche.be and installed most recent JEM-Project-JEM-4.1.1-dev
The delete button is now properly displayed and functional
