### ISSUE TITLE
Frontend- Enhancement / Feature request : Show total under column "Places"

### ISSUE THREAD

**Issue by jobrusche** [jemproject/JEM-Project#1685]
Would be practical  to show total reserved places under the places column in the attendees list .

**Comment by mckillo** [comment]
In the registratioin form (FE), the user can show this number.
![image](https://github.com/jemproject/JEM-Project/assets/2765316/f790bb33-68e0-4096-899f-0d73f4558c88)
Total=8 => 2 reserved + 6 booked. => Free = 0

**Comment by jobrusche** [comment]
In what version is that ?
Don't see this info with JEM-4.1.1-dev

**Comment by mckillo** [comment]
In JEM 4.1.0 you have this statistic when the event has active the registration.
In JEM 4.1.1 dev, there are new options in the event page.

You can go to JEM setting (BE), and in the Event Page tab (right side), you have the Registration options and when you create/edit an event, you must set the registration.

![image](https://github.com/jemproject/JEM-Project/assets/2765316/2712640d-2f53-4567-8089-dc21374ec1bf)

Enjoy the registration options
More info about new option: https://github.com/jemproject/JEM-Project/issues/1683

**Comment by jobrusche** [comment]
With the JEM-4.1.1-dev I just installed I have these new settings, but I do not see any additional info in the frontend.

**Comment by mckillo** [comment]
I can create a new event from BE, and in the registration tab (right side), active the registration, for example like this:
![image](https://github.com/jemproject/JEM-Project/assets/2765316/66fdf6c7-293b-4638-abab-66af8f73d0e9)
Save the event, and go to this new event in the frontend. Surprise, you can have places free  :-)

**Comment by jobrusche** [comment]
OK, I took an existing event with reservations, then saved it as a copy and now I see the places info in the frontend.
