### ISSUE TITLE
This extension does not provide a checksum 

### ISSUE THREAD

**Issue by mckillo** [jemproject/JEM-Project#1689]
When I update JEM form 4.1.0 to 4.2.0 from Joomla Update extension, the JEM update works but Joomla show the following message:
"This extension does not provide a checksum for validation of the integrity of the downloaded file."
We have to research about solve it, I suppose that JEM needs any file with checksum list in the package.

**Comment by mckillo** [comment]
Into update.xml, add the <sha256> of the download file.
<update>
  <update>
    <download>
       <sha256>9D9BFC3EF5EC410E67AE430E3E2BBB7B6FE07EAFA12DE4A30969F7E69ABB8CA1</sha256>

**Comment by Heklaterriol** [comment]
Cool.
Than means that when we release a new vesion of JEM we have to calculate the new checksum and insert it here, right?

**Comment by mckillo** [comment]
Yes, with each version.
In any case, we are restinga this case when the file is uploaded.
