### ISSUE TITLE
FR: option to hide events table in venue details view

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1690]
There are sites which don't need the events table at the end of venuedetails.

**Comment by mckillo** [comment]
Added a new option, 'Show list of events,' in the Venues section of Global Parameters to display the list of events at venues on the venue page

![image](https://github.com/user-attachments/assets/285de71f-8cec-4a09-ab2d-837dede2fa80)

**Comment by jojo12** [comment]
thanks, will test it.
