### ISSUE TITLE
Missing icon for adding new events in calendar

### ISSUE THREAD

**Issue by mckillo** [jemproject/JEM-Project#1692]
When the admin user go to calendar view in the frontend, the add event and venue icons is missing (Issue from forum).

**Comment by mckillo** [comment]
![image](https://github.com/jemproject/JEM-Project/assets/2765316/2b6395ea-8788-44cc-8966-e4c846c935c0)

**Comment by jojo12** [comment]
Perhaps this helps, but normally you can add new event with the + icon!
![grafik](https://github.com/jemproject/JEM-Project/assets/2960236/8b551950-8d61-4bcd-8108-79387a2601c3)

**Comment by jojo12** [comment]
it's fixed and it works, thanks
