### ISSUE TITLE
downloading an attached *.pdf on a smartphone  will be changed into a*.pdf.html (with an additional .html

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1693]
there's a post of bergente in forum. I can reproduce this.
Is this a bug from JEM ?
( when I cut the .html and let *.pdf, the attachment can be red normal.)

**Comment by mckillo** [comment]
Yes, it a JEM bug. I'll debut it tomorrow.

**Comment by mckillo** [comment]
@jojo12 Forgot this issue, I would like to solve it before release 4.2.1. Tomorrow I tell you any new.

**Comment by mckillo** [comment]
I simulate it...

**Comment by mckillo** [comment]
@jojo12 Please test it and tell me if It works for you. See the commit above.

**Comment by jojo12** [comment]
I made a fresh zip from JEM4.2.1-dev installed and tested then on my smartphone:
when pdf is opened, there are very cryptic signs (not possible to read)!
-> not fixed!

**Comment by mckillo** [comment]
I tested it again, in JL 4.4.4 with PHP 8.1 and JL 5.1.0 with 8.2, attachements jpg, png and pdf files. it works.
Test with other files or send PM with the PDF file.
Now, fopen uses rb (read in binary mode).

**Comment by jojo12** [comment]
I tested (in J!5.1) with jpg too. In smartphone it adds an additional .html. When I cut this manually, then I can read the original.
If not, then all is cryptic. Even when I open it as html.

**Comment by mckillo** [comment]
I can download tour PDF and I see that is music sheet. 
I don't know where is the problem. Test with other navigator.

**Comment by jojo12** [comment]
With my smartphone it does not work. Perhaps it is the problem of the smartphone. Because I know how to procedure ( take away the added .html) we can let this!
It won't be fixed.

**Comment by Heklaterriol** [comment]
In my iPhone it is still with the html extension, like `filename.pdf.html` and opens as text (pdf raw code)

**Comment by mckillo** [comment]
Sorry, the commit above is for issue  "archive icon in view", copied other title.

**Comment by mckillo** [comment]
@Heklaterriol I use Androir and iPhonoe with Chrome and Firefox, and it works. 
This issue is with Safari in IPhone and save PDF as HTML 
Why? Any idea, look for info.

**Comment by jojo12** [comment]
I tested in Android with Chrome and Firefox. Had the error on both.

**Comment by mckillo** [comment]
@jojo12 when you can, test the commit above. I think that it work now.

**Comment by jojo12** [comment]
Hi, I exchanged the file with your new one, cleared cache. Then went to smartphone and downloaded the attachment. Same error.
I tried with an attachmend in the new uddeIM. I get a good result.
So in JEM the problem persists. (sorry)

**Comment by mckillo** [comment]
Have you apply the last commit? If it's so. Now I can't simulate the error, in my test it works.

**Comment by jojo12** [comment]
yes, that was the last commit. Don't loose time for that, there's a solution, not the best, but it works.

**Comment by jojo12** [comment]
that's strange: after a bit time, I have installed and uninstalled a pdf viewer on my smartphone, the download, does not change to .html. But first it says, it can not read it. When I open then in the download folder I am asked which pdf reader and then I can read it.

**Comment by mckillo** [comment]
But was the file saved as .pdf or .html?

**Comment by jojo12** [comment]
now it was saved as .pdf

**Comment by Heklaterriol** [comment]
the fix works here too. @mckillo thx!
