### ISSUE TITLE
Question: CSS files vs CSS responsive files

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1694]
It's not clear for me (and others):
Switching between layout style and responsive style in the JEM settings:
does it switch automaticly between normal css files and responsive css files?

And what about JEM>layout>custom stylesheets ? 
Does this take the indicated file only for legacy or for responsive or both?

The settings JEM>layout>backgroundcolor/bordercolor/color seem to be for both (legacy and responsive). Is this right?
And where are they saved? in a css file?

**Comment by mckillo** [comment]
The CSS of styles are in \media\com_jem\css, the files finished with  _responsive are of responsive style. These CSS are used by views (.html). The legacy CSS files don't finish  with any suffix.
The customs CSS files  are saved into \media\com_jem\css\custom folder. By default, that custom folder is empty, if the user saves a custom CSS, this is the place where you find custom CSS files.
And for your last question, yes, any attribute can be in both CSS files (there are commons) or not, depending on what style is active.

**Comment by jojo12** [comment]
welcome back :-)
I tried to ask an other question !
in JEMsettings>Layout>Custom Stylesheets you can change between core JEM-CSS-stylesheets and custom CSS stylesheets.
when I use modern style, it seems to take automaticly jem-responsive.css (without changing here something).
when I want to change now something in jem-responsive.css? Have I to insert this into the field for custom jem.css and activate this button?

**Comment by mckillo** [comment]
In Layouts - Custom Stylesheets, If you have Yes in jem.css, and in file you write new.css. Then, you have to create a new CSS file in  \media\com_jem\css\custom folder.
Then, you can go to 'Edit new.css' on the right site of JEM - Control Panel -  CSS Manager page.
For example, the content of news.css could be:

![JEM-edit_new_css](https://github.com/jemproject/JEM-Project/assets/2765316/a825a644-8a6c-4cb8-9987-1cde94625be0)

and save this new.css file form CSS Manager. Go to the frontend and you can see the calendar view. Now, the style is jem.css + new.css (overwrite div#jem).

![JEM-edit_new_css-frontend](https://github.com/jemproject/JEM-Project/assets/2765316/5993eed3-ddc6-4f3a-aa32-600a73c0a726)

jem.cs is valid for the view, new.css is valid to add new style or overwrite the style of jem.css
