### ISSUE TITLE
How to better integrate login into JEM 

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1697]
When I study the Kunena Forum, then I see, that the visitors don't have any problem to registrate for the site.
When JEM says, registration is needed for  JEM eventregistration, the same users say, they don't want to registrate into  Joomla site.
Kunena seems to suggest, there are less problems with registration.
Because of this I am asking: 
Is there a possibility to integrate Login and Registration more into JEM? normally it is only needed for eventregistration!

**Comment by mckillo** [comment]
How do you want to integrate it? You could expand the any proposal about it

**Comment by jojo12** [comment]
In kunena is a login inside the kunena menue. Like this, it suggests not to register in the whole site (but this is not true)
But it feels better 😉

**Comment by mckillo** [comment]
I'm sorry but I don't see it, JEM uses the Joomla user to control the registration and access.
JEM doesn't have a parallel ACL only for JEM, and If it had to be developed it would not make sense (time and redundancy) with the user management that Joomla has, it is more powerful and flexible.
