### ISSUE TITLE
editevent and editvenue have no special css (only template.css)

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1698]
I  would like to give a better overview in editevent and editvenue with better titles. But there is only the normal site css.
How can I /we adapt? in jem.css/jem-responsive.css or where?
EDIT: Until now, I can only formate it inside edit.php with: 
`<style>
  .jem-legend {background-color:#ccc; 
  }
</style>`
How to do it in a css-file?

**Comment by mckillo** [comment]
You can have custom css for editevent and editvenue.
In editevent, you load custom css [line 188 \components\com_jem\views\editevent\view.html.php]
In editvenue, you load custom css [line 159 \components\com_jem\views\editvenue\view.html.php]
You can create a custom css for jem.css into JEM setting - Layouts - CustomStylesheets - jem.css [Yes, jem-new-css] and create jem-new.css file into \media\com_jem\css\custom\

**Comment by mckillo** [comment]
I don't know if my answer was enought or if you need to do any dev. If it's no, this issue could be closed.

**Comment by Heklaterriol** [comment]
@jojo12 Is this question answered by mckillos contribution?
