### ISSUE TITLE
No fontawesome icons, if you persist on latest joomla4

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1700]
Is there a help for users?

**Comment by mckillo** [comment]
I think that this is the error. There are two content, the second is the right (f35d with support to Awesome 5.0.0 y 6.5.0, 
I delete the old content f08e (don't have support to Awasome 5.0.0).
More info: https://fontawesome.com/search?q=f35d&o=r

**Comment by mckillo** [comment]
If you want to delete the icon link in the calendar, you can delete this code into media\com_jem\css\calendar-responsive.css line 75:
.daynum a::after {
    font-size: 10px;
    padding-left: 5px;
    font-family:var(--fa-style-family,"Font Awesome 6 Free", "Font Awesome 5 Free");
    font-weight:var(--fa-style,900);
    content: "\f35d";
}

**Comment by mckillo** [comment]
I tested it with JL 4.4.1 and JL 5.0.1 with PHP 8.2. It works. 
Tell me if this is solved the issue of the user.

**Comment by jojo12** [comment]
I am looking after all the jem teaser and jem banner modules!

**Comment by jojo12** [comment]
I've no J!4 anymore so I can't test
