### ISSUE TITLE
Updatecheck results in several warnings  JEM 4.2.0/ Joomla 5.0.2

### ISSUE THREAD

**Issue by jobrusche** [jemproject/JEM-Project#1702]
Updatecheck result in several warnings like:
Warning: simplexml_load_string(): Entity: line 1: parser error : StartTag: invalid element name in administrator/components/com_jem/models/updatecheck.php on line 42
Warning: simplexml_load_string(): <!doctype html> in administrator/components/com_jem/models/updatecheck.php on line 42

See attached screenshot for complete list of warnings
Switching debug ON/OFF makes no difference.

The updatecheck finishes with the correct result  :"Good, the latest version of JEM is installed. Always check for updates!"
The Joomla V5 compatibility plugin is enabled

![JEM_4-2-0_error](https://github.com/jemproject/JEM-Project/assets/117929258/5c9ad215-1718-487f-ab88-1df1f9e25492)

**Comment by jobrusche** [comment]
The links "Click for more information" and "Click to download" result in an error 404 'Page not found'
<br%20/><b>Warning</b>:%20%20Undefined%20property:%20stdClass::$download%20in%20<b>/var/www/clients/client25259/web29072/me-cvs/administrator/components/com_jem/views/updatecheck/tmpl/default.php</b>%20on%20line%20<b>86</b><br%20/>

THIS HAPPENS on ALL Joomla V5.0.* that I manage.

**Comment by mckillo** [comment]
I have checked it, it's fine for me with JL5.0.2, PHP 8.2 and JEM 4.2.1 (branch with last commit).

**Comment by jobrusche** [comment]
Installing PHP 8.2.13 cured the warnings.

However "Search for updates" still results in

Update: :Extension: https://www.joomlaeventmanager.net/updatecheck/update_pkg_jem.xml kon niet ontleed worden (Dutch)

in english "update_pkg_jem.xml could not be parsed"

**Comment by jobrusche** [comment]
With PHP 8.2 the updatecheck result looks like this:

![JEM_4-2-0_PHP82](https://github.com/jemproject/JEM-Project/assets/117929258/c39929a2-80d4-406d-888f-4819cef313fb)

The links return to the updatecheck result in a new window/tab

**Comment by mckillo** [comment]
I have tried it again with 5.0.3 clean, 
![image](https://github.com/jemproject/JEM-Project/assets/2765316/4a5122e0-1014-426d-a92e-b2b5797cec6f)
It works.

**Comment by mckillo** [comment]
The xml file downloaded must be: https://www.joomlaeventmanager.net/updatecheck/update_pkg_jem.xml

**Comment by jobrusche** [comment]
As the original poster I can confirm the all my sites with JEM 4.2.0 on Joomla 5.0.3
display the correct information for the updatecheck.
Thanks and regards,
Johan.

**Comment by jobrusche** [comment]
Closing
