### ISSUE TITLE
Calendar Module causing Deprecated

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1705]
Running Joomla 5.0.2+ and JEM 4.20 and php 8.2
Getting the following error in the Calendar Module:
Deprecated: Creation of dynamic property Joomla\Registry\Registry::$module_id is deprecated in /libraries/vendor/joomla/registry/src/Registry.php on line 937

**Comment by mckillo** [comment]
I have tried to simulate the error, but for me, it works in the same environment.
![image](https://github.com/jemproject/JEM-Project/assets/2765316/39d1acf7-2ba5-4fe1-a0f8-c897ffff7dfa)

**Comment by mckillo** [comment]
Reviewed the issue, I have simulated it and fixed. See commit above.

**Comment by jojo12** [comment]
fixed
