### ISSUE TITLE
(Short) Dateformat settings for backend can't be localized

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1707]
@mckillo: There's a post in the forum
The (short) dateformat settings for backend can't be changed to m-d-y, which is used in US. This should be adapted. 
the author [dlborgman] says in the JEM version for Joomla 3.3 this was possible.

**Comment by mckillo** [comment]
@jojo12: Now, in the events view, the Start Date column is format as JEM Setting defined in Basic Settings - Display - Format Date (short). If the Format Date (short) is empty, then the 'd.m.Y' is the default date format.  See commit above. Is it right?

**Comment by jojo12** [comment]
I think it would be better, if this is set as short format, because this is a table which needs short dates.
The details view can be the long date format!

**Comment by jojo12** [comment]
when I use your change, and the JEM setting for short date format is empty, there is a very strange thing instead of the date

**Comment by mckillo** [comment]
Check now the commit above

**Comment by jojo12** [comment]
with that, when I empty the JEM setting, it's the same strange result!

**Comment by mckillo** [comment]
I agree with you, I get the same strange string.
I have reviewed the code and there is missing string into INI to define the date format. 
See the commit above, and now It works.

**Comment by mckillo** [comment]
@jojo12 I have updated the commit of this case. My events view was also affected by the error. Do you agree with the solution? It it's so, close the issue.

**Comment by jojo12** [comment]
I agree. thanks
