### ISSUE TITLE
JEM4.2 on J5: error when saving css in css manager

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1708]
I get following notification:

Joomla\CMS\Event\Model\SaveEvent::onSetSubject():
Argument #1 ($value) must be of type object, array given, called in
/home/httpd/vhosts/mysite.ch/libraries/src/Event/AbstractEvent.php
on line 225 

() | JROOT/libraries/src/Event/Model/SaveEvent.php:42 |  
-- | -- | --
2 | Joomla\CMS\Event\Model\SaveEvent->onSetSubject() | JROOT/libraries/src/Event/AbstractEvent.php:225
3 | Joomla\CMS\Event\AbstractEvent->setArgument() | JROOT/libraries/src/Event/AbstractEvent.php:115
4 | Joomla\CMS\Event\AbstractEvent->__construct() | JROOT/libraries/src/Event/AbstractImmutableEvent.php:51
5 | Joomla\CMS\Event\AbstractImmutableEvent->__construct() | JROOT/libraries/src/Event/Model/ModelEvent.php:55
6 | Joomla\CMS\Event\Model\ModelEvent->__construct() | JROOT/libraries/src/Application/EventAware.php:106
7 | Joomla\CMS\Application\WebApplication->triggerEvent() | JROOT/administrator/components/com_jem/models/source.php:179
8 | JemModelSource->save() | JROOT/administrator/components/com_jem/controllers/source.php:203
9 | JemControllerSource->save() | JROOT/libraries/src/MVC/Controller/BaseController.php:730
10 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/administrator/components/com_jem/jem.php:54
11 | require_once() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
12 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73
13 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
14 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:150
15 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:195
16 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:306
17 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:58
18 | require_once() | JROOT/administrator/index.php:32

**Comment by mckillo** [comment]
I can't simulate this ussue, for me, it works, save the change of css file from CSS Manager.
Do you have more info about the case? File modificated? is custom file? Content of this file? PHP version? Joomla version 5.0.3?

**Comment by mckillo** [comment]
PHP version?

**Comment by jojo12** [comment]
PHP 8.1.27

**Comment by jojo12** [comment]
There is a new post in the forum which says the same on: Joomla: 5.0.3 and JEM: 4.2.0

**Comment by jojo12** [comment]
in my case this is the solution!
(I had no access to ftp, so it was difficult to view into it. I succeeded finally with phoca commander. I changed and now there is no error.  I hope, this is for others too.

**Comment by mckillo** [comment]
This issue already was fixed. See https://github.com/jemproject/JEM-Project/commit/4d8fe1ad3d5c009b82421180c65dde566a9174c5 for next 4.2.1
