### ISSUE TITLE
Create XMAP Plugin for JEM

### ISSUE THREAD

**Issue by neyworg** [jemproject/JEM-Project#171]
Create XMAP plugin for JEM so that XMAP can create sitemap for it's component. 

Related to and cannot be done until bug #48 is fixed.

**Comment by Hoffi1** [comment]
Xmap is finally gone!

**Comment by JKoelman** [comment]
as noted on the site:  http://www.jooxmap.com/

**Comment by jojo12** [comment]
I'm not sure. There is a xmap3 continued
![xmapcont](https://cloud.githubusercontent.com/assets/2960236/6547042/6839b342-c5cb-11e4-9dc8-72c32be9cf40.png)

**Comment by Hoffi1** [comment]
Thanks Jojo. Seems we need to watch that so I will create a topic in dev forum. And if we find the time we can create a new issue for task tracking.

**Comment by JKoelman** [comment]
@Hoffi1 

you're right, didn't think of that one :( 
there is indeed a xmap3 and Branko seems to be very active (for now) but am wondering why Xmap was discontinued ah well. Unfortunately it won't help that it ain't listed in the JED but we'll have to see how the future will be.

beside that: if anyone wants to create a plugin for it then he/she is still welcome to do so.

**Comment by Hoffi1** [comment]
So should we reopen this issue so he/she can see it? :wink:

**Comment by JKoelman** [comment]
some info about xmap + alternatives: http://nathanhawks.us/joomla-tips/recommendations/99-xmap-gone-what-are-the-alternatives  (It was posted at Linkedin but wanted to share it)

**Comment by jojo12** [comment]
only to say, it's a post from nearby one month before.

**Comment by JKoelman** [comment]
@jojo12 actually it was updated at 01/04/2015 (see bottom of the article).

In the article he is mentioning OSMap  and if someone is wondering of the location of OSMAP at Github,  it's here: https://github.com/OSTraining/OSMap

**Comment by jojo12** [comment]
Ok, sorry.
