### ISSUE TITLE
Urgent Problem in My Events: when the user changes from unpublished to published, the event will rest unpublished!

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1710]
when the user changes from unpublished to published, the event will rest unpublished!
There is a post from "gnarly", 
I reproduced this issue
@mckillo

**Comment by mckillo** [comment]
In the new JEM version to J4/5, the field checked_out is null by default. Now this status is checked right when the admin click in the publish, unpublish and trash icons into my events and my venues view (frontend)

@jojo12 Please check the commit above for this issue. Now, the icons work.

**Comment by jojo12** [comment]
yes, it works (hope for gnarly too) will see.
(@mckillo you're great, thanks a lot!

**Comment by mckillo** [comment]
I saw that other views have the same issue with archive icon...I have to apply the solution to these views.
