### ISSUE TITLE
Start of a 4.2.1 package?

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1712]
I think, the fix for myevents is important (after all)!

**Comment by mckillo** [comment]
We could fix a date to release 4.2.1, and before close all issues possible. In 2 weeks?

**Comment by jojo12** [comment]
Ok, I agree

**Comment by mckillo** [comment]
Check the JEM-4.2.1-dev, I think that it can be a release candidate of JEM 4.2.1
@hekla if you want, you can create a night.zip file in the root  to test it before release (merge to master).

**Comment by Heklaterriol** [comment]
pkg_jem_nightly20240422.zip is created an uploaded:
https://github.com/jemproject/JEM-Project/blob/JEM-4.2.1-dev/pkg_jem_nightly20240422.zip

**Comment by mckillo** [comment]
Thanks, 
How I told you, I have finish 2 commits, and they are uploaded (after your zip, sorry, yesterday I don't time in the night to finish).

**Comment by Heklaterriol** [comment]
Thank you. Do I get you right, that I can create the JEM 4.2.1 package now?

**Comment by jobrusche** [comment]
The changelog for 4.2.1 (https://www.joomlaeventmanager.net/project/changelog-jem-4) is already online but the package is not.

**Comment by jojo12** [comment]
We're on the way: there's a nightly inside the branch 4.2.1dev.

**Comment by mckillo** [comment]
In my test of last zip, there are two issues:
- JSession not found --->Fixed with commit: 035f6fea606c83182ca83bee2ed4f6fd4068e943 (review all JSession in front and back)
- Error in queries with null from datetime field ---> Fixed with commit: e736a43e3788e25524c2addb604975892112d320
Please test it and inlcude these commits into final zip.

**Comment by mckillo** [comment]
In the next version 4.2.2, I have 4 pending issues:

- new finder plugin (there is a new branch)
- recurrence events edit
- redesign attachment tab
- time to start registration

Wishes to improve, although everything takes time.

**Comment by Heklaterriol** [comment]
A new nightly build is uploaded:
https://github.com/jemproject/JEM-Project/blob/JEM-4.2.1-dev/pkg_jem_nightly20240424.zip

**Comment by jojo12** [comment]
#1719 is a new found problem!

**Comment by Heklaterriol** [comment]
Fixed, see https://github.com/jemproject/JEM-Project/commit/9d964e7be2ded5c01c066535888bc9f40a6f47c7

**Comment by Heklaterriol** [comment]
Ok fine. Thank you!
@jojo12 When you give me your Go! too, then I will publish the release 4.2.1.

**Comment by jojo12** [comment]
@Heklaterriol : Go! Thank you, both, for all your efforts!

**Comment by Heklaterriol** [comment]
JEM 4.2.1 package is created and in the repository
the branch JEM-4.2.1-dev is merged into master
a branch JEM-4.2.2-dev is created`

`update_pkg_jem.xml` is partly updated (information, release date, checksums) but not the link.
The link (now https://www.joomlaeventmanager.net/download?download=124:jem-4-2-0-stable) has to be updated.

Who will upload the file to the server?
Who will update `extensions.joomla.org`?

**Comment by jojo12** [comment]
german transifex files are ready. There were 17 which were forgotten the last time and now 2 more.

**Comment by Heklaterriol** [comment]
@mckillo : You just committed some new changes. Are they for 4.2.2 or should I quickly include them in 4.2.1?

**Comment by mckillo** [comment]
You are free to add it, I have uploaded to 4.2.2 because I think that the 4.2.1 was closed.

**Comment by mckillo** [comment]
Merge 4.2.2 to master or copy commits

**Comment by jobrusche** [comment]
Flemish (nl_BE) transifex files are ready.
However I have some doubt about the translation of de date-string "j.m.y" . For nl_BE it would be "d.m.j"

**Comment by jojo12** [comment]
Ich komm nicht mehr draus! I don't understand nothing anymore!

**Comment by Heklaterriol** [comment]
> Ich komm nicht mehr draus! I don't understand nothing anymore!

I added some commits to the JEM 4.2.1 package today, which come after the package creation of yesterday.
The updated package is in the releases: https://github.com/jemproject/JEM-Project/releases/tag/v4.2.1-stable
