### ISSUE TITLE
J!5.1 JEM4.2 php 8.2.16 Frontend and Backend>event edit>save -->error 

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1714]
White page: class "Events" not found

**Comment by jojo12** [comment]
in backend:

# | Function | Location
-- | -- | --
1 | () | JROOT/plugins/finder/jem/services/provider.php:38
2 | Joomla\DI\ServiceProviderInterface@anonymous/home/folktanz/public_html/plugins/finder/jem/services/provider.php:23$1f3b->{closure}() | JROOT/libraries/vendor/joomla/di/src/ContainerResource.php:172
3 | Joomla\DI\ContainerResource->getInstance() | JROOT/libraries/vendor/joomla/di/src/Container.php:95
4 | Joomla\DI\Container->get() | JROOT/libraries/src/Extension/ExtensionManagerTrait.php:177
5 | Joomla\CMS\Application\CMSApplication->loadExtension() | JROOT/libraries/src/Extension/ExtensionManagerTrait.php:99
6 | Joomla\CMS\Application\CMSApplication->bootPlugin() | JROOT/libraries/src/Plugin/PluginHelper.php:232
7 | Joomla\CMS\Plugin\PluginHelper::import() | JROOT/libraries/src/Plugin/PluginHelper.php:192
8 | Joomla\CMS\Plugin\PluginHelper::importPlugin() | JROOT/plugins/content/finder/src/Extension/Finder.php:174
9 | Joomla\Plugin\Content\Finder\Extension\Finder->importFinderPlugins() | JROOT/plugins/content/finder/src/Extension/Finder.php:76
10 | Joomla\Plugin\Content\Finder\Extension\Finder->onContentBeforeSave() | JROOT/libraries/src/Plugin/CMSPlugin.php:289
11 | Joomla\CMS\Plugin\CMSPlugin->Joomla\CMS\Plugin\{closure}() | JROOT/libraries/vendor/joomla/event/src/Dispatcher.php:454
12 | Joomla\Event\Dispatcher->dispatch() | JROOT/libraries/src/MVC/Model/AdminModel.php:1293
13 | Joomla\CMS\MVC\Model\AdminModel->save() | JROOT/administrator/components/com_jem/models/event.php:333
14 | JemModelEvent->save() | JROOT/libraries/src/MVC/Controller/FormController.php:689
15 | Joomla\CMS\MVC\Controller\FormController->save() | JROOT/libraries/src/MVC/Controller/BaseController.php:730
16 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/administrator/components/com_jem/jem.php:54
17 | require_once() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
18 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73
19 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
20 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:150
21 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:195
22 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:306
23 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:58
24 | require_once() | JROOT/administrator/index.php:32

**Comment by jojo12** [comment]
it seems to be a problem in the 4.2.1 corrections

**Comment by mckillo** [comment]
Desactive JEM finder plugin, the new version of this plugin isn't finish. 
This file "JROOT/plugins/finder/jem/services/provider.php" is new and it shouldn't be in the last commit, sorry.

**Comment by mckillo** [comment]
How do you have this file "/plugins/finder/jem/services/provider.php"?
I think I don't have upload anything of new version of this plugin

**Comment by jojo12** [comment]
you're right, When I was looking through the plugins, I forgot to disable again the finder.
So this can be closed!
