### ISSUE TITLE
FR: Pointing to today (next event) in frontend and backend

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1715]
The problem: if you want to see in calendar views all (past, actual and future) events, then you need to disable the archive possibility.
But then in backend>events and frontend>simplelist (and more lists) you have all events listed and you need time to search the next upcoming event.
It would be helpful, when you open the list, the list would point to the actual date.

Is this easy and possible to add? Perhaps as feature you can enable/disable?

**Comment by mckillo** [comment]
Yes, it's possible. It isn't harás but it need tiem to dev.

**Comment by mckillo** [comment]
I've been thinking about this issue and I have several options:

1. Add background colour to past (red), actual (blue) and future (green) events
2. Add a new filter to show the events --> Combo: Archive, Today or Incoming events (include today)
3. Add a new option to the menu setting menu, date combo: incoming from now (order: date ASC), archived until now (order: date DESC), all events + indicate a time (X days). 
4. If the initial filter is Date, show the event page closest to the current day. This option is dependent on the order of the table.

Which do you like? Voting accepted.
Do you see any idea more about it?

**Comment by jojo12** [comment]
Hi, Good Morning!
An other idea (which seems me easier) is:
if you choose the setting to archive past events, then to force the calendar(s) to show the archived events too!

**Comment by jobrusche** [comment]
Below my original post in the forum
""
In the basic and wide module as wel as in the content plugin one can select to list only events in the future.

I would like to obtain the same but from clicking on the list by category link or the list by location link
in de display of a single event

With the current software (4.2.0) those links show all non-archived events in the database and that can be a very long list.
I could work around that by archiving events within a shorter period but that has the unwanted side-effect that
the visitor cannot see the past events in the kalender module.

Would a custom ccs be able to accomplish this ?
If not, maybe via new feature request ?
""

**Comment by mckillo** [comment]
@jojo12 This feature is in this commit. Now in the calendar menu, can select 'Yes' if the admin also wants to see the archived events in the calendar view.

![image](https://github.com/jemproject/JEM-Project/assets/2765316/7e1077c4-462e-4e64-93e7-fc6403673f39)

Tell me if it was this and works,

**Comment by jojo12** [comment]
Setting is: Archive events after 1 day. The new menue point is set to yes
The menue is fine. 
The new menue point is set to yes.
Clean cache
open calendar: now archived events displayed!

**Comment by mckillo** [comment]
Thanks for testing and weekcal view add too (see last commit).
If it's fine, this issue can be closed.

**Comment by mckillo** [comment]
@jobrusche Could you tell me more details about your case (example)?

**Comment by jojo12** [comment]
I have general JEM settings =archive past events (after 1 day). This works best.
In backend and in frontend the eventlists are like that: the actual event is at top of the list
Normal in calendar I see the whole month, but events only from today until end of month.
I would like to see all events of the month (the past events the event today and upcoming events..)
Until now this was not possible. (Only when I set general JEM to: do nothing with past events, the calendar is, like I would have it!
But testing now, nothing changed, All past events are hidden.

**Comment by mckillo** [comment]
This could be the option that you want in the eventlist view:

![image](https://github.com/jemproject/JEM-Project/assets/2765316/69c4b857-8b8c-4266-9e40-9cb786c6e088)

**Comment by mckillo** [comment]
Right? It is just a draft.

**Comment by jojo12** [comment]
I think, you forgot to add the eventslist.xml (there's only the model)

**Comment by mckillo** [comment]
It's a draft, I can't upload XML....I have to dev the rest of code (filter to the query).
But is it right?

**Comment by jojo12** [comment]
There were posters (perhaps because of the hidden past events in the calendar. When you decide not to archive, then you serarch  in a long list in frontend and backend for the right event. 
For me, who preferes to archive, it is enough to see in calendar the past events too.
So if you want to give others this possibilities, go on!

**Comment by mckillo** [comment]
Maybe it's my mistake, mixing two views in this case, but I don't understand. Do you mean the calendar or ceventlist view? Maybe it's my mistake, mixing two views in this case, but I don't understand. Do you mean the calendar or the list of events?
If you can be more explicit, it would be appreciated, to correctly imagine the solution :-) it's monday.

**Comment by mckillo** [comment]
Other solution can be:
Show list events from “X” days ago. The admin writes the X, X is the number of days. This way it is more simplified and customizable, it could be 365 days ago (last year).

In the calendar, it is not necessary. Whether to show archived events (includes past non-archived assets as well).

**Comment by jojo12** [comment]
I think, the users wishes comes from different settings:
1st setting in general JEM settings: **todo with past events->archive** then there's the "strange" thing in calendar: you only see upcoming events. All earlier than today is empty. This gives the feeling, that this event organisator has only events from today on (so he must have not much experience with events!).
In this situation the wish is to see all events in calendar.

2nd setting in general JEM settings:**todo with past events->nothing** then past and upcoming events are visible in calendar. Here it is fine. But then in backend and frontend event list all past and upcoming events are visible and they are in ascending order.
So on top you may have an event from years ago!! And you have to search for todays or next upcoming events. The same is, when you order descending, then you see an event far in the future and you have to search for today! Both is not ideal!
If this general JEM setting is chosen, then it needs something like a button or else which leads directly to @today.

The 3rd setting in general JEM settings:**todo with past events->delete** doesn't help in these cases.

[For frontend eventslist there is an other feature request: is it possible to show borders between the different months:
e.g. between the last event in february and the first event in march, there is a line where's a text "March".
This would help for quicker orientation in event list. 
But this feature request does not belong to the feature request here, in my eyes.]

**Comment by mckillo** [comment]
1st setting is solved with new option "Show archived events"=Yes, see all events in the calendar, right?

2nd setting will be solved with the other new option "Show list events from", so, you see the list events from x time to the end. To avoid a large list upcoming events, we need to define the "Show list events until" for upcoming events (with options in oppositive direction, right? or define a filter options by day "Show events from X days ago and until Y days from now" (X, Y: Number)

**Comment by jojo12** [comment]
1st setting: yes.
2nd setting: I am not sure, perhaps I've not enough imagination ;-)

**Comment by mckillo** [comment]
![image](https://github.com/jemproject/JEM-Project/assets/2765316/6267fd47-1056-4d2c-b5e2-f37376569010)
Can it be a solution for the 2nd setting? The admin can be set the number of days (before and after) to filter events to the list.

**Comment by jojo12** [comment]
I think: yes. But this is for others, not for me!
