### ISSUE TITLE
after zip and install now, i get error

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1717]
Class "CSMPlugin" not found

must be somewhere a typo

content/jem.php line 20

**Comment by jojo12** [comment]
I zipped it myself 5 minutes ago, it is in yours

**Comment by jojo12** [comment]
commit/97f767c84044ff5b1ff8e68c5e50b4551838fe9f

**Comment by mckillo** [comment]
@jojo12 
See CSMPlugin -> CMSPLugin.... sorry.
I have updated with other commit for JModelLegacy to BaseDatabaseModel

**Comment by jojo12** [comment]
was an other (new) typo CMSMPlugin instead of CMSPlugin. I corrected
commit https://github.com/jemproject/JEM-Project/commit/2f8272e76d2f00dee9f7f4adceb830f161ef5a06

**Comment by mckillo** [comment]
Sorry, many changes, All of them are manual because I have to check the code, in this case, I don't use refactor or replace tool.
