### ISSUE TITLE
Error in stable (please look): Loosing all but letters in description

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1719]
I installed the nightly and worked then with JCE-Editor in Eventdescription:
The format is broken: there are no new lines,  all in same (no bold) 
EDIT: Same with TinyMC-Editor

**Comment by mckillo** [comment]
I'm going to see ...

**Comment by mckillo** [comment]
I don't find the error, can you upload a capture/video with the error?

**Comment by jojo12** [comment]
It's a bit difficult, to show how I found it:
There was I text with full formation (bold, h2...).
I opened it added some words and saved it. Result: all in one line, no h2, no bold. 
(It's a bit like in mod_jem_banner view with description. There it is ok, that there are no h2...in the description.
Now I can only create a new description (now I do it in frontend) make a printscreen before saving, and then after saving.
![Description changed](https://github.com/jemproject/JEM-Project/assets/2960236/6383e5ae-9332-424f-a6f2-5501e43d2c5c)

**Comment by Heklaterriol** [comment]
I can reproduce the error in the **frontend** (the venue description works fine …)

**Comment by Heklaterriol** [comment]
I found the bug, a new package is coming …

**Comment by mckillo** [comment]
I have review the front (clean) but int he back there are some JComponentHelper. 
I have uploaded a commit to fix (see above)

**Comment by Heklaterriol** [comment]
Thx, McKillo. I included the changes in https://github.com/jemproject/JEM-Project/blob/JEM-4.2.1-dev/pkg_jem_nightly20240425_v2.zip

**Comment by jojo12** [comment]
After the todays post of Kurtus in the forum I tested again, and the problem is not yet fixed or is back.
If you use in frontend editvenue, and save, then there's the problem.
In editvenue and in backend, there's no problem!

**Comment by jojo12** [comment]
when I compare frontend event.xml and venue.xml, then I see the filter="safehtml" in venue.xml. When I copy this into event.xml in fronten, then the formatted articletext persists as he should be. I changed this in backend too and it works.
I will now test, if e.g. images rest in the text. (will be continued)

**Comment by Heklaterriol** [comment]
I cannot reproduce it. I  even reinstalled the newest version (JEM 4.2.1) – it works fine here

**Comment by mckillo** [comment]
For me, I works, I can create/edit event with HTML description. I tested with  languages in english and spanish. From front and back. I cannot reproduce it too.

**Comment by mckillo** [comment]
You write that the error is in events.xml:
- back; \administrator\components\com_jem\models\forms\event.xml line 13:
`   filter="ComponentHelper::filterText"`
- -front: \components\com_jem\models\forms\event.xml line 6:
`   filter="\Joomla\CMS\Component\ComponentHelper::filterText" hide="pagebreak"/>`

Info of form xml in Joomla:
 - Standard form field types: https://docs.joomla.org/Standard_form_field_types
 - Editor type: https://docs.joomla.org/Editor_form_field_type (this field was created in J1.5)
 
I think that this error come from Joomla: https://issues.joomla.org/tracker/joomla-cms/41259
- In this commit the right change is to `filter="\Joomla\CMS\Component\ComponentHelper::filterText"`

@jojo12 how you can simulate the error, you can change this:
- back; \administrator\components\com_jem\models\forms\event.xml line 13:
`   lter="\Joomla\CMS\Component\ComponentHelper::filterText"`
- -front: \components\com_jem\models\forms\event.xml line 6:
`   filter="\Joomla\CMS\Component\ComponentHelper::filterText" />`

Tell us, if it works

**Comment by jojo12** [comment]
I am very confused now: I don't know exactly, what settings @Kurtus in the forum has. 
I tested as follows: 

> Testing with different templates (Cassiopeia, t4_purity_IV)
with Firefox Developer
Php 8.2.18 Joomla! 5.1.0 Stable 


Compat-Plugin: Activated
filter="JComponentHelper::filterText"
Result: works in FE and BE
filter="ComponentHelper::filterText"
Result: Problems in FE and BE
filter="safehtml
Result: works in FE and BE

Compat-Plugin: Deactivated
filter="JComponentHelper::filterText"
Result: error Class “JComponentHelper”
filter="ComponentHelper::filterText"
Result: Problems in FE and BE
filter="savehtml"
Result: works in FE and BE

Can you say me, why in both "venue.xml" is used "safehtml", which has the same structure with "description"?

(I will continue to test with your extended filter (filter="\Joomla\CMS\Component\ComponentHelper::filterText")

**Comment by jojo12** [comment]
This last prososal works with and without compat plugin! 
What we have to do now? If there will be more system which loose all descriptions, this is heavy. Do we have to cre te a new version or what?

**Comment by mckillo** [comment]
But on the other hand, the description of event or venue must be HTML code and for it, filter="savehtml" is enough.

**Comment by mckillo** [comment]
In other part of the code, for example, when JEM edits CSS file by CSS manager, this editor has a filter="raw". JEM uses the filter to ensure the content format.

**Comment by mckillo** [comment]
The questions is:
Do we want the content of the field where the event and venues descriptions are stored to be html safe or defined by the Joomla text filter?

**Comment by mckillo** [comment]
For example, if filter="savehtml", the description will be html code without call to iframe, scripts, style, ... but I don't find info in Joomla 5 about this filter and I don't know if it will support to J6.

**Comment by mckillo** [comment]
In Joomla 5.1, almost all filter (type=editor in xml file) are filter="\Joomla\CMS\Component\ComponentHelper::filterText"

**Comment by jojo12** [comment]
That means for me, that we should change it in venue.xml too!

**Comment by mckillo** [comment]
@jojo12 Please test this commit with the final solution about filter in xml file

**Comment by mckillo** [comment]
I think that this will be a patch into next version 4.2.2.
We'll try to resolve other issues to include into a new release, and we could close a release 4.2.2 in May 2024 (for example in 2-3 weeks). We can detect others new issues of 4.2.1 during this time too. The solution of filter field (this issue) is here.

**Comment by jojo12** [comment]
I tested: the event.xml and venue.xml in frontend work fine. The event.xml in backend works fine too!
But as question: To be consistent--> in venue.xml in backend should be changed from "savehtml" to  "\Joomla\CMS\Component\ComponentHelper::filterText" ?

But I see an other problem during testing: when opening and saving existing venue in backend, I get error:
`Call to a member function format() on bool`

**Comment by mckillo** [comment]
@jojo12 Now all filter in the editor type are consistent. Check it.
About the new error, I can't simulate it, I can edit and save venues in back without any error. 
I'm work with JEM-4.2.2-dev branch.
