### ISSUE TITLE
JEM finder

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1720]
1) the en-GB language files must be in administrator/language. If not, you see only the keys.
2) Attention KEYS: PLG_FINDER_JEM....
`PLG_FINDER_JEM="Smart Search - JEM"
PLG_FINDER_JEM_FIELD_SEARCH_ARCHIVED_DESC="When changing this setting, you have to run the index command in Smart Search before this takes effect."
PLG_FINDER_JEM_FIELD_SEARCH_ARCHIVED_LABEL="Search Archived Content"
PLG_FINDER_JEM_TAXONOMIES_AUTHOR="Author"
PLG_FINDER_JEM_TAXONOMIES_VENUE="Venue"
PLG_FINDER_JEM_TAXONOMIES_CATEGORY="Category"
PLG_FINDER_JEM_TAXONOMIES_LABEL="Taxonomies to Index"
PLG_FINDER_JEM_TAXONOMIES_LANGUAGE="Language"
PLG_FINDER_JEM_TAXONOMIES_TYPE="Type"
PLG_FINDER_JEM_XML_DESCRIPTION="Updates the indexes of JEM Event whenever an event is created, modified or deleted. NOTE the JEM - Smart Search plugin must be enabled."
PLG_FINDER_QUERY_FILTER_BRANCH_P_EVENT="Events"
PLG_FINDER_QUERY_FILTER_BRANCH_P_VENUE="Venues"
PLG_FINDER_QUERY_FILTER_BRANCH_S_EVENT="Event"
PLG_FINDER_QUERY_FILTER_BRANCH_S_VENUE="Venue"`
3)

**Comment by mckillo** [comment]
Yes

**Comment by mckillo** [comment]
This wa applied into new JEM plugin. Go to https://github.com/jemproject/JEM-Project/issues/1605.

**Comment by jojo12** [comment]
I tried it:
with compat, I get: `Unknown format specifier "S"`
w/o compat, I get: `Class JFactory not found`

**Comment by mckillo** [comment]
Sorry, but the finder plugin isn't finished, and I don't have upload the last code, I'm debugging.
