### ISSUE TITLE
4.2.0 to 4.2.1 Checksum verification failed. Please make sure you are using the correct update server!

### ISSUE THREAD

**Issue by jobrusche** [jemproject/JEM-Project#1722]
Sofar I tried to update JEM 4.2.0 to 4.2.1 on 3 of my servers.
All 3 reponded with : The checksum verification failed. Please make sure you are using the correct update server!

A rebuild of the update servers did not cure the problem

Regards,
Johan.

**Comment by Heklaterriol** [comment]
Oh sorry, I messed it up twice, now the checksums are ok (I just tested it), see teh correct file here:
https://raw.githubusercontent.com/jemproject/JEM-Project/master/update_pkg_jem.xml

**Comment by Heklaterriol** [comment]
@ernst67 
now the checksums are ok (I just tested it), see the correct file here:
https://raw.githubusercontent.com/jemproject/JEM-Project/master/update_pkg_jem.xml

**Comment by jobrusche** [comment]
Has this file been put online @ https://www.joomlaeventmanager.net/updatecheck/update_pkg_jem.xml  ?
Still same problem ...

**Comment by Heklaterriol** [comment]
the checksums are still wrong:

the correct ones are:

```
<sha256>2464c0da7073c4165b3edae2dfb85a5f940771c9313f53eee4fc93699af7e7ba</sha256>
<sha384>94c64866918e9a47ac26db3e5e7e8604c115928d9b6ec88c478953acf0c4c3aaffc0f859beef6dc11a66f40abb6fa0a4</sha384>
<sha512>79c1c876f1860fc8e3d2fe568a50b55b6f33cc88622a0ffca57ce893df4446bc3d8374ba67a014aaadef27456310b0f9daf543de697c63d9e1edb73688791884</sha512>
```

See the correct xml file here:
https://raw.githubusercontent.com/jemproject/JEM-Project/master/update_pkg_jem.xml

**Comment by mckillo** [comment]
This issue is fixed, it could be closed, right?
