### ISSUE TITLE
JEM4.2.1 on J!5.1: there seems to be a problem in jemlistevents Plugin!

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1724]
I tried to add it to startpage. Does'nt work! I tested on 2 different sites.

**Comment by mckillo** [comment]
Have you applied the last commit of 4.2.2 dev?

**Comment by mckillo** [comment]
It doesn't work in J5.1. It needs to be updated. This plugin can't call with the old structure.
When I finish with the finder plugin, I'll update it too.... and all others JEM plugins.

**Comment by jojo12** [comment]
When I look into different finder plugins (I am testing w/o compat plugin), most of the finder plugins work without the new system!
So I think, there is other thing, which doesn't work in content/jemlistevents plugin.

**Comment by Heklaterriol** [comment]
Is this solved or clarified what it was about?
I tried to reproduce it on Joomla 5.1.1 but did not find any problems …

**Comment by jojo12** [comment]
I think, there is no problem, if you prepare the plugin (until to the end). This is important!!!
I first tried, only to input {jemlistevents} , and forgot to fill the form: nothing happened, perhaps because of the default "unfinished"
But when good preparing with the form, it is excellent:
*Proposal: it would be better to set "upcoming" as default!!! (to do)
