### ISSUE TITLE
JEM4.2.1 on J!5.1: crypted instead of a sign in calendar view

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1725]
there is something crypted instead of the sign
![calnosign](https://github.com/jemproject/JEM-Project/assets/2960236/9fc8c123-ff8c-4b97-8741-752a1e52e45e)

**Comment by mckillo** [comment]
This was solves in a old commit. I have to find it

**Comment by mckillo** [comment]
We were speaking about it in https://github.com/jemproject/JEM-Project/issues/1700.

In Joomla 5.1, the library is update FontAwesome to 6.5.1, and I can check this icon in https://fontawesome.com/v6/search?q=f35d&o=v and it's right. 

In my calendar view, I can see the icon to link day view. 

Is it with Cassiopeia template? If it's no, review the template config to any reference of FontAwesome.

**Comment by jojo12** [comment]
you're right, it's the same and like that it will always come back. How can we make it better?
I tested with purity_iv, there I can separately choose fontawesome 4 or 5 or 6 or icomoon or combinations.
Here my test:
![fa_icomoon](https://github.com/jemproject/JEM-Project/assets/2960236/8ccc8d32-b670-4603-8931-edb60a94c7b2)

**Comment by jojo12** [comment]
when I test with cassiopeia, I don't see the sign in calendar, but the signs in mod_jem teaser I can see.

**Comment by mckillo** [comment]
No, we have the same version of joomla at the beginning. The Joomla core is the same for all users and comes with FontAwesome in 6.5.1.

Previously, jquery had the same problem, there are several versions in the Joomla installation and there are conflicts, the same thing happens with FontAwesome.

I assume that your Joomla has more extensions (templates, components), and that the extensions come with another old version of FontAwesome, and there is some conflict with this library.

**Comment by jojo12** [comment]
Thanks. For me it looks like we have two systems in JEM: icomoon and fontawesone. It seems Joomla core tries to go only on fontawesome, which grows, when there's a newer fontawesome. For me it only helps when I change to t4_templates, where I can add each fontsystem individually. 
But in core it should work with cassiopeia!

**Comment by mckillo** [comment]
For me, in J5.1 clean, works.

**Comment by Pinkeltje** [comment]
Unable to reproduce. For me icons are visible in Cassiopeia and Yootheme Pro.
