### ISSUE TITLE
Errors when uninstalling JEM-Package

### ISSUE THREAD

**Issue by Heklaterriol** [jemproject/JEM-Project#1742]
There are problems with uninstalling JEM.

Each JEM item can be uninstalled individually without any problems. 

But when uninstalling JEM-package there are problems:
When I uninstall it, it uninstalls all the other items too (except Quickicons), but if the other items are already uninstalled, it causes error messages (even though they are uninstalled successfully).
This also happens when I try to install all JEM elements at once, because they are uninstalled individually and at the same time JEM-Package tries to uninstall them again.

![uninstall](https://github.com/jemproject/JEM-Project/assets/28540581/38616770-3b08-40b7-892c-1b90d06c2930)

I suggest that we modify the JEM package, that it only uninstalls itself and not all the other JEM items as well.

**Comment by mckillo** [comment]
If the admin uninstalls any JEM extension before uninstall JEM package, Joomla shows the warning. We don't have control of this Joomla warning. If the admin uninstalls JEM package, then all JEM extensions are uninstalled, include JEMm quickicon plugin (if the commit is applied).

**Comment by mckillo** [comment]
@Heklaterriol Thanks, now JEM uninstall is clean. Test it and if it works, close the issue.

**Comment by mckillo** [comment]
Extension Uninstall Dependency (https://docs.joomla.org/Package/en)
"As of Joomla! 3.7.0, a package extension can declare that its child elements cannot be uninstalled independently with a <blockChildUninstall>true</blockChildUninstall> element in the package manifest. If your package needs all its extensions to operate effectively, set this to true or 1."

We can block to uninstall, but I think that it isn't necessary. The admin could uninstall JEM modules or plugins, if aren't used.

**Comment by Heklaterriol** [comment]
Thnx McKillo, I agree and I'm fine this way.
