### ISSUE TITLE
Error in Backend venue saving: Call to a member function format() on bool

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1743]
in backend, when opening existing venue and saving it, I get error:

`Call to a member function format() on bool`
1 | () | JROOT/libraries/src/Form/Field/CalendarField.php:400
-- | -- | --
2 | Joomla\CMS\Form\Field\CalendarField->filter() | JROOT/libraries/src/Form/Form.php:1047
3 | Joomla\CMS\Form\Form->filter() | JROOT/libraries/src/Form/Form.php:991
4 | Joomla\CMS\Form\Form->process() | JROOT/libraries/src/MVC/Model/FormModel.php:219
5 | Joomla\CMS\MVC\Model\FormModel->validate() | JROOT/libraries/src/MVC/Controller/FormController.php:636
6 | Joomla\CMS\MVC\Controller\FormController->save() | JROOT/libraries/src/MVC/Controller/BaseController.php:730
7 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/administrator/components/com_jem/jem.php:54
8 | require_once() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
9 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73
10 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
11 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:150
12 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:195
13 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:306
14 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:58
15 | require_once() | JROOT/administrator/index.php:32

**Comment by jojo12** [comment]
Solution like #1713
```
               format="Y-m-d H:i:s"
               translateformat="false"
			   filterformat="Y-m-d H:i:s"
```

**Comment by mckillo** [comment]
I can't simulate it, I can edit and save venues in back without any error.
I'm work with JEM-4.2.2-dev branch. Check that the xml file is updated.

**Comment by mckillo** [comment]
Here you are, test it.

**Comment by mckillo** [comment]
Tell me if it works in German language.

**Comment by jojo12** [comment]
yes, thanks!

**Comment by mckillo** [comment]
I have updated the commit. I tested with spanish language inbackend, it works.
