### ISSUE TITLE
FR: in frontend eventslist: make a break each month for better orientation

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1744]
[For frontend eventslist there is an other feature request: is it possible to show borders between the different months:
e.g. between the last event in february and the first event in march, there is a line where's a text "March".
This would help for quicker orientation in event list. 
But this feature request does not belong to the feature request here, in my eyes. I will put this in a separate issue!]

I take this separate from #1715

**Comment by jojo12** [comment]
example:
![grafik](https://github.com/jemproject/JEM-Project/assets/2960236/5d44586a-552d-497b-b14f-425ab6c35bf8)

**Comment by mckillo** [comment]
How solution, I created a new filter by month in the eventlist view

![image](https://github.com/jemproject/JEM-Project/assets/2765316/2c866bb0-6895-4a4f-bd23-6a733f672e0e)

Do you like it?
(see next commit)

**Comment by mckillo** [comment]
Also you can set the new option "Show row with month name", this option is only applied in responsive layout, because in legacy layout break the order of table.

![image](https://github.com/jemproject/JEM-Project/assets/2765316/02e6dd8f-95e6-4b19-a627-4d678b82f255)

By defauld the list in this view is not limited, but the admin can set the limit of days (before and after today):

![image](https://github.com/jemproject/JEM-Project/assets/2765316/79f57528-694b-4aff-884c-101f4c9e5c1e)

You can see the eventlist view with this options active:

![image](https://github.com/jemproject/JEM-Project/assets/2765316/104d5b55-1e9c-414d-97c4-d2a91d24003e)

**Comment by Heklaterriol** [comment]
Thank you @mckillo,
I will test it.
One thing I noticed is, that in my JEM, the pop-up mini calendar in the search field is not there:

![month-filter](https://github.com/jemproject/JEM-Project/assets/28540581/71822179-38cb-4d9d-90ae-d7b5a8a77be8)

An if I insert something like "July 2024" I get an error
`Call to a member function format() on bool  on JROOT/components/com_jem/models/eventslist.php:452`

I don't know how the pop-up mini calendar works but it should be the way, that you only can insert the date in the correct format.

**Comment by Heklaterriol** [comment]
And I suggest an additional css class in the month title for styling

**Comment by mckillo** [comment]
@hekla this input is an input of type="month" and included in HTML5 (https://www.w3.org/TR/2011/WD-html5-20110525/the-input-element.html). 
Sorry, I didn't check the navigator support and this type isn't supported in Firefox and Safari, but in Chrome and Egde work.

You can try these pages to check this input type:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/month
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_month

Proposal solution:
Add a placeholder to input with the format: YYYY-MM, so in Firefox and Safari show the format in this field.

In this case, the line 117 in _\components\com_jem\common\views\tmpl\responsive\default_jem_eventslist.php_, change to:

```
<input type="month" name="filter_month" id="filter_month" **placeholder="YYYY-MM"** value="<?php echo $this->lists['month'];?>" min="<?php echo $monthNow; ?>" max="<?php echo $monthEnd; ?>">
        </div>

```
![image](https://github.com/jemproject/JEM-Project/assets/2765316/07b1ced3-a9e1-4342-8574-6355bdd7ec51)


Change too the line 42 in _\components\com_jem\common\views\tmpl\default_events_table.php_:

`<input type="month" name="filter_month" id="filter_month" **placeholder="YYYY-MM"** value="<?php echo $this->lists['month'];?>" min="<?php echo $monthNow; ?>" max="<?php echo $monthEnd; ?>">`

![image](https://github.com/jemproject/JEM-Project/assets/2765316/b96662c3-eb6a-442e-8d08-17ae204a6f35)

Is the solution good until these browsers implement the month type in input ?

**Comment by mckillo** [comment]
Applied style to title of month (last commit) and use the format in the Month filter (use YYY-MM in Firefox), the view show so:

![image](https://github.com/jemproject/JEM-Project/assets/2765316/ef4c5406-aec5-4aa3-9969-e060b7ade576)

**Comment by jojo12** [comment]
very good the tablelike responsive view! (the line between on top of a new month).
does it need a placeholder (for new people) to know how to insert the month?

**Comment by jojo12** [comment]
does it need a placeholder (for new people) to know how to insert the month?

**Comment by jojo12** [comment]
I got a deprecated:
`
Deprecated: strtotime(): Passing null to parameter #1 ($datetime) of type string is deprecated in C:\xampp\htdocs\joomla\components\com_jem\common\views\tmpl\responsive\default_jem_eventslist.php on line 182

Deprecated: strtotime(): Passing null to parameter #1 ($datetime) of type string is deprecated in C:\xampp\htdocs\joomla\components\com_jem\common\views\tmpl\responsive\default_jem_eventslist.php on line 183

Deprecated: strtotime(): Passing null to parameter #1 ($datetime) of type string is deprecated in C:\xampp\htdocs\joomla\components\com_jem\common\views\tmpl\responsive\default_jem_eventslist.php on line 184

Deprecated: strtotime(): Passing null to parameter #1 ($datetime) of type string is deprecated in C:\xampp\htdocs\joomla\components\com_jem\common\views\tmpl\responsive\default_jem_eventslist.php on line 185`

**Comment by jojo12** [comment]
when I have an event with opendate, then the month is "January 1970". Not tragic, but good to know.

**Comment by mckillo** [comment]
Teh placeholder was added, you should see 'YYYY-MM'.
In the last commit, the deprecated error of strtotime go way, ok?
Send me capture with month "January 1970" or seeting of events to simulate it.

**Comment by jojo12** [comment]
![grafik](https://github.com/jemproject/JEM-Project/assets/2960236/cd5ad066-cb23-4793-9028-d19d40c17e66)

**Comment by jojo12** [comment]
the default_jem_eventslist_small is now ok too
but at least here the deprecated is present.

**Comment by jojo12** [comment]
the month breaks are all english, 
There are no language keys, are they hardcoded?
for opendates it's "January 1970".

**Comment by mckillo** [comment]
See the #1764 or this commit b14c625d7f59a69412078eb588b4b9bac70d15cf

**Comment by mckillo** [comment]
The event with open date are shown in the top without Month row.

**Comment by jojo12** [comment]
works fine with opendate and language files for month
filter with placeholder is fine too,
this can be closed

**Comment by jojo12** [comment]
Placeholder is hardcoded, would be better as key: COM_JEM_DATEPLACEHOLDER="YYYY-MM" . Then we can localize!

**Comment by mckillo** [comment]
In this case, the format is fix 'YYYY-MM' by definition of type.
See https://www.w3schools.com/tags/att_input_type_month.asp
Don't need any key. This is only showing with Safari y Firefox, with Chrome and Edge this input type shows a calendar table.

**Comment by jojo12** [comment]
with edge (chrome) I can't choose earlier month!
![grafik](https://github.com/user-attachments/assets/5cf67198-40fb-4557-a600-d3b80de9e5cf)

**Comment by Heklaterriol** [comment]
This is becaus of the set limits in the html:
`<input type="month" name="filter_month" id="filter_month" placeholder="YYYY-MM" value="" min="2024-07" max="2026-07">`

or in the code:
`<input type="month" name="filter_month" id="filter_month" placeholder="YYYY-MM" value="<?php echo $this->lists['month'];?>" min="<?php echo $monthNow; ?>" max="<?php echo $monthEnd; ?>">`

I think it does not make sense to limit min an max.
I mean, when the given month is set in value, it should be enough orientation

**Comment by mckillo** [comment]
I added min and max attributes with future events in mind. However, they don't make sense for archived events. I change it.

**Comment by jojo12** [comment]
there's a typo
![grafik](https://github.com/user-attachments/assets/a112e60c-d964-4450-85dd-5ee5ea214553)

**Comment by mckillo** [comment]
Thanks. Fix typo and set padding button filter to avoid 2 lines of filters. See next commit.

**Comment by jojo12** [comment]
BE filter attendees not nice (date and title broken)
![grafik](https://github.com/user-attachments/assets/3692d80b-53db-4097-be69-62814c14459c)

**Comment by jojo12** [comment]
col-md-3 would be better for the first line!
