### ISSUE TITLE
error: readmore always in modules, even disabled!

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1745]
From a post, and I reproduced this issue in **mod_jem_banner**!
EDIT: 
in mod_jem_teaser too (and there is in xml even not a point to disable!)

**Comment by mckillo** [comment]
Now, the Read More = NO in the banner module setting works (in responsive layout too).
If it's YES, It will depend on whether the event description has a Read More.

**Comment by mckillo** [comment]
Go to the teaser module... but this module doesn't have a 'Read More' option in its seting (I reviewed the XML file, and it's nothing).
What do we do?
Should we add it? In the code, there is rest of copy&paste code, but it isn't active because there isn't data.

**Comment by mckillo** [comment]
Now, teaser module has an option 'Read more' in the setting (add fied in the xml file).
Clean the code in default.php file (responsive and legacy layout).

Check it and it's good, you can close this issue.

**Comment by jojo12** [comment]
Readmore works, but there is a problem together with #1831: if the image overdrive the border, then the text of eventdescription overdrives too!

**Comment by mckillo** [comment]
@jojo12 The issue #1831 was closed and this issue was fixed too. Could you close it?
