### ISSUE TITLE
After installed JEM4.2.1 all formatting is missing

### ISSUE THREAD

**Issue by over40** [jemproject/JEM-Project#1747]
I have updated JEM4.2.0 to JEM4.2.1. If i edit or add entries and save it, all formatting of the event description is lost. The text is only displayed between code <p>blablabla</p>.

**Comment by jojo12** [comment]
This is known. Our apologies. It will be fixed in next version. Meanwhile here's a patch:
in frontend and backend in models/forms/event.xml exchange the filter for articletext to
`filter="\Joomla\CMS\Component\ComponentHelper::filterText"`

**Comment by jojo12** [comment]
there's a nightly

**Comment by Heklaterriol** [comment]
I prepared a new release, JEM 4.2.2
