### ISSUE TITLE
larger date range in sample events

### ISSUE THREAD

**Issue by Heklaterriol** [jemproject/JEM-Project#1756]
When testing JEM with sample data, the loaded events are only until 4 day in the future. Every fourth day I have to delete the JEM data and reload the sample data. 

I suggest a larger data range. 

What do you think about my suggestion?

**Comment by Heklaterriol** [comment]
See my suggestion in the branch [larger data range in sample data](https://github.com/jemproject/JEM-Project/commit/972cb8d55d92dffc7763510df6876aa371cc2f0a)

**Comment by mckillo** [comment]
I agreee. You can also include a recurring event and another with registration (x places).

**Comment by Heklaterriol** [comment]
Good idea. I added it
