### ISSUE TITLE
Backend light/dark mode 

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1758]
I have a question: atum has a switcher between light and darkmode: do we have to adapt color/backgroundcolor settings for this? And if yes, how

**Comment by Heklaterriol** [comment]
Good point.
At first glimpse II found:
- Help section
- Icons in JEM Control Panel have to be PNG with transparency
- all multible select fields (like in: Setting > Basic Setting >  Meta Option > Edit Keywords, in 
Add/Edit  Event > Access)
- table footer (tfoot) in listings

I will check out how it is implemented in the autumn template-

**Comment by Heklaterriol** [comment]
In addition:
the table footers in listings (with the dropdown menu to choose the number of displayed lines) are not the same as the footers in Joomla standard listing like in Articles etc.
I suggest to adapt the Joomla way (and to move the choice of number of displayed lines to the top)

**Comment by jojo12** [comment]
the dark/light colors for backend are well done! I like.
and I like your proposal 
`I suggest to adapt the Joomla way (and to move the choice of number of displayed lines to the top) and also to makre the filter line on the top more beautiful.`
go!

**Comment by mckillo** [comment]
This is closed, but I think to improve the toolbar of events view in the backend, like this (draft):

![image](https://github.com/user-attachments/assets/639b190d-5265-49de-8314-a4dfc574cdc9)

Is it right? dev?

**Comment by jojo12** [comment]
Yes, this is good.
All like this: attendees, venuec, events, categories, groups.

**Comment by mckillo** [comment]
It can be improved, but the change is rapid for this draft. Please let me know if it's OK for you, and I apply it to the other views.

**Comment by Heklaterriol** [comment]
@mckillo  Please go ahead with your ideas!

**Comment by mckillo** [comment]
Here you are. 
Review filter toolbar style in categories, events, venues and groups views. Now, all of them show filters in only one line.
And the pagination footer shows in the right colour by Joomla profile (light/dark).
Check it and it's right, the issue can be closed.

**Comment by jojo12** [comment]
the only thing which is not yet finished: attendees!

**Comment by mckillo** [comment]
Here you are.

**Comment by jojo12** [comment]
thanks, can we close now!
