### ISSUE TITLE
Tooltip - HTML-Code

### ISSUE THREAD

**Issue by over40** [jemproject/JEM-Project#1759]
At your Demo-Site: **https://demo.joomlaeventmanager.net/ JEM - Module-Calendar** the Mouse-over tooltips are shown as HTML-Code. At my Site this is the same. I have not found a Solution till now.

**Comment by jojo12** [comment]
We had this (long time ago) and it was solved.

**Comment by mckillo** [comment]
With this last commit, the recurrence is generated correctly, but the editing of the series needs review too and others improvements. To achieve this, the first element (root event) must be edited.

If any of the following data are changed in the first event:
- start date
- end date
- recurrence type (daily, weekly, monthly, weekday, yearly)
- repeating every (number)
- recurrence counter (until date)

The root event will be updated, the entire previous series will be deleted, and a new one will be generated based on the saved data.

What do you think about the proposed revision of the recurrence? Is it consistent with its use?

**Comment by mckillo** [comment]
Good point. That's curious and possibly helps to discover the problem, there is something that is not loading. Thank you and I will investigate the case.

**Comment by Heklaterriol** [comment]
The script /media/vendor/bootstrap/js/popper.min.js should be loaded for the mouse-over tooltips to work.
On a JEM component pages it is loaded, but not on pages, where only a JEM module is active.

**Comment by mckillo** [comment]
Thank both for the tips to solve it. Check the commit.

**Comment by over40** [comment]
I can confirm that it works.. Many thanks

**Comment by Heklaterriol** [comment]
thx
