### ISSUE TITLE
Quickicon plugin causes stackdump JEM 4.2.2

### ISSUE THREAD

**Issue by jobrusche** [jemproject/JEM-Project#1766]
Joomla 5.1.1  /   PHP 8.2.17
JEM 4.2.2
Admin side
 System Dashboard -> Plugins -> Quick Icon -JEM

An error has occurred.
0 The file jem.xml could not be found.
Call Stack
#	Function	Location
1	()              JROOT/administrator/components/com_plugins/src/Model/PluginModel.php:279
2	Joomla\Component\Plugins\Administrator\Model\PluginModel->preprocessForm() 
                        JROOT/libraries/src/MVC/Model/FormBehaviorTrait.php:115
3	Joomla\CMS\MVC\Model\FormModel->loadForm()							 
                        JROOT/administrator/components/com_plugins/src/Model/PluginModel.php:109
4	Joomla\Component\Plugins\Administrator\Model\PluginModel->getForm()			 
                        JROOT/libraries/src/MVC/View/AbstractView.php:159
5	Joomla\CMS\MVC\View\AbstractView->get()								 
                       JROOT/administrator/components/com_plugins/src/View/Plugin/HtmlView.php:64
6	Joomla\Component\Plugins\Administrator\View\Plugin\HtmlView->display()		 
                       JROOT/libraries/src/MVC/Controller/BaseController.php:697
7	Joomla\CMS\MVC\Controller\BaseController->display()						 
                       JROOT/administrator/components/com_plugins/src/Controller/DisplayController.php:65
8	Joomla\Component\Plugins\Administrator\Controller\DisplayController->display()	 
                       JROOT/libraries/src/MVC/Controller/BaseController.php:730
9	Joomla\CMS\MVC\Controller\BaseController->execute()						 
                       JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
10	Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch()					 
                       JROOT/libraries/src/Component/ComponentHelper.php:361
11	Joomla\CMS\Component\ComponentHelper::renderComponent()				 
                      JROOT/libraries/src/Application/AdministratorApplication.php:150
12	Joomla\CMS\Application\AdministratorApplication->dispatch()					 
                      JROOT/libraries/src/Application/AdministratorApplication.php:195
13	Joomla\CMS\Application\AdministratorApplication->doExecute()					 
                      JROOT/libraries/src/Application/CMSApplication.php:306
14	Joomla\CMS\Application\CMSApplication->execute()		JROOT/administrator/includes/app.php:58
15	require_once()										JROOT/administrator/index.php:32

This happens on all my sites with JEM
[quickicon-plugin.txt](https://github.com/user-attachments/files/15811175/quickicon-plugin.txt)

**Comment by jojo12** [comment]
yes, I can reproduce this

**Comment by Heklaterriol** [comment]
I did some coding with help of a KI.
And I added two langage files – until now quckicon was without language strings and only in english.

**Comment by jojo12** [comment]
Hi, I don't know how to install! When  I upload it via ftp and install there, I then have always 2 quickinstall icons. With testing it works fine as is should. And I added the german translation too. Works fine.

**Comment by Heklaterriol** [comment]
Try it this way: 
Uninstall the old plug-in in Joomla and then zip the folder "plg_quickicon_jem" free m the repository and install it manually.
You probably have to activate the plug-in in Joomla.

**Comment by jojo12** [comment]
I uninstalled the old quickicon plugin, then installed the new zipped, works best! 
EDIT: 
But then I looked with ftp into folders: there's nothing in quickicon

**Comment by Heklaterriol** [comment]
So, now it's done I think.
