### ISSUE TITLE
LimitBox in JEM backend tables should be on the top

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1768]
I made a separate item for this (separated from dark/light mode #1758)

the table footers in listings (with the dropdown menu to choose the number of displayed lines) are not the same as the footers in Joomla standard listing like in Articles etc.
I suggest to adapt the Joomla way (and to move the choice of number of displayed lines to the top) and also to makre the filter line on the top more beautiful. 

JEM Events:
![jem](https://github.com/jemproject/JEM-Project/assets/28540581/13a748af-88f0-4cb8-b20d-2591d353a6ce)

Joomla articles:
![article](https://github.com/jemproject/JEM-Project/assets/28540581/0f2d0cd2-a0d9-4063-8a2b-bdbffbf14c09)

**Comment by jojo12** [comment]
I tried a bit:
	<?php echo $this->pagination->getLimitBox();?>
should be inside of:
	<div id="j-main-container" class="j-main-container">
<tfooter> can be deleted
and after </table>:
<div class="col-md-9">
<?php echo  (method_exists($this->pagination, 'getPaginationLinks') ? $this->pagination->getPaginationLinks(null) : $this->pagination->getListFooter());?>
                </div>

**Comment by jojo12** [comment]
I think, the filter part should be the same in all these backend views: attendees, categories, events, groups, venues.
So why not add `<fieldset id="filter-bar" class=" mb-3">` to attendees!

**Comment by mckillo** [comment]
See the proposal in https://github.com/jemproject/JEM-Project/issues/1758
