### ISSUE TITLE
Update of post installation text

### ISSUE THREAD

**Issue by Heklaterriol** [jemproject/JEM-Project#1773]
I just noticed, that in the text appearing after the installation ther is some outdated information:
- is there still a woking "Comments plugin"?
- is there auto geotagging?
- should we add the quckicon plugin

See the full text:

> JEM is an Event Management Component for Joomla.
> 
> It's not a classical calendar – it is an easy way to manage and present your events for your group, company or community.
> JEM offers a lot of features and possibilities which make your work easier, like the Venue database, Event recurrence, Auto geotagging and much more.
> But also for your site visitors, JEM has some additional features to offer, like a simple registration system, map service links, or the submission/edit of events and venues from the frontend …
> 
> This package consists of the JEM component combined with the following essential modules and plugins:
> 
>     Search plugin
>     Finder plugin (smart search)
>     Mailer plugin
>     Comments plugin
>     Content List Events plugin
>     Latest Events Basic module
>     Latest Events Wide module
>     Calendar module
>     Teaser module
>     Banner module
>     Jubilee module
> 
> If you want to use any of these modules and plugins, please do not forget to publish them in the module manager and the plugin manager in your site's backend.
> 
> Community support is provided at [www.joomlaeventmanager.net/forum](https://www.joomlaeventmanager.net/forum).
> 
> JEM is based on Eventlist by Christoph Lukes.

**Comment by jojo12** [comment]
Yes, the jem comments work fine.
Yes we add the quickicon plugin,
What is autogeotagging?k

**Comment by Heklaterriol** [comment]
> What is autogeotagging?

no idea …

**Comment by ernst67** [comment]
Auto geotagging is the concept where JEM allocates the longitude / latitude coordinates to a venue, based on the address entered.

**Comment by Heklaterriol** [comment]
@jojo12 and @mckillo : Do you remember if this works?

**Comment by jojo12** [comment]
yes, it works.
