### ISSUE TITLE
Backend events view too much

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1775]
I'm not happy with the events view in backend, there are too many columns inside.
Even if you can hide columns, you allways have to do this from new.
And after all in small screens, you can't reach the attendees column!

is it possible to hide some columns as default? How?
Should we move the attendees column more to the left?

**Comment by jojo12** [comment]
Or:
How can I get in backend attendees view directly? When I can't reach the right side of events view?

**Comment by Heklaterriol** [comment]
I agree. 
We could leave eway "City", "State" and "Country" as they anyway are connected to "Venue" …

**Comment by Heklaterriol** [comment]
As I like your suggestion @jojo12,  I played with it, see the commit above.

I removed "City", "State" and "Country", renamed "Startdate" into "Date" (which by the way is a correct correction) and rearranged two columns according to the Joomla article listing.

![JEM  Backend Event Listing](https://github.com/jemproject/JEM-Project/assets/28540581/05a7e34b-a528-4a38-a35a-e947df51e313)

**Comment by jojo12** [comment]
much better than the all-in-one!.
But in smartphone (even in landscape view) the problem persists. I can't reach the attendees column.

**Comment by Heklaterriol** [comment]
Yes, but I think this has a low priority - I mean, who works in the Joomla adminstration on a smartphon!?
Already in standard Joomla there are many display difficulties on a smartphone …

**Comment by jojo12** [comment]
You're right!
