### ISSUE TITLE
recurring event: empty form after saving

### ISSUE THREAD

**Issue by Heklaterriol** [jemproject/JEM-Project#1784]
After saving a recurring event I get an empty event form, see video clip. Changes in the event are not saved.

https://github.com/user-attachments/assets/78a97da2-0b37-4693-902b-1bf79158501f

Before saving the URL was 
```html
/administrator/index.php?option=com_jem&view=event&layout=edit&id=2
``` 
after saving
```html
administrator/index.php?option=com_jem&view=event&layout=edit
``` 

in the log I find

```
CRITICAL error
Uncaught Throwable of type Joomla\CMS\Router\Exception\RouteNotFoundException thrown with message "Page not found".

Stack trace:

#0 [ROOT]/libraries/src/Application/SiteApplication.php(754): Joomla\CMS\Router\Router->parse(Object(Joomla\CMS\Uri\Uri), true)
#1 [ROOT]/libraries/src/Application/SiteApplication.php(244): Joomla\CMS\Application\SiteApplication->route()
#2 [ROOT]/libraries/src/Application/CMSApplication.php(306): Joomla\CMS\Application\SiteApplication->doExecute()
#3 [ROOT]/includes/app.php(58): Joomla\CMS\Application\CMSApplication->execute()
#4 [ROOT]/index.php(32): require_once('/www/htdocs/w02...')
#5 {main}
```

**Comment by mckillo** [comment]
@Heklaterriol Thanks to report, see the last commit and test it again. Tell me if it's OK.

**Comment by Heklaterriol** [comment]
It is possible to save the event now, but I cannot save a chosen event. See the video clip

https://github.com/user-attachments/assets/1038129c-48e6-4689-b90a-ec92d636f0da

**Comment by mckillo** [comment]
Solved. See last commit.

**Comment by mckillo** [comment]
@Heklaterriol I have updated the last commit (It was not complete).

**Comment by Heklaterriol** [comment]
It works now. 
Cosemtics: after saving I get the system message: "The event has been successfully updated in the following fields: cats, locid [ID:2]"

![successfully saved ](https://github.com/user-attachments/assets/490dc5e8-2b91-4b15-bb1c-e1413c4b00eb)

**Comment by mckillo** [comment]
Don't you like this info message about what fields were changed or update?

**Comment by mckillo** [comment]
Only occurs in modified recurring (child) events.
