### ISSUE TITLE
Archived events not visible in calendar for superusers

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1786]
Even when calendar menu has 
Show archived events=yes
General JEM setting is: Handle old events=archive, after 1 day

**Comment by jojo12** [comment]
strange, long time there were no archived events, now they are.
Perhaps a cache problem?

**Comment by jojo12** [comment]
strange, sometimes it shows, sometimes not, in the same site without any reason!

**Comment by mckillo** [comment]
I don't know.Sometimes yes or no, it isn't normal. Is the event archived or not in the DB?
Send me the url of the calendar view

**Comment by jojo12** [comment]
When I'm not logged in, I can see the archived events in the calendar. When I am logged in, they are hidden!

**Comment by jojo12** [comment]
Why superuser can't see the past events in calendar? Why he is not allowed?

**Comment by mckillo** [comment]
@jojo12 Here you are the fix about the issue. The admins have recovered their sight :-)

**Comment by jojo12** [comment]
fixed, thank you, can be closed
