### ISSUE TITLE
error, when sending unattending a series

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1788]
deleted and closed

**Comment by mckillo** [comment]
I can't simulate this issue, for me it works, I can unregister of all events of series.
I have created a recurrence event with this setting:

![image](https://github.com/user-attachments/assets/3a564f64-b460-44d6-b873-6d7cacf7fe91)

When I save this event, JEM creates the series, the user registers in one event, and the user is registered in all of them.  After, unregistered in one of them and all registers are marked as unattended.

Tell me if there is any data difference in the event.

**Comment by mckillo** [comment]
This error go way, if it's so, can close this issue

**Comment by jojo12** [comment]
it's closed
