### ISSUE TITLE
Information about nightly builds

### ISSUE THREAD

**Issue by Heklaterriol** [jemproject/JEM-Project#1790]
Hey guys, I just want to mention that I started to make nightly builds whenever I'm on github in the late evening and see that there are new commits.
I put them into the "_nighly_builds" directory

**Comment by mckillo** [comment]
Thanks, they are perfect as reference and test pro fresh installation.

**Comment by mckillo** [comment]
I think that the last night zip "pkg_jem_nightly_build_20240723-v1.zip" could be the RC1 of JEM 4.2.3.

**Comment by Heklaterriol** [comment]
I included the first version of the css classes for event/venue/category and created the next one: pkg_jem_nightly_build_20240724-v1.zip
