### ISSUE TITLE
The user should be able to book or unbook single events of a series (not only one)

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1792]
(thanks for more explanations)

I have a series of 7 events (dayly)
SERIESBOOKING=YES
SINGLEEVENTS=YES
I book Testeventreihe 1 -> ok
I go to Testeventreihe 2, try to book only this event --> I can only book all following events. 

The user should be able to book or unbook single events of a series (not only one)

**Comment by mckillo** [comment]
I have created a recurrence event (7 events in 4 days with seriesbooking=Yes and singeevents=Yes)

![image](https://github.com/user-attachments/assets/45f141dc-36ae-423f-987f-d18efa094eba)

How you can see, I can register for each event, I don't set the checkbox 'I will attend all events in this series from now on' at the end.

Now, the user is registered in two events of series.

![image](https://github.com/user-attachments/assets/0cd557bb-42cd-49cf-a006-d1b20b1f4257)

It works, I can't simulate the error. Tell me if you see any difference with your screens.

**Comment by mckillo** [comment]
And this is the event setting (first):

![image](https://github.com/user-attachments/assets/129b70bd-024d-4833-bb42-83310f294705)

**Comment by mckillo** [comment]
Check that SERIESBOOKING=1 SINGLEEVENTS=1 in the event table (database)... for all event of series.
