### ISSUE TITLE
What with Myattendances and Attendeesmanager in FR?

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1793]
I think there should be some notification, when it's for series. ?

**Comment by mckillo** [comment]
In my attendances view, there is a recurrence icon after the title to indicate that the event is part of a series

![image](https://github.com/user-attachments/assets/30b8305a-0d72-4540-89b5-15d47c99d1e0)

In Attendeesmanager, before the admin does click in from event, and in the event view (FR), the admin can see the icon after 'Event' (title) if this event is or isn't a recurrence event (part of a series).

![image](https://github.com/user-attachments/assets/e76b8d59-b5bc-47c6-92cf-69f9132f8709)

Tell me more details about your idea for this issue, I don't see it.

**Comment by mckillo** [comment]
Improving details:
With this commit, if the event was created as series then in the 'Add attendee' view shows option the 'Series event booking' checkbox.

![image](https://github.com/user-attachments/assets/4c3395c1-59b3-4201-9991-c84094a2a672)

This is for BE, in other commit I will upload for FE.

**Comment by jojo12** [comment]
![grafik](https://github.com/user-attachments/assets/85416853-5a91-4db0-b7bc-6d19655eb882)

**Comment by mckillo** [comment]
Now, the filter toolbar in Attendees manager for event (FE) is showing in one line.

![image](https://github.com/user-attachments/assets/f3b1cd70-43ac-4b1c-8ba4-09f842d7cbc9)

See next commit

**Comment by mckillo** [comment]
I have added the recurrence icon in the right side of title
The user and admin can see if the event is recurrence or not (part of series).

![image](https://github.com/user-attachments/assets/7bb1813f-41d3-4b7e-9038-7c4ba1e4bafd)

In the table isn't possible because user list.
See the last commit.

**Comment by jojo12** [comment]
well done, thanks, can be closed
