### ISSUE TITLE
Series: When I am invited and I say attending, it's only for one event, even with seriesbooking

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1794]
When I am invited and I say attending, it's only for one event, even with seriesbooking
EDIT: 
Procedure: I invited as admin in BE, then the user accepted.

**Comment by mckillo** [comment]
If the admin invites a user to one event of a series, don't set the 'Series event booking' checkbox. You can see in the attendence manager (BE) 
If the admin invites a user to all events of series from now on, then the admin has to set 'Series event booking'.

![image](https://github.com/user-attachments/assets/c4c0b108-67b6-4884-8300-4566502e40ce)

**Comment by mckillo** [comment]
But if the admin invites a user to one event and the series hasn't set 'single booking' then the user has to register for all events.

**Comment by mckillo** [comment]
This table of registration can have all status (in function of setting and register of user):

![image](https://github.com/user-attachments/assets/7d9c9ce6-f7ce-4420-99ba-c69e51d35c05)

**Comment by jojo12** [comment]
I invited now in BE my tester, which wasn't attending and I got
![grafik](https://github.com/user-attachments/assets/a81f7b62-2fd6-4404-a030-8347748b78e2)

**Comment by mckillo** [comment]
Try it again with this commit. 
We are fine-tuning.

**Comment by mckillo** [comment]
,Other solution of info message is show the list ids as [ID: 145,146,147,148,....]

**Comment by mckillo** [comment]
Although I think it is not necessary, especially when it is a series with many events.

**Comment by jojo12** [comment]
I tried now to invite, the problem persists. the ids where it says the user is just attending, are from any other events, where noone is attending! Heavy!

**Comment by jojo12** [comment]
Even when I use "series booking", it's only on the first event invited. (is this as you want it?)

**Comment by mckillo** [comment]
But the invited user doesn't book any places, the status is 0 in the register table. The user has to confirm the places.
If you want to book any places to user, you can select 'Attending' in the status.
I don't understand the case.
"Seriesbooking" is applied when the user registers places as attending.

**Comment by mckillo** [comment]
I have added 'Series booking' in the Add attendees view (FE) in the last commit.
I have to do more tests on this and try your case, play with invitation (don't use).

**Comment by jojo12** [comment]
well done, thanks

**Comment by jojo12** [comment]
I had series booking in BE, and invited, --> ok
tester said yes, all attending-> ok
then tester said no, nothing attending. Then the following image:
![grafik](https://github.com/user-attachments/assets/c40fb016-3fa9-4f71-be42-14f201bb318f)

**Comment by mckillo** [comment]
@jojo I think I've already seen the problem. The first element of the series was not being registered when an invitation was made with series booking activated.
Try it now with last commit. Thanks fot your test.

**Comment by jojo12** [comment]
works, thanks, can be closed!
