### ISSUE TITLE
the actual event of a series misses in the status table

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1795]
![grafik](https://github.com/user-attachments/assets/9024b125-212e-474c-b4e1-ba8556772f01)
in my eyes, it would be clearer, to show it in the list too!
not a bug, but can lead to a bug of understanding

**Comment by mckillo** [comment]
@jojo12 Here you are. Now, the actual event is showing in the status table into registration form. See last commit.

**Comment by jojo12** [comment]
fine, thanks, can be closed
