### ISSUE TITLE
language packs 4.2.2 have inside of the files 4.0.0

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1796]
this should be changed, because it irritates! At least for the new packages for 4.2.3!

**Comment by Heklaterriol** [comment]
In the master branch all english language files have version 4.2.2. IN the German language pack there are 4.0.0 and others. So it is wrong on transifex. 
How can we change that?

**Comment by mckillo** [comment]
I think that the version number (mayor:minor:patch)  shouldn't be include in the files. If JEM files have to indicate a version, it will be mayor version, for example JEM v4. Each version is tagged in git and jem.xml (and orhers xml files of JEM package and extenxion). So, we don't have to changed all files. It is an idea.

**Comment by mckillo** [comment]
Others extensions (JCE, Yootheme, Akkeba, ..) don't write the version number in all files, they have a simple header:

<?php
/**
 * @package     JCE
 * @subpackage  Editor
 *
 * @copyright   Copyright (C) 2005 - 2020 Open Source Matters, Inc. All rights reserved.
 * @copyright   Copyright (c) 2009-2024 Ryan Demmer. All rights reserved
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */
 
 <?php
/**
 * @package   akeebabackup
 * @copyright Copyright (c)2006-2023 Nicholas K. Dionysopoulos / Akeeba Ltd
 * @license   GNU General Public License version 3, or later
 */
 
 <?php
/**
* @package   Widgetkit
* @author    YOOtheme http://www.yootheme.com
* @copyright Copyright (C) YOOtheme GmbH
* @license   http://www.gnu.org/licenses/gpl.html GNU/GPL
*/


<?php

/**
 * Kunena Component
 *
 * @package         Kunena.Administrator.Template
 * @subpackage      Categories
 *
 * @copyright       Copyright (C) 2008 - 2023 Kunena Team. All rights reserved.
 * @license         https://www.gnu.org/copyleft/gpl.html GNU/GPL
 * @link            https://www.kunena.org
 **/

 and Joomla too:

<?php

/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   (C) 2006 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

**Comment by jojo12** [comment]
I agree: it is better to have no version inside the language files!

**Comment by Heklaterriol** [comment]
Ok. So it would also be good to have a uniform header.

**Comment by Heklaterriol** [comment]
We can remove all the version number in the files for version 4.2.3. 
I create a branch for that

**Comment by ernst67** [comment]
I presume we will keep the version number in the installation file?

**Comment by Heklaterriol** [comment]
Yes, in the xml files of the extension and each plugin/module
