### ISSUE TITLE
question: user on waitinglist is not shown with these settings. I think it should be visible?

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1805]
General JEM settings>Event page>Registration>Show Attendee Names to "Everybody"
(Display Registration=Show, 
Display Counters=Show, 
Show all related users=Yes)
This chapter "Registration" seems not to work as it should!

**Comment by mckillo** [comment]
It works but there is detail, the waiting users are shown if the user logged.
If the user isn't logged, then the list of user registered is the attendes confirmed with this setting. 
I think that this has not changed since version 3. Isn't right?

**Comment by jojo12** [comment]
you're right, can be closed! Sorry
