### ISSUE TITLE
GB Language file error

### ISSUE THREAD

**Issue by zri-dev** [jemproject/JEM-Project#1807]
As a native UK GB English speaker I am puzzled as to why the en-gb language file includes ZIP for postcodes.  ZIP codes are used EXCLUSIVELY in US (and a couple of small dependencies).  It is utterly annoying that I would need to modify the language file EVERY update  (FTP to server and edit the erroneous file).  By all means add a en-US language file but al least correct the en-GB file.  
And no, I won't accept an override kludge.

**Comment by Heklaterriol** [comment]
Hi zri-dev, thank you for your contribution.
I'm one of the contributing users/devs, like some other volunteers, who invest effort, time and money for this project.

In JEM we have English  en-GB as standard language and origin for all other translations.
As the contributing users/devs are all not native english speakers there might be errors.

Of course it would be good to have two english language files (en-US and en-GB), if we have people who maintain the languages.

That leads me to the crucial question:
**Would you check the en-GB language files for correct British English? Or even mark the differences to US english?**

**Comment by zri-dev** [comment]
I would love to get involved, I will submit a language file, in fact THE language file that I use.   There a a few instances of "hard coded" errors that I will submit as well.   I think this is a useful and worthwhile project and would be happy to see it flourish :)

**Comment by Heklaterriol** [comment]
Wonderful! Do you need any assistance?

**Comment by jojo12** [comment]
I really hope, this will not change language keys! If then we have much work with all languages.

**Comment by Heklaterriol** [comment]
The keys must remain the same, regardless of whether it is British or American English!

**Comment by zri-dev** [comment]
Agreed, no-one cares what the keys are called, the important thing is that the client facing output is in their language and intelligable. ZIP (Zone Improvement Plan)  has no meaning outside the US (and a couple of small dependencies) In the UK and other European countries,  Post Code has a very  specific meaning.  
There are also issues with the back end translations but it is the  actual  cms output which is the more important problem.

**Comment by Heklaterriol** [comment]
Hi @zri-dev, we are about to release JEM  4.2.3.
Without wanting to put you under pressure: If you manage to check the language files within the next week, we could include them in the new version, which would of course be woderful.

**Comment by zri-dev** [comment]
No problem, how do you want me to submit the changes?   I can let you have the site en-gb straightaway, the backend en-gb language file is also a mess, and would take a few more days.

[en-GB.com_jem.zip](https://github.com/user-attachments/files/16550804/en-GB.com_jem.zip)

This is the file I use on my installations.  ( I have prepended site- to the filename)

**Comment by Heklaterriol** [comment]
Thank you zri-dev. I was on holidays and offline. 
It works this way. If you want to fork JEM and then create a pull request would also be possible.

**Comment by Heklaterriol** [comment]
I created a new branch for the modifications in the language files. 
https://github.com/jemproject/JEM-Project/tree/JEM-4.2.3-dev_en-GB%2BUS

I integrated your language file.
There are now en-GB and en-US files.

Are you aware that this was only the main frontend language file `en-GB.com_jem.ini`. You already mentioned the backend, but in addition there are one or two language files for each module and plugin.

The list of language files:
en-GB.com_jem.ini
en-GB.plg_search_jem.sys.ini
en-GB.plg_search_jem.ini
en-GB.plg_jem_mailer.sys.ini
en-GB.plg_jem_mailer.ini
en-GB.plg_jem_comments.sys.ini
en-GB.plg_jem_comments.ini
en-GB.plg_finder_jem.sys.ini
en-GB.plg_finder_jem.ini
en-GB.plg_content_jemlistevents.sys.ini
en-GB.plg_content_jemlistevents.ini
en-GB.plg_content_jem.sys.ini
en-GB.plg_content_jem.ini
en-GB.plg_acymailing_tagjem.ini
en-GB.pkg_jem.sys.ini
en-GB.mod_jem.sys.ini
en-GB.mod_jem.ini
en-GB.mod_jem_wide.sys.ini
en-GB.mod_jem_wide.ini
en-GB.mod_jem_teaser.sys.ini
en-GB.mod_jem_teaser.ini
en-GB.mod_jem_jubilee.sys.ini
en-GB.mod_jem_jubilee.ini
en-GB.mod_jem_cal.sys.ini
en-GB.mod_jem_cal.ini
en-GB.mod_jem_banner.sys.ini
en-GB.mod_jem_banner.ini
en-GB.com_jem.sys.ini
en-GB.com_jem.ini
plg_quickicon_jemquickicon.ini
plg_quickicon_jemquickicon.sys.ini 

I already had a quick look at your changes in `en-GB.com_jem.ini` and integrated them in the plugin and module.language files (postal code -> postcode, zip -> postcode, unregister -> deregister etc.)

(And you have also found some general english mistakes - thank you!)

**Comment by Heklaterriol** [comment]
I created a branch with en-GB and en-US and a nighly build to test in the branch:
https://github.com/jemproject/JEM-Project/tree/JEM-4.2.3-dev_en-GB%2BUS

Modifications:
- add en-US language
- modifiy strings en-GB language according to zri-dev changes
- removal of language prefixes from the language files
- update of language linking

**Comment by mckillo** [comment]
One point/opinion: I don't think it makes sense to add en-US if Joomla doesn't have en-US installed by default, In Joomla, if you want en-US have to install it as new language (like, German, Spanish, ....). Other extensions include one language (en-GB) by default.

**Comment by Heklaterriol** [comment]
Ok, if en-US is not installed by default then we will keep it as an extra language in the list of language downloads.
