### ISSUE TITLE
correct linking to language files

### ISSUE THREAD

**Issue by Heklaterriol** [jemproject/JEM-Project#1808]
I noticed that in the component, the modules and plugins the link to the language files is not established the same way in all the xml files.

**There are now some longer explanations and a short question at the end.**

Most of them just name the language folder and nothing more (com_jem, mod_jem, mod_jem_wide, mod_jem_banner, mod_jem_cal, mod_jem_jubilee, mod_jem_teaser, plg_search_jem, plg_content_jemlistevents, plg_jem_comments, plg_tagjem, jem.xml)

`<folder>language</folder>`

In the xml file of the package (pkg_jem.xml) the language folder is not mentioned but the file is linked to:
```
<languages folder="frontend">
	<language tag="en-GB">language/en-GB/com_akeebabackup.ini</language>
</languages>
```

In the plugin _plg_content_jem_ both the language folder is named and the file is linked to:

```
<files>
	<filename plugin="jem">jem.php</filename>
	<filename>index.html</filename>
	<folder>language</folder>
</files>

<languages>
	<language tag="en-GB">language/en-GB/en-GB.plg_content_jem.ini</language>
	<language tag="en-GB">language/en-GB/en-GB.plg_content_jem.sys.ini</language>
</languages>
```

The same in the _plg_quickicon_jem_ **but the link is made in a different way**:

<files>
	<filename plugin="jemquickicon">jemquickicon.php</filename>
	<filename>script.php</filename>
	<folder>services</folder>
	<folder>src</folder>
	<folder>language</folder>
</files>
<languages folder="language">
	<language tag="en-GB">en-GB/plg_quickicon_jemquickicon.ini</language>
	<language tag="en-GB">en-GB/plg_quickicon_jemquickicon.sys.ini</language>
</languages>

Similar in _plg_finder_jem_ **but here there is a comment from Joomla 2.5 – is this still valid?**

```
<files>
	<file plugin="jem">jem.php</file>
	<filename>index.html</filename>
	<folder>language</folder>
</files>

<!-- Do not remove the language tag, because the language file is needed
	in the administrator/language folder. The language file will only be
	loaded from this location when accessing the finder component at the
	frontend. This is a limitation in J2.5 -->
<languages>
	<language tag="en-GB">language/en-GB/en-GB.plg_finder_jem.ini</language>
</languages>
```

I had a look at akeeba backup, there I found

```
<files folder="frontend">
	<folder>language</folder>
	<folder>src</folder>
</files>

<languages folder="frontend">
	<language tag="en-GB">language/en-GB/com_akeebabackup.ini</language>
</languages>
```

in Joomla 6alpha it is

```
<languages>
	<language tag="en-GB">language/en-GB/plg_finder_content.ini</language>
	<language tag="en-GB">language/en-GB/plg_finder_content.sys.ini</language>
</languages>
```

**So the question: what is best practice?**
- Link to the files like in core Joomla? Or is linking to the folder only sufficient?
- no language prefix in the filename like in core Joomla? (`plg_finder_content.ini` instead of `en-GB.plg_finder_content.ini`)

**Comment by mckillo** [comment]
Good point. I agree with linking to language files, like in Joomla, without using a prefix (e.g., plg_finder_content.ini).

**Comment by Heklaterriol** [comment]
It is not clear to me, what effect this will have, if we changes the linking and then use the new JEM version to update old installations. May we encounter conflicts, buggy language file links etc.?
And what about overrides?

**Comment by Heklaterriol** [comment]
I just realized, that the langauge files in all the other languages are all with a language codes prefix.
I will runs some compatibility tests, how to move to prefixless naming

**Comment by Heklaterriol** [comment]
I created a branch to update the language linking in the way it is realized in Joomla:
https://github.com/jemproject/JEM-Project/tree/JEM-4.2.3-dev_en-GB%2BUS

Included languages at the moment: `en-GB` and `en-US `

Modifications:
- update of language linking
- removal of language prefixes from the language files

I tested:
- clean install – OK
- update from JEM 4.2.2 English - OK (old prefixed languages files are not overritten - seems safer now)
- update from  JEM 4.2.2 German - OK (the prefixed German languages files still work)

There is a nighly build to test in the branch.

**Comment by mckillo** [comment]
I test it, if I installed your zip on JEM 4.2.3 (installed), then I have 3 files for english:

components\com_jem\language\en-GB\en-GB.com_jem.ini
components\com_jem\language\en-GB\com_jem.ini
components\com_jem\language\en-US\com_jem.ini

I guess that JEM will have en-GB by default and the en-US is download by language package, right?

Finally, the installation script needs to be modified to remove the old language files (ex: en-GB.com_jem.ini and so on) so they don't remain in the system.
