### ISSUE TITLE
Howto: users registering for an event should at first go to waitinglist?

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1811]
A FR from the forum:
How to change or proceed for this:
Each user who registers for an event comes as default on waitinglist. 
Then the admin of the event can decide, which users can participate.
(e.g. for putting together a sports team, admin is the trainer)

**Comment by mckillo** [comment]
The admin needs to create an event where the number of Max Places equals the number of Reserved Places. This means there are no available places. 

![image](https://github.com/user-attachments/assets/3a2e903d-5e47-45c7-a8ee-fbdb37e4f766)

I used 10 as an example, but it can be any number (not 0; 1 works too). All users for this event will be registered on the waiting list.
