### ISSUE TITLE
[Fix] Important: Some columns in table weren't created during migration and restore the JEM schema

### ISSUE THREAD

**Issue by mckillo** [jemproject/JEM-Project#1816]
Some errors in the JEM migrations occurred because certain new columns in the JEM table weren't created. I find the reason of this issue.

When using ALTER TABLE in the sql update file, Joomla 4/5 requires the 'COLUMN' keyword in the array_string[4] if it needs to add a new column to the table. This is defined in \libraries\src\Schema\ChangeItem\MysqlChangeItem.php [line 90 in Joomla 5.1.2]. 
![image](https://github.com/user-attachments/assets/49ae3673-c428-45e7-a817-c98f59032f8e)

And for this reason, these columns weren't created during the migration process or when Joomla attempted to fix the JEM schema. There ware an error into some sql file.

However, with the next commit, this issue is now resolved.

**Comment by mckillo** [comment]
How to fix it:
1. Update this commit in your \administrator\components\com_jem\sql\updates\
2. Run this script in your mysql:

```
UPDATE #__schemas as s 
INNER JOIN #__extensions as e ON e.extension_id = s.extension_id
set s.version_id ='4.0.0'
WHERE e.name ='com_jem';
```
[Change #_ with your Joomla db prefix]

3. Go to Joomla backend and clic in Maintenance -> Database 
   Clic checkbox for JEM and clic 'Update structure' buttom.

**Comment by Heklaterriol** [comment]
I created 4.3.0.b2 with your correction.
Do I get you right, that the fix is included in the commits?

**Comment by mckillo** [comment]
No, the commit prevents the issue, but is useful for migration from JEM 4.0.0 or earlier.
If the user has the lastest version, our installation script doesn't run old sql files.Therefore, if they encounter the issue, they will need to apply the workaround mentioned above.

**Comment by Heklaterriol** [comment]
OK, an under which circumstances exactly does it occur?

**Comment by Heklaterriol** [comment]
And do we need to inlcude this information somewhere in the post installation information?
Or maybe even a button/link to run the script, like:
_"If you encounter the error x then, please use this url to fix it: https://www.domain.tld/administrator/components/com_jem/table-fix.php"_

**Comment by mckillo** [comment]
If the admin did a JEM migration from 2.x to 4.x (<4.3.0), it is possible that you have an error because entries are missing from some of the columns that indicate the commit files. If that is the case, an update does not solve the problem, nor does the Joomla database maintenance check see any error in the JEM schema structure, in which case you must apply the workaround (3 points).
This way the user solves the problem, keeping what he has in JEM and without installing from 0.

**Comment by mckillo** [comment]
Internally, the patch could be applied, if any of the indicated columns do not exist, they can be created on the fly, but this is only needed once.

I think this specific verification could be integrated into the installation script for new versions. Let me see how to do it and add the changes, to avoid incidents.

**Comment by mckillo** [comment]
... and it will be thansparent to the user/admin.

**Comment by mckillo** [comment]
@Heklaterriol Here you are the fix into update script.
During the JEM update script, it checks for the existence of columns in the database tables. If any required columns are missing, they will be created as part of the update process (see new function checkColumnsIntoDatabase).
The array $columnsToCheck in this function can be used in the future if we have to check (add) any field in the JEM tables.
I have tested it, but verify if you have time.

**Comment by Heklaterriol** [comment]
Thank you, I will test it today.

**Comment by mckillo** [comment]
I think it was teste and I can be closed this issue.
