### ISSUE TITLE
 Warnung Duplicate column name 'places' Paket Update: Bei der Installation der Erweiterung trat ein Fehler auf: com_jem.zip

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1817]
When I install pkg_JEM_4.3.0.b3 over pkg_JEM4.3.0.b2, then I get above error:

> Warnung
> Duplicate column name 'places'
> Paket Update: Bei der Installation der Erweiterung trat ein Fehler auf: com_jem.zip 

and the whole package is not installed

EDIT: The second try it gives me

> Warnung
> Duplicate column name 'emailacljl'
> Paket Update: Bei der Installation der Erweiterung trat ein Fehler auf: com_jem.zip

**Comment by jojo12** [comment]
replaced script.php and tried to install again over 4.3.0.b2. Worked fine, it's now on 4.3.0.b3

**Comment by Heklaterriol** [comment]
Thanks for reporting and fixing, pkg_jem_4.3.0.b4.zip is uploaded.

For testing is also alway important to simulate a "normal user", e.g. to update from their version (4.2.2) to the potential next release (4.3.0.b4)

**Comment by jojo12** [comment]
You're right, but I've not enough place on my PC to test all.

**Comment by Heklaterriol** [comment]
Yes, it is a piece of work. I always completely uninstall JEM (including the database tables) and reinstall the current version (4.2.2), load the sample data and only then I test the update ...
