### ISSUE TITLE
missing functionality in search (missed migration from mootools to jquery)

### ISSUE THREAD

**Issue by Heklaterriol** [jemproject/JEM-Project#1818]
When restyling the search form ( #1797) I stumbled over an other issue:

In the search form there is the field `continent`, an below the initially hidden fields `country` and `city`.
Previously (JEM 2.x) the functionality was like this:
After chosing a `continent`, the fields `country` appeared directly, then after choosing a country fields `city` appeared, impemented with mootools.

See here:

https://github.com/user-attachments/assets/fa52b835-c115-4931-a669-69a6d19f3f5d

As JEM 4/Joomla 4 moved from mootools to jquery, then functinality has to be adaped, but we overlooked this during the migration. At the moment the fields `country` and `city` are not displayed directly after chosing a continent/country, but only after hitting the search button.

See here:

https://github.com/user-attachments/assets/4744cf00-6a2e-4968-8039-c5f370d7df34

**Comment by jojo12** [comment]
My question is as follows: In most of situations you are searching inside one continent in one country, inside a city. Then it is bad, that you have to fill always "Continent", click search, fill "Country", click search, fill "City", click search.
It would be much better, if you just choosed in the JEM settings e.g. "Switzerland", that "Europe" and "Switzerland" are set as default, and you can choose, if you want to change that, inside this search.

**Comment by mckillo** [comment]
I want to understand, if Jem has define a 'Default Country" into Setting - Global Parameters - Advanced Parameters, then the continent and country filters are select by default and the City select is showning, right?

**Comment by jojo12** [comment]
I try to explain:
My default country is "Switzerland"
In JEM search I see: "Choose a continent"-->I press button and see contintents->I choose "Europe" between the others, then click
then I see: "Choose a country" --> I press button and see "Switzerland"--> I choose "Switzerland", then click
then I see: "Choose a city"-->I press button and see all Cities --> I choose a proposed city and click, only then I get a result!

**Comment by mckillo** [comment]
I understand that, but do you want to have?
I guess that if Country default is defined, then you only clic in the last step, select the city. Is this what you want?

**Comment by jojo12** [comment]
yes, I only need, the last step, but I can't get it, it opens only after choosing the other steps! Perhaps this isn't possible, but it is very complicated (because of that, I nearby never use this search menue!

**Comment by mckillo** [comment]
@jojo12 test the last commit and tell me if it's OK.

**Comment by jojo12** [comment]
yes, my problem is solved but heklas not. todo!

**Comment by Heklaterriol** [comment]
> yes, my problem is solved but heklas not. todo!

fixed
