### ISSUE TITLE
Updateproblem from 4.2.2 to 4.3.0.b4

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1819]
I installed on a fresh Joomla 5.1.4 a JEM 4.2.2 with the jem_demo plugin. All worked well.
Then I tried to update 4.3.0.b4->following error:

> Warnung
> JInstaller: :Install: SQL-Fehler Duplicate column name 'seriesbooking'
> Die Installation der Erweiterung wurde gestoppt.
> Paket Update: Bei der Installation der Erweiterung trat ein Fehler auf: com_jem.zip

EDIT: The config info shows: only the JEM component has 4.3.0.b4, all others persist on 4.2.2

Question: Can this be a problem of the jem_demo_plugin? 
I disabled JEM_demo plugin, deleted all JEM contents, tried to install 4.3.0.b4 -->

> Warnung
> JInstaller: :Install: SQL-Fehler Duplicate entry 'recurrence_anticipation_day' for key 'PRIMARY'
> Die Installation der Erweiterung wurde gestoppt.
> Paket Update: Bei der Installation der Erweiterung trat ein Fehler auf: com_jem.zip

**Comment by Heklaterriol** [comment]
I can reproduce it with a clean installation of JEM 4.2.2  trying to update to 4.3.0.b4 (without jem_demo_plugin).

I'll check it tonight.

**Comment by Heklaterriol** [comment]
I haven't figured out yet, where the error comes from.
@mckillo could you check it.

**Comment by jojo12** [comment]
It would be good, if this could added inside. If not we will have a lot of question from those who aren't actual and who don't read the instructions!

**Comment by mckillo** [comment]
@Heklaterriol Error mine. The new checkColumnsIntoDatabase function is meant to fix the incorrect database update during the migration from v4.0.0 to v4.22. In this case, seriesbooking and singlebooking should not be in this array, as these changes are for version 4.2.3 and are included in the 4.2.3.sql file.
Check the commit above, fix it.

**Comment by jojo12** [comment]
I exchanged the 2 files in b4 and tried to install. No problems! Can be closed.
