### ISSUE TITLE
b5: 0 Class "Joomla\Plugin\Quickicon\Jem\Extension\Jem" not found 

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1821]
0 Class "Joomla\Plugin\Quickicon\Jem\Extension\Jem" not found 
EDIT

  | JROOT/plugins/quickicon/jem/services/provider.php:18

I have now both quickicon plugins. 

The one which gives error is "JEM - Quick Icon"

the other is working fine: "Schnellstart Icons - JEM"

**Comment by jojo12** [comment]
my solution: uninstall both quickicon plugins and reinstall the whole b5 package!

**Comment by mckillo** [comment]
If you uninstall 4.3.0.b4, it works too.
The migration of this plugin doesn't work.

**Comment by mckillo** [comment]
The name has been changed (from jemquickicon to jem). The update isn't activated during the package installation (dont' detect any jem plugin of type quickicon). I believe that in the postflight script, the new plugin is activated, but before that, the old plugin needs to be uninstalled.

**Comment by jojo12** [comment]
So it would be good to give this information to those versions which need this! Are this only the test versions?

**Comment by Heklaterriol** [comment]
Oh, thanks for reporting. That is strange. I tested it with the update form 4.2.2. and the celan install of JEM 4.3.0.b5 - it worked.
What did I miss?

**Comment by jojo12** [comment]
With a original 4.2.2 it works. But when you meanwhile had a dev or b version, then there is the problem.
So I think the normal user comes directly from 4.2.2

**Comment by Heklaterriol** [comment]
> With a original 4.2.2 it works. But when you meanwhile had a dev or b version, then there is the problem. So I think the normal user comes directly from 4.2.2

OK, thanks for the clarification. I think we can close the issue.
