### ISSUE TITLE
mod_jem_teaser (mod_jem_banner, mod_jem_jubilee) calendar colors missing. PLEASE: talk together!

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1822]
the calendar colors red, blue, green, orange are missing! 
in mod_jem_jubilee there's no calendar color "from category"
in mod_jem_teaser there's no "user-defined" color

**Comment by Heklaterriol** [comment]
The error was already there in 4.2.3-dev. 
It is located in the function `loadModuleStyleSheet`:
https://github.com/jemproject/JEM-Project/blob/1437a9412ee09732865717ae1bc9d3e934167a85/site/helpers/helper.php#L1414

**Comment by jojo12** [comment]
> The error was already there in 4.2.3-dev.
I didn't see that, then more things in jubilee were changed, I tried and found.
This isn't a reason to let it as it is now?

**Comment by Heklaterriol** [comment]
@mckillo What was the reason for changing the function?

**Comment by jojo12** [comment]
I like this new view.
But can we let the settings with no functions visible. We have to hide them or to give them back their functionality (colors)

**Comment by mckillo** [comment]
In any time, were these module color in the categories?

**Comment by Heklaterriol** [comment]
`modules/mod_jem_teaser/tmpl/red.css` is not loaded anymore.

<img width="723" alt="teaser" src="https://github.com/user-attachments/assets/dc21c04c-8818-4f77-a23b-0e5f4b553e03">

**Comment by mckillo** [comment]
Ok, thanks for comparation,  it help me to debug it.

**Comment by Heklaterriol** [comment]
I noticed that not all calendar images had correct transprency and the image soize did not fit the sizes set in the css. See commit above.

**Comment by jojo12** [comment]
I prefere as it is/was in b5:
![grafik](https://github.com/user-attachments/assets/b31e5172-da69-4e45-8140-29f41fa322ff)
but it mod_jem_teaser settings there is no "user-defined" as in mod_jem_banner
AND
in all modules (teaser, banner and jubilee) the predefined "red, blue, green, orange" are still "white"

(in my eyes the old calendar images could be in the "legacy" style, but not in the responsive)
Perhaps we  have to discuss!

**Comment by Heklaterriol** [comment]
Oh, I see mistake in my considerations. Thank you Jojo. My previous suggestion is not good.

So I will revert the changes and suggest one modification:
When an image is chosen, **then there is no background color** (not one from the settings nor the one from the category).
This way the transparent images are not surrounded by a strange color from the background.

**Comment by jojo12** [comment]
My question is: when there is a working "user-defined color" and the defined "red", "blue", "green", "orange" don't work, would it not be  better to disable this not working points?

**Comment by jojo12** [comment]
It's important to bring out 4.3.0 now! If you find it better to let things as they are, then we can fix it later. (so I remove the releaseblocker. )

**Comment by Heklaterriol** [comment]
I just reverted the code in the helper file to the previous state (before the bug). 
Now the previous bug is there again: in the teaser module both css file are loaded (table lyout and responsive layout).

**Comment by Heklaterriol** [comment]
I also added the light/dark font color adaptation to month, weekday and day number, when using the fallback color.

**Comment by Heklaterriol** [comment]
I created a new nightly: https://github.com/jemproject/JEM-Project/blob/JEM-4.2.3-dev/pkg_jem_4.3.0.b6.zip

**Comment by jojo12** [comment]
Fixed

**Comment by jojo12** [comment]
Sorry, within RC1 we lost this again!

**Comment by Heklaterriol** [comment]
I reverted the code to the old version, which worked, but it loaded the css files for both layouts (table and responsive).

@mckillo I guess you recovered your new code, but it doesn't load the color css files like
`/modules/mod_jem_teaser/tmpl/orange.css` or the others, according to the settings in the teaser module.

So it would be good to keep the new code and fix the issues with the missing color css

**Comment by Heklaterriol** [comment]
I just came across a simpler solution:
As the chosen colors are put in a class, like `calendar-green` etc. 

```
<div class="calendar-green" title="...">
    <div class="monthteaser">September</div>
    <div class="dayteaser">Dienstag</div>
    <div class="daynumteaser">24</div>
</div>
```
We catch the class there and do not need to load anextra css file.

We just put all the stiles in the regular mod_jem_teaser.css, in table css file
```
#jemmoduleteaser .calendar-blue {background-image: url(img/calendar_blue.png);}
#jemmoduleteaser .calendar-green {background-image: url(img/calendar_green.png);}
#jemmoduleteaser .calendar-orange {background-image: url(img/calendar_orange.png);}
#jemmoduleteaser .calendar-red {background-image: url(img/calendar_red.png);}
```
and in the responsive css
```
#jemmoduleteaser .calendar-blue {background-image: url(../img/calendar_blue.png);}
#jemmoduleteaser .calendar-green {background-image: url(../img/calendar_green.png);}
#jemmoduleteaser .calendar-orange {background-image: url(../img/calendar_orange.png);}
#jemmoduleteaser .calendar-red {background-image: url(../img/calendar_red.png);}

```
I will show you in the next commit.

**Comment by jojo12** [comment]
RC1(2): the categories calendar is a bit strange but I can accept. (old style)
            the color blue doesn't work!
           the user defined is congruent with the banner new calendar image style.

**Comment by Heklaterriol** [comment]
I added a claendar sheet to categories too and some other cosmetics, see the commit.

**Comment by mckillo** [comment]
Sorry, but I try to understand this issue. First, is this image right for you? For me, I don't see any wrong.

![image](https://github.com/user-attachments/assets/01c28d6f-5659-4430-9dd0-474a7dd0f453)

The alternative category color is yellow.

If it is good, I'll upload the commit.

**Comment by mckillo** [comment]
And if I apply the last commit of Hekla, the image is:

![image](https://github.com/user-attachments/assets/37a1ea8f-eef9-474e-a6c3-1c44afa62175)

**Comment by mckillo** [comment]
One proposal, more height for month and small center fo the text. For exaple:

![image](https://github.com/user-attachments/assets/a0568026-27f9-4425-a0ab-ab84a643983e)

If it's ok, I can upload the commit with png images (+8px in the header of calendar background).

**Comment by mckillo** [comment]
Sorry, restore the mod_jem_teaser, before I were centered text with the old background images.

**Comment by jojo12** [comment]
it  looks good: so the blue is solved, you can commit (in my eyes)

**Comment by mckillo** [comment]
@jojo12 Here you are.

**Comment by mckillo** [comment]
In module teaser wasn't shown the icons, and the code doesn't the ('color'.css), Now, show the icons and use the color css.

![image](https://github.com/user-attachments/assets/9c6060b0-c4ae-499f-943e-06205b7ce17d)

Apply the next commit

**Comment by mckillo** [comment]
Please when you have time, test it.

**Comment by jojo12** [comment]
I made a new package myself, because your commit was later than heklas RC2.
Installation worked, teaser looks good print eventlist with categories works. I' ve not much time to test more. Today I had a cold, so I slept often and long. For me it's ready.

**Comment by Heklaterriol** [comment]
I made some unifications in the calendar sheet look in mod_jem_teaser, mod_jem_banner, mod_jem_jubilee.
I also checked the text color shift according to the background color brightness.

Some weeks ago I added some improved and optimizes calendar images , but they are gone. As this is not so important, I just restored the css for the images as it was before.

**Comment by jojo12** [comment]
@ hekla: your unification is good, but you two are actually working against each other: @Mckillo had an other (better) proposal for calendar images.
In my eyes: the RC3 proposal in mod_jem_banner is better than that in mod_jem_teaser.
Please talk together! Find an accord!

**Comment by Heklaterriol** [comment]
Yes, we mixed it up somehow, sorry fotr that, I wasn't aware of it. My version is not in the images you posted.

I suggest to leave it now at it is in McKillos version.
I created a new branch to find a solution for `category color` and `user color`. I would like to have the possibility to use **any color**.
I will post my suggestion here, so we can discuss and improve.

**Comment by Heklaterriol** [comment]
I uploaded the test package, as I said, it works only in the **Banner Module in responsive layout**

**Comment by Heklaterriol** [comment]
We talked and everything seems ok :-)

**Comment by jojo12** [comment]
Ok I will test the RC4
