### ISSUE TITLE
Alert! Printing simplelist gives error! in b6 too!

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1825]
I don't know when someone changed here something!

Ein Fehler trat beim Update der Datenbank auf.                        
1 | () | JROOT/plugins/system/redirect/src/Extension/Redirect.php:247
2 | Joomla\Plugin\System\Redirect\Extension\Redirect->handleError() | JROOT/libraries/vendor/joomla/event/src/Dispatcher.php:454
3 | Joomla\Event\Dispatcher->dispatch() | JROOT/libraries/vendor/joomla/application/src/AbstractApplication.php:99
4 | Joomla\Application\AbstractApplication->dispatchEvent() | JROOT/libraries/src/Application/CMSApplication.php:334
5 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:58
6 | require_once() | JROOT/index.php:32

**Comment by jojo12** [comment]
I did not print, tested only until preview!
it's in responsive and legacy: in eventlist. in the rest menu items print preview is fine.

**Comment by jojo12** [comment]
This persist on saturday evening. not yet ready

**Comment by jojo12** [comment]
@heklaterriol: can you reproduce?

**Comment by Heklaterriol** [comment]
Yes, I can reproduce it.

**Comment by Heklaterriol** [comment]
the link is: `domain.tld/&print=1&tmpl=component&&tmpl=component` with a `&`
but should be the `domain.tld/?print=1&tmpl=component&&tmpl=component` with a `?`

**Comment by Heklaterriol** [comment]
I have a dirty fix, which works (it may be that there is a second "?" in the query string instead of "&".
I push it just to have a working solution until we find create a better solution

**Comment by mckillo** [comment]
Check the last commit to fix this error.

**Comment by jojo12** [comment]
I tested within RC1, it works (at least preview)  thanks. con be closed.
(I am in holydays now, can't test too much.

**Comment by mckillo** [comment]
@jojo12 Check that the issue is solved with this commit.

**Comment by jojo12** [comment]
yes, it is solved! thanks, can be closed
