### ISSUE TITLE
Alert! Ical button gives not that what it should!

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1826]
Ical button gives not that what it should!

**Comment by Heklaterriol** [comment]
Works fine here!
What is the problem you encounter?

**Comment by jojo12** [comment]
Normally it should give the events which are on the page of the button, but itdgives only two events.
(More important is the Print error!)

**Comment by Heklaterriol** [comment]
I cannot reproduce it.
On my site all events are there in the `events.ics` file …

How are your JEM settings in Global Parameters > Advanced Parameters >  Max ics Events  ?

**Comment by jojo12** [comment]
The setting is "100".
But perhaps I have a problem with the calendars.
