### ISSUE TITLE
Placeholder is hardcoded, would be better 

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1828]
the month search in eventslist is hardcoded, I propose 
`placeholder=<?php echo Text::_('COM_JEM_SEARCH_YYYY-MM'); ?>`

**Comment by Heklaterriol** [comment]
Isn't this the same in all languages?

**Comment by jojo12** [comment]
JJJJ-MM in german

**Comment by Heklaterriol** [comment]
> JJJJ-MM in german

ah, yes, of course :-)
