### ISSUE TITLE
eternal Error page after inserting invalid month search in simplelist

### ISSUE THREAD

**Issue by Heklaterriol** [jemproject/JEM-Project#1829]
In JEM simplelist if I enter a wrong month search format (not YYYY-MM), then I get an error and I cannot leave the error page anymore to reset the search field. Reloading the page doesn't help, only deleting the cookies in the browser allows to go back to the JEM Simplelist.

**Comment by jojo12** [comment]
I reproduced this error

**Comment by Heklaterriol** [comment]
I added a field validation as a first help action

**Comment by mckillo** [comment]
Work, this is better. Thanks.

If you want, you can be more explicit in the pattern:
`^(19[0-9]{2}|20[0-9]{2})-(0[1-9]|1[0-2])$`
From 1900-01 to 2199-12

This issue could be closed, one less.

**Comment by Heklaterriol** [comment]
In principle, yes.
But I would keep it this way and leave the responsibility of the date range to the visitor.
