### ISSUE TITLE
4.3.0.rc11

### ISSUE THREAD

**Issue by Heklaterriol** [jemproject/JEM-Project#1830]
I will upload 4.3.0.rc1.

The only releaseblocker is the print window #1825 (even though it is working now wi the dirty fix)

**Comment by mckillo** [comment]
Hekla the #1825 is solved, zip it again and we'll test rc1.

**Comment by mckillo** [comment]
I have found old code in components\com_jem\helpers\helper.php, I supppose a new commit was overwritte, so I need to review the change history of that file.

**Comment by mckillo** [comment]
Solved, this last commit recovered code from recent commit that was overwritten.
Go to new zip.

**Comment by Heklaterriol** [comment]
Woderful!
A new rc1 is uploaded

**Comment by jojo12** [comment]
see #1822 reopenedd

**Comment by Heklaterriol** [comment]
I fixed it, see new RC1 (sorry, still the same vesion number – I didin't want to put RC2 on it)

**Comment by Heklaterriol** [comment]
pkg_jem_4.3.0.rc3 with all recent changes is uploaded

**Comment by jojo12** [comment]
What is the newest one?

**Comment by Heklaterriol** [comment]
it is RC4:
https://github.com/jemproject/JEM-Project/blob/JEM-4.2.3-dev/pkg_jem_4.3.0.rc4.zip

Or RC4 with the calendar sheet redesign in the modules teaser, banner and jubilee:
https://github.com/jemproject/JEM-Project/blob/4.3.0-calendar-sheet/pkg_jem_4.3.0.rc4%20cal%20sheet.zip

**Comment by Heklaterriol** [comment]
4.3.0.rc8, the final RC version.

**Comment by jojo12** [comment]
Final countdown 01?

**Comment by Heklaterriol** [comment]
I created a branch "JEM-4.3.0-dev", since we left 4.2.3.
After releaseing JEM 4.3.0 I will merge "JEM-4.3.0-dev" into "master" and create the branch "JEM-4.3.1-dev"

**Comment by Heklaterriol** [comment]
I think JEM 4.3.0 is ready with the last achievement (SmartSearch plugin), which makes me really happy! 

Do you agree?

**Comment by jojo12** [comment]
Tested JEM 4.3.0 RC9+ on Joomla 5.2 RC4 final. Works fine!

**Comment by Pinkeltje** [comment]
Made another pull request, sorry didn't see this remark

> I created a branch "JEM-4.3.0-dev", since we left 4.2.3.

**Comment by Heklaterriol** [comment]
No problem, I keep them synchronized

**Comment by Heklaterriol** [comment]
I added the latest commits and created a (hopefully last) package 4.3.0.rc11: [pkg_jem_4.3.0.rc11.zip](https://github.com/jemproject/JEM-Project/blob/JEM-4.3.0-dev/pkg_jem_4.3.0.rc11.zip)

@jojo12 and @mckillo : Please check if ready to release

**Comment by jojo12** [comment]
ready to go!

**Comment by mckillo** [comment]
Sorry, I can't test it until saturday morning.

**Comment by Heklaterriol** [comment]
No Problem, thank you.

**Comment by Heklaterriol** [comment]
@mckillo  I included you 3 last commits. Is it ready according to you?

**Comment by jojo12** [comment]
For me too. 
Will be away until Wednesday!

**Comment by Heklaterriol** [comment]
OK, thanks.
I will create the JEM 4.3.0 package and create the new branches.
