### ISSUE TITLE
mod_jem_teaser: the width of event image and venue image in sidebar-light and sidebar-left is too big

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1831]
with both JEM settings flyer=yes and flyer=n0:

![grafik](https://github.com/user-attachments/assets/48dc8de1-f4d2-403b-b9d3-304180d28619)

my solution:
` imagewidth='auto';`

**Comment by jojo12** [comment]
This is not new, I saw it before RC1!

**Comment by Heklaterriol** [comment]
I cannot reproduce it.
In my case it depends on the settings in "Max. Height of Thumbnails" and "Max. Width of Thumbnails"

**Comment by jojo12** [comment]
Ok, when I want images in event and venue bigger, then I set these bigger, then it's good for eventdand venue details, but not in teaser.

**Comment by mckillo** [comment]
I have not been able to reproduce it, but if nothing needs to be done, then this issue can be closed.

**Comment by jojo12** [comment]
the following situation: The JEM settings are: max.imagefile size 2000, max. height of thumbnails 300, max. width of thumbnails 400, flyer= yes, layout table width=100% (tablelike style)
with that I get good and big eventimages and venueimages in details view. (I know there are people who want big event images in details view (not in simplelist)
But then in mod_jem_teaser the event and venueimages go over the size of the template! in banner you can handle that.
As I wrote above, I can fix it with adding imagewidth = 'auto';
But if noone else can reproduce this, it's ok.

**Comment by mckillo** [comment]
Send me the url of image in the begining by PM 
I want to use the same image file.

**Comment by jojo12** [comment]
I think, the problem is in the <style> of resonsive default.php

**Comment by mckillo** [comment]
I see the issue, and fix. This is teaser module with your setting in responsive layout:

![image](https://github.com/user-attachments/assets/103b64fa-52d0-4c56-9427-32ef3d91475d)

TEASER MODULE in TOP-A POSITION
![image](https://github.com/user-attachments/assets/0dc95c62-b8dc-4788-a469-33516e01c34e)

TEASER MODULE in SIDEBAR-RIGHT
![image](https://github.com/user-attachments/assets/304569b1-a557-4b2a-b98c-b3362724e63c)

Is right?

**Comment by mckillo** [comment]
I don't use Flyer, and I'm not sure if this module is correct, but I believe that this module doesn't use Flyer. Is that possible?

**Comment by mckillo** [comment]
Check this commit, I hope it resolves the issue.
