### ISSUE TITLE
Beautiful Calendar Sheets in all Colores in Teaser, Banner and Jubilee Modules

### ISSUE THREAD

**Issue by Heklaterriol** [jemproject/JEM-Project#1832]
I created a branch to do this: https://github.com/jemproject/JEM-Project/tree/4.3.0-calendar-sheet

I already worked on the **Banner Module in responsive layout**.
I'll post a test package in some minutes.

**Comment by Heklaterriol** [comment]
I uploaded the test package, as I said, it works only in the **Banner Module in responsive layout**

**Comment by mckillo** [comment]
I tested it with your lastest RC3 + lastest change in the branch, I like it. It works.

See my coment in:
https://github.com/jemproject/JEM-Project/commit/08bde7402e33427a23a7498b1247ec48fe2e6bc5

**Comment by Heklaterriol** [comment]
Thank you. I will apply it to the whole modules teaser, banner and jubilee.

**Comment by mckillo** [comment]
In the RC4 sheet, the jubilee module doesn't load the new style

![image](https://github.com/user-attachments/assets/316f1262-9cfa-41cb-889e-7e35e4fcecb7)

Banner & Teaser modules work.

**Comment by jojo12** [comment]
if background-color: var(--body-bg-color);
then you don't see the number of the day
![grafik](https://github.com/user-attachments/assets/c2e9957b-a7df-4d4a-b4df-f2fcc83dd68c)

**Comment by mckillo** [comment]
In this image, the month name must go down a little (in dark mode)

**Comment by Heklaterriol** [comment]
Thank you for your feedback. I will check it out in the afternoon.
If you want to make some fixes, please go ahead.

**Comment by Heklaterriol** [comment]
> In the RC4 sheet, the jubilee module doesn't load the new style

In my first version this was missing. It is added in the recent one.

**Comment by jojo12** [comment]
with ja_purity_IV: my simple solution for both dard and light is:
add e.g. mod_jem_teaser.css --> add color:black;

#jemmoduleteaser [class|="calendar"] .daynumteaser {
  font-weight: bold;
  position: relative;
  z-index: 2;
  display: block;
  padding: 0;
  text-align: center;
  color: black;

**Comment by Heklaterriol** [comment]
Acording to my tests with 4.3.0.RC6 it is finished.

**Comment by mckillo** [comment]
Thanks, I'll test it next weekend.

**Comment by mckillo** [comment]
Tested RC7, everything works.
 - Checked clean install.
 - Checked migration from 4.2.2
 - Checked recursive events
 - Checked loading al modules
 - Checked all view (review load, and string).
 - Checked new style of calendar icon in modules (good job).
 
 Some minor details:
 - The 'Changes' section in the Update Check view [BE] needs updating with GitHuib link for each point (update the XML file).
 - A new commit has been uploaded to fix the css file loading in the calendar module (See 01b4cf2d3551f8d189cbd349bfa995bbc1e13651, please include it in the final version)
 
**Goog job team, 476 commits. Guau!!**
For me, 4.3.0 is ready to be released. You can open the new JEM-4.3.1-dev branch  and we move on to the next release

**Comment by Heklaterriol** [comment]
it's done!

**Comment by Heklaterriol** [comment]
In jubilee the custom color is not taken for the calendar sheet, but only the fallback color.
I check it out.
