### ISSUE TITLE
CB user link in event registration

### ISSUE THREAD

**Issue by mckillo** [jemproject/JEM-Project#1834]
From forum https://www.joomlaeventmanager.net/kunena/jem-4-x-for-joomla-4-community-support/12753-cb-user-link-in-event-registration

![image](https://github.com/user-attachments/assets/aaafcea5-07a7-4166-9a42-474ac0744782)

The user link for CB is resolved with the following commit. Now, if the CB profile menu exists, the user link will direct to that CB profile menu.

**Comment by mckillo** [comment]
Fixed this issue in JEM 4.2.2/4.2.3(dev) with CB 2.9.3 on Joomla 5.1.4

**Comment by inLIMITit** [comment]
Hi mckillo, tested it also with Joomla 5.1.4 and Joomla 2.9.3 and the fix works! Thank you :)

**Comment by mckillo** [comment]
Thank you for reporting it and testing it. It is already included in the upconming version 4.3.0.
