### ISSUE TITLE
Nomenclature in the name of JEM plugins

### ISSUE THREAD

**Issue by mckillo** [jemproject/JEM-Project#1836]
![image](https://github.com/user-attachments/assets/7ff41385-f368-457b-a8c8-a550a21fcd05)

There are two names wrong:

'JEM LIst Events' should be changed to 'JEM - List Events'
'Smart Search - JEM' should be changed to 'JEM - Smart Search'.

So, all JEM plugins will have the same nomenclature of names.

**Comment by mckillo** [comment]
it's a minor details but I think it's better now.

![image](https://github.com/user-attachments/assets/2e429949-c4d7-49db-84ef-110c5bcf9f96)

**Comment by Heklaterriol** [comment]
Hi McKillo, it was me because of the nomenclatura of Joomla, which is "Smart Search - [extension name]" …
I didn't think about the conflict with the JEM nomenclatura.

![finder](https://github.com/user-attachments/assets/b5ef3db5-17a9-4405-8b50-4740f3a41099)

I haven't deceided yet, what I consider to be the better way.

**Comment by mckillo** [comment]
For me, I would delete 'plugin' from the name. It's redundant, as it's already defined as type in Joomla extension. 

![image](https://github.com/user-attachments/assets/d6b8242d-8d93-4563-874c-7193fe7e5e02)

Other extensions don't use it.

![image](https://github.com/user-attachments/assets/be3f0603-1b56-4ce5-9797-67567c7a5184)

![image](https://github.com/user-attachments/assets/65ff1e0d-54ff-402a-9b04-44f21856aecf)

![image](https://github.com/user-attachments/assets/e4f3a399-2402-4849-b7a3-0a0711e97a27)

![image](https://github.com/user-attachments/assets/eced647c-55a1-44d5-a94e-f99fb6e7bd23)

Regarding the nomenclature, in my opinion, Joomla's naming convention is for core extensions. Other extensions should first be defined by their name, as seen with Acymailing, Akeeba, Phoca, and Community Builder.

![image](https://github.com/user-attachments/assets/da61712c-ebc7-4ae2-81a1-5dc3f24b52e0)

Based on my personal experience, that admins first search for extensions by name, and secondly because it makes the extensions easier to locate. JEM is main keyword to find and Identify our extensions.  

My vote is for the last image: JEM in the begining and delete plugin at the end. I hope this explanation is helpful to you.

**Comment by Heklaterriol** [comment]
Thank you, @mckillo, I'm fine with your suggestion.
Let's do it this way.

**Comment by Heklaterriol** [comment]
An other thin in this issue: the names of the language files are not very nice:
 
![nomenclatura lang files](https://github.com/user-attachments/assets/7f813e2c-79ca-4140-8c70-f3c663864924)

I guess we have to fix this on transifex.

**Comment by Heklaterriol** [comment]
In fact it goes on with the names of modules
![jem mod](https://github.com/user-attachments/assets/dd3ccbb8-40c6-4252-81ce-3b8dff06277b)

Should we rename "JEM - Module Wide" to "JEM - Wide Module"? Would be consequent.

**Comment by mckillo** [comment]
I agree with you; I’ve already made that change in my proposal (see the previous image). Thanks.

**Comment by mckillo** [comment]
In that image, I mark two details more in two plugin.
![Screenshot_20241109-084037_Chrome.jpg](https://github.com/user-attachments/assets/1c1d02f1-34c7-40bb-85ba-73435bcf175a)

Add 'plugin' at the end, so all JEM plugins will have the same nomenclature too.

**Comment by Heklaterriol** [comment]
Why didn't you take all of them like:

<img src="https://github.com/user-attachments/assets/98de620f-b6be-42b6-a3fb-8180c54299ac" width=25% height=25%>

**Comment by mckillo** [comment]
I sent it as a proposal but I didn't it. If you want to change it. For me OK.

**Comment by Heklaterriol** [comment]
done

**Comment by mckillo** [comment]
Perfect. Onen less.
