### ISSUE TITLE
Error when trying to update

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1838]
![Screenshot_20241020-154626_Chrome](https://github.com/user-attachments/assets/4a39d00c-26b9-4d0c-9264-4d62a429866d)

**Comment by jobrusche** [comment]
Have the same problem: checksum error on the new 4.3.0 kit

**Comment by Heklaterriol** [comment]
Oh, did I mess it up again…?

**Comment by Heklaterriol** [comment]
fixed

**Comment by jobrusche** [comment]
Confirming fix is OK
