### ISSUE TITLE
Error: event registration from..until is always combined with "only invited users"

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1842]
If JEM general setting is "Allow invitation":
When the eventregistration is from...until, then the "only invited users" is always checked, if you try to uncheck, then after saving, it's checked again, and users can't registrate for event!
EDIT: this is in frontend in legacy and responsive style.
in backend there's no "invited users only" button.

**Comment by mckillo** [comment]
Review the registration process with or without user invited, and with combination of _registration_from_ and _registration_until.

![image](https://github.com/user-attachments/assets/cd3c9a59-3f86-45f6-959d-781404382e20)

Applied others fix and improvement.

@jojo12 When you have time, check it.

**Comment by jojo12** [comment]
I made a com_jem package and installed.
JEM general settings:
Registration>Allow event registration→Use event setting
Allow invitation→ Yes
Result: NOT SOLVED
After creating Testevent  in Backend, Result in Responsive Style:
![grafik](https://github.com/user-attachments/assets/d3da2a2e-820b-410d-a8b4-a497d07070f2)

**Comment by jojo12** [comment]
Before and after changing and saving in frontend editevent:
the "Invited users only" is always checked
with the consequence above: the user is not entitled to...
![grafik](https://github.com/user-attachments/assets/79c5f98c-168c-4b60-8137-4ee11e9ede88)

**Comment by jojo12** [comment]
the words are better!

**Comment by jojo12** [comment]
JEM general settings:
Registration>Allow event registration→Use event setting
Allow invitation→ NO
it works fine.

Question: Are I thinking wrong? 
I think, it should be possible, to invite some users AND to fix event registration from...until.
Does JEM general setting "Allow invitation"-> only invited users can participate?

**Comment by mckillo** [comment]
I think that the error was with Registration = Invited users only
![image](https://github.com/user-attachments/assets/d83f5448-52a8-4f39-9b0f-43711b3f1f59)

I don't know, I don't use JEM to invite users. I have had to see your image, ah, there is a option for it:
![image](https://github.com/user-attachments/assets/da03efaa-765a-4e3e-a409-c83d37c39e26)

But this option doesn't show to the admin int the setting, you need to set in JEM Global Setting - User control -Registration:
![image](https://github.com/user-attachments/assets/c5dd95f1-a157-49b8-a76b-6db894e69ca7)
By default, this option is set to 'NO' in a clean installation of JEM.

I think there are two options (cehckbox and combo): to limit registration to invited users only, and, on the other hand, to have this 'checkbox' field active by default. However, the code reads this setting from the 'reginvitedonly' field in the event table, which does not exist in the table structure. Additionally, the code saves this option as a 2 or 3 in the registra field of the same table.

I think that if this option for 'only invited users' have worked, it's pure lucky. What a mess, I suppose it's the result of inheritance changes and ideas of old JEM version.

**Comment by mckillo** [comment]
Here’s a possible solution, I'm going create a table with the combinations....give me a few minutes.

**Comment by mckillo** [comment]
![image](https://github.com/user-attachments/assets/3d02fcfa-783e-4594-b387-6e7ee11e3b04)

**Comment by mckillo** [comment]
In JEM 4.3.1 the _registra_ field in the _events_ table can have thes following values:
0: The event doesn't allow user registration.
1: The event allows registration the both users and invited users.
2: The event allows registration for users and invited user within a date range (from and until dates).
3: The event allows registration only for users invited by the admin.

**Comment by jojo12** [comment]
I agree

**Comment by mckillo** [comment]
![image](https://github.com/user-attachments/assets/f043a68c-16c8-457c-9d1f-bb43b0933780)

Now this option is active and this field exists in the events table.

**Comment by jojo12** [comment]
Installed - changed the db -
works fine -will test more- thanks

**Comment by jojo12** [comment]
it seems to work fine, but there is an error: "There are tables not up to date" and it shows JEM one problem
Database version 4.3.1
Manifest version ‎4.3.1.dev1

**Comment by mckillo** [comment]
This error occurs in the development environment when we are working with patches. I would need to see the zip file of your package, but I suspect a version in the XML file is out of sync.

Run the 4.3.1.sql script to ensure that all new fields in the event table are updated.
Joomla checks the database schema version against the latest SQL file.
When @hekla will create a first zip to 4.3.1, this issue should be fixed.

**Comment by mckillo** [comment]
If you give me the OK, merge this branch to 4.3.1-dev

**Comment by mckillo** [comment]
If you think this isn’t the issue, please send a capture with the error and send me de zip file. So, I can try to replicte it.

**Comment by jojo12** [comment]
I agree

**Comment by jojo12** [comment]
I think, with the last fix you did change back something: now the check for "only invited users" is back and always checked like before and the new button is lost ago. ???

**Comment by mckillo** [comment]
I've already seen it in the FE (only, BE no), when the reginvitedonly is 0 . Let's me debug it.

**Comment by mckillo** [comment]
Fixed.
When 'Invited users only' was active, if it was unset, the new status wasn’t saved in the database and it remained active all the time for this event. In new event, this option is unset by default.
See the commit above and test it.

**Comment by jojo12** [comment]
thanks. Please don't unfix it again :-)
