### ISSUE TITLE
Change: Event registration from...until -->would be better only date without time

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1843]
I think, it is much more userfriendly to use only date without time, it's my proposal.
That means the same like dates/enddates.

**Comment by mckillo** [comment]
I don’t understand the proposal. Previously, steps were set by hours (change it for int to float), but after the request was datetime (good, as Joomla). 

Now it’s organized (last commit in this branch) by datetime (step by seconds, which is the same as Joomla articles).

The suggestion is to move to a day-based step system. However, I’m not in favor of this change, as it causes JEM to lose granularity in these deadlines. I want to understand that the user will be able to set up these timeline fields, equal to what is done with the articles in Joomla. This isn't complex. It's only a scheduler calendar like alarm in the clock/phone.

**Comment by mckillo** [comment]
Now, in the afternoon, I'll see the issue above... and debug it.

**Comment by mckillo** [comment]
Issue #1842 has been resolved.

**Comment by Heklaterriol** [comment]
In my option it is better to have the time included.
For example if you want to close the registration 2hrs before the event …

**Comment by jojo12** [comment]
ok, I agree
