### ISSUE TITLE
Event register from...until -->is it possible to localize datetime format?  d.m.Y

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1846]
Event register from...until -->is it possible to localize datetime format?  d.m.Y
Would be better for other languages.

**Comment by mckillo** [comment]
![image](https://github.com/user-attachments/assets/11f50bfb-3dc6-4308-9675-2fe7937ee67a)
Like this?

**Comment by jojo12** [comment]
it works fine 
but
you need to replace in both files all "JHtml" to "HTMLHelper"

**Comment by mckillo** [comment]
I agree you, sorry, change it.

**Comment by Heklaterriol** [comment]
Thanks McKillo!
@jojo12 Did you test it?

**Comment by jojo12** [comment]
I tested, it works fine. Only problem is to find good and short german translation!

**Comment by jojo12** [comment]
[trans.zip](https://github.com/user-attachments/files/17646106/trans.zip)
corrected language files en-GB and de-DE

**Comment by mckillo** [comment]
For me Ok, I have updated the jem.ini for en-GB admin
Question:
Delete COM_JEM_EVENT_FIELD_REGISTRATION_UNTIL_POSTFIX in the code?
