### ISSUE TITLE
JEM 4.3.0 on J!4.4.9 ->Calendar menue can't move between month

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1847]
A problem from the Forum: this problem is only in J!4.4.9. We have some who persist on J!4.

**Comment by mckillo** [comment]
In Joomla 5, the icons are loaded using <i class="fa-solid fa-backward-step"></i>, which is compatible with Font Awesome v6. However, in Joomla 4.4.9, Font Awesome Free 5.15.4 is loaded, and this code doesn’t support v5 icons. Please update the JEM code to support the older version of icons (characters) in the calendar while displaying the new icons in Joomla 5.

The user only have to apply the commit to JEM 4.3.0.

**Comment by jojo12** [comment]
Is this an answer, we can give to users of 4.4.9 or a duty for us?

**Comment by mckillo** [comment]
The commit is the solution. The answer is the explication.
