### ISSUE TITLE
Recurrence and edit root icon don't display in the event view (FE) with Joomla 4

### ISSUE THREAD

**Issue by mckillo** [jemproject/JEM-Project#1848]
![image](https://github.com/user-attachments/assets/51961702-5475-4784-b2d9-e1901c6901e6)

The recurrence icon and edit root icon in the event view (FE) with Joomlal 4.4.9 and JEM 4.3.0.

**Comment by mckillo** [comment]
Latest commit: fixed the display of the recurrence and edit root icons in the event view (Joomla 4). The icons now reflect changes aligned with Joomla's Font Awesome version.

**Comment by jojo12** [comment]
My question: is it possible to create a fix?
Or do we have to create quickly a new package 4.3.1. The users of 4.9.9 can't wait a year for the next output!

**Comment by Heklaterriol** [comment]
seems to be fixed
