### ISSUE TITLE
Error on install 4.3.1 b1 over JEM4.3.0

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1850]
Warnung
JInstaller: :Install: SQL-Fehler Truncated incorrect seconds value: '5400000'
Die Installation der Erweiterung wurde gestoppt.
Paket Update: Bei der Installation der Erweiterung trat ein Fehler auf: com_jem.zip
![grafik](https://github.com/user-attachments/assets/8d75d940-9b60-4fca-91e4-e3b1319ec217)

**Comment by Heklaterriol** [comment]
I cannot reprodce the error.
Was it over a clean 4.3.0 installation, also with the originall 4.3.0 tables?

I have tested it with a clean installation of JEM 4.3.0. All files were deleted before and then recreated during the insallation.
Then I installed sample data and then I mad an update – no problem …

@mckillo : any idea?

**Comment by mckillo** [comment]
Before version 4.3.1 the `unregistra_until` field was defined as `int(11) NOT NULL DEFAULT '0'`
In JEM 4.3.1, this field changes to  `datetime DEFAULT NULL`. Therefore,  the 4.3.1.sql script run these lines to convert the initial integer value (hours save in second) to the new datetime format (Add comments to understand):

```
// This field can be a NULL
ALTER TABLE `#__jem_events` CHANGE `unregistra_until` `unregistra_until` INT(11) NULL DEFAULT '0'; 

// All value of this field = 0, update to NULL.
UPDATE `#__jem_events` SET unregistra_until = NULL WHERE unregistra_until = 0;

// Change the type to VARCHAR(20), now this values are a strings.
ALTER TABLE `#__jem_events` CHANGE `unregistra_until` `unregistra_until` VARCHAR(20) NULL;

// Avoid error when this fields has a value and the date and times of event don't have defined, in this case update to NULL
UPDATE `#__jem_events` SET unregistra_until = NULL WHERE unregistra_until != 0 AND times IS NULL OR dates IS NULL;

// Convert the string (hours) to string with date format
UPDATE `#__jem_events` SET unregistra_until = CONCAT(dates, ' ', TIME_FORMAT(SUBTIME(times, SEC_TO_TIME(unregistra_until * 3600)), '%H:%i:%s')) WHERE unregistra_until != 0 AND times IS NOT NULL AND dates IS NOT NULL;

// At the end, all values in this field should be NULL or string in date format. Change the type of this field to datetime.
ALTER TABLE `#__jem_events` CHANGE `unregistra_until` `unregistra_until` datetime DEFAULT NULL;
```

If there is a warning about the changes, what is the data type of this field, and what was the initial (integer) value before truncation? If the value is 5400000 seconds, this equates to 1500 hours. If the event has a specific date and times, this value must be converted to a datetime format. 
you can test the changes in this value by running each of these lines one by one and checking the results.

**Comment by mckillo** [comment]
I have mistake in the post previous, in JEM 4.0-4.2, the unregistra_until save the value in hours., and the max was 999
```

<field name="unregistra_until" type="number"
			size="4"
			class="inputbox"
			label="COM_JEM_EVENT_FIELD_ANNULATION_UNTIL"
			description="COM_JEM_EVENT_FIELD_ANNULATION_UNTIL_DESC"
			filter="integer"
			min="0"
			max="999"
			showon="unregistra:2"
		/>
```
Then, 5400000 is an incorrect value. The maximum should be 999. Additionally, 5400000 hours equals approximately 616 years, which seems to be the error — an incorrect initial value. Can be?

**Comment by mckillo** [comment]
During the development of the new feature, there was an initial release in the branch where the unregistra_until field was saved in seconds (initially, the plan was to store it in seconds, but later it was changed to a datetime field).

**Comment by Heklaterriol** [comment]
thanks. What is the solution?

**Comment by mckillo** [comment]
@jojo12 has to check the value in this field for the same event. 
I think in the events table, you have an event with an incorrect value that is causing the warning.
And that value was generated during one of the initial tests, converting 1500 hours into seconds, and it was saved. However, during a migration from JEM 4.2.0 or 4.3.0, those values were not applied.

**Comment by mckillo** [comment]
run `SELECT *  FROM `a8wlc_jem_events` WHERE `unregistra_until` IS NOT NULL AND `unregistra_until` != 0` to see the event with any value in this field.

**Comment by jojo12** [comment]
@mckillo:
This is not true:
I installed on a clean 4.3.0, which  never used to test new event registration!
This commit I always tested only local.

**Comment by mckillo** [comment]
Neither truth nor lie, it was just an assumption :-) Sorry if my English is interpreted in another way.

Remember that I have in front of an issuef, I try to reproduce it for debugging starts blindly, from a sentence, a question, an image, a data, or an error. I almost always have to assume situations, configurations, actions, and/or causes that could trigger it.

If it's a clean 4.3.0 version, then we are starting with the sample data, right? If that's the case, I can't reproduce it on my local branch, and it works for me. I haven't tested the latest Hekla zip (4.3.1.b1). I suppose it could be the sample data, I try to review when I have time. 

Can you send me the events table before migrating to 4.3.1.beta 1?"

**Comment by jojo12** [comment]
I'll send you the file with PM.

**Comment by jojo12** [comment]
I really don't know what I can do to update database structure. Before update in 4.3.0 all was ok. After update it always shows:
"There are tables not up to date".
I can change manually jem_events the unregistra_until. But when I then use the "update structure button", the old setting is back.

**Comment by jojo12** [comment]
The machanism works really fine, no errors. Only this db info is bad

**Comment by mckillo** [comment]
UPDATE `#__jem_events` SET unregistra_until = CONCAT(dates, ' ', TIME_FORMAT(SUBTIME(times, SEC_TO_TIME(unregistra_until * 3600)), '%H:%i:%s')) WHERE unregistra_until != 0 AND times IS NOT NULL AND dates IS NOT NULL;
This line had issues when unregistra_until contained large numbers. 
The latest commit resolves this, and now there are no warnings. Thanks to @jojo for reporting the issue and providing the table.

**Comment by mckillo** [comment]
![image](https://github.com/user-attachments/assets/c5879091-2588-4ce4-bdb3-53f0556d45e5)

Regarding the database structure, it’s normal when you’ve modified it with the 4.3.1.sql file. In the database, you’ll find that the schema for the JEM extension is version 4.3.1. Joomla compares with version in the pkg_jem.xml and detects changes that aren’t from 4.3.1 [<version>4.3.1.b1</version>], which is why you’re seeing this behavior, and when you restore, it reverts back to 4.3.0 (overwriting the changes), because doens't exist 4.3.1.b1.sql.

In @#__schemas, you’ll find the ID for the JEM extension, and in version_id you’ll have the schema version of the installed version. If you’ve installed 4.3.0, it will show 4.3.0; if you’ve installed 4.3.1.b1, it will show 4.3.1.

This should match the XML (manifest) copied locally, but it doesn’t because the version in the SQL file name is what’s applied to the schema, while the XML indicates another version, 4.3.1.b1. That’s why Joomla shows there’s an issue with the structure.

It’s a minor detail managed during development and synchronized when releasing the final version. I think, that it isn't necessary to create 4.3.1.b1.sql, ... when we have in dev version. Don't worry this it's solve in the final release 4.3.1 (in this case, all value are the same).

**Comment by jojo12** [comment]
ok, I studied your declarations and it's clear now!
