### ISSUE TITLE
Question: A special Registration only for Eventregistration as Enhancement

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1852]
In the Forum there was often the theme: 
Lots of JEM guests don't want to registrate into Joomla community, if they want only to registrate for an event. 
(But we need secure informations to know, there are no fake event registrations! (Captcha is only against machines)

A solution can be a special form e.g. Breezingforms or even Contact form, where guests have to give the necessary informations. 
An other solution is, to add a link to an other system which counts the participants and the free places.
But in this two ways, you can't use the JEM counts and event registrations

Is there a possibility with Joomla to create a special registration/login which makes a guest to a member of a special "JEM event user" group, with no more rights?
It would be good if this login would be inside JEM?

Is there a solution?

**Comment by mckillo** [comment]
So, if I understand correctly, you want a registration system without user identification, right? You don't want to identify the user; it would remain anonymous, correct? In that case, you'll need to provide the user with a code (a locator) that identifies their booking. In this case, JEM could create a locator (like a password) of reserve and display in the view (and user has to save this code in somewhere).

In Joomla, you need an email to create a registered user, but I don't think that's necessary in this case.

**Comment by jojo12** [comment]
No, I want to identify the user. I have to identify: I need at least email, name and firstname. I think with thatdI have enough to identify. 
But a lot of guests fear the joomla registration and they don't want more rights than what they need to event registrate. 
e.g. the small registration/login in kunena seems (it isn't!) for many users easier than the joomla registration/login.

**Comment by mckillo** [comment]
A posible draft:
![image](https://github.com/user-attachments/assets/18d05955-7916-40a6-ac8f-1b937fdc17a1)

**Comment by jojo12** [comment]
This essay looks interesting, but I think, it's better to  stop it.
