### ISSUE TITLE
4.3.0+ Alert: Userdefined fields can't be changed when event series

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1853]
I have an event with a userdefined custom event field.
I had to clean/change this content
I empty the content and save then (I tried in frontend and backen).
There's an info: Die Veranstaltung wurde erfolgreich in den folgenden Feldern bearbeitet custom1 [ID:331]
The old content persist.
(Backend and Frontend seem not to be congruent, too!)

EDIT:
This seems only to be in event series!

**Comment by jojo12** [comment]
Strange, I tried again: no problems! Sorry

**Comment by mckillo** [comment]
I can't reproduce the issue. I have used version 4.3.1-dev from both FE y BE, I have created, changed and deleted (custom field 1) and it works.
Any additional details?

**Comment by jojo12** [comment]
Created you an event series?

**Comment by mckillo** [comment]
Thanks for scenario, so, I have to debug it. Test the last commit.

**Comment by jojo12** [comment]
welldone! can be closed

**Comment by jojo12** [comment]
only thing is: that it is b4  (it's a typo!)
