### ISSUE TITLE
New Screenshots for extensions.joomla.org

### ISSUE THREAD

**Issue by Heklaterriol** [jemproject/JEM-Project#1857]
I just realized that the screenshots in the slider on the JEM page on extensions.joomla.org are really old.
I will create new ones.

For the state of the arts, see: https://extensions.joomla.org/extension/jem/

**Comment by Heklaterriol** [comment]
Are you fine with these ones?

![67349-JEM4](https://github.com/user-attachments/assets/626c9ab9-85c5-49c6-92a6-8e2375d16182)

![67351-JEM4](https://github.com/user-attachments/assets/34ec935d-fa22-498a-bbd3-8446b10f6c4d)

![67350-JEM4](https://github.com/user-attachments/assets/272f7037-14d0-47ad-90b0-63eead65686b)

![67353-JEM4](https://github.com/user-attachments/assets/6d379261-5279-49c4-a396-f55af36b0878)

![calendar - JEM4](https://github.com/user-attachments/assets/97709a4e-cf3e-48ed-8d67-4ec0cff56693)

![search - JEM4](https://github.com/user-attachments/assets/73c2d6ce-f9d6-4454-9f64-45f37e4d1ca0)

![simplelist - JEM4](https://github.com/user-attachments/assets/c8c8c720-9171-4448-ab56-41598b110e77)

![registration - JEM4](https://github.com/user-attachments/assets/071f595f-c4f3-4c5c-b855-be403bfb6941)

![modules - JEM4](https://github.com/user-attachments/assets/18810fbe-cf99-4f3d-a3c4-acecd3ec7662)

**Comment by jojo12** [comment]
What's the difference?

**Comment by ernst67** [comment]
@Heklaterriol :
Sorry, I did have a look last weekand forgot to reply. I'm fine with these... Will put them on JED today!

**Comment by Heklaterriol** [comment]
Wonderful thank you. And there was no hurry, I just wanted to be sure, that you see them!

**Comment by Heklaterriol** [comment]
Thanks @ernst67 for putting them online
