### ISSUE TITLE
Sometimes the map flyer shows the whole world,  after refreshing the page the right map is visible

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1863]
I think, it's not possible to change this!
Perhaps it would be good to have a hint, to refresh the page!

**Comment by Heklaterriol** [comment]
Yes, I can reproduce it, but it seems random. 
When reloading then it is always correct/zoomed in to the location

**Comment by Heklaterriol** [comment]
@jojo12 can you check out, if in this package the problem is solved:
https://github.com/jemproject/JEM-Project/commit/c6fea65c2485fa828a26b017575936238b3be48a

**Comment by jojo12** [comment]
I first tested the v1. This worked but I had the impression, that it changed the map settings to google map.
I tested now the v2 and this works fine. 
Can you commit it to the bugfix, please.
(I have problems to know, what I should test and how I can test them together)

**Comment by Heklaterriol** [comment]
It's actually just a trick in tow steps:
1) Since the maps are displayed correctly after reloading, I trigger a reload of the content of the iframe and 2) the css only slowly fades in the map so that the flickering of the reload is not visible.
