### ISSUE TITLE
4.3.1error: lightbox of event image and venue image is not anymore visible

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1865]
in forum from pinkeltje
JEM general settings: thumbnails=yes, lightbox=yes, flyer=no
mouse over image shows hand, but clicking on it, gives only some dark

**Comment by mckillo** [comment]
We don't use jquery, right?

**Comment by mckillo** [comment]
The lightbox call to jquery, and I think that could be the problem. It will try to check it this weelend.

**Comment by jojo12** [comment]
a hint/question: in the modules (banner) there may be used a lightbox too. It shows the image (may be not bigger, but it shows!)

**Comment by Heklaterriol** [comment]
I updated lightbox.min.css to v2.11.5, see https://github.com/lokesh/lightbox2

Now it works again
