### ISSUE TITLE
Adapt Joomla radio buttons style to JEM settings radio buttons

### ISSUE THREAD

**Issue by Heklaterriol** [jemproject/JEM-Project#1866]
When working on  #1861 I noticed, that the JEM setting readiobutton styling is very wide and not like in the Joomla settings.

So I propose to switch them to the Joomla styling:

JEM style:
![settings previous](https://github.com/user-attachments/assets/49243be9-49a9-4da1-84e1-a007d8df9ba5)

Joomla style:
![settings new](https://github.com/user-attachments/assets/8a6420e3-aa98-4615-a240-a15c846090cd)

There is one minro point: when set to "No" or "Hide" the button is just grey and not red

**Any objections to adjusting it to the Joomla settings style?**

**Comment by jojo12** [comment]
I agree to the Joomla settings style!

**Comment by mckillo** [comment]
I agree too.

**Comment by Heklaterriol** [comment]
After some experiments I have a new suggestion: just make the buttons smaller:
![radio-buttons](https://github.com/user-attachments/assets/836577f5-7e6d-4089-8bcb-d64d470f468f)

**Comment by jojo12** [comment]
I like it, well done!
