### ISSUE TITLE
4.3.1 warning, eventedit when adding image and when general JEM settings: thumbnails aktivieren=no AND flyer=no

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1867]
I wanted to add an image in eventedit, I got this:
Warning: getimagesize(images/jem/events/small/testbild_1_1432686910.jpg): Failed to open stream: No such file or directory in mysite.ch/components/com_jem/classes/output.class.php on line 1229

I tried, this comes, when activate thumbnails = no AND flyer=no

It's not so tragic, because normally you use or thumbnails or flyer, but perhaps would be better to inform

**Comment by Heklaterriol** [comment]
I cannot reproduce it.
And warning is not necessarily a bug.
