### ISSUE TITLE
 Error when clicking on archive button in venue view

### ISSUE THREAD

**Issue by Heklaterriol** [jemproject/JEM-Project#1873]
Similar to issue #1872 
When I click on the archive button in the venue view, let's say on the page: https://domain.tld/events/venue/1:douala, I get an error
`404 View not found [name, type, prefix]: venue-calendar, html, jemView`
The incorrect link is:
https://domain.tld/events/venue-calendar?id=1:douala&task=archive&filter_reset=1
the following link would work:
https://j5.datenablage.info/o/venue?id=1:douala&task=archive&filter_reset=1

**Comment by Heklaterriol** [comment]
The fix seems to be easily done.

**Comment by mckillo** [comment]
Doesn't work. If you go to the venue view and click the Archive button, then navigate to the venue-calendar view (layout), the right view incorrectly displays the venue view with archived events. See next commit (fix it)

**Comment by jojo12** [comment]
fine, can be closed
