### ISSUE TITLE
warning in category-calendar after the fix for category - archive

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#1875]
(Tested in Responsive) , I get:
Warning: Undefined variable $archive_link in /home/folktanz/public_html/components/com_jem/views/category/view.html.php on line 150

**Comment by mckillo** [comment]
Check it, it should be solve it.

**Comment by mckillo** [comment]
Sorry, forget to upload some lines... check the last commit.

**Comment by jojo12** [comment]
Now there is no more the archived events in the calendar, even with setting "show archived events =yes"

**Comment by jojo12** [comment]
I tried last commit, but it doesn't show archived events in category-calendar!

**Comment by mckillo** [comment]
Do you have commit a87b1669f5e6f06462a5f0b15813447e10b6094d?

**Comment by jojo12** [comment]
Yes, and retried with cache cleaning before, doesn't show archived events in category calendar.

oops and retried category-archive in responsive: shows now venue_archive!!!

**Comment by mckillo** [comment]
Sorry, call other route. See the last commit.

**Comment by jojo12** [comment]
category - archive is back, thanks, 
but category - calendar doesn't show archived events in calendar!

**Comment by mckillo** [comment]
No calendars have an archive icon (top right corner). In the code, there is no code about it. 
This is for dev (new feature for calendars).
You can see the archive events in the calendar, if you set 'Show archived events' in the menu setting.

**Comment by jojo12** [comment]
this is not true: at least the general calendar has this and the option is in menu settings!

**Comment by jojo12** [comment]
> You can see the archive events in the calendar, if you set 'Show archived events' in the menu setting.

No, event when this setting is yes, you can't see archived events in the category - calendar-

It is possible, that this was made only in calendar and not in category - calendar. (even if the setting is in the menu)

**Comment by mckillo** [comment]
Sorry bit I don't agree, this option un menú setting was dev by me months ago. JEM has haved the archive icon in the top-right  for the calendar views. There isn't $archive_link un the code of these views.

**Comment by jojo12** [comment]
I think there is a misunderstanding: there are two different things: 
1) archive button top right with link to archive
2) menue setting to show archived events in calendar

The calendar views don't need (absolutely NOT) an archive button top right!
The general JEM calendar (menue) shows archived events when "show archived events=yes"
(I am not sure, but it could be a new feature, to show archived events in the other calendars too (venue calendar, category calendar, week calendar). It seems, this is prepared, because there is a menue setting "show archived events=" too.

**Comment by jojo12** [comment]
So I would say, the warning is away. The problem is solved.
