### ISSUE TITLE
Hide the icons in the sorting menu (eventlist view)

### ISSUE THREAD

**Issue by mckillo** [jemproject/JEM-Project#1876]
New option menu in the eventlist view to hide the icon in the sorting menu.

![image](https://github.com/user-attachments/assets/548e6e3d-35d9-418d-aac1-3abe131c3d62)

**Comment by mckillo** [comment]
Now in Legacy layout, the event list view shows the icon too, when this new options is YES.

![image](https://github.com/user-attachments/assets/6edc50cf-f1d5-416a-a59d-e27f1f0da702)

See last commit

**Comment by mckillo** [comment]
Add new options for the icons in title and event data

![image](https://github.com/user-attachments/assets/b99dcc76-95ab-497d-a27c-5f31d55d9243)

**Comment by jojo12** [comment]
This is only for legacy!?

**Comment by mckillo** [comment]
For responsive too

**Comment by jojo12** [comment]
I tried the menue setting is there but no changes in the view.

**Comment by mckillo** [comment]
This new feature is all changes of this branch.

**Comment by jojo12** [comment]
Aah, I know now: we forgot that responsive has 2 different layouts: default_jem_eventlist.php and default_jem_eventlist_small.php!
and you only adapted the one (default_jem_eventlist.php =tablelike look). 
That can be discussed: if the modern look (default_jem_eventlist_small.php) should have this possibility too or not.

**Comment by Heklaterriol** [comment]
cool, thank you!

**Comment by mckillo** [comment]
Yes, I can update it too, I'll try to find a time windows to do it.

**Comment by jojo12** [comment]
So you forgot it or you decided,  that this will not be needed? We can discuss!

**Comment by mckillo** [comment]
Here you are, I haven't test it, please if you can.
If you want this commit 49a0514036b48185a6dc54689c33faeb465618d7 has the indexed lines for this file.

**Comment by jojo12** [comment]
It seems, that there are some  "else" , when there is no e.g. county, so it writes "-", but with the icon!

**Comment by mckillo** [comment]
Solved, when the layout has defined a % in the table, use the small layout.

With Show Icons in event data = NO:

![image](https://github.com/user-attachments/assets/7452d422-2cdb-4d51-8854-4c53b7a34df8)

With Show Icons in event data = YES:

![image](https://github.com/user-attachments/assets/e8e5b598-b8d6-4a1b-a663-a41ec2246f38)

**Comment by jojo12** [comment]
fine, can be closed
