### ISSUE TITLE
Module's Basic and Wide the Date Format is not working as expected.

### ISSUE THREAD

**Issue by neyworg** [jemproject/JEM-Project#216]
Per
http://php.net/manual/en/function.date.php formats.

On the JEM component settings:
I use D, M d Y for my Format date
I expect:
Tue, Jul 09 2013

In the modules:
If I try to use D, M d Y in the modules I get
D, M d Y

if I try using
%D, %M %d %Y
I get
07/09/13, 00 09 2013

**Comment by Heklaterriol** [comment]
Date/time formatting works in JEM4
