### ISSUE TITLE
Different URL values in modules

### ISSUE THREAD

**Issue by neyworg** [jemproject/JEM-Project#241]
Recently broken

URLs generated in modules are returning different values depending on if you are viewing a JEM related menu item or not

Example (Non-JEM) menu'd page
http://www.localhost.com/component/jem/event/1-this-is-my-event

Example (JEM) menu'd page
http://www.localhost.com/events/event/1-this-is-my-event

**Comment by mckillo** [comment]
Closed. This issue is older and I think that don't apply in the current JEM 4 version.
