### ISSUE TITLE
Ordering/sorting the same when menu-item is linking to same view

### ISSUE THREAD

**Issue by JKoelman** [jemproject/JEM-Project#521]
What i meant is:
- create two links to Eventslist and you'll see that the limitbox/sorting/search is the same

Wouldn't call it as a bug but it needs to change.

**Comment by mckillo** [comment]
Two months ago, an user in the forum request the posibility to have initial orden of eventlist view.
I found this old issue in Github with the beginig of code about it.

Today, I have improved these features, now from the eventlist menu link you can customize the type of field to be sorted (Date, Title, Venue, City, State, Category) and the direction of said order (ASC, DESC)

![jem_eventlist_menu-options_order_table_front](https://github.com/jemproject/JEM-Project/assets/2765316/5173c04a-5957-4c45-a361-7bfe5ac2df97)

The steps is easy, the JEM admin creates a new menu of JEM Eventlist, and in the Options tab select two new fields:
Sort table by 
Order direction

The first time the eventlist view is displayed, the table is sorted according to the settings of the created menu item.
If the user clicks on the table header to do another sorting (field and address), this option remains on page refreshes (without logging out, that is, without closing the browser).

See the commit below for the next version of JEM (4.2.1)
