### ISSUE TITLE
Mailplugin + link to event  (send when added/edited)

### ISSUE THREAD

**Issue by JKoelman** [jemproject/JEM-Project#552]
Did see that adding events in the backend is also triggering the mailer.

The problem with that can be that's somewhat annoying as you probably want to split it up. Mail when edited from the front and not from back.  

But the thing with it is that a link is being send pointing to the admin-site. It makes sence as JURI base is being used. But well better to use Juri root.

maybe it has been changed it meanwhile but will take a better look later.

**Comment by Hoffi1** [comment]
If adding/removing attendees on backend an email is sent. So we need to change ```JUri::base()``` to ```JUri::root()``` as @JKoelman suggested.
