### ISSUE TITLE
editevent: "send email to attendees" option

### ISSUE THREAD

**Issue by Hoffi1** [jemproject/JEM-Project#595]
If an event with attendees is edited there should be an (pre-selected) option to automatically send an email to all attendees.
In case mail plugin is disabled user should be informed instead that there are uninformed attendees.

Don't know if this is possible in backend too. Maybe we should document to edit events (relevant data) in frontend only.

**Comment by mckillo** [comment]
The mailer plugin already shows a message to the admin when there is any change to an event.
There is no further information.
