### ISSUE TITLE
settings ELimport/JEM version < 1.9.5

### ISSUE THREAD

**Issue by JKoelman** [jemproject/JEM-Project#612]
with JEM 1.9.5 some of the settings are moved to the attribs field and are linked in the front. But previous version didn't had that and Eventlist is also different.

so am wondering if we should consider, in case of an upgrade, to take the params-settings filled in the previous versions and fill that in the params field or should we make a notice that people have to visit the settings in the backend?

**Comment by mckillo** [comment]
This issue is old and doesn't apply to the current vesion.
The import and export process in JEM was reviewed for the migration from JEM 3.x to 4.x and it's working fine.
