### ISSUE TITLE
how to show different image width for eventview and flyer in eventslist

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#687]
How is it possible to use different width for images in eventview and eventlistview?
This was a post in feature request. This could be good, perhaps with a possibility to choose.
I don't know if this is much work or easy to create (e.g. in a override) but I don't know how.

**Comment by JKoelman** [comment]
hmm, maybe something that can be to add additional options.

we do have a thumb+orginal but what if we:
- add an option to set width/height for a table image
- add an option to set width/height of event-view image

when an image is viewed in the front by visiting the tables or event-view the image is created.
when viewing a table we pass 'table' to the imgcreator and when in eventview an 'event'.
- both created images are being stored in the thumb folder with name of the file+selected sizes.

**Comment by Hoffi1** [comment]
Sounds good, but maybe it's more flexible (also related to modules) to give creator function params for width and height directly? Or a string which can be 'large', 'small', '40x30' where the first two refer to global settings but the third allows free width and height values. So the decision is inside the views and can be overridden if needed.

Additionally if user changes one of the width/height settings in JEM config all files corresponding to old setting should be deleted. This will reduce disk space and in worst case (user mistake) files will be recreated on demand.
