### ISSUE TITLE
Replacing in postSaveHook JModel with JModelLegacy

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#690]
In the post
"postSaveHook with type hinting on J3.x "
it's said that we can (should) replace JModel with JModelLegacy
in site/controllers/event.php and venue.php
This is good for both versions (J3 and J2.5)
It this is true, then we should do it!

**Comment by Hoffi1** [comment]
For JEM 2.1 it's "fixed" so I will close it.
@JKoelman: If this is relevant for JEM 3 please make an issue there.
