### ISSUE TITLE
Filtering by (end)date in admin bug

### ISSUE THREAD

**Issue by stimpsonjcat** [jemproject/JEM-Project#719]
When setting date filers in the listview of events, the end date doesn't filter correctly. Startdate works fine, but entering an enddate, filtering actes strange.

**Comment by mckillo** [comment]
At the time, there was a commit, and recently the JEM 4.2.x had a commit to resolve an issue with date filter, which was solved.
Now, JEM 4.2.2 and the upcoming JEM 4.3.0 haven't this issue with the date filter. 
This old issue is closed.
