### ISSUE TITLE
calendar: event+multi-cat,special rights -> event-view has problems

### ISSUE THREAD

**Issue by JKoelman** [jemproject/JEM-Project#725]
The following:
- create 2 categories (1 public, 1 special)
- create event + assing to both category's
- create menu-item calendar
- point to the category that ain't public
- visit the front but don't login
- view the calendar
- the event will show up but when clicking at it the user will be prompted that he has no access

the reason is that it check for the show unauthorized setting that can be set in the back. hmm, maybe better to remove it completely.  but enabling does not show up the event this as the "special" category probably overrides the other category's.

so here we  also have to move the category code out the Query to a seperate function. The layout-raw probably needs to be addressed too...

**Comment by mckillo** [comment]
Closed. This issue is older and the case of use is complex, because the event is public by one categoy..
