### ISSUE TITLE
Implement Updater using J2.5 Update Interface

### ISSUE THREAD

**Issue by diesl** [jemproject/JEM-Project#77]
J2.5 has an update checker already integrated. Use it to check for updates instead of the Eventlist update checker which is broken right now: 

Class 'Snoopy' not found in .\administrator\components\com_jem\models\updatecheck.php on line 68

**Comment by ernst67** [comment]
This has now become essential for the next version, if we want to keep our listing at JED.

Please do not implement Github as the updateserver..... We will loose statistics!

**Comment by Heklaterriol** [comment]
Update via joomla updater works in JEM 2.3.6 and also in JEM4
