### ISSUE TITLE
Importing very big collections aborts without hint

### ISSUE THREAD

**Issue by Hoffi1** [jemproject/JEM-Project#775]
I tried to import 10,000 venues (~13MByte). After a while I was redirected to admin's home (Joomla dash board) without any information about the cause.
The redirect is not the surprise but some info should be shown. So I don't know why import failed.

**Comment by mckillo** [comment]
Closed. This issue is older and doesn't apply in current JEM version. Don't have any limitations in JEM 4 to import. Review and change the upload_max_filesize and post_max_size directives in PHP.
