### ISSUE TITLE
JEM 2.0.0: recurrence + (image - fixed in 2.0.1) / attachment

### ISSUE THREAD

**Issue by Hoffi1** [jemproject/JEM-Project#817]
When creating (tried in frontend) a new event with recurrence there are problems with image and attachments:
- image is correctly uploaded and attached to all events but user will get an error message for each except the first created event that the image is not an image - this message should not be shown
- attachments are uploaded and attached correctly but only to the first event - it should be attached to all events of this series

**Comment by mckillo** [comment]
Closed. This issue is older and doesn't apply in current JEM version. Don't have any error with image in recurrence event in JEM 4.
