### ISSUE TITLE
JEM 2.1: Can't go back to 1st page of lists on J! 3.3 frontend

### ISSUE THREAD

**Issue by Hoffi1** [jemproject/JEM-Project#841]
Seems pagination has changed. On J! 2.5 buttons to reach first page have ```limitstart=0``` but on J! 3.3 they have nothings. Fixing this maybe difficult because then we always jump to first page, also when changing count, sorting, filter etc.

Also I realised that on backend only first page is shown, no navigation possible.
Not sure if that's advance of J! 3 to split pages into 1st for backend and all others for frontend...

**Comment by Hoffi1** [comment]
Because the milestone of the fix on Joomla! site has changed from 3.3.7 to 3.4.0 I decided to implement a workaround in all list views affected by this Joomla! bug.
The models now work with or without "limitstart=0" in the request.
Hint: Relates to Joomla! 3.3.4, 3.3.5, 3.3.6 (latest version yet).

**Comment by Hoffi1** [comment]
Hm... this has a little side effect:

If users enters the list view again (e.g. via menu item or breadcrumbs) it will always show the first page.
On previous versions the page last shown was shown again.

For all Joomla versions removing limitstart is no other solution. It will always start on first page.
But for all other versions incl. 3.4.0 we could provide the original behavior - until it will be removed again, nobody knows...

**Comment by JKoelman** [comment]
guess it has to with the userstate then but think it's indeed better to show first page.

**Comment by Hoffi1** [comment]
Yes it has. Previously ```getUserStateFromRequest()``` had returned 0 if limitstart was present or the stored value otherwise. Now limitstart is never present so the decision is impossible.

But in the meantime I also think so, showing first page is better in most cases (except the breadcrumbs we have no real "go back" button).
So it can be as is.
