### ISSUE TITLE
JEM2.1: error notices in eventslist

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#843]
in my JEM 3.3.6 with JEM2.0.2 I updated to JEM 2.1 from jem21-dev
installation ok. 
error reports on development:
now in eventslist:

above the table:
Notice: Undefined property: stdClass::$showstate in .../components/com_jem/views/eventslist/view.html.php on line 145

inside of the table
Notice: Undefined property: stdClass::$showstate in .../components/com_jem/common/views/tmpl/default_events_table.php on line 62

Notice: Undefined property: stdClass::$showstate in .../components/com_jem/common/views/tmpl/default_events_table.php on line 88
and a lot of
Notice: Undefined property: stdClass::$showstate in .../components/com_jem/common/views/tmpl/default_events_table.php on line 162

**Comment by Hoffi1** [comment]
I've never seen this until now. Is it gone and never returned, @jojo12?
Can we close it?
