### ISSUE TITLE
JEM 2.1: strange: $discatheader was lost in db

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#847]
strange and for me unknown reason: discatheader was lost in db.
like the last time. After new creating this in db jem_settings the error notice is away. 
EDIT:
This was after the long way upgrading an J2.5.27 site to J3.3.4 with JEM2.0.2 installed.
Then installing JEM2.1dev over this.
Now I finished this experiment. I  uninstalled JEM and cleaned the db. Then reinstalled JEM2.1dev.
Now such problems seems away.
Before uninstalling I exported the CSV files. And after reinstalling I imported the CSV files. All ok.

**Comment by Hoffi1** [comment]
Think this can be closed.
