### ISSUE TITLE
jemquickicon should be adapted

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#870]
for having an icon in Joomla 3 too,
in jemquickicon.php there should be (about line 35):

		if (version_compare(JVERSION, '3.0', '>')) {
			$image = 'calendar';
		} else {
			$image = JURI::base().'../media/com_jem/images/icon-48-home.png';
		}
		return array(
			array(
			'link' => 'index.php?option=com_jem',
			'image' => $image,
			'text' => $text,
			'id' => 'plg_quickicon_jemquickicon'

is this right?

**Comment by Hoffi1** [comment]
Thanks Jojo, I must confess that I not tried it on J! 3.x yet.
Will take a look today evening...

**Comment by jojo12** [comment]
super! did look to other quickicon plugins. But kunena is really good for all versions: I tried with hathor and isis on J3. Thanks. It was indeed only a little thing, but it's much better now.
