### ISSUE TITLE
Error notice in JEM 2.1.0 when clicking on choose event in  choosing menu "single event"

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#872]
Hi, in Joomla 3.3.6 (php5.3.29) and updated JEM 2.1.0 I wanted a menuitem "single event" and got the following error notice:
1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'GROUP BY a.id ORDER BY a.dates , a.dates LIMIT 0, 100' at line 1 SQL=SELECT a.*, loc.venue, loc.city,c.catname FROM ntshl_jem_events AS a LEFT JOIN ntshl_jem_venues AS loc ON loc.id = a.locid LEFT JOIN ntshl_jem_cats_event_relations AS rel ON rel.itemid = a.id LEFT JOIN ntshl_jem_categories AS c ON c.id = rel.catid WHERE ((a.published IN (1))) AND ( c.published = 1) AND ( c.access IN (1,1,2,3,5) GROUP BY a.id ORDER BY a.dates , a.dates LIMIT 0, 100 

EDIT:
I tried the same in Joomla 3.3.6 (php5.4.35) with JEM 2.1.0 and got the same error notice!

**Comment by Hoffi1** [comment]
Oops - there is a ')' missed just before "GROUP BY"

**Comment by jojo12** [comment]
in which file I can find this typo?

**Comment by Hoffi1** [comment]
I think it's in admin/models/eventelement.php(229):
```$where = ( count( $where ) ? ' WHERE (' . implode( ') AND (', $where ) : ')' );```
should be
```$where = ( count( $where ) ? ' WHERE (' . implode( ') AND (', $where ) . ')' : '' );```

**Comment by Hoffi1** [comment]
Hm... normally I don't like the way you suggest - but a complete new release for this one line...
I don't know where this model is involved, if there are more views which will not work - maybe @JKoelman knows?

Regardless, I can't test or create a new package before today evening.

**Comment by ernst67** [comment]
Do you want me to take 2.1.0 offline for now?
Is it a lot of work to create 2.1.1? (tonight I mean)

**Comment by Hoffi1** [comment]
@ernst67: Because it isn't promoted on JED now this could be an idea.
The work itself is something around one hour + testing. So would say something around 7..9 PM CET (Berlin).

**Comment by Hoffi1** [comment]
Another idea would be to add a section "Known issues" on Download page and describe that (rarely used) Single event menu item can't be created in JEM 2.1.0 which will be fixed in JEM 2.1.1. If this is the only thing which will not work.

**Comment by jojo12** [comment]
You surely know, I tried your proposal some posts ago. And like that the error is away: I get the list of events I can choose. Thanks.

**Comment by Hoffi1** [comment]
Thanks @jojo12. The only thing I don't know if this was the only view having problems with this bug.
But for sure I will commit the fix and 2.1.1 preparation today evening - regardless when we release 2.1.1.
Got no feedback from @ernst67 so not sure what we decided...

**Comment by ernst67** [comment]
Sorry @Hoffi1, forgot I had to respond.
I would prefer to release a new pack, because a 'known error' warning will be easily ignored.

I will be driving back to Amsterdam tonight, but can upload a new version after about 23:00 (CET)

**Comment by Hoffi1** [comment]
Ok, then I have two additional hours to fix something more... :grinning:
