### ISSUE TITLE
problem with jcomments plugin

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#875]
I tried to reproduce a problem with the avatars of attendees. I added attendees in the backend and went then to see the event in the frontend. With development error notice I got the following notices:

Warning: require_once(/srv/www/vhosts/mysite.ch/httpdocs/includes/application.php): failed to open stream: No such file or directory in /srv/www/vhosts/mysite.ch/httpdocs/components/com_jcomments/plugins/com_jem.plugin.php on line 31

Fatal error: require_once(): Failed opening required '/srv/www/vhosts/mysite.ch/httpdocs/includes/application.php' (include_path='.:') in /srv/www/vhosts/mysite.ch/httpdocs/components/com_jcomments/plugins/com_jem.plugin.php on line 31

then I disabled Jcomments plugin, and there were no problems.
I made this with Joomla 3.3.6/php 5.4/JEM2.1

**Comment by Hoffi1** [comment]
Hm... if I remember right I changed this long time ago. Seems you have an old version.
But I don't remember if and where I provided the newer one...

**Comment by Hoffi1** [comment]
...seems I forgot to commit it. :flushed: 
Will take a look when at home.

**Comment by jojo12** [comment]
tried this fix, but get the same error notices or white page

**Comment by Hoffi1** [comment]
This can't be because this line has been removed.

**Comment by jojo12** [comment]
I'm sorry. You're right. I changed on the wrong site. ;-(.
Now it's ok. can be closed.

**Comment by Hoffi1** [comment]
I've more than 40 local and ~5 hosted sites - I know this problem. :smile: 
But you've found the bug, so please take my big thanks. :+1:

**Comment by jojo12** [comment]
you're welcome (even when you are once in switzerland) :-)
