### ISSUE TITLE
JemOutput: add second function to format date/time into two lines

### ISSUE THREAD

**Issue by Hoffi1** [jemproject/JEM-Project#881]
Currently we provide event's date/time values in a mixed format like ```startdate, starttime - enddate, endtime``` where 7 variants are possible (no time, no enddate etc).
Some users want to show this in another form, e.g. ```startdate - enddate<br>starttime - endtime```. To do so they need to override the tmpl files for all relevant lists and add a lot of code there to respect these 7 variants.

We can help them by providing an alternative function in JEMOutput class which returns the two-line form shown above. Also the date and time part should be encapsulated in a ```span``` with css class to allow styling (e.g. date line strong, time line italic).

We can more help by adding a JEM layout setting where user can choose the one-line or two-line formatting for all lists, and check this in JEMOutput::showShortDateTime() (which is used by the lists).
Then the only thing for users is to choose the right formatting option and add css styling as needed.

**Comment by JKoelman** [comment]
would indeed be nice to have..

**Comment by Hoffi1** [comment]
...and it works perfect - on my local dev-site. :wink: 

The only thing is that the setting requires new language strings and alteration of settings table. So it requires installation instead of simple file upload.
