### ISSUE TITLE
change in mod_jem_teaser for better time name display!

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#885]
it would be better in line 85ff
			<?php if ($item->time && $params->get('datemethod', 1) == 1) :?>
			<div class="time">
			<?php $starttime2 .= JEMOutput::formattime($item->time);?>
			<small><?php echo $starttime2; ?>
			</small>
			</div>
			<?php endif; ?>
like that you have included the time name like "Uhr" or "h"

**Comment by Hoffi1** [comment]
Not looked into teaser mod yet but using JemOutput class to format date/time is the way I would generally prefer.

**Comment by jojo12** [comment]
We can use the methodes from the mod_jem
then you can choose the time and dateformat in xml. and even the timesuffix.
