### ISSUE TITLE
Acymailing plugin: all archived events shown in choice window

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#887]
I've just seen: when I want to show only some events in a newsletter, the program opens a modal window with all events. But with all events! That means I have to search through all archived events the actual event, I want. I think, this is not wanted. Would be better to show only the actual and upcoming events. 
What do you mean?

**Comment by Hoffi1** [comment]
You're right, this seems to be very useless - except one needs to write an oldsletter. :wink: 

Must take a look, at the moment I don't remember much about Acy plugins. Sorry, seems the time speeds up currently...

**Comment by Hoffi1** [comment]
...erm - about which version do you talk?
I don't see any old events nor some with open date.

**Comment by jojo12** [comment]
tagjem 1.9 on JEM 2.1.1

**Comment by jojo12** [comment]
strange is: in choose window, the open dates have the date of today. But in newsletter there is open date.
and the archived events you can see the dates in image
![choose archived](https://cloud.githubusercontent.com/assets/2960236/6117529/6ebd0b2c-b0b5-11e4-8436-f46b1d15a635.png)

**Comment by Hoffi1** [comment]
Ok, the old events are shown because in plugin Basic Options "Hide Past Events" is set to "No, display all events".
But it seems the ```published``` clause is missing which is bad (because it should also show unpublished and trashed events).

**Comment by jojo12** [comment]
You're right I did not see the " hide past events.

**Comment by jojo12** [comment]
I tried your fix #887 (only with exchanging the old tagjem.php with the new one,  but then there's nothing to choose. I then changed back: the events are back.

**Comment by Hoffi1** [comment]
Hm... On my site it worked. Stupid question: Do you have published, non-archived events?
I forgot to prepend "a." to be completely unambiguous (see my comment on the commit) - but I wonder why it work on my site. So sorry for wasting your time. :worried:
