### ISSUE TITLE
jem-dev21 problems

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#888]
Hi, I made a package of dev21 and tried to install after uninstalling with cleanup all old jem.
I got a lot of error messages and only after the 3rd time I got the message install ok. But then I got in settings a lot of error notices. (I have printscreens, but perhaps they're not needed, because I am too early.

**Comment by Hoffi1** [comment]
Hm... I had expected it works. But had not tried it until now.
Will setup a new test site and try to fresh install it.

At the moment my only (bad) idea is a script timeout by a stressed server...

**Comment by jojo12** [comment]
perhaps this helps:
during the first installation:
![jem222_1](https://cloud.githubusercontent.com/assets/2960236/6116634/bb9493cc-b0ae-11e4-8733-bb87275ca310.png)
during the second installation:
![jem222_2](https://cloud.githubusercontent.com/assets/2960236/6116637/c2a0acfa-b0ae-11e4-87c7-dbb1438a0db5.png)
after the third installation, in settings:
![jem222_3](https://cloud.githubusercontent.com/assets/2960236/6116639/c7af201e-b0ae-11e4-9ee6-470c6cb13f95.png)

**Comment by JKoelman** [comment]
uhm, if remembered correctly there was an additional field added for the eventdate and maybe that one leads to the problem.

**Comment by Hoffi1** [comment]
Argh... I added the field in sql file - but not the default value...

And the third warnings are a result of the first: settings table is empty.

**Comment by jojo12** [comment]
I exchanged your fixed file in the package and then reinstalled (today). I got:

1. Installation:
1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1 SQL=INSERT IGNORE INTO `byazt_jem_categories` (`id`, `parent_id`, `lft`, `rgt`, `level`, `catname`, `alias`, `access`, `published`) VALUES

2. Installation over the first
Warnung
JInstaller: :Install: Die Joomla!-XML-Installationsdatei konnte nicht gefunden werden.
JInstaller: :Install: Die XML-Installationsdatei konnte nicht gefunden werden.
Nachricht
Die Paket-Installation wurde abgeschlossen!

3. Installation over the second
Nachricht
Die Paket-Installation wurde abgeschlossen!

After it seems ok.
(the date in two lines is very nice!)

**Comment by Hoffi1** [comment]
Hm... is that the complete message? nothings after VALUES ?
But do you have a root category?

If so (first question) it could be Joomla ignores the last line in install*.sql maybe because it hasn't a linefeed character. But this part is very old, always without linefeed and worked fine on J! 2.5 (some months ago I tried fresh install).

I don't dare ask: Have you enough time and motivation to try it again? Then you could please append a new line at end of the file, something like "-- end (please do not remove)" (I hadn't used an apostroph just to be sure not creating a new mistake)
It's just an idea but the only I have yet.

Today I'm very busy (@home) so not sure if I find the time to try it myself.

(regarding date thank Leonie :smile: you know you can/must style it yourself in css, e.g. bold date or so)

**Comment by JKoelman** [comment]
alright, did do a clean install today but didn't got a notice during install.

- did download the dev2.1 package
- created a zip with files needed to install the component
- then installed that file in Joomla 3
--> no problems

**Comment by Hoffi1** [comment]
Bummer! A reproduced problem I like more.

**Comment by jojo12** [comment]
me too! :-(

**Comment by jojo12** [comment]
I made a new package (12:30 MEZ), I uninstalled all JEM with cleanup preparation.
Then I installed new --> no problems! Happy but sorry, I waisted your time.

(Trying to find causes of the problems:
I had mod_jem_banner in the package too. but added in the xml the mod_jem_banner
I had a menu with a entry with tries of listevent plugin and jem event button plugin. which was not deleted.)

**Comment by jojo12** [comment]
Played around adapting to my favourites, importing events, categories, venues and catevents.
No problems, all seems to work fine!

**Comment by Hoffi1** [comment]
No problem, Jojo. You found a real bug in sql file so there you saved my time. :+1: 
So for me it's around +/-0. :smile:
