### ISSUE TITLE
mod_jem_banner: how can I change my files for the module you uploaded?

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#895]
I made some changes  I would like to share. can I only fork this module here. Or shall I copy/paste directly into the files?

**Comment by Hoffi1** [comment]
Hm, good question. As I see I hadn't committed any modifications yet, seems I was interrupted by 2.1.2 release. I remember I made some adaptions (to remove "Uhr" and so :wink: ) but some more are outstanding.
So not sure what's the best way. You could commit directly (on dev21 branch) and I look what had changed. But I would like to have the mod more universal so maybe I must change some things specific for your needs.
On the other hand if you fork (which would be right out of the textbook - theoretically) and I commit you may become a problem with integrating my changes. It's possible but a bit more complicated (GitHub for Windows simply says "I can't do that, please use the command line").
A third way could be a branch derived from dev21 head which allows a bit easier merges.
A forth variant would be to wait until I committed my changes - but then I fear you need to merge locally or start again. :worried: 

A well, don't have a favorite...
...too many tasks at the moment, seems I need vacation...

**Comment by jojo12** [comment]
Thanks for your answer. Meanwhile I made a fork modban and exchanged the files with my new files:
I added the possibility to give the datesystem (then uhr as suffix can be included. I adapted that you can use opendate too if you have an eventID etc. On my site it works really fine.

**Comment by Hoffi1** [comment]
Thanks Jojo. If I read this I fear we made things twice - because you haven't access to my local disc. Sorry if so. Had I'm already sayed that I'm sometimes a bit slow? :sleepy:

**Comment by jojo12** [comment]
No problem Hoffi, for me it's a bit of learning! What I don't know: can you see my fork or how can I show you. I surely will look good to understand your changes to learn a bit from a master

**Comment by Hoffi1** [comment]
Until you pay for private repositories everbody can see all things committed.
The only thing owner can decide is who have which write access.
It's your own repo, nearly the same as if you had created one, except all data were copied from this repo here and it's marked as fork to e.g. simplify pull requests.

**Comment by JKoelman** [comment]
question: can this issue be closed?
