### ISSUE TITLE
JEM 2.1: catoptions field in frontend works not correct

### ISSUE THREAD

**Issue by Hoffi1** [jemproject/JEM-Project#898]
In J! 3.4 the backend version of catoptions field would be used - this fix is tracked in #892 

But the frontend version is also not fully correct.
- Super users will get all categories, also such they don't have view access - that's wrong on frontend
- for other users is a maintainer check where users with general event creation permission will only see categories without group or with group user is member of - I would say such users should see all categories (they have view access, of course), but other users only categories connected to their groups. Also users without this general permission and not member of any jem group shouldn't see any category (maybe pure theoretical because they shouldn't be able to enter the editevent view).

Also I will made some advanced tests regarding non-accessable parent categories...

**Comment by JKoelman** [comment]
yeah, that catoptions field is definately something to improve..   one other thing that can be added to the category's are assets/rules as it will make it easier to assign rights to Joomla Groups

**Comment by Hoffi1** [comment]
Regarding the ACL thing currently implemented:
- I will allow all users with "core.create" permission for com_jem (normally Authors, Editors, Publishers, but also Admins and Superusers) to see all categories ignoring group ids.
- I will keep the other check untouched, because this relates to JEM settings (User control - AC Events) and not to Joomla ACL. So there it could be ok/useful to limit subission to categories not attached to a JEM group or user must be member of that group.

that means:
- Authors, Editors, Publisher, Manager, Administrator, Superuser etc. will be allowed to attach events to any category.
- Users in a JEM group will be allowed to attach events to categories attached to that group.
- All other registered users will be allowed to attach events to "group-less" categories if "New events from users" setting is set to "All registered users".

This is an intermediate solution using JEM's current access rights system.
This maybe changed later by full Joomla conform ACL system as suggested by @JKoelman above.

**Comment by jojo12** [comment]
You write: 
Authors, Editors, Publisher, Manager, Administrator, Superuser etc. will be allowed to attach events to any category.
I am not sure: I can give writes to authors to write an article I will then publish. But it could be, that I don't want, that this person can post an event in any category.

**Comment by Hoffi1** [comment]
I know. But on Joomla members of common group Author are generally allowed to write articles etc.
Think about it as site author which can write anything anywhere on the site.
If you need partial authors (also only able to write articles on some categories) you need to create a new group not giving core.create permisson in general but e.g. on specific category. (hope it works, not tried yet)

Because the permission is requested for com_jem it would be possible not to take the global permissions (but I don't know how). In that case the admin has to manually give e.g. global authors the permission to also create events. (currently you could deny this but that has always priority so it would be impossible to give the permission on e.g. a specific category - if this would be implemented)

**Comment by JKoelman** [comment]
> : I can give writes to authors to write an article I will then publish. But it could be, that I don't want, that this person can post an event in any category. (I didn't think about longer, but this is an example)

with applying category assets and adding code for it this could be achieved.
cause then you can define per category the Cando rights for the joomla groups

**Comment by Hoffi1** [comment]
Can we close this @jojo12 ?
I think it's now conform to Joomla as good as JEM's current ACL support allows.

**Comment by jojo12** [comment]
I didn't try at the moment, but I am confident to your work!

**Comment by Hoffi1** [comment]
As our Chief Tester you shouldn't do that! :wink:

**Comment by jojo12** [comment]
sometimes there's a real life!

**Comment by Hoffi1** [comment]
That's understood. I never thought different. Would only say that testers shouldn't blind trust developer's work and I fully agree this rule also as affected developer. So the word "that" in my previous post was intended as pointer to "confident", not to "didn't try" which is of course fully accepted.
(In my real life I must sometimes motivate our testers to ruthless mistrust my and other dev's work. I like them even if they point to my mistakes.)

**Comment by jojo12** [comment]
to be honest: I don't understand this topic enough! I should understand before I can test. So I can only say, when I run into problems which could be caused by that I will immediately inform you.

**Comment by Hoffi1** [comment]
Agreed. So I will close this issue. The number is refered on our Changelog so we can find it if required. And if there are more problems we use new issues with it's own milestones for better tracking.
