### ISSUE TITLE
mod_jem_banner: seems to work fine

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#905]
I replaced my version with yours and it seems, it's working fine. Like it. will test more.

**Comment by Hoffi1** [comment]
Thanks. There are some little differences to your personal version (e.g. I completely removed the "bold" style for description so site templates style will/can be used).
I tried to make it more universal for the masses but hope it's not too far from your needs. :smile:

**Comment by jojo12** [comment]
No, it' good to make it more official. If someone wants he can make an override. Hope the masses will like it!

**Comment by JKoelman** [comment]
question: should it be open or closed?

**Comment by Hoffi1** [comment]
From my point of view it could be closed. Don't know what's Jojo's intention was...
