### ISSUE TITLE
date in jem_banner is really special!

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#907]
I have an event: Do, 2. April 2015, 19.00 Uhr - So, 5. April 2015, 15.00 Uhr
the date in jem_banner shows: "Von l, j. F Y bis l, j. F Y"

![dateproblem](https://cloud.githubusercontent.com/assets/2960236/6527580/10049f30-c41c-11e4-8327-fc8a52f3cce7.png)

**Comment by Hoffi1** [comment]
Hm... sorry, but I can't reproduce this and also see no problem in code.
Are you sure to have the original code from GitHub running?

**Comment by jojo12** [comment]
you're right, sorry. You can close it
