### ISSUE TITLE
to change: in frontend eventslist should be a "horizontal schieber" too

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#911]
![schieber](https://cloud.githubusercontent.com/assets/2960236/6555473/c5ee3f1c-c666-11e4-9daa-321d4c3748f6.png)
I don't know how this blue thing is called! Horizontal slider? - horizontal scroll bar
when I use a small screen, then e.g. in backend events view, I get this schieber to move to the right to see the rest of the image.

In frontend e.g. eventslist view, this is not! So for example with all columns enabled and with small screen, the rest of the table is cut and cannot be viewed.
Is it possible, to add this. 
(I think this would be the best resolution for smartphones too!)

This would be an enhancement for JEM 2.1.4 and JEM 3.0.8!
![cuttable](https://cloud.githubusercontent.com/assets/2960236/6555628/c3eb87f0-c667-11e4-8a50-e2477160edf0.png)

EDIT: adapted translations

**Comment by Hoffi1** [comment]
This thing is called scroll bar. It is automatically created by the browser if it detects content area is larger than display area.
It seems one of the e.g. <div>'s around the <table> resizes always relative to display area where the table has a minimum width so we get an overflow.
If we find the right element we could try to add a css rule ```overflow: scroll;``` which would let the browser add a horizontal scroll bar for the table only.
The alternative would be to ensure complete content area gets never smaller than the table requires at minimum so browser can add the scrollbar for the complete page.
The question is which element becomes smaller than the content inside requires. (at the moment I can't analyse this; if you have Firebug or so you can try to find the "bad tag" and play around with css)

**Comment by jojo12** [comment]
it's not the best solution but whe I change in jem.css in about line 80 from 
overflow: hidden; to overflow: visible
then I get automatcly the scroll bar from my browser.

But like that it's not so beautiful because only the table overflows and breaks a bit the layout.

**Comment by Hoffi1** [comment]
Thanks Jojo, it's not the solution but a first inspiration. :smile:
