### ISSUE TITLE
Problem with our website?

### ISSUE THREAD

**Issue by Hoffi1** [jemproject/JEM-Project#912]
Currently I can't post to Forum nor write a PM.
I get Error 500 or connection aborted...

**Comment by jojo12** [comment]
with me it worked

**Comment by Hoffi1** [comment]
Now I could post, but the server seems to be partially instable, I had to download the package I would look into multiple times until it was complete.

**Comment by ernst67** [comment]
I experienced a moment of inactivity yesterday too. Seems that every few months they have some bad days....
