### ISSUE TITLE
transifex is not uptodate!

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#915]
Hi, after having updated the german language files, I got emails from mailer plugin which were english.
I looked in transifex: it says, german is 100% translated.
I compared the english file with the german. There are words in the english file which are not (!) in the german file. That's bad.
Where's the problem?

**Comment by ernst67** [comment]
Trying to understand you here...

Are you saying there are strings in the English version that are not there in the German translation? Are you talking about  plg_jem_mailer.ini?

**Comment by jojo12** [comment]
Hi,
yes
e.g.
PLG_JEM_MAILER_ADMIN_UNREG_ONBEHALF_BODY_5="The user %s \nbecame unregistered by user %s \nfrom the event: %s \nDirect Link: %s \n\nThank you\n%s"
this seems to be a newly added expression.

**Comment by jojo12** [comment]
strange, I found these KEYs in the german and they are translated.
But I updated the german files. 2.1.3

**Comment by ernst67** [comment]
"But I updated the german files. 2.1.3"
What do you mean..?

Did you update the files at transifex?

**Comment by Hoffi1** [comment]
Can't verify.
Have JEM 2.1.3 with de-DE 2.1.3, language used is German. Registered another user in backend and got all emails in German.
Maybe you'r language was set to English Jojo?
