### ISSUE TITLE
category email not sent when event created/edited in backend?

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#916]
Hi, 
is this possible, that there's no email sent to category-emails, when event created/edited in backend.
It's enabled in my mailer plugin. The plugin is enabled. The emailaddress is inserted in category.
I get the email, when created/edited in frontend.
If you can reproduce, then it seems to be a bug!
tested on Joomla 3.4.1 and JEM 2.1.3

**Comment by Hoffi1** [comment]
Yes, it's possible.

Maybe backend doesn't trigger the plugin. If I remember right it was on Registration (on behalf of) from backend too, but this works now.

Will take a look...

**Comment by JKoelman** [comment]
can't remember but it's indeed good possible that the mail is not being send by the backend.
