### ISSUE TITLE
JEM CB Plugins: prepare for JED

### ISSUE THREAD

**Issue by Hoffi1** [jemproject/JEM-Project#918]
The CB plugins are not accepted by JED watchdog.

Add missed GPL comment and change JEXEC line to be conform.

**Comment by Hoffi1** [comment]
Improved the plugins a bit more. Now multiple categories and maxplaces/waitinglist are supported, also code optimised a bit.

Also I tried the sql query on tables of JEM 3.0.6 and got no errors. But maybe recurring events will not work, don't know, not tested.

**Comment by ernst67** [comment]
Can they now be uploaded to JED again?

**Comment by Hoffi1** [comment]
Yes, that's my intention.
I'll prepare the zip files and inform you when ready.

**Comment by ernst67** [comment]
OK, I'm travelling abroad from this Friday morning till Monday evening.
