### ISSUE TITLE
mod_jem_banner: click on image should link to event too

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#919]
This is a proposal:
Clicking on image in this module should link to the event too (not only clicking the title)
I think this would be better.

**Comment by Hoffi1** [comment]
I thought about this too. But there are also some settings (Show Flyer, Modal window) expecting click on image will open original image.
So I think it should be a new setting like "Image links to..." (Event, Image) where descriptions say "Image" is required for the other two options to have effect.

**Comment by jojo12** [comment]
Because the image is a bit bigger than the normal teaser images (terrible! ;) the link to the modal window is not so important. I see always people clicking on the image for to get the details (even much more than clicking on the title).

**Comment by Hoffi1** [comment]
I replaced option "Modal Window" (Yes / No) with option "Flyer links to..." (Image on full page / Image in modal window / Event's details page). The first two choices are well-known whereas the third adds a link to event's details page. Also I changed the tooltip text to "Click to enlarge" in first two cases.
