### ISSUE TITLE
JEM 2.1.3 Banner mod: add option to shuffle events

### ISSUE THREAD

**Issue by Hoffi1** [jemproject/JEM-Project#924]
In some cases banner module could be intended to show only one random event, e.g. one of the upcoming within next X days.

Because I already posted a working idea [here in our forum](http://www.joomlaeventmanager.net/forum/jem-3-0-x-for-joomla-3-test-forum/9011-events-banner-module-–-event-rotator-–-horizontal-display) we should add this (maybe a bit more configurable) to official code. :wink: 

But it will be a pure shuffle. No history, no weighting, no refresh button, ... Simply "get max. N events within next X days, shuffle, and show as much as configured to display". Also the admin has to decide if this feature in combination with the other settings is useful or not.

**Comment by jojo12** [comment]
I agree

**Comment by jojo12** [comment]
Something seems to be buggy:
I Installed your fix and tried with two event IDs, but then nothing changes, always the same event.
With your posted version in forum, the events changed

**Comment by Hoffi1** [comment]
Hm... I also tried yet with two fixed IDs and one event to show.
It works fine on me. Sure, because it's random and with 50:50 chance it's possible to get a lot of times the same event. So it's possible you need 10 or more tries. Or you increase the pool.

btw: I added Display type "Open date events" to show such events without the need to type in there IDs.

Also note that I explicitely keep the ordering of shown events untouched. So if more than one event should be shown they are always from now to the future.
