### ISSUE TITLE
JEM 2.1.3: Add banner mod to Configinfo (JEM Settings)

### ISSUE THREAD

**Issue by Hoffi1** [jemproject/JEM-Project#927]
I wonder if we should add all the missed plugins too?

Also this table inspires me to set the version of ALL parts of JEM package to same version. Looks better there.

**Comment by Hoffi1** [comment]
I altered the model to get all parts in a single db query. Also an array is used to simplify adding of new parts (one in JemModelSettings::getConfigInfo() as filter, second in view's default_configinfo.php to attach corresponding text labels).
Additionally creationDate is shown and also if the part is disabled.
And MagicQuotes will not be shown for PHP 5.4 or newer.

**Comment by JKoelman** [comment]
:+1:

**Comment by JKoelman** [comment]
about enabled/disabled:

when a module is disabled't it won't be shown correctly, this as we Joomla has a seperate table for the modules.

**Comment by Hoffi1** [comment]
You're right, that's not the publishing state of concrete module instances. It reflects if a component/module/plugin is enabled or disabled in general.
So if you disable e.g. mod_jem_banner in Extension Manager - Manage it should not show any instance of that module - regardless if they are published or not.
(and it works :wink: on Module Manager they will be shown with Status "Extension disabled")

More helpful for us are the plugins, e.g. if mailer is disabled. There it isn't important if Extension Manager or Plugin manager was used, both trigger the "disabled".

**Comment by JKoelman** [comment]
ah, ok that clarify's it.
