### ISSUE TITLE
view Imagehandler: Uncaught ReferenceError:Joomla

### ISSUE THREAD

**Issue by JKoelman** [jemproject/JEM-Project#928]
When changing the limit of images to be displayed it's trowing in an error.

See http://www.joomlaeventmanager.net/forum/jem-2-1-x-for-joomla-2-5-joomla-3-community-support/9042-js-error-when-trying-to-switch-page-in-the-image-selector#18219

**Comment by Hoffi1** [comment]
Agree, this should be fixed.
