### ISSUE TITLE
add xtd-event plugin from JEM 3.0.7  to JEM 2.1.4

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#930]
@Hoffi1: 
this plugin should be in JEM 2.1.4 too.
(it works, when you add the file views/eventslist/tmpl/modal.php from JEM 3.0.7 in the same place in JEM 2.1.3+.)

[NOTE: at the moment I am waiting for the new cb groupjive events, there you can use xtd-plugins in event description. In the old CB this was possible, at the moment not.]

**Comment by JKoelman** [comment]
one additional thing with the plugin is that we should make it inline with the single event-select.
