### ISSUE TITLE
no saving when adding a user to an event and using "save"

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#932]
When I want to add a user to an event in backend and I click "save and close", the attending user is saved.
But when I use only "save", the attending user is not saved.

I would expect, that the user is saved and I can choose a new participating user.

**Comment by Hoffi1** [comment]
I tried it with JEM 2.1.3 but I can't reproduce exactly that.
If I ```Save``` the selected user is registered and emailed as attendee. After ```Close``` I see the correct list.

BUT: If I select user A, click ```Save```, user A will be saved as attendee (like above). If I then don't close but instead select another user B and click ```Save``` (again), user B will be saved as attendee but user A will no longer be attendee (and receives an unattend email).

This sounds crazy but is consequent Joomla behaviour. The page represents a registration object where you change the content - here the user. That's the same as if you edit an article - from computer's point of view.

What you want to register multiple users are the buttons ```Save & New``` or ```Save as Copy```.

**Comment by jojo12** [comment]
You're right. So it would be good to have a "save and new". But after all it's important to know.

**Comment by Hoffi1** [comment]
Will try to add the buttons to 2.1.4...

**Comment by Hoffi1** [comment]
Adding the buttons is no problem but they don't work without changing some more code. So I can't add this until Friday.

Instead I would add an Attention text in 2.1.4 saying that changing the user will unregister the original attendee and register the selected user instead when Save is pressed.

The buttons with correct working functionality would be one of the first motivations to update to JEM 2.1.5. :wink:

**Comment by jojo12** [comment]
ok, thanks!

**Comment by Hoffi1** [comment]
Added notice shown if editing existing attendee entry. That's the hotfix for 2.1.4.

But I don't set it to ```fixed``` because the buttons will be added later (2.1.5).

**Comment by Hoffi1** [comment]
Now the buttons are working too.

**Comment by jojo12** [comment]
when using save and new, the attended person is saved, even when I add an other person. But there is a new thing (problem?):
when I don't choose a user and use save and new or save and close, I have an additional user with id 0 but nooname which is counted as attending.

**Comment by jojo12** [comment]
@Hoffi1:
sorry, I didn't see that this is just closed. Because it's something not the best, I reopened.
Can this be fixed?

**Comment by Hoffi1** [comment]
Hm... seems we never found this before but I'm relatively sure it's an established bug. :wink:

Will take a look (today evening) how to ensure user field isn't empty on Save...

**Comment by jojo12** [comment]
Yes, that can be, that it was there just before. It's a pity, that I find such things just in the moment we want release an update!
If it was just before there and you find, we can live with that, or when it's not easy to change, then I would say, we postpone it.

**Comment by Hoffi1** [comment]
No! You awakened my ambition. :grinning:

**Comment by jojo12** [comment]
that's a good teamwork!

**Comment by Hoffi1** [comment]
Got it! :triumph: 

There was an old JavaScript to check for empty user id which was not called.
Don't know if my fix is perfect but it works stable.

**Comment by jojo12** [comment]
Tried it, works best now! Thanks
This issue can be closed.
