### ISSUE TITLE
Banner/Teaser mod: option to use category color

### ISSUE THREAD

**Issue by Hoffi1** [jemproject/JEM-Project#933]
It could be nice to use category color for calendar image.

**Comment by Hoffi1** [comment]
On Teaser module there's an additional "color" option used in calendar image. :wink: 
Same could be also added to Banner module.

**Comment by Hoffi1** [comment]
There was a little mistake showing Fallback color's description text as label - fixed now.

**Comment by Hoffi1** [comment]
On Banner mod too now.

**Comment by jojo12** [comment]
fine! thanks.
