### ISSUE TITLE
onEventEdited can't be used if jemMailer plugin is disabled

### ISSUE THREAD

**Issue by simokarpin** [jemproject/JEM-Project#937]
When looked into code i saw that event "onEventEdited"  get called only when jem mailer plugin is enabled but there is no dispatcher event when its not enabled? - There should be dispatcher event "onEventEdited" for custom logic if needed.

**Comment by Hoffi1** [comment]
Thanks Simo, you're right. It should fire the event to all plugins in jem group.
I think it was to generate the warning in case mailer plugin is disabled to inform user that nobody will be informed.
