### ISSUE TITLE
missing<br>breaks template in venues view

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#939]
see post  #18437 in the forum
I think, there should be a \<br>.

**Comment by Hoffi1** [comment]
Must take a look...

**Comment by Hoffi1** [comment]
Hm... I wonder if multiple dt/dd pairs can be inside a single dl block or if each pair should get it's own?
Must go and learn details about dl/dt/dd ...

**Comment by JKoelman** [comment]
some info: http://www.w3schools.com/tags/tag_dl.asp

**Comment by Hoffi1** [comment]
I tried a lot but hadn't found a solution working in all (crazy) situations.
So I decided to simply encapsulate both items into it's own ```<dl>``` with floattext css class. This was the easiest solution only touching the tmpl file.

**Comment by jojo12** [comment]
not yet!
The pagination at the end is half outside! see image
![pagin](https://cloud.githubusercontent.com/assets/2960236/7742888/071f3df8-ff95-11e4-9c90-7b5ffd05d224.png)

**Comment by Hoffi1** [comment]
Oops...
Is it frontend? Which template? Also if you have a description below the counters?
I wonder why "Powered by" is above the pagiantion.

Maybe a ```<div class="clr"> </div>``` is required if discription is switched off.
(possibly directly before the ```<?php endforeach; ?>``` line or a bit above before the ```<?php endif; ?>``` as ```<?php else : ?>``` alternative - can't try it out until evening...)

**Comment by jojo12** [comment]
sorry, it's with purity_iii template. in beez3 it looks ok
will try with your proposal

**Comment by Hoffi1** [comment]
I tried with beez3 and protostar but can't see this effect.
No problem to add the clr div, but I wonder because in jem.css is a rule ```clear:both``` for div.pagination. So I don't know the cause for your screenshot and if the clr div solves it.
