### ISSUE TITLE
totally blocked for joomlaeventmanager

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#945]
Hi, since yesterday morning I can' t reach the site.  
@all: do you have no problems?

**Comment by ernst67** [comment]
Everything is working fine here....
Still blocked?

**Comment by jojo12** [comment]
yes,nothing!
can you have a look, am I (jojo12) blocked?

**Comment by ernst67** [comment]
Nope...
You can't even see the site frontend at all?

**Comment by jojo12** [comment]
no nothing, I can't enter nor in frontend nor in backend

**Comment by ernst67** [comment]
Did you try a different browser?

**Comment by jojo12** [comment]
yes, I tried with IE, with chrome, too, normally with firefox

**Comment by ernst67** [comment]
a mystery.

hold on..: you can see the site, but nan not log in?

**Comment by Hoffi1** [comment]
Hi guys, sorry for late response but GitHub sends only sporadically notification mails 
But I've no problems accessing the jem site.

**Comment by jojo12** [comment]
no, it tries very long time to load, and then says too much time! I don't see the site. All other sites even here work fine.

**Comment by ernst67** [comment]
Hmm.. absolutely no idea. 
I thought you accidently tried logging in with your (changed) password to the normal site.
So I wanted to give you the hint that the demo site is a separate db.

anyway, I reset your password of the demo site to the one I set it up with yesterday.

**Comment by jojo12** [comment]
ok

**Comment by jojo12** [comment]
@Hoffi1:
I always get:
Fehler: Netzwerk-Zeitüberschreitung

Der Server unter www.joomlaeventmanager.net braucht zu lange, um eine Antwort zu senden.

    Die Website könnte vorübergehend nicht erreichbar sein, versuchen Sie es bitte später nochmals.
    Wenn Sie auch keine andere Website aufrufen können, überprüfen Sie bitte die Netzwerk-/Internetverbindung.
    Wenn Ihr Computer oder Netzwerk von einer Firewall oder einem Proxy geschützt wird, stellen Sie bitte sicher, dass Firefox auf das Internet zugreifen darf.

**Comment by ernst67** [comment]
i'm sending you an email....

**Comment by jojo12** [comment]
no, with this site it's the same no go!

**Comment by jojo12** [comment]
I phoned with my provider bluewin.ch and they said, perhaps I came on a blacklist on your hoster!
Perhaps because I have a swiss IP? So can you contact them and ask, and say, that's ok.

**Comment by ernst67** [comment]
Then it indeed seem a matter of blocking.... 
We don't hate the Swiss though ;-)

I will contact the hosting provider and see what they say... could you maybe check the site via a proxy?

**Comment by jojo12** [comment]
sorry, :( , I don't understand

**Comment by ernst67** [comment]
can you surf to the via via a proxy server in, for instance, germany?

**Comment by ernst67** [comment]
Could you please email me your ip address. The hoster is having a look...

**Comment by jojo12** [comment]
85.0.111.234

**Comment by Hoffi1** [comment]
I understand the proxy thing but have no idea how to do this. But a smartphone using mobile network (not own wlan) should have the same effect.

**Comment by ernst67** [comment]
yep, same idea.

**Comment by ernst67** [comment]
OK, they white-listed the ipadress. Please check again in 10 minutes

**Comment by jojo12** [comment]
I tried with the smartphone of my daughter with their ip. This works I came in. So it seems to be the problem of my IP.

**Comment by Hoffi1** [comment]
I would really rofl if our dutch hoster uses a "1234" blocker. Maybe it works after 24 hours if you get a new IP, Jojo - but you wrote "simce yesterday morning"...

btw: [de] Ich wusste ja gar nicht, dass es in Zürich eine Straße gibt, die nach einem Badeort auf Rügen benannt ist - was man alles so mit Hilfe einer simplen IP-Adresse erfährt... :grinning:

**Comment by jojo12** [comment]
da kannst du dich täuschen. auf myip... habe ich gesehen, dass meine IP an einem ganz komischen Ort ist, aber sicher nicht in zürich.

**Comment by Hoffi1** [comment]
Ich sag' ja nicht, dass Du da wohnst. Sonst hätte ich mich hier garantiert nicht darüber geäußert. Das ist die Anschrift Deines Providers.

**Comment by jojo12** [comment]
somewhere lost in amsterdamse grachten ;)

**Comment by jojo12** [comment]
Until now nothing! I will inform you here, when I am back!

**Comment by jojo12** [comment]
Nothing: 10 minutes must be very long!

**Comment by jojo12** [comment]
Hi,
after a total reset of my router, I've got now a new IP adress and can reach the site at least as user.
At the moment I will not try to enter backend! Perhaps you can understand me.
But I am back.

**Comment by ernst67** [comment]
Well, as investigated yesterday, it's not only this site, but all sites running on the same server.

So the IP block must be at the hosting provider, but thy have whitelisted you yesterday.
I'm not concinced it has anything to do with logging in the backend of the demo though....

**Comment by Hoffi1** [comment]
Good morning guys and welcome back Jojo. :smiley: 

I don't know which things the provider has running but if an IP is black and white listed black wins.

One idea could be to take a look into the logs if Jojo's old IP is listed. But I agree, because he was blocked on both sites it would mean on both is the same "smart" blocker running - so provider level is more logical (also because I don't know if it is possible to tell Joomla completely not to answer a request, also not with an error code).

**Comment by ernst67** [comment]
I have another site running on the same server, and that one was inaccessible too.

Anyway, I propose we delete this discussion, as it's not necessary for the whole world to read along.. ;-)

**Comment by jojo12** [comment]
Ok, for new problems I send you a mail.
