### ISSUE TITLE
jem 2.1.4: error starting import view in backend

### ISSUE THREAD

**Issue by level420** [jemproject/JEM-Project#947]
Running Joomla 3.4.1 on Centos 6.6, php 5.4.

When clicking on the "Import Data" button in the JEM backend nothing is displayed and the server error log states:

```
[10-Jun-2015 11:12:05 Europe/Berlin] PHP Fatal error:  
Can't use function return value in write context in
/opt/www/migrationstest/root/administrator/components/com_jem/views/import/tmpl/default.php
on line 76
```

A search revealed (seems so) a corresponding thread in stackoverflow:
http://stackoverflow.com/questions/1532693/weird-php-error-cant-use-function-return-value-in-write-context

I think this error occurs because I use php 5.4.

Any help would be great!
Regards
Dietrich

**Comment by level420** [comment]
The following patch seems to fix the bug:

```diff
--- administrator/components/com_jem/views/import/tmpl/default.php.orig 2015-06-10 11:10:24.036810981 +0200
+++ administrator/components/com_jem/views/import/tmpl/default.php      2015-06-10 11:17:52.358866415 +0200
@@ -73,7 +73,8 @@
                ?>
        </ul>
        <?php
-       if ((count($missedTables) == 2) && empty(array_diff($missedTables, array('eventlist_attachments', 'eventlist_cats_event_relations')))) {
+       $weird = array_diff($missedTables, array('eventlist_attachments', 'eventlist_cats_event_relations'));
+       if ((count($missedTables) == 2) && empty($weird)) {
                echo "<p>".JText::_('COM_JEM_IMPORT_EL_MISSING_TABLES_V11')."</p>";
        }
        ?>
```

**Comment by Hoffi1** [comment]
Yes, my chronical mistake. :cry: I already know this problem but from time to time I'm ill and write such natural things not allowed in PHP prior 5.5. There ```empty``` requires a variable, a return value of a function is not accepted. So your patch fixes the problem.
Maybe replacing ```empty(...``` by ```!count(...``` is an alternative patch not needing an additional variable, but not tried yet.

Thanks @level420 for your report.

**Comment by jojo12** [comment]
What we do with that?
We give a quickfix patch for 2.1.4? Or we renew 2.1.4? Or make immediate a 2.1.5?
I would accept one or two, three is too much work for nearly nothing.

**Comment by Hoffi1** [comment]
Hm... don't know how to provide a hotfix the user can simply install via Extension Manager.

We can create an updated package, helpful for the "late birds" (maybe we call it 2.1.4b). But we also need something for users already updated.

Affected are all users running current 2.1.4 on PHP < 5.5 and need to import data.
The problem can be solved by exchanging one file on the server - should be ok for many users to do this manually. As alternative the renewed 2.1.4 package can be installed over 2.1.4.

@ernst67 What do you think? (we can continue this internal discussion in the Forum)

**Comment by ernst67** [comment]
Maybe a post in the forum would be enough for now. As a 'known issue'...?

**Comment by jojo12** [comment]
This idea is not so good. So all the peoples have to wait 2 month until to the next update and can't import! Just now when the import from earlier version is forced!

**Comment by jojo12** [comment]
I would propose to create a new package with the exchanged file (You can call it 2.1.4b if you want).
And we inform to redownload and reinstall the package.

**Comment by level420** [comment]
I think a version number which is distinguishable from the one which contains the bug would be very good. 2.1.4b would be perfect!

**Comment by Hoffi1** [comment]
Fixed package available on our download area.
