### ISSUE TITLE
JEM 2.1 fe Event view: support new CB image file locations

### ISSUE THREAD

**Issue by Hoffi1** [jemproject/JEM-Project#950]
On a fresh CB 2.0.x installation "noavatar" image is located on another path as on CB 1.9.
Also gallery images have a 'tn' version (thumbnail) which should be prefered.

Note: CB does NOT respect the path choosen in Media Manager. It always uses /images

**Comment by Hoffi1** [comment]
@jojo12: I'm sure you'll test this because you're a CB user. :smile: 

Please don't be surprised if you see a different "no avatar" image. That's because I start with the new path used in CB 2.x and have the old path as fallback. If you updated CB from 1.9 to 2.0 you'll have both images.

**Comment by jojo12** [comment]
@Hoffi1: for sure, I tested :)
But Because I never liked the no avatar image, I changed long time ago.
With your changes you get the default nophoto file. That's ok. 
A problem is, when you use cb overrides. But then the user has himself to resolve this.
