### ISSUE TITLE
dev21-2.1.5: error notice 

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#951]
Perhaps I am too quick and you know it:
Strict Standards: Declaration of JemUser::getInstance() should be compatible with JUser::getInstance($identifier = 0, JUserWrapperHelper $userHelper = NULL) in /srv/www/vhosts/mysite.ch/httpdocs/components/com_jem/classes/user.class.php on line 0

**Comment by Hoffi1** [comment]
Oops - no, hadn't seen this, thanks. Which Joomla version do you use? I've not checked on all yet.

**Comment by jojo12** [comment]
I was trying on Joomla! 3.4.1 (and 3.4.2 RC2 nightly)

**Comment by Hoffi1** [comment]
You're right, with J! 3.4 they badly enhanced parameter list.
Must think about a solution...

**Comment by Hoffi1** [comment]
...grabbed into my bag of tricks - should be strict now. :smile:
