### ISSUE TITLE
dev21-2.1.5 error notice

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#952]
my registered user in testgroup with all group-rights opens in frontend a new event.
global settings user are only admins
error notice above categories:
Notice: Undefined variable: editown in /srv/www/vhosts/mysite.ch/httpdocs/components/com_jem/classes/user.class.php on line 339
same when edit event from my category

**Comment by Hoffi1** [comment]
Yep, found it, thanks. There's a typo, instead ```$editown``` it must be ```$edit_own```.
But I wonder why line 339. Should be 386 (last version) or 348 (previous version).
Will be fixed with next commit...
