### ISSUE TITLE
editevent: Strict standards:  Declaration of JEMControllerEvent::postSaveHook() should be 

### ISSUE THREAD

**Issue by JKoelman** [jemproject/JEM-Project#957]
when using editevent-view in J3 it will create an entry in the logfile:

```Strict standards:  Declaration of JEMControllerEvent::postSaveHook() should be compatible with JControllerForm::postSaveHook(JModelLegacy $model, $validData = Array)```

**Comment by Hoffi1** [comment]
I added a little wrapper class JemControllerForm which will be used instead of JControllerForm.
Involved are Editevent, Editvenue on frontend and backend.

**Comment by JKoelman** [comment]
:+1:  am not seeing the notice anymore in the logs
