### ISSUE TITLE
Outputclass - function flyer:  the "/" after Juri::base should be removed

### ISSUE THREAD

**Issue by JKoelman** [jemproject/JEM-Project#960]
In the function we are defining the path as ```JUri::base().'/'.```  but as JUri::base will have an ending "/" at default we should change things.

**Comment by Hoffi1** [comment]
Not sure if it's true. Maybe only if base is '/' but not if there's a subdirectory as root?
Mostly I have problems if a '/' is missing but not if there's one more. Normally things like "what.ever//index.php" should be tolerated/work.
Cleanest would be "add as needed" - but I don't like "if..." cascades :wink: 

I will also take a look to learn more details...

**Comment by JKoelman** [comment]
some info about Juri::base:  https://docs.joomla.org/JURI/base
and it was reported somewhere in the forum+bugtracker

**Comment by Hoffi1** [comment]
Ok, so there the separator is explicitely appended (as long as pathonly isn't set) whereas on all the JPATH... defines no separator is present at end - one thing to burn into my brain... :wink:

**Comment by Hoffi1** [comment]
would say it's fixed?

**Comment by JKoelman** [comment]
> would say it's fixed?

would say so too
