### ISSUE TITLE
adding JEM3 plugins and module to JEM2

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#961]
I would like to propose to add the following JEM 3 plugins to the JEM 2 package or offer it separately as plugins for JEM 2 too.

JEM event button
JEM content listevents

I use them on JEM 2 and have no problems. (with Joomla 3.4.3)

EDIT:
I mean the mod_jem_calajax from JEM 3 dev too!

it's clear only if Bluefox agrees

**Comment by jojo12** [comment]
I'll ask the same in the dev forum

**Comment by JKoelman** [comment]
@jojo12 
it's not only my decision to make but would say that if it works (with a bit of adjusting) why not?
