### ISSUE TITLE
Important: remove extensions html and htm in attachment settings!

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#964]
if they are officially allowed to be attached, bad Thing can be attached which can execute malicious software on the guest pc. If they are not allowed, the Administrator of JEM is deciding himself if he wants this risk. (it's on 2.1.4 and 3.0.7

**Comment by Hoffi1** [comment]
It's part of JEM 2.1.4.1, 2.1.4.2 and must be integrated into 2.1.5. (because it's not on dev21 yet)

So keep it open to remember...

**Comment by Hoffi1** [comment]
merged into dev21
