### ISSUE TITLE
2.1.5 fatal error notice in myevents

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#965]
when I try to open in myevents an event, I get:
Fatal error: Can't use method return value in write context in /srv/www/vhosts/mysite.ch/subdomains/intra/httpdocs/components/com_jem/views/editevent/view.html.php on line 182

**Comment by Hoffi1** [comment]
Arrghh... you're using PHP 5.3 and I misused again ```empty(function())``` :cry:
