### ISSUE TITLE
possible bug: myevents: no icon for icon-publish

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#966]
Hi, in myevents view in the status column, there it needs a icon-publish and a icon-unpublish.
But to show such icon, you need protostar with moon font,
I can't control it, but as much I remember this is not in Joomla 2.5, and me using t3_purity I am not using this too. 
are these icons for all others visible?

**Comment by Hoffi1** [comment]
If you're a publisher icons are created using ```JHtml::_('jgrid.published', ...``` so Joomla itself decides.
For non-publishhers "static" icons are shown which are part of /media/com_jem/images/

So there maybe different icons used depending on user role (oops - improvable) but there should be always icons shown.

**Comment by jojo12** [comment]
I don't understand - what means your oops?

**Comment by JKoelman** [comment]
@jojo12 i think Hoffi is talking about "Object Oriented Programming" (PHP)

**Comment by Hoffi1** [comment]
@jojo12: The "oops" meant an inconsistency:
In case of user without permission to publish JEM uses own icons (/media/com_jem/images/tick.png and /media/com_jem/images/publish_x.png) but if user can publish (publisher, admin etc) Joomla decides which icons will be shown. So it maybe the same icons e.g. in case of beez3 template or "icons" from e.g. the icomoon font.
So it would be better (improvable) to use the same icons in both cases.

On the other hand it's completely handled in views/myevents/tmpl/default_events.php (lines 199ff) so it can be easy changed by site owners using template overrides - so it's a minor issue, I think. :wink:

**Comment by JKoelman** [comment]
:) thx @hoffi1 for the clarification

**Comment by jojo12** [comment]
:) thx @hoffi1 from me too

**Comment by jojo12** [comment]
for my purity_iii template, I find solution. I am not so easy :-(

**Comment by Hoffi1** [comment]
Don't worry, at least take the new rules from jem.css I just committed which ensures "our" icons are used always and on each template. :smile:

**Comment by jojo12** [comment]
works great on 2.1.5 dev 6 tested myevents and myvenues.
(but not on 2.1.4, so have to wait
