### ISSUE TITLE
strange comportment in create new event 

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#973]
#in addition to #972:
when I open create new event the categories are in black.
in the moment I use the sroll down, all categories are in red.
when I choose one, they fall back to black, except the chosen one whick has background for chosen.

as publisher with "all registered"

**Comment by Hoffi1** [comment]
This seems to be a "feature" of Joomla I've often seen in backend with default template: Required fields become red also if I click into the field to be able to type in data required - old Joomla wasn't so nervous.

I think we don't have a chance to suppress this. (except recommending to use J! 2.5 :grinning: )

**Comment by jojo12** [comment]
yes :)

**Comment by jojo12** [comment]
I associated the 3 categories with the group "Mitarbeiter".
In create event view they were away, that's ok.

Then I changed the associated group to "no group".
The problem in create event view was back.

Loud thinking: Is it possible to release a category from his associated group?

**Comment by Hoffi1** [comment]
> Loud thinking: Is it possible to release a category from his associated group?
Why not? As Admin can change Permissions of Joomla Categories it's possible to change (JEM) Group associated to (JEM) Category.

> Then I changed the associated group to "no group".
> The problem in create event view was back.
Don't understand. Which problem? The red?

**Comment by jojo12** [comment]
no, see image
![catreg2](https://cloud.githubusercontent.com/assets/2960236/9698859/cb9c74b0-53c9-11e5-8c90-b5b800f1f02c.png)

**Comment by jojo12** [comment]
wrong issue, sorry
