### ISSUE TITLE
Registered can create events in all categories

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#974]
is this right?
when settings = all registered
a registered person can create event in each published category.
Means that: the categories aren't reserved for the group users? with this setting.

**Comment by Hoffi1** [comment]
Users not member of a JEM group can create events in all categories not attached to a JEM group.
Categories attached to a JEM group are "reserved" to members of that group (or "global" Authors, Editors etc.).

**Comment by jojo12** [comment]
Thanks!
