### ISSUE TITLE
2.1.4.2 no language files in transifex - so no translation possible!

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#976]
Hi, after updating to 2.1.4.2.
in the modulemanager in column type it shows me Banner modules as Jubilee Module (i did look only in german)
when I open existing modules the it's right: banner module.
I don't know where to change.

**Comment by Hoffi1** [comment]
Currently there is no (official) german translation for Jubilee module. :wink: 
It seems you made your own and forgot to change "MOD_JEM_BANNER..." to "MOD_JEM_JUBILEE..." in de-DE.mod_jem_jubilee.sys.ini.

On my English test site and in files on GitHub I can't see any problem.

**Comment by jojo12** [comment]
currently there is no english file in transifex for jubilee.
@ernst67: can you upload it?

**Comment by jojo12** [comment]
Thanks yes, I forgot in my german files to change in the de-DE.mod_jem_jubilee.sys.ini.

**Comment by Hoffi1** [comment]
Ok, because 2.1.4.2 is on hotfix branch I must merge it to master branch first.
After this @ernst67 can add it on transifex.

**Comment by Hoffi1** [comment]
Hm... Pull request can't be merged automatically - so I must do that today evening at home...

**Comment by Hoffi1** [comment]
2.1.4.2 is merged to master branch so adding mod_jem_jubilee to transifex should be possible.

**Comment by jojo12** [comment]
please load not only admin/com_jem.ini to transifex, but mod_jem_jubilee.ini and mod_jem_jubilee.sys.ini too.

**Comment by Hoffi1** [comment]
@jojo12: The admin file was already added so transifex detected my merge and updated the file automatically. The Jubilee file must be manually added by @ernst67 first.

**Comment by jojo12** [comment]
yes: was strange to get now a mail with information I have to translate 1 expression!

**Comment by Hoffi1** [comment]
I got a mail ```A new source file has been uploaded for the resource [ADMIN] com_jem.ini of the project JEM. ``` - which caused a loud "Hä???" in my mouth. The subject says "...has been updated" but the message text is really confusing because only a new version of an already known source file has been uploaded.

**Comment by jojo12** [comment]
I was very quick, that was only one new expression inside.
