### ISSUE TITLE
frontend attendees shows attendees with username

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#978]
in frontend when I look attendees, it shows me always the username, even if I normally selected name.
is it possible to change that? Seems me a little bug or an inconsistency!

**Comment by Hoffi1** [comment]
With commit 49f1b68670fe85a8dbdf9923931f66ac3fc5517f I changed this on Jul 12 so it will be part of 2.1.5.
But please note that JEM unfortunately has it's own setting which is respectedinstead of Joomla's setting.

**Comment by jojo12** [comment]
ah well, I looked in 2.1.4.2 because of forum question. So you can put fixed!
