### ISSUE TITLE
dev8: abbrechen nach edit venue in myvenues

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#981]
I was as author in myvenues and edited a unpublished venue, I created earlier.
after I wanted to close without saving.
I got a "Forbidden". and after there was a breakdown of the whole site.

Last logs:

85.0.120.113 - - [05/Oct/2015:11:03:17 +0200] "POST /index.php/veranstaltungsorte?a_id=69 HTTP/1.0" 403 408 "http://mysite.ch/index.php/veranstaltungsorte/editvenue?layout=edit&a_id=69&return=aHR0cCUzQSUyRiUyRmludHJhLmthdGgtanVnZW5kLmNoJTJGaW5kZXgucGhwJTJGdmVyYW5zdGFsdHVuZ3NvcnRlJTJGdmVudWUlMkY2OS10ZXN0b3J0LWF1dG9y" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0"

85.0.120.113 - - [05/Oct/2015:11:03:20 +0200] "GET /index.php/veranstaltungsorte/editvenue?layout=edit&a_id=69&return=aHR0cCUzQSUyRiUyRmludHJhLmthdGgtanVnZW5kLmNoJTJGaW5kZXgucGhwJTJGdmVyYW5zdGFsdHVuZ3NvcnRlJTJGdmVudWUlMkY2OS10ZXN0b3J0LWF1dG9y HTTP/1.0" 200 13658 "http://mysite.ch/index.php/veranstaltungsorte/venue/69-testort-autor" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0"

85.0.120.113 - - [05/Oct/2015:11:03:24 +0200] "POST /index.php/veranstaltungsorte?a_id=69 HTTP/1.0" 403 408 "http://mysite.ch/index.php/veranstaltungsorte/editvenue?layout=edit&a_id=69&

85.0.120.113 - - [05/Oct/2015:11:03:17 +0200] "POST /index.php/veranstaltungsorte?a_id=69 HTTP/1.0" 403 408 "http://mysite.ch/index.php/veranstaltungsorte/editvenue?layout=edit&a_id=69&return=aHR0cCUzQSUyRiUyRmludHJhLmthdGgtanVnZW5kLmNoJTJGaW5kZXgucGhwJTJGdmVyYW5zdGFsdHVuZ3NvcnRlJTJGdmVudWUlMkY2OS10ZXN0b3J0LWF1dG9y" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0"

85.0.120.113 - - [05/Oct/2015:11:03:20 +0200] "GET /index.php/veranstaltungsorte/editvenue?layout=edit&a_id=69&return=aHR0cCUzQSUyRiUyRmludHJhLmthdGgtanVnZW5kLmNoJTJGaW5kZXgucGhwJTJGdmVyYW5zdGFsdHVuZ3NvcnRlJTJGdmVudWUlMkY2OS10ZXN0b3J0LWF1dG9y HTTP/1.0" 200 13658 "http:/mysite.ch/index.php/veranstaltungsorte/venue/69-testort-autor" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0"

85.0.120.113 - - [05/Oct/2015:11:03:24 +0200] "POST /index.php/veranstaltungsorte?a_id=69 HTTP/1.0" 403 408 "http://mysite.ch/index.php/veranstaltungsorte/editvenue?layout=edit&a_id=69&

85.0.120.113 - - [05/Oct/2015:11:03:17 +0200] "POST /index.php/veranstaltungsorte?a_id=69 HTTP/1.0" 403 408 "http://mysite.ch/index.php/veranstaltungsorte/editvenue?layout=edit&a_id=69&return=aHR0cCUzQSUyRiUyRmludHJhLmthdGgtanVnZW5kLmNoJTJGaW5kZXgucGhwJTJGdmVyYW5zdGFsdHVuZ3NvcnRlJTJGdmVudWUlMkY2OS10ZXN0b3J0LWF1dG9y" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0"

85.0.120.113 - - [05/Oct/2015:11:03:20 +0200] "GET /index.php/veranstaltungsorte/editvenue?layout=edit&a_id=69&return=aHR0cCUzQSUyRiUyRmludHJhLmthdGgtanVnZW5kLmNoJTJGaW5kZXgucGhwJTJGdmVyYW5zdGFsdHVuZ3NvcnRlJTJGdmVudWUlMkY2OS10ZXN0b3J0LWF1dG9y HTTP/1.0" 200 13658 "http://mysite.ch/index.php/veranstaltungsorte/venue/69-testort-autor" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0"

85.0.120.113 - - [05/Oct/2015:11:03:24 +0200] "POST /index.php/veranstaltungsorte?a_id=69 HTTP/1.0" 403 408 "http://mysite.ch/index.php/veranstaltungsorte/editvenue?layout=edit&a_id=69&

EDIT:
after a while I could reach again my site, but can't reproduce the problem! :-(

**Comment by Hoffi1** [comment]
Hm... tried as author too but can't reproduce.
From My Venues I must go to Venue details view first where I can click edit icon to enter Edit venue view. Adter pressing Cancel I'm back on Venue details view.

btw: The actual Venue details model/view does not check publish field (which is a bug I will fix) so I've no idea where "Forbidden" should come from.
