### ISSUE TITLE
Problem with attachment in JEM 2.1.4.2

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#986]
Hi, in my official site I wanted attach a zip. In the settings it is allowed.
But I get the message: for safety reasons it's not uploaded.
I need the possibility to attach a zip, what's going wrong
(Question, I didn't test: how is it in 2.1.5?)

**Comment by Hoffi1** [comment]
Must take a look but I'm sure we don't block it if admin adds it to the list of allowed extensions.
The message sounds to me as if this is a new, unwanted feature of Joomla itself.

**Comment by Hoffi1** [comment]
Hm... tried with JEM 2.1.5 on J! 3.4.4. Attached three zip files: with simple txt, harmless html, and html with php tag - all three were uploaded (as super user on frontend) without problems.
Tried not allowed html file - got "Extension not allowed: ...html".

So I must look deeper which specific constellation angers you...

**Comment by Hoffi1** [comment]
Ok, found it. As I feared it's an unwanted Joomla feature: If your archive contains a file with extension ".php" it will not be uploaded.
btw: If the archive contains a html file with the same php code included all is fine and archive is uploaded!

Now we need a way to switch off specifically this stupid "feature" without activating someone wrongly reporting this as attack and dropping us from jed.

**Comment by jojo12** [comment]
bad: because I don't had a php.
I made a zip with 4 short *.mid files and a *.pdf.

**Comment by Hoffi1** [comment]
Hm... .mid and .pdf are ok.
BUT: The implementation is very stupid. If your archive contains one of the byte sequences ".php", ".inc", ".pl", ".cgi", ".fcgi", ".java", ".jar", ".py" - regardless if as part of a filename or accidental part of content - it will be rejected.

If it's not too big and not secret you could send me this archive?
also you could try to upload it (for test) in Kunena or e.g. PhocaDownload if you have installed. They should have the same problem because it's Joomla 3.4.4. (3.4.3 had a bug so it hadn't rejected).

You could also test by modifying com_jem/classes/attachment.class.php line 81 to
```JFile::upload($post_files['tmp_name'][$k], $filepath, false, false, array('forbidden_ext_in_content' => false));``` (adding the three params)

**Comment by jojo12** [comment]
the same problem is with attachments extension and it's new since 3.4.4
you'll find some discussions on github too.
The message is:
Fehler
Fehler beim Hochladen von ''! (Sie müssen eine Datei zum Hochladen auswählen!) (ERR 129)

**Comment by jojo12** [comment]
for me this is not a reason to hold back JEM 2.1.5. after all because it seems joomla related.
(did you see, there's an important security update for joomla 3.3.2+

**Comment by jojo12** [comment]
I will send you the file, when I am back home

**Comment by Hoffi1** [comment]
@jojo12; Thanks for both - the file and the hint to the brand new Joomla 3.4.5.

**Comment by Hoffi1** [comment]
I marked it as "invalid" because it's a bug in Joomla 3.4.x.

But I can provide a workaround by switching off this stupid archive check.

**Comment by jojo12** [comment]
I don't hope there will  be a security problem with these changes!

**Comment by Hoffi1** [comment]
I thought about this too, but
- Joomla's installer completely disables all checks
- these checks are new in Joomla 3.4.x
- the check can detect script files inside zip archives but not inside e.g. tgz archives
- I have no idea why a php, phyton etc. script inside a stored archive should be a risk as long as it's not extracted on the server (and there is no way for a user to do that)
- in the Joomla forum a posted "solution" is to completely deactivate the checks - and no developer or moderator vetoed
- I've posted there and also filed an issue - no response yet, must wait a bit...
