### ISSUE TITLE
Problem 2.15 with our CB modules

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#989]
After updating I can't reach CB profiles when our cb plugins are activated!
with debugger:
Fatal error: Class 'JemFactory' not found in /srv/www/vhosts/kath-jugend.ch/httpdocs/components/com_jem/classes/categories.class.php on line 450

when I deactivate our cb plugins I can reach the profile (with a notice of not responding script)

strange:
Skript: http://www.mysite.ch/media/jui/js/jquery-migrate.js:197

**Comment by Hoffi1** [comment]
Argh... Thanks @jojo12, you're fully right. The modules I checked but the CB plugins were outside my focus.

So there will be a JEM 2.1.5-rc3...

**Comment by jojo12** [comment]
I tried the new improvements with JEM 2.1.4.2. There it is ok. So it seems to be the probleme in combination of
JEM 2.1.5 and cbplugins

**Comment by Hoffi1** [comment]
Hi @jojo12, you need the changes I made on the component. See commit https://github.com/jemproject/JEM-Project/commit/66e4ad91be2e665b30eafc70890e3ec30e9d85cb

**Comment by jojo12** [comment]
I must have been stupid or sleepy, sorry.!
After these changes in component. It's working well. 
only the "old" sign

**Comment by Hoffi1** [comment]
No problem, it's complex mater. :smile: 

Regarding "old" sign: That's the problem we already discussed a lot. On GitHub the xml works on CB 1.9 and 2.0 so it causes "old" on 2.0. Finally I will create packages for CB 1.9 (as checked in) and CB 2.0, where in the xml the ```<version>``` tag is set to 2.0.

**Comment by jojo12** [comment]
yes, I just tried: it's like you say!
