### ISSUE TITLE
CB plugins: some improvements

### ISSUE THREAD

**Issue by Hoffi1** [jemproject/JEM-Project#991]
Additionally I've some improvements:
- Show number of items in tab title (CB 2.0+)
- Add option to show start and end date and time in a single column as in JEM lists
- Attendings: show additional status column to indicate "registered" vs. "on waitinglist"

**Comment by jojo12** [comment]
I tried to install the two improved cbplugins on cb 2.0.11+
Installation ok, but sign of old plugin
when activating same: 
white screen when going to profile
with joomla debug: 
Fatal error: Class 'JemFactory' not found in /srv/www/vhosts/mysite.ch/httpdocs/components/com_jem/classes/categories.class.php on line 450
and in admin very slow when opening tab.

**Comment by jojo12** [comment]
I tried with JEM 2.1.4.2. There it is ok. So it seems to be the probleme in combination of 
JEM 2.1.5 and cbplugins

**Comment by jojo12** [comment]
I like these improvements! Thanks.

**Comment by Hoffi1** [comment]
Regarding the number in tab title: Depending on my own setup I liked to append this number only if the tab is shown on a Canvas position and as type Menu. The original Article plugin hasn't this limitation.

What do you think @jojo12 should I remove this limitation and show it always?

**Comment by jojo12** [comment]
is this chinese? I don't understand!
