### ISSUE TITLE
Problem with Translation of cbplugins

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#992]
Because in the old plugins there was a special kind of translation with english.php and german.php
I don't know how and where to translate to e.g. german.

I can translate the frontend words in german.php.

But in the backend it seems the expressions are hardcoded! How to change that?

**Comment by Hoffi1** [comment]
Yes, it is.
I tried to add it to english.php but it was not used. I don't know if there is any way to add language strings for backend only within the plugin itself. CB collects all the strings required by their own plugins within a big file inside the component / the one and only language plugin - no way for third-party...

So at the moment I've no idea how to provide a backend language file.

**Comment by jojo12** [comment]
I am trying to understand:
In the new CB 2.0 plugins, they don't use english.php anymore.
they use in the php a e.g. CBTxt::T( 'Left group successfully!' )
and have a 
language/default_language folder
with language.php and admin_language.php inside.
...

**Comment by jojo12** [comment]
There are 2 tutorials on youtube for cb language and cb language override. Perhaps they help understand the new language concept.

**Comment by Hoffi1** [comment]
Thanks @jojo. Sorry for giving it a very low priorety in my brain. Our plugins continue using english.php (and others) as in CB 1.9. But this way you can't translate backend because english.php (and others) isn't loaded there.

If I find a bit more time and hopefully a good document (I normally don't watch videos where describing words are faster to read and much more helpful).

**Comment by jojo12** [comment]
ok, 
because it's backend it's not so important. 
I understand a little bit english :-)
For frontend it's good to have a translation. I have my german.php (identical with english.php) but with german translations.
