### ISSUE TITLE
question: add collapsible sidebar in backend - gives more place

### ISSUE THREAD

**Issue by jojo12** [jemproject/JEM-Project#994]
it's relatively easy to add sidebar (with show and hide) in backend. (this is a new feature in JEM 3)
I can do that for my own version.
The changes in views/default,php can easily be done with overrides, but
the problem is there is a change in helpers.php and in each view.html.php. you can't override them. 

Is this a reason to start with a version only for Joomla! 3.4+?
or is this possible to integrate it  in the version for both Joomla 2.5 and 3?

**Comment by Hoffi1** [comment]
@jojo12 Could you change based on 2.1.5 the helpers.php and one default.php + view.html.php (e.g. categories or events view) and provide me as example?
This would be the easiest but most precise way for me to understand the changes and get inspired... :wink: I'm sure there is a good way to get them all.

**Comment by jojo12** [comment]
I think the best is to go to JEM 3 dev and search the commits on 28 february (added new sidebar)
but I will send you on a dev in forum too

**Comment by jojo12** [comment]
in post #19895

**Comment by jojo12** [comment]
I tried to change to hathor backend template. there is no problem, if I have only changed the helper.php and the view.html.php s.
The view/tmpl/default.php I can use as override in isis backend template.
