### ISSUE TITLE
JEM 2.1.5: Fix en-GB MOD_JEM_CAL_DEFAULTSTYLESHEET_DESC

### ISSUE THREAD

**Issue by Hoffi1** [jemproject/JEM-Project#995]
There is a surprising "15q" in css filename of describing text.

**Comment by ernst67** [comment]
Comes from the old module name.. can be deleted.

**Comment by JKoelman** [comment]
whoops, had a typo in the issue nr.

**Comment by JKoelman** [comment]
it was changed so will close the issue
