### ISSUE TITLE
Field "Categoryedit" - Fatal error: Class 'JemFactory' not found

### ISSUE THREAD

**Issue by JKoelman** [jemproject/JEM-Project#998]
Error: Fatal error: Class 'JemFactory' not found in ....\administrator\components\com_jem\models\fields\categoryedit.php on line 135

**Comment by jojo12** [comment]
when do you get this error? It remembers me a problem that was resolved.

**Comment by Hoffi1** [comment]
Could it be caused by mod_jem_calajax in backend? There is a field of type categoryedit whereas our other modules have a simple text field.
So maybe we need to include factory.php also in model fields using JemFactory.

**Comment by JKoelman** [comment]
@jojo12  it was caused by mod_jem_calajax just as Hoffi1 did suspect. The module is indeed using that field instead of a text field to fill the numbers.  Not sure how it will be in case of menu-items but would say it won't heart to include factory.php in the field.

**Comment by JKoelman** [comment]
ah good to see that Hoffi1 did change some code :)
